- .travis.yml
- script/cibuild
- script/test
This configures Travis CI according to http://docs.travis-ci.com/user/languages/go/
We won't be able to test this until the repository is public, so we can wait to merge this at that time.
> Configure Travis CI

- commands/command_track.go
Two really tiny changes, bumped into them while reading the code, said "why not?".
Have a great day!
> Tiny refactor of command_track

- .vendor/src/github.com/github/git-media
- script/install.bat.example
Remove some media refs, from #216
> Remove a few more git media refs

- script/gpm
> Add gpm's license to its file

- ROADMAP.md
Here are the high level ideas we're thinking of for future releases of Git LFS.  Nothing is final until it's merged into master.
> Create a roadmap

- docs/spec.md
Corrects some configuration documentation, reported in #239
> Update spec to reflect lfs.url and lfsurl

- .travis.yml
> Skip the install step in travis, everything is vendored

- README.md
to make it a little easier to discover.
> Link to roadmap in readme

- lfs/http.go
See [Article](http://biasedbit.com/blog/golang-custom-transports/)
> add default timeout to http client

- CHANGELOG.md
- CONTRIBUTING.md
This brings over the items from #268 to a new changelog file.
> changelog file for next release

- lfs/lfs.go
- test/test-submodule.sh
> Fixed `LocalWorkingDir` for directories in submodules

- commands/command_track.go
- lfs/lfs.go
- test/test-submodule.sh
- test/test-track.sh
> Further improvements of LocalWorkingDir and LocalGitDir detection

- commands/command_track.go
- commands/command_track_test.go
- test/test-track.sh
* Improved detection of duplicate paths
* Writes relative paths to `.gitattribute` files; fixes #230
* Don't track file outside the repository
> Fixed some tracking issues and improved codebase of command track

- lfs/lfs.go
> Used 0755 as file mode bits when creating directories

- git/git.go
- lfs/config.go
- test/test-env.sh
Also fixed a typo and added missing env tests.
All config/env related and therefore bundled in one PR.
> Use .gitconfig in LocalWorkingDir instead of PWD

- lfs/transfer_queue.go
To reproduce the deadlock, put `runtime.Gosched()` right after `workersReady <- 1`.  The `q.authCond.Signal()` is the being sent without any worker waiting at `q.authCond.Wait()`.  Therefore all workers block at `q.authCond.Wait()` and the main goroutine blocks at `wg.Wait()` (deadlock).
Use case 1 `q.transferables` is empty:
> `<-workersReady` is not (endlessly) blocking, because the additional `go func` closes the channel.  The `q.authCond.Signal()` does not do anything.
Use case 2 `q.transferables` is not empty:
> `<-workersReady` in combination with `q.authCond.L.Lock()` blocks until at least one worker is waiting (`q.authCond.Wait()`). Therefore the `q.authCond.Signal()` signals one of the goroutines to
run.
> The size of the channel `workersReady` makes sure that every worker that …
> Resolved race condition

- commands/command_untrack.go
- test/test-untrack.sh
> Improved command untrack

- lfs/config.go
- lfs/credentials.go
- lfs/http.go
- lfs/util.go
Merges latest master into #387.
> Michael k cleanup config

- lfs/config.go
- lfs/credentials.go
- lfs/http.go
- lfs/util.go
Picks up an idea by @technoweenie: https://github.com/github/git-lfs/pull/380#discussion_r32227378
Cleaned up the config on the way.
> Check environment variables only once per git-lfs process

- lfs/config.go
- lfs/credentials.go
- lfs/http.go
> Parse boolean environment variables

- lfs/lfs.go
I have updated the code to use constants in place of the 0755 along with a note about possibly using the umask of the system git-lfs is installed.
> Directory Permissions - Changed to use constants

- commands/command_logs.go
- test/test-logs.sh
You can't modify a 0 len array. I didn't want to append on each iteration, so I went with a slice instead.
> fix logs command

- rpm/INSTALL.md
- rpm/SPECS/git-lfs.spec
- rpm/build_rpms.bsh
- script/centos-build
Added a bunch of minor fixes for building in CentOS
> Centos fixup

- lfs/client.go
- test/cmd/lfstest-gitserver.go
- test/test-chunked-transfer-encoding-batched.sh
- test/test-chunked-transfer-encoding.sh
> Support chunked Transfer-Encoding

- README.md
- commands/command_track.go
- docs/spec.md
- test/test-track.sh
Fixing https://github.com/github/git-lfs/issues/473
> Use -text instead of -crlf

- commands/command_init.go
- commands/commands_uninit.go
- docs/man/git-lfs-init.1.ronn
- docs/man/git-lfs-uninit.1.ronn
- lfs/setup.go
- test/test-init.sh
- test/test-uninit.sh
> Better init

- rpm/INSTALL.md
- rpm/SPECS/git-lfs.spec
- rpm/build_rpms.bsh
- script/centos-build
> Backport #428 for v0.5.x: Centos fixup

- lfs/client.go
- test/cmd/lfstest-gitserver.go
- test/test-pre-push.sh
> Backport #442 for v0.5.x: Support 307 redirects using relative Location headers

- commands/command_init.go
- commands/commands.go
- commands/commands_uninit.go
- docs/man/git-lfs-init.1.ronn
- docs/man/git-lfs-uninit.1.ronn
- lfs/setup.go
- test/test-init.sh
- test/test-uninit.sh
- test/testhelpers.sh
- test/testlib.sh
This backports #446, #451, and #465.
> Backport #446 for v0.5.x: add some basic init tests

- test/cmd/lfstest-gitserver.go
- test/test-init.sh
> Backport #452 for v0.5.x: Update test server to support operation field in batch request

- commands/command_clean.go
- commands/command_pre_push.go
- lfs/pointer_clean.go
- lfs/upload_queue.go
- test/test-clean.sh
- test/test-pre-push.sh
> Backport #447 for v0.5.x: Clean fix

- lfs/client.go
- test/cmd/lfstest-gitserver.go
- test/test-chunked-transfer-encoding-batched.sh
- test/test-chunked-transfer-encoding.sh
> Backport #386 for v0.5.x: Support chunked Transfer-Encoding

- commands/command_pre_push.go
- commands/command_push.go
- lfs/upload_queue.go
- test/test-push.sh
> Backport #449 for v0.5.x: Add option to push object ID(s) directly.

- commands/command_fetch.go
- commands/command_fsck.go
- commands/command_ls_files.go
- commands/command_pre_push.go
- commands/command_push.go
- commands/command_status.go
- lfs/scanner.go
- lfs/upload_queue.go
- test/test-commit-delete-push.sh
- test/test-ls-files.sh
> Backport #461 for v0.5.x: Push deleted files

- test/cmd/lfstest-gitserver.go
- test/test-batch-transfer-unsupported.sh
- test/test-batch-transfer.sh
- test/test-chunked-transfer-encoding-batched.sh
- test/test-chunked-transfer-encoding.sh
- test/test-fetch.sh
- test/test-happy-path.sh
- test/test-pre-push.sh
- test/testhelpers.sh
> Backport #463 for v0.5.x: Test helper fixes

- .gitignore
- docs/linux-build.md
- rpm/INSTALL.md
- rpm/SPECS/git-lfs.spec
- rpm/SPECS/git.spec
- rpm/build_rpms.bsh
- script/centos-build
This backports #480.
- .gitignore
> Backport #480 for v0.5.x: Git for CentOS

- docs/man/git-lfs-push.1.ronn
> documents git lfs push --object-id

- ROADMAP.md
1. @sinbad is anxious to tackle local storage management: #490. I combined items since they're all covered by his task list.
2. This [Extensions proposal](https://github.com/github/git-lfs/blob/master/docs/proposals/extensions.md) is very important to @ryansimmen (#460). Hooks on hooks on hooks.
3. I demoted client side metrics reporting. While @rubyist added better HTTP stats to the client (#366), I don't know if we need clients reporting this data to servers.
> update roadmap to point to the new local storage management issue

- git/git.go
- lfs/setup.go
- test/test-uninit.sh
We need to run `git config` with the `--remove-section` arg. Fixes #529
> teach 'uninit' how to remove git config sections

- CHANGELOG.md
- commands/commands.go
- debian/changelog
- git-lfs.go
- git/git.go
- lfs/client.go
- lfs/lfs.go
- lfs/setup.go
- script/build.go
- script/run
- test/test-logs.sh
- test/test-uninit.sh
Fixes:
* #530
* #534 
Patches:
* #536 
* #537
> Release 0.5.4

- lfs/progress_meter.go
- lfs/transfer_queue.go
If progress is not delayed it can interfere with credential helpers asking for credentials to make the API calls.
> Delay progress output until the transfer starts

- commands/command_clean.go
- commands/command_ext.go
- commands/command_pointer.go
- docs/man/git-lfs-ext.1.ronn
- docs/proposals/extensions.md
- lfs/config.go
- lfs/config_test.go
- lfs/extension.go
- lfs/extension_test.go
- lfs/pointer.go
- lfs/pointer_clean.go
- lfs/pointer_smudge.go
- lfs/pointer_test.go
- lfs/scanner.go
- lfs/upload_queue.go
- test/test-ext.sh
Code for proposal https://github.com/github/git-lfs/blob/master/docs/proposals/extensions.md
> Git LFS Extensions

- lfs/client.go
- lfs/credentials.go
- test/cmd/lfstest-gitserver.go
- test/test-credentials.sh
Some additions to the credential tests in #561, written specifically for #554.
> add more credential tests

- lfs/client.go
- lfs/credentials.go
- test/cmd/git-credential-lfstest.go
- test/cmd/lfstest-gitserver.go
- test/test-credentials.sh
- test/testenv.sh
- test/testhelpers.sh
Trying to spike out some tests for the git credential behavior. This is so we can find out if we break the credential flow, and test changes to it like #554.
> Credential tests

- commands/command_pre_push.go
- commands/command_push.go
- test/test-push.sh
> Fix pushing other branches

- lfs/config.go
- lfs/config_test.go
- lfs/credentials.go
- lfs/credentials_test.go
- lfs/download_test.go
- lfs/upload_test.go
Builds on #611 with some more tests for git credentials.
> More cred tests

- docs/api/http-v1-batch-response-schema.json
- docs/api/http-v1-batch.md
Updates the batch API spec to match https://github.com/github/git-lfs/issues/597.
> describe how validation errors are returned from the batch api

- commands/command_fetch.go
- docs/man/git-lfs-fetch.1.ronn
- lfs/progress_meter.go
- lfs/scanner.go
- test/test-fetch.sh
Support for `git lfs fetch --all` for backup/migration purposes.
> Fetch --all

- commands/command_pre_push.go
- test/test-pre-push.sh
> Fix pre-push hook with multiple branches

- lfs/lfs.go
- test/testutils.go
Fixes 2 issues with the test package:
* AddCommits: multiple random files of the same size in commit 0 are now guaranteed to be different
* Make sure the global dir vars are updated when using test.Repo
> Testutils fixes

- test/testutils.go
You could still end up with duplicated seeds between commits which could cause unintended consequences.
> Make sure random test data is seeded differently between commits

- CHANGELOG.md
- CONTRIBUTING.md
- debian/changelog
- docker/test_lfs.bsh
- docs/man/mangen.go
- lfs/lfs.go
- rpm/SPECS/git-lfs.spec
- script/nsis/installer.nsi
- test/test-init.sh
- test/test-push-bad-dns.sh
- test/test-push-failures.sh
- test/test-push-legacy-failures.sh
- test/test-update.sh
This bumps the version number, and makes a few changes to get the docker scripts to run.
* Skipped some tests that depend on `GIT_LFS_TEST_DIR`. 
* Hardcoded the root path in `docs/man/mangen.go` so that Git LFS builds on the Debian docker images.
> Release 1.0

- docs/extensions.md
Extensibil***i***ty, not extensibilty.
> Fix typo in docs/extensions.md

- lfs/client.go
> guard against res being nil

- commands/command_fetch.go
- commands/command_pre_push.go
- commands/command_push.go
- lfs/scanner.go
Should fix #794
/cc @sinbad @rubyist
> Fixes a race condition accessing the maps inside goroutines

- docs/api/README.md
Minor change to fix broken spec.md link
> Update spec.md broken link

- appveyor.yml
First working version producing an unsigned git-lfs.exe
> Appveyor Proof of concept

- script/packagecloud.rb
Updated the script to upload packages for Ubuntu, AND generate a bunch markdown links for the releases page to manually download them.
NOTE: I already ran this, so the ship has sailed for v1.1 :)
/cc @ssgelm and @andyneff
> upload ubuntu packages and generate some markdown package download links

- CONTRIBUTING.md
- README.md
My goal here is to describe more of the development workflow, and update the instructions for clarity.
> big updates to the readme and contributing guide

- lfs/progress_meter.go
> Progress bar col fix

- README.md
Change PackageCloud link to go to more intuitive install page since this is what the list bullet is about.
> Update PackageCloud Link

- lfs/scanner.go
> skip scanner lines that are too short

- commands/command_fetch.go
- commands/command_pre_push.go
- commands/command_push.go
- commands/commands.go
- lfs/errors.go
- lfs/errors_test.go
- lfs/upload_queue.go
> Backport #1023 for v1.1.x: Better errors on push

- .travis.yml
- script/bootstrap
- script/build.go
- script/integration
- script/release
- script/run
- script/test
- test/test-credentials-no-prompt.sh
- test/testhelpers.sh
> Backport #1025 for v1.1.x: Go 1.6

- commands/command_pre_push.go
- commands/command_push.go
Applying #1037 against the release-1.1 branch.
> better handling on push errors

- CONTRIBUTING.md
- README.md
I've been wanting a Git LFS core team for a while. I wanted something more "official", but this at least gets us started.
/cc @andyneff @rubyist @sinbad
> Add core team

- lfs/certs.go
- lfs/certs_test.go
- lfs/http.go
> Support gitconfig sslverify for specific host

- CONTRIBUTING.md
Google:
* "pat yourself"  -> 451,000 results
* "pat your self" -> 22,700 results and `Did you mean: "pat yourself"`
> Replace "pat your self" with "pat yourself"

- test/README.md
- test/testenv.sh
- test/testhelpers.sh
If user doesn't specify a specific one, create one in the temp area & clean up when done if KEEPTRASH=0
> Always run integration tests in a separate GIT_LFS_TEST_DIR

- README.md
While following the instructions in the README made my first commit and then realized I hadn't added the `.gitattributes` file. I think the instructions should be explicit about this step.
> You should add the .gitattributes file before committing

- lfs/ssh.go
> SSH should be called more strictly with command as one argument

- ROADMAP.md
I have one more larger proposal for a feature (file expiration), and a bunch of smaller bugs to add.
> update roadmap for v1.3+

- INSTALLING.md
- README.md
Adds some details around installing from packagecloud.  #1074 .
> Added INSTALLING.md for packagecloud

- script/windows-installer/inno-setup-git-lfs-installer.iss
* Fixed an issue (#1120) where the newly added Git LFS `PATH` location wasn't refreshed in time for use later in the installer script and silently failed to initialize Git LFS.
* If for any reason there is an issue running `git lfs install`, the installer will display a message box asking the user to manually do so.
* Added a `GIT_LFS_PATH` global env var for later use.
> Fixed an issue that caused the Win installer to fail to init Git LFS

- ROADMAP.md
Just adding a few things so I can scratch them off my personal todo list. Some of these may be good candidates for "help-wanted" issues. I'll keep this PR open for 1 day and merge it, unless there are any oppositions. Feel free to add suggestions in the mean time.
> small roadmap update

- ROADMAP.md
This is focused on build/compilation stuff. Adding these items now so I don't forget later.
> More roadmap updates!

- git/git.go
Fixes #1159 
Stop using the psuedo-tty & pass through streams directly. Getting pty to work with stdin was too difficult, even when it worked passwords were displayed on the terminal which is no good. We no longer need to filter the stderr for known warnings; Git 2.8 is now released which deals with them and for Git 2.7 and below we can fall back on `cat` instead of a blank filter; it's slightly slower but eliminates the problem more simply. We used to do this for git < 2.2 anyway which didn't support blank filters at all.
> Fix problems with user prompts in `git lfs clone`

- lfs/transfer_queue.go
Found another one:
```
fatal error: concurrent map read and map write
goroutine 58 [running]:
runtime.throw(0x618f40, 0x21)
/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:530 +0x90
fp=0xc820793cc0 sp=0xc820793ca8
runtime.mapaccess2_faststr(0x429280, 0xc8202984e0, 0xc8202b7d00, 0x40,
0xc82064c708, 0xc82042a401)
/usr/local/Cellar/go/1.6.1/libexec/src/runtime/hashmap_fast.go:307
+0x5b fp=0xc820793d20 sp=0xc820793cc0
github.com/github/git-lfs/lfs.(*TransferQueue).batchApiRoutine(0xc820074
680)
/Users/rick/go/src/github.com/github/git-lfs/lfs/transfer_queue.go:242
+0xb52 fp=0xc820793f88 sp=0xc820793d20
runtime.goexit()
/usr/local/Cellar/go/1.6.1/libexec/src/runtime/asm_amd64.s:1998 +0x1
fp=0xc820793f90 sp=0xc820793f88
created by github.com/github/git-lfs/lfs.(*TransferQueue).run …
```
> fix concurrent map read and map write

- lfs/lfs.go
- test/test-env.sh
- test/test-worktree.sh
Adds all Fetch/Prune config details to the `env` command, as well as extensions which weren't reported.
> Add missing config details to `env` command

- docs/proposals/locking.md
- docs/proposals/locking_api.md
This PR adds to @sinbad's original proposal and extends it to document some particular commands that we will have to teach the LFS client.
All of the documentation surrounding these new commands and API methods are in the contents of this PR, so I will keep this description brief 😄
Thanks in advance for reading! 👋
> Locking commands

- debian/rules
- script/test
Makes Debian build work on my machine, needs checks for correctness. #1290.
> [WIP] Debian build vendor test excludes

- CHANGELOG.md
- debian/changelog
- lfs/lfs.go
- rpm/SPECS/git-lfs.spec
- script/windows-installer/inno-setup-git-lfs-installer.iss
This pull request applies the commit 79bedebb2536485317ed5470d4e6d72cdc92d0c4 onto `master`, thereby bumping the version to `1.2.1`.
> release git-lfs v1.2.1

- README.md
> README: add @ttaylorr to core team

- docs/api/v1.3/http-v1.3-batch-response-schema.json
- docs/api/v1/http-v1-batch-response-schema.json
- docs/api/v1/http-v1-batch.md
- test/cmd/lfstest-gitserver.go
- test/test-push.sh
- transfer/adapterbase.go
This pull-request rejects pushes with actions that have size less than zero bytes, as according to the spec changes.
> Handle artifactory responses

- api/schema/schema_validator.go
- script/test
- test/testenv.sh
- tools/filetools.go
A bunch of fixes on Windows, details in the individual commits. 
Integration tests all appear OK but require some user interaction to cancel GUI auth prompts which the Windows version of OpenSSH seems to be throwing up.
> Windows fixes

- debian/rules
- rpm/SPECS/git-lfs.spec
- rpm/build_rpms.bsh
- test/testhelpers.sh
This updates the debian and rpm build scripts to go with https://github.com/andyneff/git-lfs_dockers/pull/3.
/cc @andyneff
> Linux build fixes

- CONTRIBUTING.md
New section (Branching strategy). This could be filled out a bit but I
don't know enough about your workflow to write it up with any more detail.
Explicitly mention master in the PR section.
> Added branch name (master) to CONTRIBUTING.md

- glide.lock
- glide.yaml
- script/test
- script/vendor
- vendor/github.com/pkg/errors/.gitignore
- vendor/github.com/pkg/errors/.travis.yml
- vendor/github.com/pkg/errors/LICENSE
- vendor/github.com/pkg/errors/README.md
- vendor/github.com/pkg/errors/appveyor.yml
- vendor/github.com/pkg/errors/errors.go
- vendor/github.com/pkg/errors/errors_test.go
- vendor/github.com/pkg/errors/example_test.go
- vendor/github.com/pkg/errors/format_test.go
- vendor/github.com/pkg/errors/stack.go
- vendor/github.com/pkg/errors/stack_test.go
This PR vendors the `github.com/pkg/errors` package for use in the upcoming `error` package refactoring :metal: 
-
> Vendor errs

- commands/command_fetch.go
`fetchAndReportToChan()` can optionally receive a channel for sending `*lfs.WrappedPointer` objects. This is [used in `git lfs pull` to send files to checkout](https://github.com/github/git-lfs/blob/177984f2212a9232e1614c5ffc4e0bd55204783f/commands/command_pull.go#L41-L42).  The [checkout process](https://github.com/github/git-lfs/blob/177984f2212a9232e1614c5ffc4e0bd55204783f/commands/command_checkout.go#L74-L80) processes files as it reads them off the channel.
This PR renames `skippedAndUniqPointers()` to `readyAndMissingPointers()`, and changes it so the only pointers that are considered "ready" are those that already exist in `.git/lfs/objects`.
> don't report "seen" objects as ready to checkout

- docs/man/git-lfs-config.5.ronn
> docs/man: note GIT_LFS_PROGRESS

- CHANGELOG.md
- ROADMAP.md
- config/version.go
- debian/changelog
- lfs/lfs.go
- rpm/SPECS/git-lfs.spec
- script/windows-installer/inno-setup-git-lfs-installer.iss
> release: Git LFS v1.4.1

- commands/command_fsck.go
- commands/command_status.go
- git/git.go
- lfs/scanner.go
- test/test-status.sh
Fixes #1536 
Also makes added files appear in the staged area before the first commit.
> Status initial commit

- docs/man/git-lfs-config.5.ronn
> docs/man: document `lfs.transfer.maxretries`

- CHANGELOG.md
- ROADMAP.md
- config/version.go
- debian/changelog
- lfs/lfs.go
- rpm/SPECS/git-lfs.spec
- script/windows-installer/inno-setup-git-lfs-installer.iss
cc @technoweenie @rubyist @sinbad @larsxschneider @sschuberth
> release: v1.4.2

- README.md
This pull requests moves our Travis badge down to a newline, and adds an AppVeyor badge for the build status on `master` right next to it.
--
/cc @technoweenie @sschuberth
> Appveyor badge

- CHANGELOG.md
- config/version.go
- debian/changelog
- lfs/lfs.go
- rpm/SPECS/git-lfs.spec
- script/windows-installer/inno-setup-git-lfs-installer.iss
> release: v1.4.3

- CHANGELOG.md
- config/version.go
- debian/changelog
- lfs/lfs.go
- rpm/SPECS/git-lfs.spec
- script/windows-installer/inno-setup-git-lfs-installer.iss
cc @technoweenie @rubyist @sschuberth
> release: v1.4.4

- docs/proposals/locking.md
> Ported locking workflow doc changes into separate PR

- CHANGELOG.md
- config/version.go
- debian/changelog
- lfs/lfs.go
- rpm/SPECS/git-lfs.spec
- script/windows-installer/inno-setup-git-lfs-installer.iss
cc @technoweenie @rubyist @larsxschneider @sinbad @sschuberth
> release: 1.5.0

- docs/man/git-lfs-filter-process.1.ronn
> docs/man: document git-lfs-filter-process(1)

- rpm/SPECS/git-lfs.spec
> rpm: build Git LFS in the right directory

- git/pkt_line_reader.go
- git/pkt_line_reader_test.go
- test/test-filter-process.sh
c.f. https://github.com/git-lfs/git-lfs/issues/1697
> filter-process:  fix reading 1024 byte files

- CHANGELOG.md
- config/version.go
- debian/changelog
- lfs/lfs.go
- rpm/SPECS/git-lfs.spec
- script/windows-installer/inno-setup-git-lfs-installer.iss
cc @technoweenie @larsxschneider @rubyist
> release: 1.5.2

- config/endpoint.go
> Backport #1737 for v1.5.x: fix ssh endpoint parsing

- commands/command_install.go
- commands/command_uninstall.go
- commands/run.go
- localstorage/currentstore.go
- test/test-install.sh
- test/test-uninstall.sh
> Backport #1727 for v1.5.x: Fix Install in root problems

- CHANGELOG.md
- config/version.go
- debian/changelog
- lfs/lfs.go
- rpm/SPECS/git-lfs.spec
- script/windows-installer/inno-setup-git-lfs-installer.iss
> release: 1.5.3

- .travis.yml
- appveyor.yml
> Backport #1734 for v1.5.x: build: use Go 1.7.4

- commands/command_checkout.go
- commands/command_clone.go
- commands/command_fetch.go
- commands/command_fsck.go
- commands/command_ls_files.go
- commands/command_pre_push.go
- commands/command_prune.go
- commands/command_pull.go
- commands/command_push.go
- commands/command_status.go
- commands/uploader.go
- lfs/gitscanner.go
- lfs/gitscanner_index.go
- lfs/gitscanner_log.go
- lfs/gitscanner_refs.go
- lfs/gitscanner_tree.go
- lfs/scanner_git_test.go
- test/test-fsck.sh
Merged #1725 into `fast-walk-no-channels`, which was already merged. This PR merges a10f90926e24045c6538055085bfe530a4bc7aa8 into master. See #1725 for prior discussion.
> Gitscanner callbacks master

- progress/meter.go
- progress/spinner.go
> Backport #1806 for v1.5.x: progress: guard negative padding width, panic in `strings.Repeat`

- CHANGELOG.md
- config/version.go
- debian/changelog
- lfs/lfs.go
- rpm/SPECS/git-lfs.spec
- script/windows-installer/inno-setup-git-lfs-installer.iss
> release: 1.5.4

- test/test-clone.sh
See: https://github.com/git-lfs/git-lfs/pull/1782#issuecomment-267678319.
---
> clone: debug transient "clone" failure

- circle.yml
- test/cmd/lfstest-gitserver.go
- test/test-batch-transfer.sh
Adds an NTLM integration test. Just rewrote #1836 on top of the API refactor #1839.
> test: add ntlm integration test

- CHANGELOG.md
- config/version.go
- debian/changelog
- lfs/lfs.go
- rpm/SPECS/git-lfs.spec
- script/windows-installer/inno-setup-git-lfs-installer.iss
> release: 1.5.5

- commands/command_install.go
- commands/command_uninstall.go
- git/git.go
- lfs/attribute.go
- lfs/setup.go
- test/test-uninstall.sh
> Teach uninstall cmd about --local and --system

- commands/uploader.go
I think this is a better way to handle the feedback in https://github.com/git-lfs/git-lfs/pull/1905#discussion_r99072847.
> track lock pointers to reduce struct copies

- README.md
> README: Add a status badge for the CircleCI build

- commands/command_lock.go
- commands/command_unlock.go
- test/test-unlock.sh
> Fix `lfs unlock --force` on a missing file

- appveyor.yml
Also refresh the environment properly so both Golang 1.7.4 and Inno Setup are found in PATH.
> Use Chocolatey again on AppVeyor to install Golang 1.7.4

- commands/command_lock.go
- commands/command_locks.go
- commands/command_unlock.go
- commands/commands.go
- commands/commands_test.go
- test/test-lock.sh
- test/test-locks.sh
- test/test-post-checkout.sh
- test/test-post-commit.sh
- test/test-pre-push.sh
- test/test-unlock.sh
Final step of https://github.com/git-lfs/git-lfs/issues/1908
> commands: allow lock commands to be used without env flag

- CHANGELOG.md
- config/version.go
- debian/changelog
- lfs/lfs.go
- rpm/SPECS/git-lfs.spec
- script/windows-installer/inno-setup-git-lfs-installer.iss
Getting the deadlock fix from http://github.com/git-lfs/git-lfs/pull/1932 out to users.
> release: 1.5.6

- test/test-lock.sh
- test/test-locks.sh
- test/test-pre-push.sh
- test/test-unlock.sh
- test/testhelpers.sh
I got tired of seeing this everywhere. Also, the `"()"` was breaking Atom's syntax highlighting and driving me nuts :)
> test: introduce get_lock_id() helper

- circle.yml
This should solve build errors like the one in
https://circleci.com/gh/git-lfs/git-lfs/1012
> CircleCI: Use XCode 8.2 to make brew happy

- appveyor.yml
- script/bootstrap
- script/cibuild
Please have a look at the individual commit messages for the details.
Depends on PR #1980.
> Use system Go 1.8 on AppVeyor

- CHANGELOG.md
- config/version.go
- debian/changelog
- rpm/SPECS/git-lfs.spec
- versioninfo.json
> release: v2.0.1

- docs/man/git-lfs-config.5.ronn
Followup to #1999 to work in @technoweenie's feedback. ❤️ 
I hope that covers the intention  & status quo well enough.
> Reword the introduction to address the changes in config handling

- docs/man/git-lfs-config.5.ronn
The only example I found was in the [LFS wiki](https://github.com/git-lfs/git-lfs/wiki/Tutorial#lfs-url). I think it's prudent to at least provide one example showing how to create the config file in the man page as well.
> Add an example on how to write a `.lfsconfig` file

- commands/command_track.go
- commands/command_untrack.go
- test/test-batch-error-handling.sh
- test/test-batch-transfer.sh
- test/test-checkout.sh
- test/test-chunked-transfer-encoding.sh
- test/test-clone.sh
- test/test-credentials.sh
- test/test-custom-transfers.sh
- test/test-fetch-paths.sh
- test/test-fetch-recent.sh
- test/test-fetch.sh
- test/test-happy-path.sh
- test/test-ls-files.sh
- test/test-pre-push.sh
- test/test-prune-worktree.sh
- test/test-prune.sh
- test/test-pull.sh
- test/test-push.sh
- test/test-resume-http-range.sh
- test/test-resume-tus.sh
- test/test-smudge.sh
- test/test-track-wildcards.sh
- test/test-track.sh
- test/test-untrack.sh
- test/testhelpers.sh
> Backport #2077 for v2.0.x: commands/{,un}track: extract {,un}EscapeTrackPattern()

- commands/command_clean.go
Adds a little more detail to the error message. Fixes #2060
> commands: show real error while cleaning

- test/test-verify.sh
- tq/basic_upload.go
- tq/custom.go
- tq/tus_upload.go
- tq/verify.go
- tq/verify_test.go
> Backport #2083 for v2.0.x: tq/verify: authenticate verify requests if required

- commands/uploader.go
- test/test-pre-push.sh
- test/test-push-missing.sh
- test/testhelpers.sh
- tq/errors.go
- tq/errors_test.go
- tq/transfer_queue.go
> Backport #2082 for v2.0.x: commands,tq: specialized logging for missing/corrupt objects

- docs/man/git-lfs-config.5.ronn
- lfsapi/client.go
- lfsapi/creds.go
- lfsapi/creds_test.go
- lfsapi/lfsapi.go
- lfsapi/ssh.go
- lfsapi/ssh_test.go
> Backport #2080 for v2.0.x: ssh auth and credential helper caching

- commands/command_clean.go
> Backport #2081 for v2.0.x: commands: show real error while cleaning

- docker/README.md
> Backport #2021 for v2.0.x: remove the the duplicate work

- docs/man/git-lfs-config.5.ronn
> Backport #2019 for v2.0.x: Reword the introduction to address the changes in config handling

- docs/api/locking.md
> Backport #2033 for v2.0.x: More lock api documentation fixes

- locking/locks.go
- test/cmd/lfstest-gitserver.go
> Backport #2107 for v2.0.x: locking: send locks limit to server

- commands/uploader.go
- locking/locks.go
- test/cmd/lfstest-gitserver.go
- test/test-pre-push.sh
> Backport #2110 for v2.0.x: commands,locking: don't disable locking for auth errors during verify

- CHANGELOG.md
- config/version.go
- debian/changelog
- rpm/SPECS/git-lfs.spec
- versioninfo.json
> release: v2.0.2

- commands/command_push.go
Signed-off-by: Steffen Prohaska <prohaska@zib.de>
> commands/push: Fix typo in comment

- CHANGELOG.md
- config/version.go
- debian/changelog
- rpm/SPECS/git-lfs.spec
- versioninfo.json
> release: v2.1.0

- docs/man/git-lfs.1.ronn
> Backport #2232 for v2.1.x: Add git-lfs-lock and git-lfs-unlock to help index

- CHANGELOG.md
- config/version.go
- debian/changelog
- rpm/SPECS/git-lfs.spec
- versioninfo.json
> release: v2.1.1

- git/githistory/rewriter.go
- git/githistory/rewriter_test.go
This pull request teaches the `*git/githistory.Rewriter` type to accept a `TreeCallbackFn`, which allows for customizing each re-assembled subtree beyond calling `BlobRewriteFn` on each entry. 
For instance:
```go
_, err := rewriter.Rewrite(&RewriteOptions{Left: "master",
TreeCallbackFn: func(path string, t *odb.Tree) (*odb.Tree, error) {
return &odb.Tree{
Entries: append(t.Entries, &odb.TreeEntry{
// ...
}),
}, nil
},
})
```
which would append any amount of additional entries into the rewritten tree _before_ saving to disk. The caveat of this is twofold:
1. The callers must save new objects to the object database before marking them as reference-able from the rewritten `*odb.Tree` instance.
2. The callers must persist changes to the respective `*odb.Tree`s, as the original history is not …
> git/githistory: provide TreeCallbackFn before saving tree to ODB

- commands/command_status.go
- docs/man/git-lfs-status.1.ronn
- test/test-status.sh
Admittedly, I'm a total golang noob :) (my only other real project being a [bridge to python](https://github.com/asottile/setuptools-golang))
This is for #2289, I'd love some feedback.
> Implement status --json

- git/githistory/rewriter.go
This pull request teaches the `*git/githistory.Rewriter` type how to eagerly generate an in-memory cache of commits to migrate according to the given `*git/githistory.RewriterOptions`. 
We maintain an in-memory cache so that we can log more informative statistics about migrate progress with an upper bound of total commits to migrate. Maintaining this cache in-memory is relatively inexpensive, since each commit is 20 bytes long, plus an additional platform-specific amount of bytes to store a pointer to the underlying `[20]byte` array. The output of a `--topo-order`-ed `git-rev-list(1)` is also stored in memory. Git's builtin also stores this data in memory: [[source][1], [source][2], & [source][3]]
This is required work for the `git-lfs-migrate(1)` command (see discussion: #2146).
---
/cc …
> git/githistory: maintain eager in-memory cache of commit SHAs

- commands/command_clone.go
> Backport #2369 for v2.2.x: commands: only pass --jobs to 'git clone' if set

- commands/command_status.go
- test/test-status.sh
> Backport #2374 for v2.2.x: git lfs status --json only includes lfs files

- git/githistory/rewriter.go
- test/test-migrate-info.sh
> Backport #2383 for v2.2.x: git/githistory: fix hanging on empty set of commits

- docs/spec.md
Closes #2447.
---
Cc: @technoweenie
> spec: mention that an empty file is its own LFS pointer

- tq/transfer_queue.go
This pull request teaches the `*tq.TransferQueue` to correctly alert `Watch()`-ers of duplicate transfers added to the queue.
Prior to this pull request, the `*tq.TransferQueue` would reject new incoming transfers for which an identical OID has already been seen. This behavior was intended to prevent the `*tq.TransferQueue` from performing duplicate work when it was unnecessary to do so.
When implementing the 'delay' capability (see more: #2466), I noticed that not all items I had `Add()`-ed to the `*tq.TransferQueue` would be sent back through the channel I had opened via `tq.(*TransferQueue).Watch() <-chan *tq.Transfer`. This is because, originally, the `*tq.TransferQueue` dropped new transfers that contained duplicate OIDs.
In this pull request, we change this behavior to "remember" a …
> tq: teach Add() to accept duplicate transfers

- lfsapi/creds.go
This pull request fixes a concurrent map read/write issue in the credential cacher, which was pointed out by @canyou2014 in https://github.com/git-lfs/git-lfs/issues/2489.
When using the credential cacher with a `lfs.concurrenttransfers` setting greater than 1, concurrent transfer requests were susceptible to approve/reject credentials at the same time. See the lack of synchronization:
https://github.com/git-lfs/git-lfs/blob/621d1f821f73efcedc829dda43fd9c1fcf07c6ab/tq/adapterbase.go#L154-L172
https://github.com/git-lfs/git-lfs/blob/621d1f821f73efcedc829dda43fd9c1fcf07c6ab/tq/basic_download.go#L113
https://github.com/git-lfs/git-lfs/blob/621d1f821f73efcedc829dda43fd9c1fcf07c6ab/lfsapi/creds.go#L74-L80
This pull request fixes that issue by adding a `*sync.Mutex` guarding read and write …
> lfsapi: synchronize access to credentialCacher.creds

- commands/command_migrate.go
This pull request prevents a failure from hardlinking new objects created during migration when a different filesystem is mounted at `/tmp`.
As pointed out by @ioquatix in https://github.com/git-lfs/git-lfs/issues/2381#issuecomment-327677404:
> I'm using 2.2.1 and I had to do the following:
> 
> ```
> sudo -u http TMPDIR=`pwd`/.git/lfs/tmp git lfs pull
> ```
>
> Otherwise I got the same errors trying to copy files from /tmp to /srv/http/...
Using `tmpfs` mounted at `/tmp` can still cause a cross-device link issue when trying to create a hardlink via `os.Rename()`.
I was curious why this was happening, since we use `lfs.TempDir` and `lfs.TempFile()` for creating temporary files to store objects when migrating. It turns out, however, that failing to call `lfs.InitializeLocalStorage()` will …
> commands/migrate: persistently initialize localstorage

- CHANGELOG.md
- config/version.go
- debian/changelog
- rpm/SPECS/git-lfs.spec
- versioninfo.json
> release: v2.3.0

- CHANGELOG.md
- config/version.go
- debian/changelog
- rpm/SPECS/git-lfs.spec
- versioninfo.json
I think it's a good time to put out a quick `GIT_ASKPASS` bugfix release.
> release v2.3.1

- test/test-askpass.sh
This fixes a failure when building an rpm for centos6.
> askpass test fix

- docs/man/git-lfs-config.5.ronn
- lfsapi/client.go
> bump default activity timeout

- commands/command_clean.go
- commands/command_filter_process.go
- commands/command_migrate_import.go
- commands/command_smudge.go
- commands/pull.go
- commands/run.go
- commands/uploader.go
- config/config.go
- git/git_test.go
- lfs/gitfilter.go
- lfs/gitfilter_clean.go
- lfs/gitfilter_smudge.go
- lfs/lfs_test.go
- lfs/pointer.go
- lfs/scanner_git_test.go
- lfs/util.go
- test/cmd/lfstest-testutils.go
- test/git-lfs-test-server-api/main.go
- test/testutils.go
> Remove last global config

- commands/command_pre_push.go
- commands/command_push.go
- commands/commands.go
- commands/lockverifier.go
- commands/uploader.go
- config/config.go
- config/config_test.go
- lfs/lfs.go
> config: add PushRemote() for checking branch.*.pushRemote and remote.pushDefault first

- script/packagecloud.rb
> Adding Mint Sylvia to packagecloud.rb script

- test/test-migrate-import.sh
This pull request resurrects #2799 which was closed by #2875.
##
/cc @git-lfs/core @larsxschneider
> test: add wildmatch migration tests

- script/packagecloud.rb
This pull request updates our release process to push package releases to Ubuntu Bionic, as per https://github.com/git-lfs/git-lfs/issues/2957.
Closes: https://github.com/git-lfs/git-lfs/issues/2957.
##
> script/packagecloud.rb: release on Ubuntu Bionic

- CHANGELOG.md
- config/version.go
- debian/changelog
- rpm/SPECS/git-lfs.spec
- versioninfo.json
> release: v2.4.1

- CHANGELOG.md
- config/version.go
- debian/changelog
- rpm/SPECS/git-lfs.spec
- versioninfo.json
> release: v2.4.2

- test/testhelpers.sh
> test/testhelpers.sh: look for 64 character SHA-256's

- .travis.yml
- appveyor.yml
- t/t-credentials.sh
- t/t-custom-transfers.sh
> {.travis,appveyor}.yml: upgrade to Go 1.10.3

- CHANGELOG.md
- config/version.go
- debian/changelog
- rpm/SPECS/git-lfs.spec
- versioninfo.json
> release: v2.5.0

- CHANGELOG.md
- config/version.go
- debian/changelog
- rpm/SPECS/git-lfs.spec
- versioninfo.json
> release: v2.5.1

- CONTRIBUTING.md
Update the required version of go to 1.11.0
> CONTRIBUTING: update required go version

- git/attribs.go
This change was discussed in #3200.
> Close attributes file

- CHANGELOG.md
- debian/changelog
- rpm/SPECS/git-lfs.spec
- versioninfo.json
> release: v2.6.0

- git/object_scanner.go
When we read a tree, commit, or tag from gitobj, the object is automatically closed for us, since these objects are relatively small and can be read and parsed all in memory.  However, blob objects may be large, so we return a reader which can be used to read the data from the object.
In order to properly clean up after ourselves, including closing any object files which may open, we need to call Close on the blob after reading it.  Otherwise, we'll eventually run out of file descriptors, causing us to silently hang.  Restore the reset function that was removed in e3fcde74 ("git: replace object scanner with one based on gitobj", 2018-09-05) and ensure we close objects and reset the object scanner between every call to Scan.
> git: close blob objects when finished

- tq/basic_download.go
In 4775f9c1 ("tq: avoid nil pointer dereference on unexpected failure", 2019-02-19), we fixed an issue on uploads where we could dereference a nil http.Response pointer when uploading. We should also check for this when downloading. Since the check a few lines below is now redundant, remove it.
> Avoid nil pointer dereference on download failure

- t/cmd/lfstest-gitserver.go
- t/t-resume-http-range.sh
- tq/basic_download.go
If we're attempting to resume a download but the file we have on disk is the expected size or too large, we'll send an invalid Range header where the lower bound is greater than the upper bound. If this situation occurs, simply retry the download from the beginning, since we clearly don't have the expected data (or we wouldn't be resuming) and it isn't clear how else to recover.
This fixes #3494.
> Retry on oversize file

- t/t-pull.sh
- t/t-push.sh
- tq/adapterbase.go
I found typo in my pr #3590, and fixed it.
Sorry for my carelessness.
> tq/adapterbase: fix typo enableHrefRerite to enableHrefRewrite

- go.mod
- go.sum
- vendor/github.com/git-lfs/gitobj/commit.go
- vendor/github.com/git-lfs/gitobj/pack/set.go
- vendor/modules.txt
This version contains improvements to the pack detection algorithm to let us work with oddly named packs.
Fixes #3654.
> Vendor in gitobj v1.3.0

- README.md
For some time I have not been involved in day-to-day Git LFS development
as I once have, thanks entirely to the care that the current core team
has given the project. Let's make official what has already been the
de-facto norm and move myself to the alumni section.
Working on Git LFS for the couple of years that I was involved has been
a great honor and privilege. I very much appreciate the folks that I've
worked with for giving me a chance to grow as an engineer. Likewise, I
appreciate all Git LFS's users who have made Git LFS a delight to work
on.
Thank you all.
##
/cc @git-lfs/core @git-lfs/alumni
> README.md: move ttaylorr to the alumni section

- go.mod
- tools/util_darwin.go
- tools/util_darwin_test.go
- tools/util_generic.go
- tools/util_linux.go
- tools/util_test.go
In next to linux version https://github.com/git-lfs/git-lfs/blob/master/tools/util_linux.go.
A part of https://github.com/git-lfs/git-lfs/issues/3740.
> Add clone file on MacOS X (darwin).

- lfsapi/auth.go
Go 1.12.8 introduces a security fix for parsing URLs that contain a colon followed by an invalid port number. Since our SSH remotes can contain just such a colon, our hack to make these into URLs no longer works.
Fix this by replacing the first colon in these "URLs" with a slash, which is a path delimiter, which makes them parsable by newer versions of Go. Update the name of the function since it now does more than its previous name implies.
> Fix URL parsing with Go 1.12.8

- tq/transfer_queue.go
In 1412d6e4 ("Don't fail if we lack objects the server has", 2019-04-30), we changed the code to abort later if a missing object occurs.  In doing so, we had to consider the case where the transfer queue aborts early for some reason and ensure that the sync.WaitGroup does not unnecessarily block due to outstanding objects never getting processed.
However, the approach we used, which was to explicitly add the number of items we skipped processing, was error prone and didn't cover all cases. Notably, a DNS failure could randomly cause a hang during a push.  Solve this by creating a class for a wait group which is abortable and simply abort it if we encounter an error, preventing any deadlocks caused by miscounting the number of items.
There's no test for this case because triggering it …
> Avoid deadlock when transfer queue fails

- vendor/github.com/fsnotify/fsnotify/.editorconfig
- vendor/github.com/fsnotify/fsnotify/.gitignore
- vendor/github.com/fsnotify/fsnotify/.travis.yml
- vendor/github.com/fsnotify/fsnotify/AUTHORS
- vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
- vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
- vendor/github.com/fsnotify/fsnotify/LICENSE
- vendor/github.com/fsnotify/fsnotify/README.md
- vendor/github.com/fsnotify/fsnotify/fen.go
- vendor/github.com/fsnotify/fsnotify/fsnotify.go
- vendor/github.com/fsnotify/fsnotify/inotify.go
- vendor/github.com/fsnotify/fsnotify/inotify_poller.go
- vendor/github.com/fsnotify/fsnotify/kqueue.go
- vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
- vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
- vendor/github.com/fsnotify/fsnotify/windows.go
- vendor/github.com/google/slothfs/LICENSE
- vendor/github.com/google/slothfs/cookie/cookie.go
- vendor/modules.txt
We need to vendor these modules so we can build packages for the release.
> Vendor missing modules

- docs/api/authentication.md
- docs/api/basic-transfers.md
- docs/api/batch.md
Signed-off-by: Teng Long <dyroneteng@gmail.com>
> Fix JSON comma problems in docs

- tools/kv/keyvaluestore_test.go
This PR fixes a dropped error variable.
> tools/kv: Fix dropped test error

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/other-issue.md
To help folks provide the information we need to be successful in
helping them, let's provide issue templates that prompt them for
information about their systems.
> Add issue templates

- Makefile
Can we have support for ARM please?
It would close https://github.com/git-lfs/git-lfs/issues/2464
Thank you!
> Makefile: add linux arm build and release targets

- README.md
Add myself (@chrisd8088) to the list of current members of the @git-lfs/core team.
> README: update current git-lfs/core membership

- docs/man/git-lfs-migrate.1.ronn
addresses #4330
/cc @iamhughes
> migrate import: warn about refs on case insensitive file systems

- creds/creds.go
- lfshttp/certs.go
> Translate Cygwin path patches for askpass helper and cert dir/file

- config/netrc.go
- creds/netrc.go
- creds/netrc_test.go
- go.mod
- go.sum
- vendor/github.com/git-lfs/go-netrc/netrc/netrc.go
- vendor/modules.txt
This is related change for solving #4324
> netrc: consider same machine may have different login names

- commands/command_smudge.go
- t/t-filter-process.sh
In most cases, users use a relatively modern version of Git which supports the filter-process code and delayed smudging.  This is valuable because it makes things much faster. However, it also uses a different code path from the non-delayed path. This non-delayed path is also used by git checkout-index.
The non-delayed path doesn't work properly, however, if the data is already on disk.  In such a case, we simply ask the smudge filter not to download the data, but since it's already on disk, we feed it out anyway.
Let's solve this by simply not invoking the filter and emitting the pointer if we've asked to skip.  We do the same thing if the file doesn't match the filter, since the comment at the top of the function states that's what's supposed to happen here as well.
Once we've done …
> smudge: honor GIT_LFS_SKIP_SMUDGE with checkout-index

- lfs/hook.go
Some people store their hooks inside their repository.  This isn't a secure approach, but in some cases it can be acceptable if all users are trusted.
In such a case, if Git LFS always rewrites a hook even if it hasn't changed, it can result in the file being marked as modified by `git status`, since `git status` can invoke Git LFS, which in turn invokes Git LFS, which updates the hooks.  Thus, the hooks will always appear modified.
Let's solve this by not writing the hooks if they haven't changed.  We don't include tests here because the only way to determine if changes have occurred is the mtime, and that's difficult to effectively test in the testsuite in a portable way without introducing sleeps, which would make our tests slow.
Fixes #4865
> lfs: don't write hooks when they haven't changed

- docs/api/authentication.md
note deprecation of NTLM and point to Azure DevOps Server recommendation
> note deprecation of NTLM

- commands/pull.go
Right now, creating a checkout object as used by the checkout and pull commands creates a manifest.  This manifest in turn creates an SSHTransfer object to potentially connect via the new pure SSH protocol. However, connecting to the Internet during `git lfs checkout` is unexpected and may cause this operation to fail when one is not online.
In order to set the manifest's configuration parameters correctly, we need to know whether it's possible to make a pure SSH protocol connection, so it's non-trivial to avoid this connection by delaying the initialization of SSHTransfer object.  Instead, let's lazily create our manifest in the checkout code to avoid creating the connection.  If we're performing a `git lfs pull`, then it will be used and we'll initialize it very quickly, making the …
> commands: avoid remote connections in checkout

- script/windows-installer/inno-setup-git-lfs-installer.iss
This fixes https://github.com/git-lfs/git-lfs/issues/5231.
> installer: let it work on 32-bit Windows again

- tq/transfer_test.go
The three test functions in the `tq/transfer_test.go` source [file](https://github.com/git-lfs/git-lfs/blob/b115c4cf0e0c845b6f652a01207bd65ec90bb388/tq/transfer_test.go) are all named with the prefix `test` rather than `Test`, and as a result, do not actually execute.  This oversight dates from the original introduction of these tests in the `transfer` package in commit 10623f5d7a7d785fb3863c2b190b0f2f99686b7c of PR #1265.  (The package was later renamed to the current `tq` package in commit 891db97a429405f80d54c7e09219bda9799e8e6e of PR #1780.)
We therefore change the test function names to begin with `Test`, and resolve several test regressions which have accumulated since the tests were first added.
First, the `TestBasicAdapterExists()` function calls the `GetDownloadAdapterNames()` …
> tq/transfer_test.go: enable and fix all tests

- Makefile
- script/upload
This adds support for the RISC-V architecture.
> Add RISC-V support

- script/install.sh
add option `--local` to install at `$HOME/.local` and check permission of the prefix before installing
> Add a `--local` argument to install.sh

- ssh/connection.go
Right now, if spawning the remote command fails for some reason, we get a message like the following in the trace output:
pure SSH protocol connection failed: Unable to negotiate version with remote side (unable to read capabilities): EOF
However, all we know is that we failed to connect to the remote `git-lfs-transfer` process.  That could be for any number of reasons: the remote program doesn't exist or is not in `PATH`, the user has misconfigured something locally or remotely, or any number of other problems.  We won't know unless we log the output, so let's do that so we can get more information.
> Include remote error when pure SSH protocol fails

- README.md
@bk2204 is stepping down from the core team, so move them to the Alumni category.
> Move @bk2204 to alumni

- t/Makefile
- t/testhelpers.sh
- t/testlib.sh
Fix when /bin/sh is not bash, or XDG_CONFIG_HOME is set
> t: increase portability

- git/githistory/rewriter.go
- t/t-migrate-import.sh
Android's `repo` tool creates `.git/objects` as a symlink to a place outside the `.git` directory for unknown reasons.  When that happens, Git operations where we set the working directory to that directory fail.  This is because when Git performs discovery on the working directory, it first canonicalizes the path, which takes it outside of the `.git` directory and it then fails to find anything that looks like a Git repository.
In our codebase, we set the path to the object directory root in a couple of places which cause this problem.  To avoid this problem, simply join the repository root with `..`, which is always applied before canonicalization and will result in the path being properly set to the `.git` directory, which results in `git lfs migrate import` working correctly in this …
> Fix migrations where `.git/objects` is a symlink

- docs/man/git-lfs-migrate.adoc
ref: https://github.com/git-lfs/git-lfs/issues/3421
> docs: Provide clearer instructions for non destructive imports
