- .travis.yml
The build failures were actually caused by the git config issue that was fixed later in #181.
> Sudo is not necessary for Travis

- docs/api.md
It's not clear from the documentation that `size` is in bytes, since it's only described as "an integer".
> Specify that `size` property is in bytes

- lfs/setup.go
Properly quote the arguments that are passed to `git lfs push --stdin` just in case they contain any shell metacharacters.
> pre-push hook: properly quote args that are passed along

- docs/spec.md
I'd only read the LFS spec, and not the code - thanks to @mhagger for setting me straight last night at the Git Birthday Party! The support I'm trying to put into the [BFG](https://rtyley.github.io/bfg-repo-cleaner/) has to put files in the same place as the Git LFS client, obviously - I got it [wrong](https://github.com/rtyley/bfg-repo-cleaner/blob/git-lfs-alpha/bfg-library/src/main/scala/com/madgag/git/bfg/cleaner/LfsBlobConverter.scala#L78) because I didn't check the implementation:
https://github.com/github/git-lfs/blob/a0d389385/lfs/lfs.go#L44
https://github.com/github/git-lfs/blob/a0d389385/commands/smudge_test.go#L54-L55
> Spec: clarify that filepath sharding is used in .git/lfs/objects/

- commands/command_push.go
- lfs/client.go
Somehow left this `Finish()` call out in the client rewrite for v0.5.x.  
```
[master 6bc3a3b] booya
1 file changed, 1 insertion(+), 1 deletion(-)
Uploading test1.dat
19.07 MB / 19.07 MB  100.00 %
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 363 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
```
> fix the progress bar output by calling Finish()

- docs/spec.md
- lfs/config.go
- lfs/config_test.go
Fixes #206
```
$ git config remote.master.lfs_url whatever
error: invalid key: remote.master.lfs_url
```
> use remote.{name}.lfsurl to specify an endpoint per remote

- docs/spec.md
Closes #236 /cc @borromeotlhs
Also removed some old bits about the clean filter queueing the file to be uploaded.  The local queue was removed long ago in favor of scanning the commit range in `pre-push`.
> clarify OID-PATH

- docs/spec.md
- lfs/config.go
As I was going through the spec, I realized that `git-lfs` actually reads the config values in backwards.  Local git config values should always overwrite `.gitconfig`.
> clarify how git config is loaded

- lfs/credentials.go
This would've made #209 super easy to troubleshoot.
```
$ GIT_TERMINAL_PROMPT=0 git push dev master
Uploading droidtocat.gif
Change the GIT_TERMINAL_PROMPT env var to be prompted to enter your credentials for https://some-git-lfs-server.com
```
/cc @kevinSuttle
> better error message if you call git-lfs with GIT_TERMINAL_PROMPT

- commands/command_clean.go
- commands/command_pointer.go
- commands/command_smudge.go
- commands/commands_test.go
- commands/pointer_test.go
- commands/smudge_test.go
- docs/man/git-lfs-logs.1.ronn
- docs/man/git-lfs-pointer.1.ronn
- docs/spec.md
- pointer/pointer.go
- pointer/pointer_test.go
Tightens up the pointer spec according from @swisspol in https://github.com/github/git-lfs/issues/233 and https://gist.github.com/swisspol/b9856fcca81029efb960.
> stricter pointer spec

- docs/api.md
- lfs/client.go
- lfs/ssh.go
/cc #242 @ddanier
I'm keeping the issue open until we can figure out how to securely cache the tokens.
> add the optional HREF key to the SSH output

- commands/command_clean.go
- commands/command_pointer.go
- commands/command_push.go
- commands/command_smudge.go
- commands/commands.go
- commands/pointer_test.go
This fails fast in a few commands (`clean`, `smudge`, `pointer`, and `push`) if they expect STDIN, but don't get it.  This commonly happens in `clean` and `smudge` commands if users run them interactively.
Fixes #210
> require stdin content on certain commands

- commands/command_track.go
- commands/track_test.go
@peff suggested setting diff/merge properties in `.gitattributes`.  This gives us and users a place to set custom Git LFS options for diffing and merging.  Since Git LFS has nothing for this now, it should fall back to the default diffing and merging behavior.
Note: This only affects the `git lfs track` command.  Users can still manually add the lines to `.gitattributes` with their own properties.
/cc @mhagger too.
> add diff/merge properties to gitattributes

- commands/command_push.go
- commands/command_update.go
- commands/commands_pre_push.go
- commands/init_test.go
- commands/pre_push_test.go
- commands/push_test.go
- commands/update_test.go
- docs/man/git-lfs-ls-files.1.ronn
- docs/man/git-lfs-pre-push.1.ronn
- docs/man/git-lfs-push.1.ronn
- docs/man/git-lfs-update.1.ronn
- git/git.go
- lfs/setup.go
As discussed in https://github.com/github/git-lfs/pull/228, the push command actually has two modes:
```
$ git lfs push origin master
$ echo "refs/heads/master {local-sha1} refs/heads/master {remote-sha1}" | git lfs push origin https://github.com/some/repo
```
This PR splits them apart into separate commands, and updates the docs.  The old functionality in `push` is kept, until we can safely roll pre-push updates out.
> Split push cmd

- pointer/smudge.go
Quick fix for #266.  It'd be nice if `smudge` could verify files as it's writing them.  But, it simply streams the contents to stdout.  By the time it's realized the file is bad, it's already written to the working directory.  Checking the file before writing to stdout could add significant time when smudging large files.
> fix smudge attempts from zero len file

- commands/clean_test.go
- commands/command_clean.go
- pointer/clean.go
- pointer/pointer.go
This teaches `git lfs clean` to pass Git LFS pointers straight through.  There's no point in saving a pointer of a pointer.
> pass pointers straight through 'git lfs clean'

- commands/commands.go
Trailing periods after filenames cause copy-paste annoyance. Please consider removing this or reformatting the message.
Apologies in advance if I'm ignoring a practise that exists throughout the rest of Git.
> Remove trailing period when printing log file location

- docs/linux-build.md
- script/centos-build
- script/debian-build
- script/install.sh.example
Add instructions for CentOS7, and some missing steps for Ubuntu 14.04.
> Instruction nits

- commands/commands.go
My changes are mostly refactoring.  Non-refactoring changes are:
- Don't return a file name we didn't write to eb12f25
- Write error to stderr, even if os.MkdirAll fails e8c6175
The cases where `os.MkdirAll` and `os.Create` fail, are (still) handled differently and I'm not sure if this was intended in the first place. (The previous code didn't make it that obvious.) Please review.
> Refactored and improved Errorhandling

- lfs/scanner.go
This also keeps the usages of variable 'start' close together.
> Traced performance in case of error too

- lfs/lfs.go
- test/README.md
- test/test-submodule.sh
- test/testhelpers.sh
Adds a failing test on top of https://github.com/github/git-lfs/pull/312 using the new test suite (#306).
> Michael k panic fix

- lfs/lfs.go
Fixes #310
`filepath.Abs()` created `absDir` based on the current working directory.
> Fixed detection of LocalGitDir within submodules

- script/integration
- test/README.md
- test/testenv.sh
- test/testhelpers.sh
This adds a couple new env vars for integration tests:
* `GIT_LFS_TEST_DIR` sets an alternate tmp dir for tests.  Ideally tests run outside of the git-lfs (or any) repository.
* `GIT_LFS_TEST_MAXPROCS` tells `xargs` how many tests to run in parallel.
EDIT: I was unable to get #294 to fail in the new test suite, and realized it was because they were running inside the Git LFS project directory.  Though this is fine for most uses, I think CI systems and possibly core Git LFS devs should export better settings for these env vars.  For instance, it may make sense to turn maxprocs down on Travis, which has just 2 cores.
> configurable tests

- commands/command_track.go
- test/test-track.sh
- test/testhelpers.sh
.gitattributes needs spaces in paths replaced with `[[:space:]]`
Fixes #298
> support tracking paths with spaces in the name

- docs/api.md
While playing with https://github.com/ddanier/django-git-lfs I noticed the documentation for the href attribute is a bit off. If you point git-lfs to /objects it will produce /objects/objects. So the correct URL may not contain "objects". This commit fixes this documentation issue.
> Fixed api.md not containing the correct information about href

- lfs/client.go
I tried implementing an LFS Server in JAVA and came up with this issue. According to https://tools.ietf.org/html/rfc5987, it has to always be "key = value". I also tried this change and my implementation now works (or at least I am one small step further).
> Fix charset http Content-Type header

- script/cibuild
- script/test
- test/test-happy-path.sh
Some minor things I missed from #336:
> Test tweaks

- CONTRIBUTING.md
Add a note in CONTRIBUTING about accepting the CLA.
:warning: This cannot be merged yet :warning:
@bkeepers is going to add an appropriate route to the CLA app, once that's done we can merge this.
> Add a link to the CLA to CONTRIBUTING.md

- docs/api.md
Add braces around the objects in example json response.
> The batch api example json is missing some braces

- lfs/client.go
- lfs/pointer.go
- lfs/pointer_test.go
Git LFS is not intended for zero length files, but it should handle them properly at least.
> Clean empty file

- script/build.go
- test/testhelpers.sh
- test/testlib.sh
When running test scripts and the build fails, the tests are running anyway.  This obscures the build error in case an old executable is still present.
- Return a non-zero exit status if one or more builds fail.
- Exit test with a non-zero exit status if build fails, i.e. fail test.
> Return a non-zero exit status if build fails

- docs/spec.md
Indentation is not as robust as ```.  See https://github.com/github/git-lfs/blob/afbc5818a37793ee1ea17202fde66f50975dbcb8/docs/spec.md
See https://github.com/michael-k/git-lfs/blob/spec/docs/spec.md for rendering (without diff).
> Fixed some (markdown) issues in spec

- lfs/setup.go
This change improve git-lfs performance on Windows, becuase Ms Windows function CreateProcess is too expensive (~0.2 sec per call).
This small change reduce my test repository clone time from 4970 sec to 4352 sec (1.14X faster).
See #376 for more details.
> Remove unnecessary exec the process by filter wrapper

- lfs/download_test.go
See https://github.com/github/git-lfs/pull/378#issuecomment-111231779:
> There are a couple problems that are causing the tests to deadlock.
>
> The first one is easy, some of the download tests are doing a defer reader.Close() in a loop when it should just be closing them immediately, causing the deadlock:
> Do not defer close in loop

- lfs/http.go
> Stats code tweaks

- lfs/lfs.go
- test/test-env.sh
The support for config option `core.worktree` and command line options `--work-tree` and `--git-dir` is still missing.
> Support environment variables GIT_DIR and GIT_WORK_TREE

- git/git.go
- git/git_nix.go
- git/git_win.go
Original problem (https://code.google.com/p/tortoisegit/issues/detail?id=2518):
1. Install Git LFS (https://git-lfs.github.com/)
* Download and unpack archive;
* Put git-lfs.exe on any avaialble in PATH directory;
* Run "git lfs init"
2. Clone repository from: https://github.com/bozaro/test
3. Change image "tux.png"
4. Show "Git Commit" window
On showing "Git Commit" window you will see black window blink for each changed LFS file (twice in this case).
You also will see black window blink on refreshing change list by F5 key.
> Windows: hide git application window.

- lfs/lfs.go
Because Ms Windows has very expensive CreateProcess this operation takes too long time on large file count.
> Remove useless fork per every file for "git version"

- lfs/config.go
There are 2 ways to construct LFS urls - from explicit URLs and from the
clone URL (which gets info/lfs appended). Previously there were multiple
paths where the Endpoint could be constructed in a short-circuit manner
which prevents future expansion in common functions. This standardises
the Endpoint construction so it always happens via NewEndpoint, and
NewEndpointFromCloneURL performs the extra step of appending info/lfs.
This has a current effect of supporting SSH urls in all config settings,
and not just the remote clone URL as before. But mostly this is to enable
future expansion (improved SSH support)
> Consistently construct Endpoint from urls the same way

- script/centos-build
- script/debian-build
The build script for CentOS could not build the man pages on CentOS 6 since ruby 2 is not available. However, there is a way to get ruby via the RVM. That has been added in so that CentOS 6 can build the man pages using this script
Getting golang on CentOS 5 isn't really a "supported" idea, but I looked into a number of work arounds and settled on the simplest one. I saw it mentioned in the comments and gave it a try. If you would rather say NO to CentOS 5, I can remove that, but I can also say that this will build and run git-lfs on a a CentOS 5 Machine (Tested on a 5.11 VM).
Also add the ability to use a currently cloned version of git-lfs, so it does not always clone into /tmp
> Building on CentOS

- .gitignore
- rpm/INSTALL.md
- rpm/SPECS/git-lfs.spec
- rpm/SPECS/ruby.spec
- rpm/SPECS/rubygem-hpricot.spec
- rpm/SPECS/rubygem-mustache.spec
- rpm/SPECS/rubygem-rdiscount.spec
- rpm/SPECS/rubygem-ronn.spec
- rpm/build_rpms.bsh
- rpm/clean.bsh
- rpm/golang_patch.bsh
A set of RPMs that will build git-lfs on CentOS 5, 6, and 7 for #328. A build_rpm.bsh script is included to basically automate installing (and build in the case of CentOS 5 and 6) the build dependencies, and build the git-lfs rpm and srpm
> RPMs for Centos 5/6/7

- .travis.yml
I needed this to debug Travis issues, might be useful for someone else. Usually trying to use Travis with a fork of a golang project fails because the clone path is $fork_user/git-lfs instead of github/git-lfs which breaks package references. Note that this code should work on any golang repo owned by github, in case that's useful.
> Make it possible to enable Travis on forks

- debian/changelog
- debian/rules
Thanks to the new more standard project layout we no longer need to symlink things.  I also bumped the version in preparation for #281.
> Fix the deb package build and bump the version to 0.5.2

- commands/command_env.go
- test/test-env.sh
This breaks all the tests. I see a couple options:
1. Add a switch like `--simple` for tests that excludes the versions.
2. Introduce a NEW command specifically that shows the git lfs version, git version, and git lfs env.
3. Update the tests.
Here are a couple similar commands in other cli tools:
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!
Warning: Your XQuartz (2.7.4) is outdated
Please install XQuartz 2.7.7:
https://xquartz.macosforge.org
$ gem env
RubyGems Environment:
- RUBYGEMS VERSION: 2.2.3
- RUBY VERSION: 2.1.6 (2015-04-13 patchlevel 336) [x86_64-darwin14.0]
- RUBYGEMS PLATFORMS:
- ruby
...
- …
```
> add the git lfs and git version to the top of 'git lfs env'

- lfs/client.go
- lfs/config.go
- lfs/credentials_test.go
- lfs/endpoint.go
This is another approach at fixing #362, built on #403.
This also reorganizes the `Endpoint` code from #403 into a separate file. It can easily be pulled out into a separate PR if needed.
> set request auth from optional endpoint url username/password

- CONTRIBUTING.md
- README.md
- ROADMAP.md
This streamlines the readme a bit. The contributing link is moved up. The high level feature descriptions are delegated to the feature page. The roadmap is also streamlined, so we can use issues to discuss details of the roadmap. The main addition is a section on the first principles behind the tool at the top of the contributing doc.
> streamline the readme/roadmap, add first principles to contributing

- lfs/client.go
Older versions of the API may not include the oid and size in the json payload for the check POST. If they're blank, set them to what we currently have.
> ensure the oid/size are set

- lfs/download_queue.go
- lfs/transfer_queue.go
- lfs/upload_queue.go
This is a fix for a bug in the handling of the `GIT_LFS_PROGRESS` file which is used by desktop apps, or other things integrating with the git-lfs binary.
At a later point, we should move toward a more unified progress tracking which supports this file as well as the pb progress bars via a single API. This file, the pb output, and possibly the `watchers` channel could be unified into a single event stream, cleaning up some of this code.
> Support concurrent transfers when outputting progress for desktop apps

- commands/command_fetch.go
- test/test-fetch.sh
This PR fixes two :bug: :beetle: in the `fetch` command.
1. When fetching the not current branch, the queue would not process, nothing would download.
1. When fetching the current branch, the main routine would not wait for the goroutine that copies files into the wd and updates the git index, possibly leaving the wd in an inconsistent state.
Integration tests for fetch are included.
> Fix two bugs in fetch, add tests

- lfs/transfer_queue.go
The progress tracking code in the transfer queue currently uses 64 bit integers for tracking the number of finished transfers. It sets the values using the `sync/atomic` package. There is an [alignment bug](http://golang.org/pkg/sync/atomic/#pkg-note-BUG) in the package when using int64 on 32 bit architectures.
These don't really need to be 64 bit counters, so to avoid just moving them to the top of the struct and risking them being misplaced later we'll just use 32 bit ints.
> Avoid alignment bugs on 32 bit architectures

- test/test-init.sh
- test/testhelpers.sh
- test/testlib.sh
This simply tests the current behavior in preparation for future `git lfs init/uninit` work.
> add some basic init tests

- lfs/client.go
- test/cmd/lfstest-gitserver.go
- test/test-pre-push.sh
Currently if a server responds with a 307 on POST and the Location header is relative, the re-post fails. 
Relative Location headers are valid and are more convenient for some servers which aren't aware of the original request (e.g. load balancers) without checking for other headers which can vary per routing system. git-lfs should just support relative Location responses.
> Support 307 redirects using relative Location headers

- test/testenv.sh
- test/testhelpers.sh
This is useful if you want to run the existing tests against a specific git-lfs binary.
> teach script/integration how to run against a specific git-lfs build

- docs/api/http-v1-batch.md
- lfs/client.go
- lfs/config.go
- lfs/transfer_queue.go
- test/testhelpers.sh
This PR adds full 401 support for the Batch API.
Related test server PR: https://github.com/github/lfs-test-server/pull/33
> Support 401 responses for Batch API

- commands/commands.go
Avoids display bugs if '%' are used when formatting isn't intended. e.g.
```
$ git lfs init
The clean filter should be "git-lfs clean %!f(MISSING)" but is "git lfs clean %!f(MISSING)"
```
> Error() can display odd output when % is used with no args

- commands/command_pre_push.go
- commands/command_push.go
- lfs/upload_queue.go
- test/test-push.sh
- test/testhelpers.sh
Adds a new option "--objectid" to the push command to upload objects generated by [BFG](https://github.com/rtyley/bfg-repo-cleaner/pull/87). Click [here](https://gist.github.com/larsxschneider/a31fb77c7e9a9c9b81da) for an example how to use it with BFG.
*Note:*
I am learning golang. Please point out to me anything that could be improved. Even if pedantic :smile:
> Add option to push object ID(s) directly.

- test/cmd/lfstest-gitserver.go
- test/test-batch-transfer-unsupported.sh
- test/test-batch-transfer.sh
- test/test-chunked-transfer-encoding-batched.sh
- test/test-chunked-transfer-encoding.sh
- test/test-fetch.sh
- test/test-happy-path.sh
- test/test-pre-push.sh
- test/testhelpers.sh
This replaces the `assert_server_object` and `refute_server_object` helper no-ops with real functions.
This triggered some test failures because the server was tracking just a single set of objects by OID. So `refute_server_object` in one test would fail if another test already pushed it. 
I updated the test server to track unique objects per repo. The mock Git LFS API parses the repo name from a URL like `/{repo}.git/info/lfs/....` and passes it to the mock storage API as a `?r` query param.
> Test helper fixes

- commands/command_fetch.go
- commands/command_fsck.go
- commands/command_ls_files.go
- commands/command_pre_push.go
- commands/command_push.go
- commands/command_status.go
- lfs/scanner.go
- lfs/upload_queue.go
- test/test-commit-delete-push.sh
- test/test-ls-files.sh
This fixes the scanner to find all objects in a commit range, even if an object was added and deleted in that same range. We want all `git lfs push` commands to push every object so that every individual commit is has all the objects it needs.
> Push deleted files

- lfs/config.go
- lfs/config_test.go
- lfs/endpoint.go
- lfs/ssh.go
- lfs/ssh_test.go
* Full SSH urls e.g. ssh://user@host/repo
* Custom ports in both bare and full urls
* GIT_SSH environment for alternate ssh clients
* Explicit support for plink.exe and TortoisePlink.exe
Depends on https://github.com/github/git-lfs/pull/403 (included in PR)
> Improved SSH support: non-bare urls, custom ports, and GIT_SSH/plink

- lfs/endpoint.go
- lfs/ssh.go
Some small changes to #404:
1. Implemented @michael-k's suggestion in https://github.com/github/git-lfs/pull/404#discussion-diff-32717780. It's more clear where and how both `isPlink` and `isTortoise` are set.
2. Removed any ssh stuff from `NewEndpoint()`. It now returns the correct `Endpoint` based on the url scheme. I really hope we don't try to support any other strings without a uri scheme ;)
/cc @sinbad
> Refactor some of the code in #404

- .gitignore
- script/bootstrap
This variable is a bit of a mystery to non-Go developers and it's unclear how you set it up properly. As a result, if it's not set let's set everything up how Go likes it.
Also:
- This will also help keep the Homebrew formula simpler.
- Ignore the `src` directory that we're creating now.
- script/bootstrap: exit on any errors (to be more consistent with other scripts and safer).
- script/bootstrap: remove unneeded `pwd` (the rest of this script assumes it's already in the root of the repository anyway)
Closes #388.
> Setup GOPATH if it isn't already set.

- script/bootstrap
@technoweenie Sorry, pushed an old version in #458 with a syntax error. Works now.
> bootstrap: fix syntax error.

- lfs/client.go
- lfs/config.go
When a batch request received a 401, the request was re-run without resetting the Body, causing the request to error and fall back to individual processing. This just reruns the `Batch()` function.
> Fully re-submit batch requests on 401

- lfs/client.go
This method was not checking the error from doHttpRequest() yet still manipulating the reponse object and body. In some scenarios this can cause a panic when trying to read from the nil reponse body.
Fixes #462
> Check doHttpRequest() error in UploadObject()

- debian/control
- debian/copyright
- debian/git-lfs.lintian-overrides
There were a few issues when running lintian (the debian deb linter) on the package.  This fixes them.
- Add the machine-readable license header that debian requires
- Update to the current standards version (this does not break compiling on older debian releases from what I can tell)
- Add a lintian-overrides file for a few exceptions because golfing doesn't support a few things debian likes.
> Some cleanup to make debian package pass lintian checks

- .gitignore
- docs/linux-build.md
- rpm/INSTALL.md
- rpm/SPECS/git-lfs.spec
- rpm/SPECS/git.spec
- rpm/build_rpms.bsh
- script/centos-build
-CentOS 6 only has git 1.7 available. So I had to take the existing git rpm, and update it to 2.4.5. Ever feature and capability should have been ported (Emacs, perl, etc...) So that it could probably replace the existing git with no ill effect...
-CentOS 5 was pulling an 1.7 version instead of an available 1.8.2 version. The scripts has been updated to pull the compatible version
-Building no longer fails when sudo in not installed requiring the developer to set the SUDO environment variable
-Building the SRPM no longer fails due to bad permissions
Docs updated
-Many (but far less now) integration tests still fail. I'm using this for active software development in CentOS 6.6, and it does work.
> Git for CentOS

- script/fmt
- script/lint
A quick script to warn about importing third party packages directly instead of via nut (i.e. vendored).
Example output if you mistakenly import directly (with an exit code of 1):
```
$ ./script/lint
Non vendored dependencies found:
github.com/cheggaaa/pb
github.com/rubyist/tracerx
```
Normal output (with an exit code of 0):
```
$  ./script/lint
Looks good!
```
> Dependency linter

- lfs/client.go
- lfs/http.go
The `doHttpRequest()` function sometimes returns an HTTP response with no body. This is so we don't need `res` nil checks in places [like this](https://github.com/github/git-lfs/blob/bbf2d1654f924cfaca9aa7dbfa124c36471cfc9e/lfs/client.go#L374).
Should fix #317 and #487
> ensure http responses always have a body

- script/backport-pr
Porting over a backport script from ruby to sh that we use internally at GitHub.
While experimenting with this, I'm pushing to an internal repo that we use for testing.
> initial backport script

- lfs/config.go
- lfs/config_test.go
- lfs/endpoint.go
- lfs/ssh.go
- lfs/ssh_test.go
> Backport #404 for v0.5.x: Improved SSH support: non-bare urls, custom ports, and GIT_SSH/plink

- debian/control
- debian/copyright
- debian/git-lfs.lintian-overrides
> Backport #469 for v0.5.x: Some cleanup to make debian package pass lintian checks

- lfs/client.go
- lfs/http.go
> Backport #472 for v0.5.x: Check doHttpRequest() error in UploadObject()

- README.md
- commands/command_track.go
- docs/spec.md
- test/test-track.sh
> Backport #475 for v0.5.x: Use -text instead of -crlf

- test/test-clean.sh
Handle special characters (\n) in sh script no matter what distro
(Unfortunately...) Fedora/RHEL/CentOS/etc... use the same executable for sh and bash. echo "\n" just happens to be one of the few cases when it will produces different (wrong?) results. In order to make this always work for everyone, when trying to print escape characters, using printf works
With this patch, ALL tests pass in Debian and CentOS!
> Fixed pseudo pointer with extra data test-clean to work on CentOS

- CHANGELOG.md
- Nut.toml
- lfs/lfs.go
Ships v0.5.3 from master. For a fun time, check out [this release thread](https://github.com/github/git-lfs/issues/425#issuecomment-123492545) where I find what looks like a regression, spend a few hours backporting a bunch of commits, and realizing it's not a regression.
> yay v0.5.3

- script/install.sh.example
`install(1)`'s `-D` option used in install.sh is a coreutils specific feature. OS X's
implementation does not support it and some other implementation such
as FreeBSD behaves differently.
This PR fixes this problem so that we can use this install script in those OSes.
> Fix install.sh for OS X, FreeBSD, etc.

- test/testhelpers.sh
This was caused by the fact that you can't disable the osxkeychain helper
if it's set at the system gitconfig (which is the default in recent git),
and the git credential 'store' operation will call ALL helpers, not just
the special one created for the integration tests. Because the test user
environment doesn't have a keychain this caused lots of annoying popup
error messages saying "A keychain could not be found to store X".
> Fix annoying keychain errors when running integration tests on OS X

- lfs/transfer_queue.go
When submitting to debian they found these pedantic typos on codespell.  Sorry for the extra PR noise. :smile:
> Fix typos in transfer_queue.go

- debian/control
- debian/rules
Workarounds and patches to get Debian to cross compile 32-bit on a 64-bit Debian (using the -ai386 flag)
@ssgelm Does this look okay?
> Debain cross compile

- script/integration
e.g. `script/integration fetch status` will run only status & fetch tests
> Allow a subset of tests to be run by script/integration with arguments

- docs/api/http-v1-batch-request-schema.json
- docs/api/http-v1-batch-response-schema.json
- docs/api/http-v1-batch.md
[JSON Schema](http://json-schema.org) is a pretty good format for defining the schema of a data structure. This is the exact schema that we'll be using to validating requests and responses through GitHub's implementation of the server.
Current example request and response:
```js
// REQUEST
{
"operation": "upload or download",
"objects": [
{
"oid": "abc123",
"size": 123
}
]
}
// RESPONSE
{
"objects": [
{
"oid": "abc123",
"size": 123,
"actions": {
// objects will have either a download action,
// or an upload + verify
"download": {
"href": "url",
// optional
"header": {
"Some-Header": "some value"
},
// optional UTC timestamp in iso 8601
"expires_at": "2015-07-20T21:10:55Z"
}
},
// error property is optional
"error": {
"code": "fatal",
"message": "some fatal error occurred"
}
}
]
}
```
/cc …
> initial json schemas for batch api

- lfs/client.go
This allows newClientRequest() to set an Authorization header from either an SSH response or link relation without calling git credentials. Fixes #533 
/cc @jatoben
> newClientRequest() now accepts an initial header

- commands/command_fetch.go
- commands/command_pre_push.go
- commands/command_push.go
- lfs/batcher.go
- lfs/batcher_test.go
- lfs/client.go
- lfs/download_queue.go
- lfs/pointer_smudge.go
- lfs/progress_meter.go
- lfs/transfer_queue.go
- lfs/upload_queue.go
- test/test-pre-push.sh
- test/test-push.sh
This PR splits up batch requests into several batches of `n` (currently hardcoded to 100).
> Batches of n

- script/man
Just a little fix: without the quotes the -x test passes and you get a weird error along the lines of:
`script/man: line 10: man/git-lfs-checkout.1.ronn: Permission denied`
..if ronn isn't installed, instead of the correct error message: 
`Install the 'ronn' ruby gem to build the man pages.`
> Correctly detect the absence of `ronn`

- git-lfs.go
- lfs/lfs.go
- script/build.go
- script/run
I want the version string to include the git commit that built it:
```
$ git lfs version
git-lfs/0.5.3 (GitHub; darwin amd64; go 1.3; git 0cf7c47)
```
This PR gets it working with `script/run version`, but not `script/bootstrap`.
```
$ script/bootstrap
/opt/boxen/chgo/versions/1.3/pkg/tool/darwin_amd64/6l: unknown flag -X github.com/github/git-lfs/lfs.GitCommit 22bb4ab
2015/07/28 16:04:56 exit status 2
exit status 1
```
I'm really not sure why it [fails here](https://github.com/github/git-lfs/blob/0cf7c479e403deee9f8e0cdafa9b6597d22fab71/script/build.go#L132-L139) when it works in `script/run` or running `go build` manually.
A workaround is to create a file like `lfs/aaaaa_version.go`:
```go
package lfs
func init() {
GitCommit = "22bb4ab"
}
```
Such a file could be created and then …
> SHA in user agent

- commands/commands.go
- test/test-logs.sh
I'm tired of asking people for their version info.  This update adds the Git LFS and Git versions to the top. It also throws the git lfs environment at the bottom, so we can see things like their git lfs concurrency setting.
OLD:
```
> git-lfs logs boomtown
LocalWorkingDir=/Users/rick/go/src/github.com/github/git-lfs
LocalGitDir=/Users/rick/go/src/github.com/github/git-lfs/.git
LocalMediaDir=/Users/rick/go/src/github.com/github/git-lfs/.git/lfs/objects
TempDir=/Users/rick/go/src/github.com/github/git-lfs/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=false
GIT_LFS_TEST_DIR=/Users/rick/p/git-lfs-temp
GIT_LFS_TEST_MAXPROCS=4
Welcome to Boomtown
Error!
Inner error message!
goroutine 16 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0) …
```
> re-organize the error logs to make them more useful

- CONTRIBUTING.md
- ROADMAP.md
As we march towards Git LFS v1.0, I want to make sure the installation and upgrade experience is great. @andyneff and @ssgelm have been extremely helpful with getting official RPM and Apt packages built. The homebrew community has been [keeping the recipe up to date](https://github.com/Homebrew/homebrew/search?q=lfs&type=Issues&utf8=%E2%9C%93) too. 
I think our biggest gap right now is Windows (which is also where most of our help requests come from).
The tasks are listed in more detail at #531
> Roadmap: installation experience

- commands/command_checkout.go
- commands/command_fetch.go
- commands/command_pull.go
- docs/man/git-lfs-checkout.1.ronn
- docs/man/git-lfs-fetch.1.ronn
- docs/man/git-lfs-pull.1.ronn
- lfs/lfs.go
- lfs/pointer.go
- lfs/pointer_smudge.go
- lfs/scanner.go
- lfs/transfer_queue.go
- lfs/util.go
- lfs/util_test.go
- test/test-checkout.sh
- test/test-fetch.sh
- test/test-pre-push.sh
- test/test-pull.sh
1. `fetch` no longer updates the working copy, it only downloads files
2. Added `checkout` command which updates the working copy with content if files are missing or are matching pointers. Modified files are left alone (user should reset if they want)
3. Added `pull` command which performs `fetch` and `checkout` for the current ref
4. ~~`fetch` now supports multiple refs as arguments~~
5. `checkout` will correctly populate multiple local files with the same content (old `fetch` would only populate the first one returned from `git rev-list`)
6. `fetch` only adds missing or incorrect objects to the download queue, not all of them. This improves the progress reporting; previously fetch would appear to be trying to download all objects referenced at a ref then only have to download the …
> Add checkout & pull commands, changes and fixes to fetch

- commands/command_fetch.go
- commands/command_pre_push.go
- commands/command_push.go
- lfs/download_queue.go
- lfs/progress_meter.go
- lfs/transfer_queue.go
- lfs/upload_queue.go
There should be a `SuppressProgress()` call on the upload queue when it's doing a dry run. I added it to the `pre-push` stuff but overlooked it for `push`. It only fails intermittently because the progress meter output is written in a goroutine, so during a dry run it's possible that the `push` command exits before the goroutine ever runs. On slower or more utilized machines, like this CI, it gets a chance to run and shows progress output.
> Suppress progress output for a push dry run

- lfs/util.go
- test/test-checkout.sh
Previously using `.` `./` and `.\` would only behave as expected in subdirs
(because calculating the relative dir would resolve it), using them in the
root would match nothing. Behave as expected instead.
> Support `git lfs checkout .` and similar correctly

- script/build.go
When building from a non git checkout the build script would panic when it can't find the commit hash. Instead, just ignore it.
Fixes #548
> Don't panic if we can't find the git commit for the version

- script/build.go
> Backport #549 for v0.5.x: Don't panic if we can't find the git commit for the version

- test/test-worktree.sh
- test/testhelpers.sh
I didn't notice until too late that the skip message from #546 never showed up. The problem is that `comparison_to_operator()` causes the script to halt if it returns something other than `$VERSION_EQUAL` (0) because of `set -e`.
/cc @sinbad
> build a helper for confirming the git version in tests

- lfs/client.go
- lfs/credentials.go
Support credentials from multiple accounts when useHttpPath=true is set in the git config
Provide the URL path to 'git credential fill' for credential helpers that need the path to return the right credentials
Use the objects API URL for credentials so there is a stable path passed to the credential helper for caching
> Support using credentials from multiple accounts against the LFS endpoint

- commands/command_checkout.go
Only displayed when running a separate checkout command, not on pull (lets the download queue do the progress to avoid mixing the 2)
> Add progress meter to checkout

- lfs/extension.go
This was pointed out by @WillHipschman in https://github.com/github/git-lfs/pull/486#discussion_r36108775.
* fewer slice iterations
* slices are initialized with the correct capacity
/cc @ryansimmen since this came from your pr.
> refactor lfs.SortExtensions

- test/test-fetch.sh
- test/testhelpers.sh
Spotted while working on other things that assert_pointer wasn't a good test for fetch, since it only validates that the git commit objects have the right pointer data, not that the content exists locally. 
Added assert_local_object and refute_local_object instead & used in fetch tests.
> Fetch tests should test local storage

- lfs/scanner.go
- lfs/scanner_test.go
This is part of my preparatory work to support the `prune` command; I thought I would submit this part early both to establish its use while I continue working on the specific features, and in case it is useful elsewhere. 
The focus of this PR is the `parseLogOutputToPointers` function which can scan a properly formatted `git log` output & extract relevant changes to LFS references. I've included an example of its use, ScanUnpushed() which shows what oids haven't been pushed anywhere & therefore only exist locally. However it will also be useful for other tasks (e.g. `fetch --recent`). The reason for it being able to scan for additions or removals is that depending on which direction in history you're scanning you might want either one (e.g. scanning backwards from a snapshot date between …
> Adding parsing methods to extract LFS references from arbitrary history

- commands/command_checkout.go
- commands/command_smudge.go
- lfs/pointer.go
- lfs/pointer_smudge.go
- test/test-checkout.sh
This was always the intention but the PointerSmudge functions would automatically do it if the local files were missing. Now they take a boolean argument to say whether to download or not, and the case of skipped smudge is dealt with by writing out the original pointer data and returning a known non-fatal error.
> Never download anything when using the checkout command

- lfs/client.go
- lfs/download_test.go
- lfs/transfer_queue.go
- lfs/upload_test.go
- test/cmd/lfstest-gitserver.go
This adds support for the batch api outlined in #437
> Support new batch API

- lfs/transfer_queue.go
non-batch transfer was stuck when objects already exist on lfs-server
> fix non-batch transfer

- lfs/transfer_queue.go
Previously error went to chan after `q.wait.Done()` so if a caller was blocked on `q.Wait()` it could end up checking `q.Errors()` before the error had been sent to the channel / extracted by errorCollector. Error needs to be sent before `q.wait.Done()`.
> Fix race condition meaning TransferQueue might not report errors in time

- test/cmd/git-credential-lfstest.go
- test/testenv.sh
- test/testhelpers.sh
gccgo silently ignores them, causing tests to fail.
> don't use ldflags in credential tests

- commands/command_checkout.go
This PR will avoid any use of `Panic()` while the `git update-index` loop is running. If the process exits while `update-index` is in the middle of processing a file, the index can be left in an inconsistent, locked state.
/cc #558
> Avoid panic during update index

- ROADMAP.md
- commands/command_init.go
- commands/command_update.go
- lfs/setup.go
- test/test-init.sh
- test/test-update.sh
This adds some tests to confirm that `git lfs update` can automatically update the former pre-push hooks. Also taught `git lfs init --force` how to update the pre-push hook too.
> Extend #582 with more tests

- script/install.sh.example
> Backport #519 for v0.5.x: Fix install.sh for OS X, FreeBSD, etc.

- commands/command_checkout.go
- commands/command_fetch.go
- commands/command_pull.go
- commands/command_smudge.go
- commands/commands.go
- docs/man/git-lfs-fetch.1.ronn
- docs/man/git-lfs-pull.1.ronn
- lfs/config.go
- test/test-fetch.sh
- test/test-pull.sh
- test/test-smudge.sh
Note: don't merge until we've resolved https://github.com/github/git-lfs/issues/564.
Added `lfs.fetchinclude` and `lfs.fetchexclude` config options and `--include` and `--exclude` command line args to fetch. These cause certain paths to either be included or excluded when fetching binaries so that people who work in specific subfolders and don't want to waste time or disk space fetching irrelevant things can do so. This is most common in teams using a single shared repo for all assets but where not everyone needs all of them, e.g. only texture artists might need the original .psd files vs exported runtime equivalents, only modellers/animators might need the original .max files etc. Some teams have a more complex pipeline which avoids this but for those that don't wanting to download by …
> Add include/exclude config options & params to fetch

- commands/command_checkout.go
- commands/command_fetch.go
- commands/command_pull.go
- commands/command_smudge.go
- commands/commands.go
- docs/man/git-lfs-fetch.1.ronn
- docs/man/git-lfs-pull.1.ronn
- lfs/config.go
- test/test-fetch.sh
- test/test-pull.sh
- test/test-smudge.sh
The first arg to fetch & pull is now a remote. In addition, the default remote if you don't specify is now the tracking remote as in `git pull` if it exists, and origin if that's not set. This makes it more consistent with the underlying git workflow especially in triangular fork setups.
Note: I had to base this on top of https://github.com/github/git-lfs/pull/573 to avoid conflicts.
> Add optional remote arg to fetch & pull, and default to tracking remote

- commands/command_pre_push.go
- lfs/scanner.go
- test/test-credentials.sh
this change improves drastically pre-push behaviour, by not sending
lfs objects which are already on a remote. Works perfectly with
pushing new branches and tags.
currently pre-push command analyse "local sha1" vs "remote sha1" of the
ref being pushed and if "remote sha1" is available locally tries to send
only lfs objects introduced with new commits.
why this is broken:
- remote branch might have moved forward (local repo is not up to date).
In this case you have no chance to isolate new lfs objects ("remote sha1"
does not exist locally) and git-lfs sends everything from the local
branch history.
- remote branch does not exist (or new tag is pushed). Same consequences.
But what is important - local repository always have remote references,
from which user created his local branch and …
> major pre-push optimization (alternative: look for deltas against current remote only)

- commands/command_fetch.go
- lfs/client.go
- lfs/errors.go
- lfs/transfer_queue.go
- test/cmd/lfstest-gitserver.go
- test/test-batch-error-handling.sh
A few problems with the batch code error handling can lead to a hang:
/cc #593
> Don't hang when batch calls error

- docs/linux-build.md
Added whitespace for markdown formatting of CentOS bullet points.
> Format CentOS bullet points in linux-build.md

- git/git.go
- lfs/pointer_clean.go
- lfs/scanner_git_test.go
- test/cmd/lfstest-testutils.go
- test/test-push.sh
- test/testhelpers.sh
- test/testutils.go
* Use test.Repo and AddCommits to set up complex multi-branch tests
* Can commit in the past for history tests, branch, merge and tag
* Can generate random data for files or use what you give it
* Returns full detail of the commits created including SHAs and OIDs
* Can pipe JSON from a batch file into lfstest-testutils to get the same
functionality in acceptance tests
* get_date bash util to create commit dates easily on BSD/Mac and GNU
* see test-push.sh for bash example and scanner_git_test.go for go test
> Add enhanced test setup tools for 'go test' and integration tests

- lfs/batcher_test.go
This commit adds the notion of a test case into the `lfs.Batcher` tests. Each
test case has three parameters: a batch size, the number of items to add to that
batcher, and whether or not it should exit the batcher after adding all items.
This commit also adds a helper func called `assertAll` which processes a set of
test cases, throwing assertion errors into the `*testing.T` along the way.
On the other hand, this commit does not contain any utilities to assert that a
deadlock will occur when feeding items into a Batcher, i.e., when the batch size
is set to 0.
> lfs/batcher: introduce test cases

- lfs/batcher.go
- lfs/batcher_test.go
This commit introduces several refactorings to the `run` method (now called
`acceptInput`) on the Batcher type.
- A call to `acceptInput` directly does not spawn a goroutine. The recommended
way to initialize is to spawn it as a goroutine, which is how the constructor
method handles initialization of the Batcher type.
- The responsibility of creating new batches is pushed down into the `newBatch`
func, which allocates a slice of `Transferable`s and sets its capacity at the
maximum batch size.
> lfs/batcher: refactor `run` goroutine

- commands/command_pre_push.go
- test/cmd/lfstest-gitserver.go
- test/test-batch-transfer-unsupported.sh
The test for lack of batch support turned it off globally on the test server then turned it back on, but since the server is shared between parallel tests, this introduces a race condition which can break other batch tests randomly. Instead, use a specific repo name to flag it.
Found this while investigating #625 although this isn't the complete fix. [Edit]Now it is.
> Fix Go 1.5 integration test issues

- commands/command_env.go
- docs/api/http-v1-batch.md
- docs/man/git-lfs-config.5.ronn
- git/git.go
- lfs/client.go
- lfs/config.go
- lfs/config_test.go
- test/test-env.sh
- test/test-pre-push.sh
- test/test-push.sh
- test/test-submodule.sh
This makes two changes for a Git LFS v0.6.0 release:
1. It now sets `lfs.{endpoint}.access` to "basic", not "private". This is an attempt to make the config forward compatible with possible alternate authentication methods, such as NTLM #617.
2. It now tries the batch API by default, setting `lfs.batch` to "false" if it has to fall back to the legacy API.
> batch API changes for v0.6.0

- lfs/credentials.go
- lfs/credentials_test.go
This is needed to disambiguate cases where a user has multiple usernames
on the same host. Without this the first item will be silently used
which might be wrong & cause a loop of incorrect password prompts (&
possibly a lockout on the server)
> Include the username in the creds call if present

- lfs/config.go
- lfs/config_test.go
Adds a more explicit bool parser based on `strconv.ParseBool()`. May want to write to stderr if a config value is invalid (such as `42` or `-1`).
> Config bool checks

- test/test-worktree.sh
Travis didn't spot this because it's using a git version < 2.5.0
> Fix worktree test now that batch is enabled by default

- test/testlib.sh
This PR turns on `GIT_TRACE` when running the integration tests and displays the output when a tests fails.
> Add GIT_TRACE output to integration tests

- lfs/transfer_queue.go
This was causing the intermittent batch error test failures under go 1.5. It was possible that the queue's `Wait()` function returned before all of the errors had been collected. This PR ensures error collection has finished.
> Resolve race condition in transfer queue error collection

- test/test-init.sh
I think it's coming from [here](https://github.com/github/git-lfs/blob/10dbfb5da854b3a4a1aefbb073e4aef7d0f4e898/lfs/attribute.go#L32-L47). Sometimes it returns the smudge error before the clean error. This might be a slight regression from #619. I'll have to see if the older code returned errors for every attribute and not just the first one.
> test for bad clean or smudge attribute

- commands/command_update.go
- git/git.go
- lfs/client.go
- lfs/config.go
- lfs/config_test.go
- lfs/transfer_queue.go
- test/test-update.sh
This removes the `AuthType` type in favor of strings. Also adds some unit tests. The only behavior change is that `Config.Access()` returns "basic" if `lfs.{url}.access` is still using the legacy "private" value.
> Access types

- lfs/client.go
- lfs/errors.go
Raised in #609
The legacy api path had no 401 handling, so the call would be treated as a success, allowing `git push` to exit cleanly. This PR handles a 401 in the legacy path the same way the batch path handles it, i.e. re-prompting for credentials.
> Handle 401 for the legacy api path the same way batch does

- docs/spec.md
In practice, Git LFS preserves the executable status of files when they are cleaned-to/smudged-from pointer files - in fact the [git attributes clean/smudge filter mechanism](http://git-scm.com/docs/gitattributes#__code_filter_code) doesn't actually provide any support for changing the executable status of a file, they just work on the file's contents with standard input & output.
This is good behaviour, because users don't want their big *.exe files to stop being executable when they start using Git LFS, and the executable status is not preserved anywhere else (eg. rightly, it is not stored within the pointer file).
As an example, here are two *.exe files that have been stored with Git LFS, which has preserved their exec bit in the file tree object. Note that `bar.exe` has it's exec bit …
> Fix spec: tree entry for pointer file preserves exec bit

- commands/command_checkout.go
- commands/command_fetch.go
- commands/command_fsck.go
- commands/command_ls_files.go
- commands/command_pull.go
- commands/command_status.go
- commands/command_track.go
- commands/command_update.go
- commands/commands.go
- lfs/errors.go
- script/cibuild
- script/integration
- test/test-checkout.sh
- test/test-credentials.sh
- test/test-fetch.sh
- test/test-fsck.sh
- test/test-ls-files.sh
- test/test-pull.sh
- test/test-status.sh
- test/test-update.sh
- test/testlib.sh
This prevents 7 commands from blowing up because they're not run from inside of a repository. It also makes a couple slight tweaks to the integration test suite:
1. The verbose logs at the end of a failure (server logs and your local env) are ONLY shown from `script/cibuild`. We care about this output on CI servers, but probably not on our local machines.
2. The trace file is truncated after every individual test. This way a test failure will show just its own git trace log, not the trace log for every test that has run in the file.
> In repo check

- commands/command_fetch.go
- commands/command_pre_push.go
- commands/command_push.go
- docs/man/git-lfs-push.1.ronn
- test/test-commit-delete-push.sh
- test/test-pre-push.sh
- test/test-push.sh
- test/testhelpers.sh
This uses the `lfs.ScanRefsMode` scan mode when pushing if the `--all` flag is given. This lets you confirm that everything referenced in the given ref has been pushed to the given remote.
> Push all to remote

- lfs/client.go
While running my QA checks, I noticed that the auth type wasn't being set at all:
```
$ git lfs env
git-lfs/0.6.0 (GitHub; darwin amd64; go 1.5; git 19105ed)
git version 2.3.0
Endpoint=https://github.com/github/git-lfs.git/info/lfs (auth=none)
```
#611 introduced various constructors for different types of requests that the client makes:
* `doApiBatchRequest()` - LFS Batch API requests
* `doLegacyApiRequest()` - Legacy LFS API requests.
* `doAPIRequest()` - Common function for ALL LFS API requests.
* `doStorageRequest()` - Storage requests (these actually upload and download the objects).
`doAPIRequest()` requires credentials for all non-GET requests. But all Batch API requests are POST. This is a pretty small change, but highlights that the project needs better tests around this stuff.
> always consult PrivateAccess() for batch API calls

- CHANGELOG.md
- lfs/credentials.go
- lfs/credentials_test.go
This fixes a regression with the Git LFS v0.6.0 client and GitHub Enterprise 2.2.8/2.3.2.
/cc @ginja
> Skip credential check if url has ?token

- docker/bootstrap_centos_5.dockerfile
- docker/bootstrap_centos_6.dockerfile
- docker/bootstrap_centos_7.dockerfile
- docker/build_dockers.bsh
- docker/centos_script.bsh
- docker/debian_script.bsh
- docker/git-lfs_debian_7.dockerfile
- docker/git-lfs_debian_8.dockerfile
- rpm/build_rpms.bsh
Added GOLANG_VERSION to override golang version
Disabled dependecy checking when building packages to support external
golang
Changed DOCKER_LFS_BUILD_VERSION to default to master instead.
> Added go 1.5.1 to docker scripts (via binary distro)

- .travis.yml
This removes Go 1.3 and 1.4.2 from the tests. As of v0.6.0, we're now shipping all binaries compiled with Go 1.5.1. The linux packages also bundle Go 1.5.1 to compile.
Obviously, our tests will run in about 1/3rd the time. We can also start supporting newer std lib features and code syntax that we couldn't with Go 1.3.
Any objections? This should only affect git lfs contributors and homebrew users. I think we can configure the git lfs recipe to require Go 1.5+ though.
> Stop testing Go 1.3 and 1.4.2

- git/git.go
- git/git_test.go
This PR for command `git lfs ls-files` and then error `index out of range` issue according #664
> Fixed git lfs ls-files then index out of range error.

- commands/command_ls_files.go
- git/git.go
- test/test-ls-files.sh
I like having integration tests for stuff like #668. Partly because it forces me to see how the error is handled externally. This changes the `git.CurrentRef()` error check to simply print an error and exit, as opposed to logging a stack trace.
@Aorjoa: This is just a bit of polish on your fix in #668
> add an integration test to prove #668 works

- .gitignore
- commands/commands.go
- docs/man/mangen.go
- script/build.go
Call 'go generate ./commands' to generate code from .ronn files which the cobra command can then use. Added to the build scripts but needs to be done manually at least once to test it outside that. 
I've done the minimum re-formatting for now. The man format is pretty damn ugly on the command line and I'd like to do better but didn't want to spend time on that until the principle was approved. For now it just fixes the backtick issue, other things we could do:
* Strip off the 2-line headers
* Strip 'SYNOPSIS' and pull out the command summary as the first line
* Strip '##' section markers generally
* Use an abbreviated form for `command --help` (just contents of SYNOPSIS, DESCRIPTION and OPTIONS) and only print the full text for `help command`. Cobra splits this as Usage/Help, currently …
> Use man content for `help <cmd>' and '<cmd> --help'

- lfs/transfer_queue.go
Reported in #673 
A nil check in the wrong place was preventing the retry mechanism from working in the older single mode API which had the side effect of allowing git-lfs to exit cleanly even though it failed to push.
> Properly handle retries when using "legacy" API

- lfs/client.go
This simple change goes from errors like this:
```
$ git push origin master
(0 of 1 files) 0 B / 33 B
Error for POST http://localhost:8124/rubyist/foo3/objects/batch
error: failed to push some refs to 'http://github.com/rubyist/foo3.git'
```
To this:
```
$ git push origin master
(0 of 1 files) 0 B / 33 B
Post http://localhost:8124/rubyist/foo3/objects/batch: read tcp 127.0.0.1:8124: connection reset by peer
error: failed to push some refs to 'http://github.com/rubyist/foo3.git'
```
This error path can be triggered by a number of network issues, this lets the original error message bubble through which can help in debugging. The data from the message we were providing is already included in the original error string.
> A nicer network error

- .travis.yml
- commands/command_init.go
- commands/command_update.go
- lfs/hook.go
- test/test-init.sh
- test/test-update.sh
Instead of requiring `git lfs update` to be run inside a git working directory, this relies on `lfs.LocalGitDir` to install the hooks in the correct place.
/cc @ttaylorr since you touched hook code recently. Though I'm pretty sure I'm the one that added the invalid repo error.
> teach 'update' cmd how to install hooks in bare repos

- commands/command_checkout.go
- commands/command_clean.go
- commands/command_env.go
- commands/command_ext.go
- commands/command_fetch.go
- commands/command_fsck.go
- commands/command_init.go
- commands/command_logs.go
- commands/command_ls_files.go
- commands/command_pointer.go
- commands/command_pre_push.go
- commands/command_pull.go
- commands/command_push.go
- commands/command_smudge.go
- commands/command_status.go
- commands/command_track.go
- commands/command_uninit.go
- commands/command_untrack.go
- commands/command_update.go
- commands/command_version.go
- commands/commands.go
- docs/man/git-lfs-pull.1.ronn
- docs/man/git-lfs.1.ronn
- docs/man/mangen.go
A few minor tweaks. The output of `help subcmd` and `subcmd -h` are now identical. Also, leading and ending linebreaks are consistent.
/cc @sinbad
> Docgen fixes

- commands/command_env.go
- commands/command_init.go
- commands/command_smudge.go
- docs/man/git-lfs-smudge.1.ronn
- git/git.go
- lfs/attribute.go
- lfs/setup.go
- test/test-env.sh
- test/test-init.sh
- test/test-smudge.sh
- test/testhelpers.sh
This is an attempt at a workaround for #616. It's not ideal, but it gives users a way to optimize their downloads at the cost of complicating the git workflow a bit.
```bash
$ git clone foo/bar.git
$ GIT_LFS_SKIP_SMUDGE=1 git clone foo/bar.git
$ git lfs pull
```
That workaround sucks. We can make this better for users with:
```bash
$ git lfs init --skip-smudge
$ git lfs init --skip-smudge --local
```
> smudge passthrough

- README.md
- docs/README.md
This adds a few more crucial details. This is just a start.
1. PackageCloud and Homebrew are listed as official release channels for Git LFS now.
2. The doc homepage is expanded a bit and includes a spot for video tutorials.
3. The new `help` command is featured.
> Better readme

- lfs/errors.go
- lfs/pointer.go
- lfs/pointer_test.go
- test/test-pull.sh
- test/test-smudge.sh
Git LFS uses a few properties to determine whether something is a valid LFS pointer or not. Right now, the criteria is:
1. Below the blob size threshold (1024 bytes)
2. Contains `git-lfs` in the content.
This causes problems for small test files like "this is a sample git-lfs file." So, it assumes anything that doesn't even start with `version` isn't even trying to be a Git LFS file.
/cc @rubyist: Did this by elevating the bad pointer key message to its own error type.
> Better handling for tiny files below the blob size threshold that contain 'git-lfs'

- commands/command_ls_files.go
- docs/man/git-lfs-ls-files.1.ronn
- test/test-ls-files.sh
This builds on #680:
* `lfs.ScanTree()` is used _instead of_ `lfs.ScanRefs()`. Duplicate files are now shown.
* The output includes the LFS OID and whether the file has the lfs pointer or the actual contents.
> Ls files fixes

- lfs/client.go
- test/test-batch-error-handling.sh
A status of 403 against the API would be masked with a generic message. This displays a more specific message - either one returned in the API json, or a default message about authentication.
> Display the specific error in the case of a 403

- test/test-smudge.sh
It was erroneously succeeding when that was set because the test was incorrect, should have been checking the env did NOT include GIT_LFS_SKIP_SMUDGE after unsetting. However any LFS env setting would false-positive and therefore work in Travis.
> "smudge with skip" test would fail if GIT_LFS_TEST_DIR was not set

- lfs/ssh.go
It's fix authentication issue on ssh error messages like:
```
X11 forwarding request failed
```
> Use separate buffers for stdout and stderr on executing git-lfs-authenticate

- commands/command_checkout.go
Also report stderr/out since error object is often something useless like "exit status 128".
To help with #725.
> Use LoggedError instead of Panic if update-index fails in checkout

- commands/command_smudge.go
This will cause the git checkout to abort instead of continue on as if things are OK.
/cc https://github.com/github/git-lfs/issues/731
> Exit 1 if a smudge fails

- git/git.go
- lfs/lfs.go
- test/test-env.sh
This causes tests to fail if GIT_LFS_TEST_DIR is not set, since the bare repo tests actually cascade up to the git-lfs repo itself and start modifying config files in there. Might potentially affect other cases where a bare repo is inside a non-bare repo.
Resolution is to use `git rev-parse` to locate all dirs instead of manually recursing. Could potentially remove manual processing of GIT_DIR and GIT_WORK_TREE in future but have left as belt & braces for now.
Had to remove test for using relative GIT_WORK_TREE with no GIT_DIR, git rev-parse always fails in that case so it appears it's not supported by git even though man git-config claims it is.
> Fix resolve of git dirs finding a parent non-bare repo if wd is a bare repo

- commands/command_fetch.go
- commands/command_pull.go
- commands/command_status.go
- git/git.go
- git/git_test.go
- test/test-fetch.sh
This fixes #660 and also improves a few other areas:
* Default remote is now either the tracked remote, or "origin" or any other *single* remote defined. If all of these fail there's a better error message now.
* User-supplied remotes are now validated to avoid ambiguous fail cases
* General tidy up to make it clearer what each of these git package functions are intended to do
> Improved default remote behaviour & validation for fetch/pull

- commands/command_fetch.go
- lfs/transfer_queue.go
- test/cmd/lfstest-gitserver.go
- test/test-fetch.sh
- test/testhelpers.sh
Raised as part of #731 
Includes some changes to the test git server which actually wasn't strictly complying with the 1.0 API spec. Also includes a couple of tweaks to make errors from transfer queue identifiable to the oid that caused them.
Added a 'delete' method to the git test server just for testing purposes, to create a failing condition.
> Make fetch return error code when 1+ downloads failed

- commands/command_init.go
- commands/command_update.go
- lfs/lfs.go
- test/test-init.sh
- test/test-update.sh
Fixes #717 and supercedes #752.
1. Only skips the tests in docker IF `LFS_DOCKER` is set. This may change before we ship 1.0.1, but at least now I know ALL tests run locally and on Travis.
2. Changed `lfs.InRepo()` so it looks for an empty `LocalGitDir`, instead of `LocalWorkingDir`. Bare repositories have no working directory.
3. Updated the `update` and `init` tests to check that the hooks dir is not created.
> Improve lfs.InRepo() detection in `init`/`update`

- git/git.go
- lfs/attribute.go
Attribute checks whether it thinks the setting is already in the desired state before setting, but for global options was using plain `Find()` which uses `git config` without any flags, which makes it pull in local state too. It should have been using the `--global` flag to get the current value just like it does when setting it. 
Before this fix it could incorrectly assume the global setting is there already and skip setting it, even though when you move out of that folder the setting disappears. This was causing some random failures on Windows tests. Separated from the rest of the Windows test fixing work because it's actually a general bug.
> Fix not setting global attribute when needed to b/c of local state

- lfs/client.go
The smudge filters still used the direct legacy api via the `Download()` function. This PR provides a new `Download()` which uses the batch API and falls back to a `DownloadLegacy()` if the server does not support the batch API.
This fixes #708
> Use batch API for Download, fallback to legacy if unsupported

- lfs/config.go
- test/test-config.sh
- test/test-env.sh
This whitelists the valid keys that are read from `.gitconfig`. Git LFS can't make Git read options from `.gitconfig` by default, but it should be explicit about what it allows.
* `lfs.url`
* `remote.{name}.lfsurl`
* `lfs.extension.{name}.priority`
The `.gitconfig` file is designed for common settings for all users cloning.  IMO the other settings should be set by a user's standard git config.
> whitelist the valid keys from .gitconfig

- commands/command_smudge.go
- test/test-smudge.sh
Smudge command should return 0 if download was optional and didn't occur
> Fix clone fail when fetch is excluded globally (#759)

- lfs/config.go
The `lfs.fetchinclude` and `lfs.fetchexclude` keys seem save to read from the working directory's `.gitconfig` file. /cc @sinbad @ptoomey3 
Docs: https://github.com/github/git-lfs/blob/master/docs/man/git-lfs-fetch.1.ronn
> Allow lfs.fetchinclude and lfs.fetchexclude in .gitconfig

- docker/run_dockers.bsh
Moved the the docker image generation to a separately maintained repo
and upload the images to docker hub instead. Should be a far friendlier
experience for the developer.
Almost all of the files in the docker folder should be redundant save
the `run_dockers.bsh` file at this point.
> Change the run script to download docker images instead of build

- script/fmt
- script/integration
- script/integration.go
- script/script.go
- test/test-init.sh
- test/test-uninit.sh
- test/test-update.sh
- test/testhelpers.sh
- test/testlib.sh
Replace 3 highly compact shell lines in `script/integration` with 100 lines of go code. It uses goroutines to manage the concurrency, and a channel to ensure output is dumped to stdout without race conditions.
/cc @andyneff @rubyist @sinbad
> rewrite test runner in go to reduce output race conditions

- script/integration.go
I had a failure after #790 but it was because I had an old .orig file in my test dir from a previous rebase conflict.
> Make sure we don't accidentally run *.sh.orig (merge remnants) in test

- CHANGELOG.md
- script/integration.go
- script/packagecloud.rb
- test/test-happy-path.sh
`script/integration.go` doesn't work on Windows. This fixes the easy bugs:
* file patterns didn't use back slashes
* use `which` to find the correct bash path
It still shows no output for each test though.
> Fix windows integration

- lfs/client.go
- lfs/download_test.go
- lfs/pointer_smudge.go
This fixes a devious bug that affects strict LFS API servers that verify the size of objects before it lets you download them. 
The update is hopefully temporary, until we refactor the API client as described in https://github.com/github/git-lfs/issues/779.
You can see this at play with `GIT_CURL_VERBOSE`:
```bash
$ git cat-file -p 1bca198451cc7404e257e5abe60a8478bf28d4cf | GIT_CURL_VERBOSE=1 git lfs smudge
Downloading ... (73.53 KB)
> POST /github/git-lfs-test.git/info/lfs/objects/batch HTTP/1.1
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic abcdef
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/1.0.1 (GitHub; darwin amd64; go 1.5.1; git a999185)
>
{"objects":[{"oid":"e1732d149d262963996ca77a47a5d3c51c85c6e97187afad370a8bef28 …
```
> teach 'git lfs smudge' to send the expected size to the LFS api

- lfs/ntlm.go
- lfs/ntlm_test.go
This is a proposal to merge into #820. It's complicated enough that I think it could use its own review.
Instead of buffering the entire request body into an in-memory byte buffer, this uses an internal `cloneableBody` type that only buffers up to 1MB. Any overflow is then written to a local temp file. This type can also clone itself without reading the body again. It simply creates a new struct with the same 1MB byte buffer, and re-opens the temp file.
Also, assuming all file handles are properly closed, a `cloneableBody` buffer will only delete the tempfile when the last one is closed.
> NTLM: cloneable body

- commands/command_env.go
If there are multiple remotes for the current repo, `git lfs env` shows wrong SshUserAndHost for remote endpoints.
> env: Show proper SshUserAndHost for remoteEndpoint

- commands/command_smudge.go
- test/test-smudge.sh
This change makes it so --skip does the smudge if the file
is in cache. It still skips automatic downloads as one would
expect.
This is more convenient, since it prevents one from having
to 'git lfs pull' after every 'git checkout' if the needed
objects are already available in .git/lfs/objects.
Note that the --skip option for smudge is documented as
follows:
"Skip automatic downloading of objects on clone or pull."
So even after this change we're still in line with the
documentation.
> smudge --skip will now smudge if object is in cache.

- docker/run_dockers.bsh
- rpm/SPECS/git-lfs.spec
- rpm/build_rpms.bsh
- script/bootstrap
- `run_dockers.bsh` can now auto pull the latest docker images
- More verbose (and un cut) output of 64 bit rpm builds build. No more redirect to `build.log`
- RPMs use GIT_LFS_TEST_DIR in %check
> Docker and rpm updates

- commands/command_env.go
- docs/spec.md
- git/git.go
- lfs/config.go
- test/test-config.sh
- test/test-env.sh
This changes Git LFS to read committed lfs config settings from `.lfsconfig` instead of `.gitconfig`. This makes it more clear what settings should go in that file. It does continue to check for `.gitconfig` but only IF `.lfsconfig` does not exist. This is meant as a way for projects to gradually rename this file on their own. By Git LFS v2.0, we'll remove support completely.
This also makes a few other changes:
* `ListFromFile()` doesn't run `os.Stat` anymore. The new `readGitConfigFromFiles()` function minimizes `os.Stat` calls.
* The config order was tweaked slightly, reducing the number of `git config` calls. No need to call `git config --list` AND `git config --file .git/config --list`. Now it only calls `git config --file .lfsconfig --list` and `git config --list`.
Fixes #780
> use .lfsconfig (with fallback to .gitconfig)

- README.md
- commands/command_init.go
- commands/command_install.go
- commands/command_uninit.go
- commands/command_uninstall.go
- docs/man/git-lfs-clean.1.ronn
- docs/man/git-lfs-config.5.ronn
- docs/man/git-lfs-init.1.ronn
- docs/man/git-lfs-install.1.ronn
- docs/man/git-lfs-smudge.1.ronn
- docs/man/git-lfs-track.1.ronn
- docs/man/git-lfs-uninit.1.ronn
- docs/man/git-lfs-uninstall.1.ronn
- docs/man/git-lfs-untrack.1.ronn
- docs/man/git-lfs.1.ronn
- docs/spec.md
- script/install.sh.example
- script/nsis/installer.nsi
- test/test-install.sh
- test/test-uninstall.sh
This renames both `git lfs init` and `git lfs uninit` to `git lfs install` and `git lfs uninstall`.  The old commands will be available until Git LFS v2.0.
Fixes #781
> Rename "Init" command to "install"

- lfs/client.go
- lfs/config.go
- lfs/credentials.go
- lfs/http.go
- test/test-credentials-no-prompt.sh
- test/test-credentials.sh
This prevents Git LFS from getting into an auth loop if no git credentials are found. It also adds a bit more tracing so we don't have to reach for `GIT_CURL_VERBOSE` as often. And when we do, its output is cleaned up a bit with extra linebreaks.
> Cred fixes

- script/debian-build
Ubuntu repositories no longer offer the Ruby2.0 package, thus breaking the script
> Debian build script shouldn't depend on a specific version of Ruby

- lfs/client.go
- lfs/download_queue.go
- lfs/download_test.go
- lfs/pointer_smudge.go
- lfs/transfer_queue.go
- lfs/upload_queue.go
- lfs/upload_test.go
objectResource is returned by several public functions but isn't exported itself, so fix that. 
Context: I'm using calls to Batch() in my server API test tool which is outside the LFS package & need to see the results. I remember I also needed it when refactoring the API for my old SSH PR so I think it's likely to be useful generally.
> Export ObjectResource

- debian/control
Since git-lfs requires git >= 1.8.2 this ensures that people don't accidentally install it with older versions of git
> Add git version dependency to 

- lfs/config.go
We don't care if other git values clash.
> only show git config warnings for lfs keys

- lfs/client.go
If using an SSH URL and git-lfs-authenticate returns an error, without this change the error is just reported to the trace but execution continues.
A common result is a completely made up LFS URL being returned which then 404's, which ends up setting lfs.batch=false. If the server doesn't implement the non-batch interface, this config then breaks LFS even after the SSH issue is resolved & has to be manually removed, which is quite confusing for the user.
> Fix fallthrough when git-lfs-authenticate returns an error

- commands/command_status.go
- git/git.go
Having both `git.CurrentBranch()` and `git.CurrentRef()` seemed redundant.
> Remove git current branch

- commands/command_env.go
- docs/man/git-lfs-config.5.ronn
- lfs/client.go
- lfs/config.go
- lfs/config_test.go
- lfs/credentials.go
- lfs/ssh_test.go
Fixes #945 
Right now git-lfs ignores the use of 'remote.[name].pushurl' in asymmetrical pull/push situations (within a single remote). This PR changes the way Endpoints are built so that the operation ("download" or "upload") is taken into account and the pushurl is used as a basis instead of the url when pushing. This avoids git-lfs behaving inconsistently with Git itself & the resulting confusion.
Also add support for 'remote.[name].lfspushurl' and global 'lfs.pushurl' so that push versions of urls are supported everywhere you might configure them.
This also affects the Access flags which are stored & looked up alongside the correct url based on whether you're pulling or pushing, in case the 2 urls have different auth mechanisms.
> Support remote.name.pushurl correctly to fix #945

- git/git.go
- lfs/lfs.go
- test/test-commit-delete-push.sh
- test/test-submodule-lfsconfig.sh
- test/test-submodule.sh
This is another approach to fixing #922.
While #927 fixes the bug, I'm not completey happy with it. Calling `git.RootDir()` in `loadGitConfig()` adds another os exec that's run on _every_ lfs command. This is in addition to when it's run inside `resolveGitDir()` if the `GIT_DIR` is specified. I'd like to fix the behavior without running `git.RootDir()` again.
The problem: `git submodule update --init --remote` runs `git lfs smudge` commands with the following env:
```
GIT_DIR=/path/to/repo/.git/modules/sub
GIT_WORK_TREE=.
```
When run with the above ENV vars, `LocalWorkingDirectory` is `/path/to/repo/.git/modules`, which is wrong. It should be `/path/to/repo/sub`, where `sub` is the path for the submodule. Here's the [code](https://github.com/github/git-lfs/blob/84e9e66c9156564180c96214918 …
> Fix submodule lfsconfig

- lfs/pointer.go
- lfs/pointer_test.go
This PR fixes the reported behaviour in https://github.com/github/git-lfs/issues/557, where Git reports
a delta, if an attempt was made to track empty files with LFS.
If there already have been empty files tracked with LFS, these
need to be untracked manually, as this fix only prevents that
newly created, empty files can be tracked by LFS.
Problem is, that Git never runs the clean filter on 0-byte files:
https://github.com/git/git/blob/80980a1d5c2678ab9031d7c60faf38b9631eb1ce/diff.c#L2777
This leads to a diff between the file in the repository (pointer file) and 
the actual file content. Apparently the git-fat project seems to be affected 
by this, too (https://github.com/jedbrown/git-fat/issues/18).
The fix/workaround for this in LFS is simple; just don't create pointers 
for 0-byte …
> Don't create LFS pointer for empty files

- lfs/config.go
- lfs/config_test.go
- lfs/endpoint.go
This converts `git://SERVER/REPO` remotes to an LFS URL like `https://SERVER/REPO.git/info/lfs`. This removes the need for users to manually configure the LFS url.
> convert git:// remotes to the lfs default

- lfs/client.go
- lfs/config.go
- test/git-lfs-test-server-api/.gitignore
- test/git-lfs-test-server-api/README.md
- test/git-lfs-test-server-api/main.go
- test/git-lfs-test-server-api/testdownload.go
- test/git-lfs-test-server-api/testupload.go
- test/testhelpers.sh
Created a tool called `git-lfs-test-server-api` which can be pointed at either an API URL or a clone URL and will run through a series of tests to ensure the responses are as expected. See the `Readme.md` for details of how to use it.
Currently only tests the API responses to upload/download and through inference correct authentication; HTTPS or SSH, works with both via `--clone=<url>`. Relies on the internal methods to test that content types etc are respected. In order to try to keep it simple to update in future, it just calls the `Batch()` method rather than trying to dig any deeper than that.
It can either generate its own test data (in which case it needs to be able to upload some initial state, although it doesn't push any commits, only LFS files), or it can be given lists of data …
> Add server API test tool

- commands/command_fetch.go
Finally tracked down and fixed the bug in reproduced from https://github.com/github/git-lfs/issues/904#issuecomment-169010912.
I couldn't replicate the issue with `git lfs fetch` and `git lfs checkout` individually, so I assumed the problem [came from `command_pull.go`](https://github.com/github/git-lfs/blob/064043040e1003b51f86b65c14d3f9bedc137f30/commands/command_pull.go#L45-L46).
I added some trace messages and noticed `fetchAndReportToChan()` wasn't [receiving all of the oids](https://github.com/github/git-lfs/blob/064043040e1003b51f86b65c14d3f9bedc137f30/commands/command_fetch.go#L288-L296), even though everything was downloading just fine. Turns out the transfer queues start working in the background as soon as [something is added to the …
> setup the transfer queue watcher BEFORE processing any LFS pointers

- git/git.go
- git/git_nix.go
- git/git_test.go
- git/git_win.go
- script/cibuild
The `git` package provides an api around the `git` command. It doesn't make sense to pass any `GIT_TRACE` env values to it. Here are the errors just from the tests:
```
$ GIT_TRACE=1 script/test git
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
--- FAIL: TestCurrentRefAndCurrentRemoteRef (0.21s)
assert.go:16: /Users/rick/go/src/github.com/github/git-lfs/git/git_test.go:53
assert.go:25: ! Sha: "12:08:04.097045 git.c:348               trace: built-in: git 'show' '-s' '--format=%H" != "8263b6dfdc1ec816145ab1635d3719d54bfa8d67"
trace git-lfs: RECENT: Getting refs >= 2016-01-27 12:08:04.156600185 -0700 MST
trace git-lfs: RECENT: master (2016-02-03 12:08:04 -0700 MST)
trace git-lfs: RECENT: included_branch_2 (2016-01-31 …
```
> don't pass GIT_TRACE to exec.Command calls in the git package

- commands/command_pre_push.go
- commands/command_push.go
- test/test-fetch.sh
- test/test-pre-push.sh
- test/test-push.sh
> guard against invalid remotes passed to `git lfs push`

- commands/command_track.go
- test/test-track.sh
Attempt to fix #870. The `git lfs track` command currently checks given patterns against the current working directory, preventing users from tracking files outside the repository. As pointed out in #870, this is actually incorrect. Via [gitignore docs](https://github.com/git/git/blob/f5b6079871904ba5b0a8548f91545f126caf898b/Documentation/gitignore.txt#L112-L114):
> A leading slash matches the beginning of the pathname. For example, `/{asterisk}.c` matches `cat-file.c` but not `mozilla-sha1/sha1.c`.
This removes that check, and the related tests.
> pass gitattributes patterns (mostly) unchanged

- docs/man/git-lfs-config.5.ronn
- lfs/config.go
- lfs/http.go
Allow clients to tweak the lfs http timeouts through the git config. It also bumps the normal timeout from 5s to 30s. I think the newer values make more sense for a command line tool.
> Tunable timeouts

- lfs/util.go
- lfs/util_generic.go
- lfs/util_linux.go
Use btrfs copy-on-write feature for copy lfs files from .git/lfs/objects to working copy (```git lfs checkout```).
Copy-on-write operation is look like hardlink, but change in one file is not visible in another file.
This command works like: ```cp --reflink=auto src.txt dst.txt```
For this change I use https://github.com/wertarbyte/coreutils/blob/master/src/copy.c as reference.
> Add copy-on-write support for Linux BTRFS filesystem

- script/build.go
Dang, forgot to merge this. Fixes cross compilation on my windows vm.
EDIT: `script/bootstrap -os=windows -arch=386` was complaining about writing to `c:\windows\go-build...` because no TMP value is available. That's because `build.go` is setting `cmd.Env` with the `GOOS` and `GOARCH` values.
> Build all temp env

- .travis.yml
- test/test-credentials-no-prompt.sh
With the latest Git installed (2.7 right now) the following test are executed
in addition on Linux:
test/test-credentials-no-prompt.sh (git version < 2.3.0)
test/test-prune-worktree.sh (git version < 2.5.0)
test/test-push-bad-dns.sh (git version < 2.3.0)
test/test-worktree.sh (git version < 2.5.0)
> install latest Git on Travis-CI Linux to run all tests

- lfs/client.go
- lfs/client_test.go
- lfs/credentials_test.go
Not sure why I used the base64 url encoding. Fixes #938
> Use the standard base64 encoding for Basic Auth header

- .travis.yml
Run Git-LFS tests against the Travis-CI default Git version and the
latest available Git version on the respective platform.
The default Git version is currently 1.8.5.6 on Ubuntu and 1.9.3 on OSX.
> run tests on Travis-CI against default Git and latest Git

- lfs/scanner.go
Building on #1008 (/cc @rlaakkol). Just moved the `Wait()` call before closing the channels, as described in https://github.com/github/git-lfs/pull/1008#issuecomment-185353312.
> the walking dead (pt 3)

- lfs/scanner.go
Found a few more places that weren't explicitly calling `Wait()`. /cc #1012 @sinbad
> kill more process zombies

- lfs/scanner.go
- lfs/scanner_test.go
- test/test-pull.sh
- test/testhelpers.sh
This updates the `ls-tree` command parser to use `-z`, which tells git to return lines split by a null terminator. This output is designed for scripts, and represents filenames with spaces and unicode better. See https://github.com/github/git-lfs/issues/987#issuecomment-186337634 for a more detailed writeup.
/cc @sinbad: I think we should try and use `-z` where possible. I copied `bufio.ScanLines()` and made `scanNullLines()`, so it should be easy to apply to other commands.
I also made sure `lsTreeBlobs()` calls `Wait()` on the `*exec.Command` object. Don't want another zombie herd (#1012).
> update "ls-tree" command to use -z

- .travis.yml
- commands/command_clone.go
- commands/command_pull.go
- docs/man/git-lfs-clone.1.ronn
- git/git.go
- test/test-clone.sh
- test/test-credentials-no-prompt.sh
Adds a new command `git lfs clone` which allows for more efficient cloning of LFS repositories by suppressing filters during clone/checkout then doing `git lfs pull` afterwards. Automatically suppresses error messages generated by this process. 
Addresses #931, thanks to @larsxschneider for the extensive analysis, this is 100% based on his findings.
> Implement `git lfs clone`

- commands/command_fetch.go
- commands/command_pre_push.go
- commands/command_push.go
- commands/commands.go
- lfs/errors.go
- lfs/errors_test.go
- lfs/upload_queue.go
This fixes an issue when pushing or fetching where the "inner error" is dropped, making it difficult to diagnose problems.
This also tweaks an error message from `ensureFile()` /cc @rjbell4
```bash
$ git push origin master
Trying to push "a.wav" with OID 87428fc522803d31065e7bce3cf03fe475096631e5e07bbd7a0fde60c4cf25c7.
Not found in /Users/rick/p/studious-goggles/.git/lfs/objects/87/42.
error: failed to push some refs to 'https://git-server.com/technoweenie/studious-goggles'
```
> Better errors on push

- git/git.go
Backported from the first commit in #1038.
> defer a couple more cmd.Wait() calls

- debian/rules
Removes the stray `man` binary causing havoc for man page creation.
> Fix for #719 and #995

- commands/command_push.go
- git/git.go
- lfs/scanner.go
- test/test-pre-push.sh
Fixes problem described in more detail in #1014 
Verifies that server still has all the remote refs we're using to diff which LFS objects to upload, in case one has been deleted without local knowledge and LFS objects have been GC'd in the mean time, which would lead to data loss. Proved that the test I added fails without the code change.
> Fix issues with server-side branch deletion out of sync with cached remote refs

- lfs/download_test.go
- lfs/upload_test.go
I'm adding this because I started hitting various connection errors, but only when running the tests on debian docker images, and only on my laptop. @andyneff can't replicate this.
This is an ugly hack to ignore those errors. The errors are not LFS related, but they come from the client being unable to talk to the http server that's spun up in the tests, bound to 127.0.0.1. Also, CI tests don't skip these errors, so bugs will still prevent pull request merges.
> ignore certain docker network test errors

- docs/api/http-v1-batch.md
This JSON key is only indented one space, but should be indented two spaces to align with the rest of the structure.
> Fix an alignment typo in Git LFS batch API v1 documentation

- git/git.go
- git/pty.go
- git/pty_nix.go
- git/pty_windows.go
- lfs/config_nix.go
- script/integration.go
- test/test-credentials.sh
- test/test-track.sh
- Referencing kr/pty breaks Windows, hide in extra layer
- netrc was breaking build on Windows due to needing a blank line after +build directive
- git lfs clone wasn't working because of a doubly-assigned stdout
- integration tests weren't running because of a bash path issue
> Fixes for windows build

- git/git.go
- subprocess/pty.go
- subprocess/pty_nix.go
- subprocess/pty_windows.go
TTY abstraction and subprocess came out of different PRs, makes sense to move TTY into subprocess now they're both in master.
> Move TTY wrapper to subprocess package

- docs/api/http-v1-batch.md
This may not be worth pulling or the best method or place to express the idea, but the behavior wasn't self-evident to me from the documentation while implementing an LFS server, even though it makes sense now that I understand the interaction.
> Explain a subtlety of client handling for "download" batch action

- lfs/setup.go
- test/test-env.sh
- test/test-install.sh
- test/test-uninstall.sh
- test/test-unusual-filenames.sh
- test/test-worktree.sh
Fixes #1072. Currently, the filters run a command like this when a tracked file begins with a dash:
`$ git-lfs clean -filename`
The filename is then misinterpreted as short arguments.
This installs `git-lfs clean -- %f` instead of `git-lfs clean %f`, and a similar smudge filter.
A limitation of this patch is that existing installs don't automatically upgrade to the new filters until they run `git lfs install --force`. It looks like this is consistent with the `git lfs clean` vs `git-lfs clean` precedent, but maybe encountering this behavior is realistic enough to justify trying to build some sort of auto-upgrade feature which promotes known older variants of the filter (it looks like the pre-push hook has such a list already).
In any case, this should fix new installs, and allow existing …
> Fix smudge/clean on files that begin with a dash

- commands/command_push.go
The argument order and string order are flipped. Before:
```
$ GIT_TRACE=1 git-lfs push origin master
trace git-lfs: Upload refs origin to remote [master]
```
After:
```
$ GIT_TRACE=1 git-lfs push origin master
trace git-lfs: Upload refs [master] to remote origin
```
> Fix "Uploading refs <remote> to remote <refs>" log string

- docs/api/http-v1-batch.md
I got this wrong in #1082, see:
<https://github.com/github/git-lfs/pull/1082#issuecomment-198308275>
I misread the `prePushCheckForMissingObjects()` logic and, in my local test case, I had the server send back `download` _instead of_ `upload` and saw it skip, but that isn't an accurate test because either rule (presence of `download`, absence of `upload`) passes it.
To verify this behavior properly, I had the server send back a made up action (`quack`) instead of `upload`, and observed that the client skipped the transfer:
```
$ GIT_TRACE=1 git lfs push origin master
...
trace git-lfs: HTTP: POST http://local.phacility.com/diffusion/POEMS/poems.git/info/lfs/objects/batch
...
trace git-lfs: HTTP: {... "actions":{"quack":{ ... } }}
...
Git LFS: (0 of 1 files, 1 skipped) 0 B / 87.12 KB, …
```
> Properly correct batch upload/download skip detection documentation

- lfs/scanner.go
- test/test-push-file-with-branch-name.sh
Fixes issue #1056.
When you try to push `master` but also have a file named  `master`, we run
`git rev-list ... master`. This is ambiguous, because `rev-list` accepts
paths or refs and `git` is unsure whether you mean the ref `master` or the
path `master`.
Instead, run `git rev-list ... master --`, which is unambiguous.
This adds a failing test (trying to push a file named `master` to LFS), then
fixes the test by appending `--` to the command.
> Fix `git rev-list` when a file exists with the same name as the branch

- CONTRIBUTING.md
One needs to have release engineer access rights to https://github.com/github/git-lfs.github.com to open the [link](https://github.com/github/git-lfs.github.com/blob/gh-pages/_config.yml#L4), it will show `404` otherwise.
See #1092
> Mention releng access rights to the git-lfs.github.com repository

- lfs/lfs.go
- lfs/util.go
- test/testenv.sh
I discovered this problem while setting up the integration tests to always run in an isolated temp dir if GIT_LFS_TEST_DIR is not set. On Mac that's `/var/temp`, which is a symlink to `/private/var/temp` and which immediately failed in all kinds of ways. The 2 main issues were: 
1. `git rev-parse` resolves symlinks but os.Getwd(), filepath.Abs() does not, causing internal inconsistencies and some weird relative paths from filepath.Rel() that didn't always work
1. Many integration tests failed because bash wasn't resolving symlinks vs Go doing so sometimes
I've chosen to resolve symlinks always to fix this. In bash this was more tricky because `readlink -f` doesn't exist on Mac so there's a helper function to do it.
> Fully resolve symlinks in all cases for consistency

- debian/rules
Following from #1025.  If you want to run the Debian dpkg build using Go 1.6, you need this change, otherwise the import problems noted in https://github.com/github/git-lfs/pull/1076#issuecomment-199062143 will occur.
It is super-likely that the same need to be added to RPM build `rpm/build_rpms.bsh`, and this could be added on speculation, but I don't have a current build environment on a yum-packaged dist.
> Added GO15VENDOREXPERIMENT=0 to dpkg dh build, follow-on from #1025.

- script/packagecloud.rb
I ran `mitmproxy` so I could notice that packagecloud package create was failing with an interesting error.    Prior to this change it fails silently in the script.
This change reports the failure and exits.
> Report errors generated by packagecloud, exit on failure

- commands/command_track.go
- git/git.go
- git/git_test.go
Resolves #1057 
If a file is already tracked in git when it's added to git-lfs tracking, that file is now 'touched' (`mtime`/`atime` file attributes updated) to ensure that it appears as modified in `git status` along with the `.gitattributes` and therefore prompts the user to re-commit it. Without doing this git doesn't detect that the index is dirty for this file and the user could commit `.gitattributes` but with the file content remaining as non-LFS, which can cause problems when checking out this commit in future. Checking out this commit will forever after show the file as modified in the working copy because `smudge` will not have LFS data to checkout from even though `.gitattributes` says it should have, and `clean` will show a diff.
> Touch tracked files that are already added to git

- commands/command_fetch.go
- commands/command_pre_push.go
- commands/command_prune.go
- commands/command_push.go
- lfs/scanner.go
- lfs/scanner_test.go
- test/test-pre-push.sh
- test/test-push.sh
Fixes #1100 as well as surfacing a number of other fail states previously missed.
Wraps all scanner channels so that consumer only has to worry about primary results as channels, then check error result from `wrapper.Wait()` at the end to pick up any bad exit conditions (rather than having to handle 2 channels themselves).
Fixed a bunch of other issues while I was at it.
> Catch previously undetected errors from git exit codes in async scans

- lfs/config.go
- test/test-config.sh
I don't know if you want a change this simple, as I don't know the original intent, but as mentioned in issue #1121, I was hoping to describe the access of my LFS URL as "private" in the same .lfsconfig as where I define the URL itself.  I think it makes the most sense to have this data be co-resident.  However, git-lfs won't allow me to put this content in the .lfsconfig.  This simple change allows me to define it there.
> Allow for an access mechanism to be specified in the .lfsconfig file

- commands/command_fetch.go
- commands/command_pre_push.go
- commands/command_pull.go
- commands/command_push.go
- commands/uploader.go
- docs/api/http-v1.2-batch-request-schema.json
- docs/api/http-v1.2-batch.md
- git/git.go
- lfs/client.go
- lfs/config.go
- lfs/download_queue.go
- lfs/transfer_queue.go
- lfs/upload_queue.go
- test/git-lfs-test-server-api/main.go
- test/test-push.sh
I have some issues with this code. But at least now pre-push and push both call shared functions to upload objects.
From https://github.com/github/git-lfs/pull/1040#discussion_r55821731:
> Now that filteredPointers is used in multiple places, maybe promote it to the lfs package for re-use rather than keep it in the pre-push source file?
This PR is a start towards shared functions for pre-push and push commands. While it seems to work, there are a number of things I'd like to change:
* I don't like using `lfs.Configuration` like this. I wanted something more than a `StringSet` to share between multiple ref uploads in the same command.
* Filtering could probably be cleaned up.
EDIT: Fixed this in a later commit ^^^
Instead of promoting to the lfs package, what if we started on a high level …
> extract common pre-push and push uploading code

- commands/command_pointer.go
This allows to create a pointer file by redirecting Stdout like
$ git lfs pointer --file=path/to/file > pointer-to-file
Before this change, "pointer-to-file" would also contain the line saying
"Git LFS pointer for path/to/file"
which makes the pointer file invalid.
> pointer: Only write the encoded pointer information to Stdout

- commands/command_fetch.go
- commands/command_pre_push.go
- commands/command_push.go
- commands/uploader.go
- git/git.go
- git/git_test.go
- lfs/transfer_queue.go
- test/test-pre-push.sh
- test/test-push.sh
This PR brings back the push optimizations from #1040. Hit up #1040 and #1071 to get the original context. This makes a few changes based on feedback:
* #969 is no longer included. That will come in the next PR.
* https://github.com/github/git-lfs/pull/1071#issuecomment-196280487
> Are you intending to wrap downloading in clientContext too? Although there's somewhat less for it to do than in the upload case. If not, or even if 'not right away' then maybe rename clientContext to uploadContext for now.
It's now called `uploadContext`. It's still unexported, so I expect the type to change and move from the `commands` package some day.
* https://github.com/github/git-lfs/pull/1071/files#diff-d540c48abbcd5b13b0acd4cbef433700R57
> Hmm, feels weird to have to copy the remote name when everything …
> push optimizations (take 2)

- .travis.yml
- lfs/client.go
- lfs/credentials.go
- lfs/credentials_test.go
- lfs/ntlm.go
- script/integration.go
- test/cmd/lfstest-gitserver.go
- test/test-credentials.sh
<del>Trying to replicate #906</del>
Replicated it with some more info. Running with `GIT_TRACE=1` showed me this:
```
trace git-lfs: HTTP: POST https://USER:PASS@git-lfs-server.com/repo.git/info/lfs/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: {"objects":[{"oid":"0000000000000000000000000000000000000000000000000000000000000000","size":1,"_links":{"download":{"href":"https://git-lfs-server.com/repo/info/lfs/objects/0000000000000000000000000000000000000000000000000000000000000000","header":{"Accept":"application/vnd.git-lfs"}}}}]}
trace git-lfs: HTTP:
Username for 'https://git-lfs-server.com':
```
The LFS client is authenticating `https://USER:PASS@git-lfs-server.com/repo.git/info/lfs/objects/batch` properly. However, the LFS server is not returning authenticated urls to the …
> tests for credentials in remote and lfs.url config

- lfs/credentials.go
- lfs/credentials_test.go
Whew, glad I QA'd against a real server, and not just a local test one :)
The `net.SplitHostPort` function expects the host string to have a port (like `localhost:8008`). Currently, it blows up if you use a host on a standard http port.
> fix netrc matching when host has no port

- script/packagecloud.rb
I haven't got my deb build running yet to be able to test this via push to my packagecloud.  Can build OK but the dpkg build complains about imports.
So I'm not sure this is correct, but someone with a working build would be able to test it, perhaps for the next release.
> Added Linux Mint distro to packagecloud push, issue #1074.

- CONTRIBUTING.md
As homebrew is pretty popular amongst Mac users I think it would be nice to bump the version with every update. However, I also understand that you guys can't update for every package manager out there... therefore this is just a suggestion and I am not sad if you reject it 😄
> add homebrew update to release process

- ROADMAP.md
> Roadmap item for warning about lack of `git lfs install`

- commands/command_clone.go
- git/git.go
- test/test-clone.sh
Fixes #1155 
- `git lfs clone` now correctly passes through flags to `git clone`
- `--no-checkout` and `--bare` now cause `git lfs clone` to `git lfs fetch` rather than pull
- `--origin` option is respected and changes how lfs fetches/pulls after clone
> Pass `git lfs clone` flags through to `git clone` correctly, respect some options

- commands/command_update.go
- lfs/hook.go
- test/test-install.sh
- test/test-update.sh
Fixes #1174 
Also tidies up the output a little and automatically replaces blank pre-push hooks now.
> Fix failure to return non-zero exit code when lfs install/update fails to install hooks

- script/run
Squashes script/run warning:
link: warning: option -X github.com/github/git-lfs/lfs.GitCommit 54c5efa may not work in future releases; use -X github.com/github/git-lfs/lfs.GitCommit=54c5efa
> Applied same -ldflags -X name value -> name=value fix as in a62e510f.

- commands/command_update.go
- docs/man/git-lfs-update.1.ronn
- lfs/setup.go
- test/test-install.sh
- test/test-update.sh
Related to #1174 
As discussed in chat, implemented as a command option rather than in docs so that we don't have to maintain the hook script in more than one location.
> Add `git lfs update --manual` option & promote it on hook install fail

- script/windows-installer/inno-setup-git-lfs-installer.iss
On 32-bit versions of Windows (in my case, Windows XP), the windows installer fails because it cannot expand the "pf64"constant.
By changing this very constant to "pf", it gets resolved properly on all versions of Windows.
See http://www.jrsoftware.org/ishelp/index.php?topic=consts for further explanation of the constants.
> Fix installer error on win32.

- CODE-OF-CONDUCT.md
- CONTRIBUTING.md
The URL for the code of conduct is down, so I embedded the text as a markdown file. This isn't a change of the code that the project adheres to, so we won't be discussing changes in this PR.
> embed the open code of conduct since the link is bad now

- commands/command_smudge.go
- docs/man/git-lfs-config.5.ronn
- lfs/config.go
- lfs/lfs.go
- test/test-env.sh
- test/test-smudge.sh
- test/test-worktree.sh
Fixes #1195 
Add option `lfs.skipdownloaderrors` / `GIT_LFS_SKIP_DOWNLOAD_ERRORS` to allow the smudge filter to return success on download errors, so that checkout etc can continue even without access to content.
It's an option because using this means exit codes are not propagated and scripts would be unable to detect problems with clone/checkout when LFS downloads failed. Also users if they weren't paying attention. However it's useful as an opt-in if wanting to switch branches etc when disconnected.
> Allow smudge filter to return 0 on download failure

- docs/proposals/locking.md
I've given locking some thought before so I've pulled out my notes about how I think it could work for a git-lfs proposal.
> Some design notes I wrote a while back when thinking about locking

- git/git.go
- git/git_test.go
This uses `NewRepo()` so that these 2 tests run identically from a git clone and from a plain source dump. Should fix #1202 
/cc @sinbad @javabrett
> get git tests passing when run outside of repository

- git/git.go
- git/git_test.go
Returning simply `{remote}/{branch}` doesn't help if someone creates a local branch `refs/heads/master/{remote}/{branch}`. This `RemoteRefNameForCurrentBranch()` function is only used for `ResolveRef()`. `git rev-parse` can definitely handle full refs.
> Return a fully remote ref to reduce chances of ref clashes

- api/lock_api.go
- api/lock_api_test.go
- api/schema/schemas.go
- api/schema/unlock_request_schema.json
This pull-request adds the relevant schema, tests, and type to support the ability for a client to indicate to an LFS server that it wishes to forcibly remove a particular lock.
> api: add Force option to unlock requests

- test/cmd/git-credential-lfsnoop.go
- test/test-credentials-no-prompt.sh
Some tests are failing on branches of mine because the LFS test credential helper is being overridden by the OS X system-level cred-helper. Instead of `--unset`-ing during the tests that needed it, this PR introduces a no-op credential helper, which fixes those tests.
> test: use noop credential helper for auth tests

- .travis.yml
Seems that all 3 of our osx builds have different failures associated with them. 
* https://travis-ci.org/github/git-lfs/jobs/134590303
* https://travis-ci.org/github/git-lfs/jobs/134590297
* https://travis-ci.org/github/git-lfs/jobs/134590299
These 3 seem like test related issues on travis, and not lfs bugs, so they're now ignored.
> ignore all osx ci failures

- script/test
My firewall kept alerting me to this test accepting network connections and when I denied it or didn't click fast enough it would often cause test failures. I'm not sure if this is related to the random test failures we're seeing on OS X sometimes, it's possible. I've turned it off.
/cc @technoweenie @ttaylorr
> Disable gojsonschema test, causes failures when firewalls block it

- docs/api/http-v1-batch-request-schema.json
- docs/api/http-v1-batch-response-schema.json
This is to allow us to extend the API with optional fields in future versions without breaking the schema.
We should notify server implementations to update their schema if they're using it to validate requests since we need to add optional fields for the transfer features in v1.3 even if they don't implement those features.
> Allow additional fields on request & response schema

- .travis.yml
> Backport #1273 for v1.2.x: ignore all osx ci failures

- commands/command_fetch.go
- commands/command_pull.go
- commands/commands.go
- commands/commands_test.go
- lfs/config.go
- lfs/config_test.go
- test/test-fetch.sh
- tools/filetools.go
- tools/filetools_test.go
This backports #1257.
- commands/commands.go
- lfs/config.go
- tools/filetools.go
> Backport #1257 for v1.2.x: Config include exclude

- test/cmd/git-credential-lfsnoop.go
- test/test-credentials-no-prompt.sh
> Backport #1267 for v1.2.x: test: use noop credential helper for auth tests

- .gitignore
> Backport #1271 for v1.2.x: gitignore: ignore lfstest-* files

- script/changelog
This pull-request introduces the `script/changelog` script, which enables callers to generate changelog summaries like we currently use within the releases page.
It accepts a range over which each merge commit is examined, categorized, and appended to a list. The categorization step works very similarly to `git add -i`, and allows you to slot each pull-request into a features, bugs, or misc category.
My bash is a little ugly, but this should work for now :smile:
------------
As an example, this is a changelog that I generated for the v1.2.1 release:
```
- Allow additional fields on request & response schema #1276 (@sinbad)
- Add missing config details to `env` command #1217 (@sinbad)
- Allow smudge filter to return 0 on download failure #1213 (@sinbad)
- Add `git lfs update --manual` …
```
> script: add changelog script

- auth/ssh.go
- auth/ssh_test.go
Per the spec, `GIT_SSH_COMMAND` takes precedence over `GIT_SSH`.
Fixes #1142
> Implement support for GIT_SSH_COMMAND

- commands/command_fetch.go
- progress/meter.go
- test/test-pre-push.sh
- test/test-push.sh
When a file is skipped because it already exists locally, the progress reporting was wonky and on completion would look something like this from `git lfs fetch`:
```
Git LFS: (1 of 13 files) 17.33 MB / 18.34 MB
```
That looks like it didn't finish! Actually the 1 file it downloaded is 17.33 MB and the other 12 were skipped and made up the remainder.
This PR improves this 2 ways:
- Marks files as skipped during `fetch` so the progress tells the user that files & bytes were skipped
- Reduces the estimated files & bytes when skipping so the totals match up when finished (while still showing the number of files and bytes *actually* transferred
The result after this PR is something like this instead:
```
Git LFS: (1 of 1 files, 12 skipped) 17.33 MB / 17.33 MB, 1.02 MB skipped
```
> Improve progress reporting when files skipped

- test/cmd/lfstest-gitserver.go
- test/test-resume-http-range.sh
- tools/iotools.go
- transfer/adapterbase.go
- transfer/basic.go
- transfer/basic_download.go
- transfer/basic_upload.go
- transfer/http_range.go
This PR implements resumable downloads for all storage hosts which support HTTP Range/Content-Range exchanges. Since it seamlessly falls back to re-downloading the entire file if the server doesn't support a range request, it doesn't hurt to always ask to resume and to proceed depending on what the server responds with (often these servers will just return 200 instead of 206 and send the entire file, which this caters for).
> Enhanced transfers: part 3 (resumable downloads)

- commands/command_fetch.go
- test/test-fetch.sh
Since there is no HEAD ref to resolve when a repository is cloned with the `--bare` flag, the `git lfs fetch` command learned to ignore it. Kudos to @xen2 for bringing this up in #1307.
I piggybacked the pseudo-test for bare clones onto the end of the `fetch-all` test in `test/test-fetch.sh`. I am using all of the fixture data from the test, but if we want to extract that out, I'd be more than happy to do that 😄 
Either way, this pull-request should resolve #1307!
--------------
/cc @rubyist
> Ignore HEAD ref when fetching with --all

- script/test
As described in the test/README.md, it is possible to
pass extra args to the script/test, like for example:
$ script/test lfs -run TestSuccessStatus -v
Those args must be propagated to the 'go test' script.
Signed-off-by: Olivier Monnier <olivier.monnier@intel.com>
> script/test: propagate extra args to go test

- commands/command_clone.go
- docs/man/git-lfs-clone.1.ronn
- test/test-clone.sh
This pull-request adds the ability to specify include/exclude flags to the `git lfs clone` command via `-I` and `-X`, and the repository-level `.lfsconfig` file, a-la `git lfs fetch`, etc.
Other things to note: I put the `clone{Include,Exclude}Arg string` flag outside of the `git.CloneFlags` type, since the new flags are LFS-specific, and not related to Git. If we'd rather have those flags roped into the `git.CloneFlags` type (but not passed to the `git clone` invocation), I'm cool with that, too.
Most importantly, thanks for the review! 👋
> cmd/clone: add include/exclude via flags and config

- git/git.go
- git/git_test.go
- test/README.md
- test/test-fetch.sh
The commit 39676192da53261efd441ccf0c67c85a341ae1a1
introduced a regression in the capability to fetch a
sha1 ref.
The command 'git lfs fetch origin <sha1>' was returning
following error: 'Invalid ref argument: [<sha1>]'.
This is due to the fact that 'git rev-parse --symbolic-full-name <ref>'
returns an empty content if the ref is a sha1.
Signed-off-by: Olivier Monnier <olivier.monnier@intel.com>
> Fix 'git lfs fetch' with a sha1 ref

- commands/command_checkout.go
- docs/man/git-lfs-checkout.1.ronn
- test/test-checkout.sh
This change introduces `--unstaged` ('-u') flag to the `checkout` subcommand. Originally it is intended to skip the costly `git update-index` call in the continuous integration setup where `git lfs checkout` is the last git operation performed in the clone, and the state of the index does not matter anymore.
> Add checkout --unstaged flag

- script/packagecloud.rb
Tested by:
* `sudo gem uninstall packagecloud-ruby`
* `sudo gem install packagecloud-ruby -v 1.0.2`
* `sudo gem install packagecloud-ruby`
... running `ruby script/packagecloud.rb` each time.  You get the version warning until you hit `1.0.4`, which is current.  Could make this `1.0.3`, the bare minimum, if preferred.
> Enforced a minimum gem version of 1.0.4 for packagecloud-ruby

- docs/man/git-lfs-logs.1.ronn
The `git-lfs-logs.1` man-page incorrectly listed the `clear` and `boomtown` subcommands of `git lfs logs` as `--options` rather than subcommands.
Closes github/git-lfs#1311
> docs/man: move "logs" subcommands from OPTIONS to COMMANDS

- commands/command_checkout.go
- docs/man/git-lfs-checkout.1.ronn
- test/test-checkout.sh
Fixes #1334
Reverts github/git-lfs#1262
Reverting for possible re-submission later. The reasons are:
1. Failures in the test are causing other subsequent PRs to fail. The reason is that skipping the `update-index` is unreliable at creating a clean git state, because the index cache may be out of date if the timestamp of files changes during checkout. Depending on the exact timing, the version of git, and the file system, precision issues can result in a non-clean status without `update-index`.
1. I think the flag `--unstaged` is misleading and the documentation "Do not add files to the index, keeping them unstaged." is incorrect. `checkout` never added anything to the index, it only made sure the index cache was not out of date.
If the intention is to save the expense of calling …
> Revert "Add checkout --unstaged flag"

- test/cmd/lfstest-gitserver.go
- test/test-resume-tus.sh
- transfer/adapterbase.go
- transfer/basic_download.go
- transfer/tus_upload.go
Adds a new "tus" transfer adapter which uses the [tus.io resumable upload protocol](http://tus.io/protocols/resumable-upload.html) (HEAD/PATCH methods). This allows a server to share upload action links to an endpoint which supports this protocol and therefore allow upload resuming. 
The included tests implement the server protocol too to prove it works, and I'm also submitting a PR to [lfs-test-server](https://github.com/github/lfs-test-server) which uses the official `tusd` server to prove it works using the official implementation and to demonstrate how you might go about using it.
> Enhanced transfers part 4: resuming uploads via tus.io protocol

- commands/commands.go
This pull-request introduces an additional safety check around the `requireStdin` function of the `commands` package as seen [here](https://github.com/github/git-lfs/blob/79bedebb2536485317ed5470d4e6d72cdc92d0c4/commands/commands.go#L116).
As reported in https://github.com/github/git-lfs/issues/1347, the function was panicking when trying to call Mode on a nil `os.FileInfo`. Since `os.File.Stat` is guaranteed to return a non-nil value so long as no error is present, a sanity check was added to catch and log these errors. If no error was present, the bitmask is applied and checked as normal.
An aside: I added the error logging in my second commit, whereas it was previously simply discarding the error as before. If we want to continue to discard the blanked error from `os.Stdin.Stat()`, …
> Safety check to `comands.requireStdin`

- api/object.go
- api/object_test.go
- lfs/transfer_queue.go
- test/cmd/lfstest-gitserver.go
- test/test-push.sh
- transfer/adapterbase.go
This pull request eagerly retries transfers that come back with expired actions, per https://github.com/github/git-lfs/issues/1345.
This is still a "work-in-progress", as I'm not 100% certain that I've implemented this in the right place. I followed the upload from `commands/command_push.go`, into the LFS code and the transfer code, into the `handleTransferResult`, which I think is where we want to be.
Just in case, I've left some `// NOTE`s throughout my code, which I would very much appreciate the validation of from any potential reviewers (/cc @sinbad).
Pending that validation, I'll go ahead and implement a change in the test server to validate that this behavior is used correctly and that requests are indeed retried. Since that component of the test server touches a good portion of …
> ⏳ Retry transfers with expired actions

- commands/command_track.go
- docs/man/git-lfs-track.1.ronn
- test/test-track.sh
This pull request introduces three new flags into the `git lfs track` command: `--no-touch`, `--verbose`, and `--dry-run`. It also updates the man pages and adds test for this new behavior accordingly.
- Specifying `--no-touch` will cause LFS to skip modifying the file's `atime` and `mtime`, leaving the file unmodified from the filesystem's perspective.
- Specifying `--verbose` will cause LFS to print the name of each file that it touches, so that it's more apparent what `git lfs touch` is doing when acting upon a large glob of files (see https://github.com/github/git-lfs/issues/1304).
- Specifying `--dry-run` will cause `git lfs track` to log out all of the actions it would normally preform (as given with `git lfs track --verbose`), without actually modifying files or `.gitattributes` on …
> cmd,doc,test: teach `git lfs track --{no-touch,verbose,dry-run}

- .gitignore
- Makefile
- script/genmakefile/genmakefile.go
This pull request adds the ability to build git-lfs with gccgo simply by typing "make".  No "go" command is required.
> Create Makefiles for building with gccgo

- httputil/certs_openbsd.go
This effectively allows for building git-lfs on OpenBSD.
> Unbreak building httputil on OpenBSD

- .travis.yml
The Git source version is defined by the variables GIT_SOURCE_REPO and
GIT_SOURCE_BRANCH (which can also be a Git hash). The Git source is
checked out, compiled, and installed on the Travis CI Linux machine.
Afterwards all Git-LFS tests are executed against the this Git version.
This setup helps to test features that depend on changes in the
development branches of Git and Git-LFS.
> travis-ci: add a build job to test against upcoming versions of Git

- test/test-zero-len-file.sh
With the new release of Git, version 2.9.1, our "pull zero len file" test is
broken. @larsxschneider was the first to point this out in github/git-lfs#1363.
The cause of this problem is that `git-status` changed to print "working tree
clean", instead of "working directory clean" when running in a clean working
tree. Though this is more correct, it still broke our tests :-).
This commit changes the `grep` assertion to match the new behavior of
`git-status`.
The relevant change from git/git is here: git/git@2a0e6cd.
Closes: github/git-lfs#1363.
------------
/cc @larsxschneider @technoweenie @rubyist @sinbad
> test/zero-len: update test for git v2.9.1

- lfs/scanner.go
Fixes https://github.com/github/git-lfs/issues/1318 by using `--stdin`. Hat tip to @alex-davidson for the idea. It doesn't work with the `--not` flag, so it now passes SHAs in with a `^` prefix.
> use `git rev-list --stdin` instead of passing each remote ref

- .travis.yml
The Git-core 'master' branch tracks the commits that should go into the next release (see https://github.com/git/git/blob/master/Documentation/gitworkflows.txt). 
Run Git-LFS tests against a build of the Git-core 'master' branch and require a successful pass.
> travis-ci: require successful tests against upcoming Git core release

- commands/command_clone.go
- test/test-clone.sh
Fixes #1172
git 2.9+ preserves the config settings which disable the LFS filters in submodules so any LFS files will be pointers. This makes it more optimal (previous versions will suppress these settings so the smudge filter will be used in submodules) but we must run "git lfs pull" to update the submodule working copies.
/cc @larsxschneider
> In git 2.9+, run "git lfs pull" in submodules after "git lfs clone"

- .travis.yml
- script/integration
- script/integration.go
- test/cmd/lfstest-gitserver.go
- test/test-credentials-no-prompt.sh
- test/test-credentials.sh
- test/testenv.sh
- test/testhelpers.sh
Found an intermittent test issue running `script/cibuild` on mac. While investigating, I noticed that `GIT_LFS_TEST_MAXPROCS` isn't even used now. The intermittent issue goes away when `GIT_LFS_TEST_MAXPROCS=1` too.
> teach script/integration.go about GIT_LFS_TEST_MAXPROCS

- httputil/request.go
- httputil/request_test.go
GetAuthType method in https://github.com/github/git-lfs/blob/master/httputil/request.go#L174 only takes first WWW-Authenticate header into account. If server sends the following headers:
```
WWW-Authenticate: Bearer
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
```
the code returns "basic", which is definitely not correct in this case.
This change fixes this issue.  With this change we will also handle Negotiate authentication.
Bug: https://github.com/github/git-lfs/issues/1377
> Updated request.GetAuthType to handle multi-value auth headers

- script/packagecloud.rb
I think this is all that's needed to make that packages show up for Linux Mint Sarah (18)
@technoweenie
> Added Linux Mint Sarah to package cloud script

- script/windows-installer/inno-setup-git-lfs-installer.iss
In a previous pull request I submitted, there was an error.
The installer would write to a "mingw64" directory even on 32-bit versions of Windows.
With this patch, the installer will write to the correct "mingw32" directory under Win32.
> Fix bug in Windows installer under Win32.

- config/config.go
- httputil/http.go
- httputil/proxy.go
- httputil/proxy_test.go
- lfs/proxy_test.go
This updates #1173 with the latest master. Since that PR, a lot of subpackages have been split out, and we've switched assertion libraries. 
@jonmagic @LizzHale: I also changed the main `ProxyFromGitConfigOrEnvironment()` function from #1173 for these reasons:
1. `proxyFromGitConfigOrEnvironment()` is coupled to the global `Config` value. I updated the function to accept only a `*config.Configuration` argument, and return a `func(*http.Request) (*url.URL, error)`. That cleaned up the test setup for `TestProxyFromGitConfig` a bit.
2. It returns a valid url OR error from `http.ProxyFromEnvironment` now. I didn't want to drop a potential error if users have a bad HTTPS_PROXY value, but a good git `http.proxy` value.
3. The end of the function returns `nil` now, explicitly.
Unfortunately, I …
> use proxy from git config 

- commands/command_lock.go
- commands/command_locks.go
- commands/command_unlock.go
- commands/commands.go
- commands/commands_test.go
- test/test-lock.sh
- test/test-locks.sh
- test/test-unlock.sh
To prepare for the upcoming release of Git LFS v1.3, the `git-lfs lock` and
`git-lfs locks` commands are now hidden behind a enviornment variable
`GITLFSLOCKSENABLED`. Since most (all?) implementations of LFS do not yet
support this new locking API, it makes sense to allow users to experiment with
the command while at the same time, not making it a "full" part of the release.
If users wish to run any `git-lfs lock{,s}` command, they may do so according
to the following:
```
$ GITLFSLOCKSEANBLED=1 git lfs lock <flags> [args]
$ GITLFSLOCKSEANBLED=1 git lfs locks <flags> [args]
```
This commit, when applied, adds two new things:
1. The `isCommandEnabled(cmd string) bool` func in the commands package. This
new func checks the OS's enviornment variables and determines whether or not
a command …
> commands/test: make lock commands opt-in using GITLFSLOCKSENABLED=1

- config/version.go
I'm not sure what the convention is here. Version 1.3.0 is everywhere in this branch except in version.go.
> Bump version number

- lfs/lfs.go
- test/test-env.sh
- test/test-worktree.sh
I found this useful when debugging transfers, above and beyond just showing the booleans or having to dig into the actual JSON that was sent. 
@technoweenie would be great if this could make it into 1.3 but no big deal if not.
> Report actual list of transfers that will be tried from `git lfs env`

- transfer/custom.go
Tiny tweak to tracing, makes custom adapters not add newlines everywhere when GIT_TRACE=1
> Trim custom adapter output before tracing to avoid extra newline

- commands/command_checkout.go
I've been baffled by the various issues about `git update-index` failing with no reporting. Then it dawned on me that `CombinedOutput()` is the culprit. The [implementation](https://golang.org/src/os/exec/exec.go?s=11924:11970#L433) clearly shows that the stdout and stderr on the command aren't captured until `CombinedOutput()` is called. It's designed for situations where you want to run a simple command and capture it's output in a single line.
> properly report `git update-index` errors

- httputil/certs.go
- httputil/certs_test.go
Corresponding issue: #1403
appendRootCAsForHostFromGitconfig() modified to check hosts with and without a trailing slash.
Cert unit tests made "table driven" and extended to cover this case.
> Fix sslCAInfo config lookup when host in config doesn't have a trailing slash

- docs/man/git-lfs-install.1.ronn
- lfs/hook.go
- test/test-install-custom-hooks-path-unsupported.sh
- test/test-install-custom-hooks-path.sh
This commit gives the `lfs.Hook` knowledge of the new `core.hooksPath`
configuration value that was introduce in Git 2.9.0.
When `core.HooksPath` is found in the Git configuration AND is supported (i.e.,
installed Git binary has a version greater than or equal to "2.9.0"), `git-lfs
install` will place new hooks in that directory. If the `core.hooksPath` is
specified, but the installed verison of Git does NOT support it, then it will
be ignored and installed in `.git/hooks` as per usual.
To test this behavior, two new shell tests were added:
- One that runs on Git >= 2.9.0, and tests that `core.hooksPath` is respected
- One that runs on Git < 2.9.0, and tests that `core.hooksPath` is ignored
Unfortunately, our current testing framework does not support skipping
individual tests, only …
> lfs/hook: teach `lfs.Hook` about `core.hooksPath`

- commands/command_clone.go
- commands/command_fetch.go
- commands/command_pull.go
- commands/commands.go
- commands/commands_test.go
- test/test-fetch-paths.sh
- test/test-fetch-recent.sh
- test/test-fetch.sh
- tools/filetools.go
- tools/filetools_test.go
This uses a `pflag.Flag`'s `Changed` property to determine if the `--include` or `--exclude` flags are empty or omitted. I'm not convinced using `*string` is any better than setting the default flag value to some magic string like `OPTIONAL`. It does remove any possibility of clashing with a directory in a user's repository, I suppose.
I also ran into some failures in large `test-fetch.sh` tests that run `git lfs fetch` multiple times. Those instances were really difficult to debug, so I split a couple of them up into separate files.
Fixes #1249
> distinguish between empty include/exclude paths

- ROADMAP.md
Our current ROADMAP is a list of bullet points, which makes it hard to see what's up-next, being worked on, or has priority. This changes that.
I converted our ROADMAP.md file to contain Markdown tables which have emoji representing their status. The statuses that I added are:
* :ship: - Completed
* :construction: - In Progress
* :soon: - Up next
* :no_entry_sign: - Blocked
I also proposed a new method of keeping track of the ROADMAP wherein we keep completed items on the ROADMAP until we release a version of LFS, to create an opportunity to prune and discuss the ROADMAP after each release.
I'm curious to hear thoughts on these emoji, the tables, or the process. Thanks! 👋
> ROADMAP: convert roadmap to markdown table

- auth/ssh_test.go
- commands/commands_test.go
- config/config.go
- config/config_test.go
- config/env_fetcher.go
- config/map_fetcher.go
- httputil/certs_test.go
- httputil/proxy_test.go
This pull-request removes all instances of `config.Config.Setenv` and `config.config.SetAllEnv`. References to `SetConfig` still exist, but those are `.gitconfig` related, meaning they'll be addressed in a future pull-request.
There is also now considerably more repetition in the `auth/ssh_test.go` file. It's a good candidate for table-style tests, but I also appreciate its clarity right now.
This completes step 2 of config-next:
> Update tests to not use mutable behavior like Set and SetAll.
-----------------
/cc @technoweenie @rubyist @sinbad @larsxschneider
> config-next: Remove config.{Setenv,SetAllEnv}

- commands/command_fetch.go
- commands/command_prune.go
- config/config.go
This pull-request updates the `FetchPruneConfig` type to be loaded from the new Git config parsing hotness.
-
/cc @technoweenie @rubyist @sinbad
> config-next: cleanup FetchPruneConfig()

- commands/command_fetch.go
- commands/command_prune.go
- config/config.go
- config/config_test.go
- config/environment.go
- config/environment_test.go
- config/fetcher.go
- config/git_fetcher.go
- config/map_fetcher.go
- config/os_fetcher.go
❗ The relevant diff is contained in [`config-next-prune..config-next-unmarshalling`](https://github.com/github/git-lfs/compare/config-next-prune...config-next-unmarshalling).
-
Calling `Unmarshal` on a struct-pointer will inspect each of that struct's
field's tags, and unmarshal configuration data into said field according to
three parameters:
- The environment specified, either `git` or `os`.
- The name of the key given (in the tag).
- The type of the field (either `string`, `int`, or `bool`).
If there is already a non-zero value stored in the field, then that field will
be skipped, allowing constructors to set up default behavior.
-
/cc @technoweenie @rubyist @sinbad
> config-next: Unmarshalling

- config/config.go
This pull request ensures that the `.gitconfig` is loaded before calling `Unmarshal()`.
Previously, the `.gitconfig` would go unloaded causing [this](https://github.com/github/git-lfs/blob/1845c0bf9c3b77c52484ee4e7f9b15f7eab6edce/config/config.go#L196) line to return a `nil` `*Environment`, causing `Unmarshal` to skip its operation on that field per [this](https://github.com/github/git-lfs/blob/1845c0bf9c3b77c52484ee4e7f9b15f7eab6edce/config/config.go#L151-L153) block.
The reason that this wasn't caught before is that it was only being tested by `config.NewFrom()`, which uses the `mapFetcher` implementation, instead of doing actual `.gitconfig` parsing. I don't think it's needed to add a test guarding this behavior, since the `New` constructor should be simplified shortly.
-
/cc …
> config-next: ensure .gitconfig is loaded before Unmarshal call

- config/config.go
❗ The relevant diff is contained in: [`config-next-load-unmarshal..config-next-fetch-unmarshal`](https://github.com/github/git-lfs/compare/config-next-load-unmarshal...config-next-fetch-unmarshal).
-
This pull request uses the new `Unmarshal(v interface{}) error` function to fill out the result of calling `FetchPruneConfig`.
It adds the relevant `git:"lfs.foo"` tags to the `FetchPruneConfig` type definition, and sets the defaults during the struct initialization. Currently, it `panic`s on any errors being returned from `Unmarshal`, but those errors are all internal, and the presence of one would indicate a state wherein LFS is not able to function properly (thus they are panic-able).
-
/cc @technoweenie @rubyist @sinbad
> config-next: use `Unmarshal` to fill out `FetchPruneConfig`

- commands/command_checkout.go
- commands/command_smudge.go
- lfs/lfs.go
- lfs/pointer.go
- lfs/pointer_smudge.go
- lfs/transfer_queue.go
- transfer/basic_download.go
- transfer/basic_upload.go
- transfer/custom.go
- transfer/custom_test.go
- transfer/manifest.go
- transfer/transfer.go
- transfer/transfer_test.go
- transfer/tus_upload.go
This extracts the configured transfer adapters to an explicit `Manifest` type, instead of storing them on the go package itself. We get a few benefits here:
* Tests operate on immutable `*config.Configuration` and `*transfer.Manifest` objects. No resetting global state.
* The transfer configs are only loaded as needed.
I made sure that a manifest is loaded at most once per `git-lfs` command.
> Transfer manifest

- api/api.go
- api/download_test.go
- api/upload_test.go
- api/v1.go
- api/verify.go
- auth/credentials_test.go
- config/config.go
- httputil/certs_test.go
- lfs/download_queue.go
- lfs/pointer_smudge.go
- lfs/transfer_queue.go
- lfs/upload_queue.go
- test/git-lfs-test-server-api/main.go
- transfer/basic_upload.go
- transfer/custom.go
- transfer/tus_upload.go
This pull request removes mutable `.gitconfig` behavior from the `api`, `lfs`, and `httputil` packages. Most of the work involved here is removing calls to `SetConfig` and `ResetConfig`, and also threading an instance of `*config.Configuration` through the `api` package instead of falling back to the `config.Config` global.
To retain the same behavior outside of the tests, the `api` package did gain a few references to `config.Config`, but this is a temporary measure until we remove that package entirely for v2.0. Alternatively, package `api` could own its own private instance of `*config.Configuration`, but I think that's outside the scope of this PR.
Next (and last!) up is the `transfer` package. This requires a little bit more of a fundamental change than just removing calls. The …
> config-next: remove `SetConfig` from package `api`, `lfs`, `httputil`

- config/config.go
This pull-request removes the mutable `SetConfig` and `ResetConfig` methods (along with the `origConfig` field, which was a collaborator) from the `*config.Configuration` type. They are no longer used anywhere throughout the LFS codebase 🎉 
-
/cc @technoweenie @rubyist @sinbad
> config-next: remove `SetConfig` and `ResetConfig`

- commands/command_checkout.go
- commands/command_clean.go
- commands/command_clone.go
- commands/command_env.go
- commands/command_ext.go
- commands/command_fetch.go
- commands/command_fsck.go
- commands/command_init.go
- commands/command_install.go
- commands/command_lock.go
- commands/command_locks.go
- commands/command_logs.go
- commands/command_ls_files.go
- commands/command_pointer.go
- commands/command_pre_push.go
- commands/command_prune.go
- commands/command_pull.go
- commands/command_push.go
- commands/command_smudge.go
- commands/command_status.go
- commands/command_track.go
- commands/command_uninit.go
- commands/command_uninstall.go
- commands/command_unlock.go
- commands/command_untrack.go
- commands/command_update.go
- commands/command_version.go
- commands/commands.go
- lfs/lfs.go
I thought changing `lfs.Environ()` to accept a `*config.Configuration` and `*transfer.Manifest` (instead of using global values) would be easy.  However, I wanted a spot for various "global" config objects to be created for all commands, so I picked `commands.Run()`. I may look for a way to pass some kind of context to each command and remove those too.
I built this PR off #1430, so view this diff instead: [transfer-manifest...command-var-scope](https://github.com/github/git-lfs/compare/transfer-manifest...command-var-scope)
> Command var scope

- config/config.go
- config/endpoint.go
- test/test-config.sh
Rewrite of #1117 after the config refactoring in #1425. There's no `readGitInsteadOfConfig()` anymore to hook into anymore.
We can't easily support `pushinsteadof` without bigger changes. `config.NewEndpointWithConfig()` doesn't know if the request is a push or pull.
> add support for url.*.insteadof in git config

- transfer/custom.go
As pointed out by @ericfrederich in #1439, the `Event` field of the custom transfer "init request" is encoded as `"Event":`, not `"event":` as it should be.
Running the custom transfer integration tests confirm that this is OK to do 👍 
I'm also thinking that per @technoweenie's suggestion, we backport this to our `release-1.3` branch and get this out as a part of the `v1.3.2` release.
-
/cc @technoweenie @sinbad @ericfrederich
> transfer/custom: encode "event" as lowercase

- auth/credentials.go
- auth/ssh.go
- commands/command_checkout.go
- commands/command_smudge.go
- commands/commands.go
- config/config.go
- config/config_netrc.go
- httputil/certs.go
- httputil/proxy.go
- lfs/transfer_queue.go
- lfs/util.go
🚧  This pull-request removes legacy methods from the `*config.Configuration` object such as:
|       | Was | Becomes |
| --- | :---- | :---------- |
| ✅   | `*config.Configuration.GetEnv` | `cfg.Os.Get` |
| ✅  | `*config.Configuration.GetEnvBool` | `cfg.Os.Bool` |
| ⬜  | `*config.Configuration.GitConfig` | `cfg.Git.Get` |
| ⬜  | `*config.Configuration.GitConfigInt` | `cfg.Git.Int` |
| ⬜  | `*config.Configuration.GitConfigBool` | `cfg.Git.Bool` |
-
> config-next: remove legacy methods

- api/lock_api.go
- commands/command_env.go
- config/config.go
- config/environment.go
- config/environment_test.go
- config/git_environment.go
- config/git_fetcher.go
- httputil/certs.go
- httputil/http.go
- httputil/proxy.go
- lfs/hook.go
- transfer/custom.go
This pull-request introduces a wrapped `gitEnvironment` to support the legacy behavior found in `loadGitConfig` in order to make #1436 possible.
-
In order to support lazily loading the values stored in a user's `.gitconfig`,
we must wait until calling `*config.Configuration.loadGitConfig()` until it is
_absolutely necessary_.
To accomplish this, it was proposed that we introduce a wrapped variant of the
`*Environment` type, only for interacting with the `GitFetcher` that was
capable of supporting such beahvior.
As such, a new implementation of the `Environment` type must be defined. Since
previously there only existed the concrete type `*Environment`, this commit
demotes that down to `*enviornment`, and introduces the interface
`Environment`, which it implements.
-
To wrap the old …
> config-next: Wrapped `gitEnvironment`

- api/object.go
- docs/api/v1.3/http-v1.3-batch-request-schema.json
- docs/api/v1.3/http-v1.3-batch-response-schema.json
- test/cmd/lfstest-gitserver.go
- test/test-object-authenticated.sh
- transfer/basic_download.go
- transfer/basic_upload.go
This lets servers set an `Authenticated` property on objects, that the client uses to determine if it needs to call `git-credential` or not. This is a forward compatible API change, and won't affect existing implementations.
When a client hits the batch api, it sends a payload like this:
```js
{
"operation": "download",
"objects": [{"oid": "SOMEOID", "size": 123}]
}
```
A typical server response returns a URL to transfer the object with any values for the HTTP request header.
```js
{"objects": [{
"oid": "SOMEOID",
"size": 123,
"actions": {
"download": {
"href": "https://download-this-object",
"header": {
"Authorization": "Basic ..."
}
}
}
}
```
Git LFS will use `git-credential` to find the user and pass for that download unless the `Authorization` header is set. What if the service uses a …
> add object Authenticated property

- config/config.go
- config/endpoint.go
- config/endpoint_test.go
- git/git.go
- test/test-fetch.sh
- test/test-pull.sh
- test/test-push.sh
This adds support for pushing and pulling LFS objects with a raw remote url. This was originally submitting in #1085, and updated for the current master branch. This also adds tests.
> Fetch remote urls

- docs/man/git-lfs-fetch.1.ronn
Previously the docs indicated that pattern matching was per gitignore, but actually it is done per golang's `filepath.Match()`.  Ideally it will eventually mirror gitignore, but until then the docs should be corrected.
This will help with user frustration regarding https://github.com/github/git-lfs/issues/912
> Update fetch include/exclude docs for pattern matching

- ROADMAP.md
- commands/command_fetch.go
- commands/commands.go
- commands/uploader.go
This is an extension to #1445 which also cleans up some of the duplicate logic from `commands.ExitWithError()`.  /cc @dpursehouse
> fix duplicate error reporting

- commands/uploader.go
Change-Id: Iff591518853b1c5c229b676d08d8f914f1eb6f62
Signed-off-by: David Pursehouse <dpursehouse@collab.net>
> Fixes #1356: Don't show error message twice

- commands/command_install.go
- debian/postinst
- debian/prerm
- docs/man/git-lfs-install.1.ronn
- git/git.go
- lfs/attribute.go
- rpm/SPECS/git-lfs.spec
- subprocess/subprocess.go
Fixing a merge conflict in #1177.  Otherwise, ready to go cap'n :metal:
> Javabrett config system

- commands/command_install.go
- debian/postinst
- debian/prerm
- docs/man/git-lfs-install.1.ronn
- git/git.go
- lfs/attribute.go
- rpm/SPECS/git-lfs.spec
- subprocess/subprocess.go
These changes modify the packaged install experience, pulling-up config changes currently made in the current user "global" config (`~/.gitconfig`), to instead be made at the "system" config (`/etc/gitconfig`).  That way, Git LFS is installed once per-system, and does not require additional configuration should a different user start using Git LFS and therefore require the smudge/clean filters.
Note that these changes presume that it is safe to have the Git LFS filters installed and that they do and will continue to run as fast noops in non-Git LFS repos.
The elevation from global-to-system occurs automatically provided:
1. The installation runs as root
1. `--local` is not specified.
Additionally, post-install and pre-remove scripts are added to deb and rpm packages.  Since these run as …
> Add --system config commands, elevate install config to system scope when root/packaged

- commands/command_clone.go
- commands/command_install.go
- commands/command_pre_push.go
- commands/command_pull.go
- commands/command_push.go
- commands/command_track.go
- commands/command_update.go
- commands/commands.go
- git/git.go
> check the git version is ok in some key commands

- commands/command_fetch.go
- lfs/transfer_queue.go
- test/test-fetch-include.sh
Currently just reproduces the bug described in #1437 with a test.
> [wip] fix --include bug when multiple files have same lfs content

- docs/api/v1/http-v1-batch.md
- docs/api/v1/http-v1-legacy.md
to make it consistent with the others
The others don't begin with "Returned if ".
> Reword the description of HTTP 509 status

- docs/api/v1/http-v1-batch.md
- httputil/request_error_test.go
- httputil/response.go
Mention that the server implementation may optionally return status
code 507.
This does not add any specific handling of 507 in either the client or
the test server implementation. If a server returns this status code,
it will be handled by the client as a generic "Server Error".
See #1327 and #1438.
> Add HTTP 507 (Insufficient Storage) to the list of optional statuses

- tools/iotools.go
- transfer/basic_download.go
A file download can fail for multiple reasons, e.g. due to various
network errors. Use the `TransferQueue` retry mechansim to try it again.
Possible errors due to spotty network connections:
https://github.com/golang/go/blob/64214792e214bbacb8c00ffea92a7131e30fa59e/src/io/io.go#L26-L47
> retry if file download failed

- tools/iotools.go
- tools/iotools_test.go
This pull-request is a small addendum to @larsxschneider's #1454 to add tests around the `RetriableReader`.
The only behavior change in this PR is that `RetriableReader` will no longer re-wrap already retriable errors, per https://github.com/github/git-lfs/pull/1454#discussion_r76088729.
-
/cc @technoweenie @larsxschneider for 💭  and 👀
> Test `RetriableReader`

- config/config_windows.go
- config/git_fetcher.go
This adds `lfs.pushurl` to the safelist for `.lfsconfig` files. Fixes #1488
> Allow lfs.pushurl in .lfsconfig

- lfs/attribute.go
- lfs/setup.go
- test/test-install.sh
Came across a case recently where someone hadn't used git-lfs for a while and suddenly got errors on `git lfs install` of the form:
```
filter.lfs.clean attribute should be "git-lfs clean --%f" but is "git-lfs clean %f"
```
This surprised me because I thought we had upgrade paths for our config, but turns out that was only for hooks. So rather than making them run `git lfs install --force` for something we already know about, I introduced the same concept as for hooks, a list of upgradeable values we used to use. 
While I was at this I removed the attribute upgrade path for `git-media`, since it was vague and over-general really and I don't think it's necessary any more? I can put it back if there was a specific reason it's still there but looked like a relic to me.
> Automatically upgrade old filters instead of requiring —force

- commands/command_checkout.go
- commands/command_clean.go
- commands/command_clone.go
- commands/command_env.go
- commands/command_ext.go
- commands/command_fetch.go
- commands/command_fsck.go
- commands/command_init.go
- commands/command_install.go
- commands/command_lock.go
- commands/command_locks.go
- commands/command_logs.go
- commands/command_ls_files.go
- commands/command_pointer.go
- commands/command_pre_push.go
- commands/command_prune.go
- commands/command_pull.go
- commands/command_push.go
- commands/command_smudge.go
- commands/command_status.go
- commands/command_track.go
- commands/command_uninit.go
- commands/command_uninstall.go
- commands/command_unlock.go
- commands/command_untrack.go
- commands/command_update.go
- commands/command_version.go
- commands/commands.go
- commands/run.go
This is an incomplete PR that I wanted to try after reading [this conversation](https://github.com/github/git-lfs/pull/1478#discussion-diff-75845058).
Unlike the existing `RegisterSubcommand()`, `RegisterCommand()` wraps the initialization of the `*cobra.Command` with the following properties:
* `Use` - The lfs sub command name, needed by every command.
* `Run` - The function for the command.
* `PreRun` - This is the controversial part. _Most_ commands want this set.
I agree that it's better that the few commands that don't need `.git/lfs` initialized can disable the `PreRun` hook. By default though, all `RegisterCommand` callers should work.
The `bool` return value also lets commands choose if they're activated. Currently only used for experimental commands like `locks`.
If this approach …
> commands: try out RegisterCommand()

- commands/command_clone.go
- commands/commands.go
- commands/run.go
- localstorage/currentstore.go
- test/testutils.go
Old error:
```bash
panic: Error trying to init LocalStorage: mkdir lfs: permission denied
goroutine 1 [running]:
panic(0x377740, 0xc420102920)
/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
github.com/github/git-lfs/localstorage.ResolveDirs()
/private/tmp/git-lfs-20160826-6787-1o15v20/git-lfs-1.4.1/src/github.com/github/git-lfs/localstorage/currentstore.go:39 +0x4c3
github.com/github/git-lfs/commands.resolveLocalStorage(0xc420123d40, 0x5f2ae0, 0x0, 0x0)
/private/tmp/git-lfs-20160826-6787-1o15v20/git-lfs-1.4.1/src/github.com/github/git-lfs/commands/commands.go:342 +0x14
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0xc420123d40, 0x5f2ae0, 0x0, 0x0, 0xc420123d40, 0x5f2ae0)
/private/tmp/git-lfs-20160826-6787-1o15v20/git-lfs-1.4.1/src/github.com/g …
```
> Handle local storage init errors with a short, contextual error msg

- commands/command_fetch.go
For newly initialized local repositories that are configured to track
existing LFS objects by manually creating pointer files via
git-lfs-pointer, there might be no remote configured yet. Still it should
be possible to fetch the LFS objects. Allow this by postponing the check
for a remote until it is really required.
> Allow fetch to run without a remote configured

- appveyor.yml
- script/bootstrap
- script/fmt
This build the binaries and installer for now. Not running tests yet.
> Make AppVeyor CI for Windows work again

- docs/man/git-lfs-clean.1.ronn
This pull-request adds some new documentation to `git-lfs-clean`'s man page to reflect that it is not a part of the user-facing plumbing commands. Instead, it points to the `git-lfs-pointer(1)` documentation in order to preview what the generated pointer data would look like for a particular object.
--
/cc @sinbad @kingces95 @technoweenie #1501
> docs/man: reference git-lfs-pointer(1) in clean documentation

- git/git.go
"git rev-parse --show-toplevel" is defined to already return an absolute
path, so there is no need to convert it.
> Simplify getting the absolute Git root directory

- git/git_test.go
On Windows 10, this test was failing because the current user's home
directory was in DOS-style 8.3 short path notation in the expected Git
path, whereas the actual path was using the long path notation. Fix that
by comparing files based on Stat() instead of comparing strings.
> Make path comparison robust against Windows short / long path issues

- lfs/batcher.go
- lfs/batcher_test.go
This pull-request adds the ability to immediately flush the currently accumulating batch.
The motivation behind this pull-request is the ability to support multiple retries per object in the current transfer queue implementation. Currently, we [keep track of the items that failed to transfer](https://github.com/github/git-lfs/blob/b7b1f2b7985c8f7a18c563c70898f669ffb8c13c/lfs/transfer_queue.go#L420) and then [retry them once more](https://github.com/github/git-lfs/blob/b7b1f2b7985c8f7a18c563c70898f669ffb8c13c/lfs/transfer_queue.go#L233-L242) before we exit in [`Wait()`](https://github.com/github/git-lfs/blob/b7b1f2b7985c8f7a18c563c70898f669ffb8c13c/lfs/transfer_queue.go#L218-L221).
In the future, we'd like to support retrying objects multiple times, by re-submitting them into the Batcher, …
> lfs/batcher: support immediate Flush()-ing

- lfs/transfer_queue.go
This pull-request teaches the `lfs/transfer_queue` how to retry an object more than once per transfer.
The transfer queue used to follow these steps when executing a transfer:
0. Receive a bunch of objects from calls to [`Add()`](https://github.com/github/git-lfs/blob/878165d746549404cf1ddbac0db58573904abbe0/lfs/transfer_queue.go#L84-L97)
0. Start either the [`batchApiRoutine`](https://github.com/github/git-lfs/blob/878165d746549404cf1ddbac0db58573904abbe0/lfs/transfer_queue.go#L330-L408) or [`individualApiRoutine`](https://github.com/github/git-lfs/blob/878165d746549404cf1ddbac0db58573904abbe0/lfs/transfer_queue.go#L266-L303) based on [its capabilities](https://github.com/github/git-lfs/blob/878165d746549404cf1ddbac0db58573904abbe0/lfs/transfer_queue.go#L442-L457).
0. Attempt to transfer …
> lfs/transfer_queue: support multiple retries per object

- lfs/transfer_queue.go
- lfs/transfer_queue_test.go
This pull-request introduces the extracted `RetryCounter` type, which serves two purposes:
- Allows configuration via the `lfs.transfer.maxretries` `.gitconfig` option
- Serves as a base on which to implement retry budgets
📝  I left a few notes throughout the code to point out some choices I made, but this should be a pretty minor change regardless.
I want to investigate a higher-level integration test for this behavior, but I'm not sure what it will look like after retry budgets are implemented. As a first pass, I'm thinking that we could encode "number of retries before success" on the server side and assert that we retried as many times as we could on the client side.
:wave: thanks in advance for the review.
---
/cc @technoweenie @rubyist @sinbad for 👀
> lfs/tq: extract `RetryCounter`

- lfs/scanner.go
- test/test-status.sh
This pull-request teaches the `git lfs status` command how to recognize multiple files that share the same contents. By modifying the behavior of `lfs.ScanIndex`, we now maintain a _slice_ of file metadata associated with a given OID, instead of a one-to-one association [(as before)](https://github.com/github/git-lfs/blob/d8cab9ec1ce008f0230ca6a97581eda0b362d4a1/lfs/scanner.go#L188).
`ScanIndex` now only [accepts unique pointer OIDs][1] (even if there are multiple pointers for a given OID, in the case of many files sharing the same contents), and then [resolves them all at once][2] to multiple files, per the data stored in the indexFileMap. 
[1]: https://github.com/github/git-lfs/commit/752b88e781dcb431e4fe38ea08fccb64cfddf212
[2]: …
> Teach status to recognize multiple files with identical contents

- appveyor.yml
- script/build.go
- script/integration.go
- test/cmd/git-credential-lfsnoop.go
- test/test-credentials-no-prompt.sh
- test/test-object-authenticated.sh
- test/testenv.sh
- test/testhelpers.sh
- test/testlib.sh
First round of fixes to the test framework to make tests basically run on Windows. With this, the remaining failing tests are:
In *test/test-custom-transfers.sh*:
test: custom-transfer-upload-download ...                          FAILED
In *test/test-fetch-include.sh*:
test: fetch: include first matching file ...                       FAILED
test: fetch: include second matching file ...                      FAILED
Running tests in AppVeyor will be enabled in a separate PR once these tests are fixed and https://github.com/appveyor/ci/issues/1022 is deployed.
> Windows test framework fixes

- .travis.yml
It seems some osx10.11 Travis workers already have git installed via
homebrew, resulting in
Error: git-2.10.0 already installed
To install this version, first `brew unlink git`
So only install git if not installed yet, and upgrade it otherwise.
> Travis: Only install git if not installed yet

- commands/command_fetch.go
- lfs/util.go
This removes the windows-specific hacks, and uses `filepath.Clean()` to sanitize the paths. This broke previously because it was `filepath.Match()` expects back slashes on windows.
> use filepath.Clean() when comparing filenames to include/exclude patterns

- api/api.go
- test/test-push-bad-dns.sh
- test/test-push-legacy-failures.sh
This pull request triggers a warning whenever usage of the legacy API is detected. This is a part of a larger effort to remove usage of the legacy API entirely from Git LFS by the time we release v1.5.0.
I decided to print the message out from the API, since it's the quickest way we can land this without some extra plumbing. Because the `commands` package already has a dependency leading into the `api` package, we can't use `commands.Error` or similar, thus the need for a `fmt.Fprintf` directly.
One other option is to check the config value for `lfs.batch` directly (via `coonfig.Config.BatchEnabled()`) and print it out from the commands package. This would be cleaner, of course, but doesn't accurately cover the case where we fallback to the legacy API mid-transfer.
Either way, this code …
> lfs: warn on usage of the legacy API

- test/test-fsck.sh
- test/testenv.sh
- test/testhelpers.sh
- test/testlib.sh
Some changes around using "sha256sum" instead of "shasum" on Windows, in particular on MSYS2.
> Use "sha256sum" on Windows 

- ROADMAP.md
- appveyor.yml
This depends on (and contains the changes from) PR #1566. Once that other PR is merged, this PR contains only a single commit to turn on tests on AppVeyor CI, which should now all pass.
> Enable running tests on AppVeyor CI

- .travis.yml
Since we only compile LFS on Go 1.7.1, let's update our build matrix to match.
--
/cc @technoweenie @sschuberth @larsxschneider @sinbad
> travis: run tests on Go 1.7.1

- lfs/transfer_queue.go
Previously, decrementing the surrounding `sync.WaitGroup` allowed the
`q.errorc` channel to be closed before this send could occur. This racy
behavior introduced a send-on-closed-channel panic, which is fixed in this
commit.
--
/cc @technoweenie @sinbad @rubyist
> lfs/tq: send error before terminating object

- docs/api/README.md
Also consistently use the term "legacy" instead of "original".
> docs: Fix a link to the legacy API

- api/api.go
This pull-request fixes some accidental usage of `fmt.Println` where `fmt.Fprintln` should have been used instead. Since `fmt.Println` accepts variadic arguments of the form `(vs ...interface{})`, the old behavior was to print out the address of `os.Stderr` (given as the first argument), and then the message as expected.
--
> api: correctly print legacy API warning to Stderr

- lfs/transfer_queue.go
This pull-request fixes all places within the transferqueue where an incorrect number of arguments are given to the trace log.
-
> lfs/tq: use extra arguments given to tracerx.Printf

- lfs/transfer_queue.go
- test/cmd/lfstest-gitserver.go
- test/test-legacy-retries.sh
- test/testhelpers.sh
This pull-request fixes an issue described in https://github.com/github/git-lfs/issues/1580, where, when using the transferqueue with `lfs.batch=false`, a failed legacy check would result in a nil-pointer dereference `panic`.
To ensure further safety, I added two new `oidHandler`s to force a finite number of retries into both the upload/download check for legacy transfers. I will follow this up in my next pull-request with a similar solution for the storage endpoint so we can also test this behavior when using the batch API.
--
/cc @technoweenie @rubyist @sschuberth #1580
> Test legacy check retries behavior

- test/cmd/lfstest-gitserver.go
- test/test-batch-retries.sh
- test/test-legacy-retries.sh
This pull-request adds tests asserting retry behavior when both upload and download requests are made to the storage endpoint.
I will follow this PR up with another special-case handler guarding interactions with the batch API endpoint, which, once merged, will fully cover the new retry behavior at the integration level.
--
/cc @technoweenie @sschuberth
> Storage retries

- appveyor.yml
As suggested [here](https://github.com/appveyor/ci/issues/1115#issuecomment-254367662). However, I'm wondering why I still see build for bot the branch and PR here, and now I also start seeing both for Travis CI builds.
> AppVeyor: Do not build branches with open pull requests

- api/v1.go
- auth/ssh.go
Not only expose the error message, but also the result message from
calling SSH which contains details about the cause. At the example of
using the wrong SSH key for authentication, with this the console shows
download check: exit status 255: Permission denied (publickey).
instead of just
download check: exit status 255
and the log shows
trace git-lfs: ssh: download with url failed,
error: exit status 255, message: Permission denied (publickey).
instead of just
trace git-lfs: ssh: download attempted with url.
Error: exit status 255
> Expose the result message in case of an SSH authentication error

- commands/uploader.go
- lfs/transfer_queue.go
- test/test-duplicate-oids.sh
- test/testhelpers.sh
This pull-request fixes a regression where sending a non-unique OID to a transfer queue more than once would result in a `panic()` after having decremented the `sync.WaitGroup` past zero.
The fix comes in two parts:
0. https://github.com/github/git-lfs/commit/047fe19830fd497dd9882ed38a3030ec81938491: Only allow calling `lfs.TransferQueue.Add()` once per OID.
0. https://github.com/github/git-lfs/commit/d770dfa09eb289ff4d4167d91ce4a9030f9886ed: De-dup incoming pointers such that the progress meter displays the right number of bytes and files.
Regarding https://github.com/github/git-lfs/commit/d770dfa09eb289ff4d4167d91ce4a9030f9886ed, I am not hugely excited about adding another conditional against a potentially large set of data, but given the expected lifetime of this code, and the …
> commands,lfs/tq: Only send unique OIDs to the Transfer Queue

- api/object.go
- api/object_test.go
- test/cmd/lfstest-gitserver.go
- test/test-push.sh
- transfer/adapterbase.go
This pull request enhances of the descriptiveness of the error message returned when an object has expired.
To accomplish this, we needed to teach the `api.Object` how to return which action it was expired for, so we have a basis to compare the duration against the time that the transfer was attempted.
One open ❓ I'm thinking about is whether or not we should change the behavior for the `*api.Object.IsExpired` method to also take a direction so that it can compare against a specific action, and not all of them (as it currently does). This may not actually matter so much, since spec-compliant implementations of the LFS API will only send back the action that we're interested in.
The new error message is down below:
```
Git LFS: (0 of 1 files) 0 B / 29 B
LFS: lfs/transfer: object …
```
> transfer: more descriptive "expired at" errors

- httputil/proxy.go
- q
Sometimes it makes sense to use a proxy even when the remote host is localhost
or 127.0.0.1. git-lfs in contrast to e.g. native git does not allow to use a
proxy when talking to localhost. Remove this special treatment of localhost
and react only on http_proxy or no_proxy env variables.
My use case: I wanted to debug/analyze network traffic from a git client to the
git server and the lfs server running on my developer machine. I set up
mitmproxy [1] as a proxy server running on localhost and I set http_proxy to
point to mitmproxy. I was able to see all the traffic between the client and
the local git server in mitmproxy but the the communication between the client
and the lfs server was hidden because git-lfs ignored the proxy settings
because the hostname was localhost.
> Allow usage of proxies even when contacting localhost

- test/test-filter-process.sh
This pull request adds an integration test making sure the filter protocol works as expected, when it is enabled.
The test I added creates two files tracked with LFS on two separate branches, and asserts that on each branch, each one of the files:
- exists
- has the correct "smudged" contents
- has a valid LFS pointer underneath.
Currently, running the test is gated on the `$GIT_LFS_USE_LEGACY_FILTER` being enabled (`eq "1"`), and the installed version of Git including support for the filter process. Usually, this is done with:
```bash
ensure_git_version_isnt "$VERSION_LOWER" "2.11.0"
```
but since `2.11.0` isn't released yet, the best we can do is check that the version is a pre-release and contains a "g" in the patch number, like: `git version 2.10.1.710.g6539e97`. This is done by using …
> filter_stream: Integration tests

- commands/command_filter.go
- git/packet_writer.go
- git/packet_writer_test.go
This pull-request provides an implementation of the `io.Writer` interface capable of writing packets using the Git "pktline" format to an underlying datastream.
Here's a 🔎  at some the different parts of this PR:
1. https://github.com/github/git-lfs/commit/5723bb8c016d422fa098fcdaaf1dd15e146c3e42: implement the `PacketWriter` type and add an exhaustive set of unit tests.
2. https://github.com/github/git-lfs/commit/8ab75794997d64c92dc7649abb216ce33e32fbe4: add public constructor `NewPacketWriter` which takes any `io.Writer` and returns a `*PacketWriter` wrapping that underneath. If the given writer is itself already a `*PacketWriter`, it returns that wholesale to avoid re-wrapping.
3. https://github.com/github/git-lfs/commit/a90c16285bc98ae8f7e71fea832494eeabb0caf2: Use the `io.Writer` in …
> filter_stream: provide io.Writer implementation

- commands/command_filter.go
- git/git_filter_protocol.go
- git/object_scanner_test.go
- git/packet_reader.go
- git/packet_reader_test.go
- git/packet_writer.go
- git/packet_writer_test.go
- lfs/pointer.go
- lfs/pointer_clean.go
- lfs/pointer_test.go
- tools/math.go
- tools/math_test.go
This pull-request provides an implementation of the `io.Reader` interface that can read data encoded with the protocol used for filter process communication.
This provides a huge savings on memory usage when cleaning files, as the shasum of the contents can be calculated as data is streamed in, and then discarded.
This pull request is implemented in three parts:
- https://github.com/github/git-lfs/commit/4524d1221efc54d82f4a409208e0d83a56a1c78e: Implement the underlying `PacketReader`.
- https://github.com/github/git-lfs/commit/d23c0445f4580d6b82345ae3613bf47ecaff482a: Make the `WriteStatus` method public since reading packets no longer reports success/error statuses, and this responsibility will be delegated to the caller in the following commit...
- …
> filter_stream: provide io.Reader implementation

- commands/command_filter.go
- git/git_filter_protocol.go
- git/object_scanner_test.go
- git/packet_reader.go
- git/packet_reader_test.go
- git/packet_writer.go
- git/packet_writer_test.go
- lfs/pointer.go
- lfs/pointer_clean.go
- lfs/pointer_test.go
- tools/math.go
- tools/math_test.go
This pull-request cleans up the `ObjectScanner` API to better fit the scanner-pattern, an example of which can be found in [`bufio.Scanner`](https://golang.org/pkg/bufio/#Scanner).
Commit by commit, here's the breakdown:
1. https://github.com/github/git-lfs/commit/78e583e48e83f5c3889e58079f0242e9e1736aa1: instead of logging errors directly to `os.Stderr` and returning a `bool` from `Init()`, return those messages in `error`s.
2. https://github.com/github/git-lfs/commit/6728507d5e33e832083e97be1ec53b893795864a: cleanup the `"Error: "` prefixes from the messages, since that formatting will be handled by the `commands` package now.
3. https://github.com/github/git-lfs/commit/18ac2724fd84a76a95ed494a0b3c337974d78ba9, https://github.com/github/git-lfs/commit/b2e568f56d1efb533de01accdd58348e03aa …
> filter_stream: Make ObjectScanner behave like a Scanner

- commands/command_filter.go
- git/filter_protocol.go
- git/filter_protocol_test.go
- git/git_filter_protocol.go
- git/object_scanner_test.go
- git/packet_reader.go
- git/packet_reader_test.go
- git/packet_writer.go
- git/packet_writer_test.go
- lfs/pointer.go
- lfs/pointer_clean.go
- lfs/pointer_test.go
- tools/math.go
- tools/math_test.go
This pull-request adds unit tests ensuring that the Go implementation of the filter protocol is correct.
This PR contains a fair number of changes, so here's the breakdown:
1. https://github.com/github/git-lfs/commit/8bc726dc87d4763d083c4c958842f48c34db6362: Split the high-level protocol (reading requests, writing responses) from the low-level protocol (reading/writing packets, length headers, chunking large packets, etc). This was done so that the unit tests at each "strata" of the protocol could be easily separated, and it hides the underlying implementation of the protocol from the higher-level use cases.
2. https://github.com/github/git-lfs/commit/17f9ead05c0cf3fa81f3d5bbf55a7121b11359bb: add some unit tests for the low-level protocol.
3. …
> filter_stream: Protocol unit tests

- .travis.yml
According to @technoweenie GitLFS should work with Git 1.8.2 or later:
https://github.com/github/git-lfs/issues/410#issuecomment-112976174
Git 1.8.2 is sufficient for Linux but macOS seems to require at least
Git 1.8.5 to run all integration tests. On Git 1.8.2 "test: pull" and
"test: pull with raw remote url" fail on macOS.
Details: https://travis-ci.org/github/git-lfs/jobs/174177362
> travis-ci: test GitLFS with ancient Git version

- api/api.go
- commands/command_push.go
- commands/command_smudge.go
This deprecates `git lfs smudge --info`, since `git lfs ls-files` provides us better info. 
```
$ git lfs pointer --file CHANGELOG.md | git lfs smudge -i
Git LFS pointer for CHANGELOG.md
WARNING: 'smudge --info' is deprecated and will be removed in v2.0
USE INSTEAD:
$ git lfs pointer --file=path/to/file
$ git lfs ls-files
20704 --
```
It also deprecates `git lfs push --stdin`, since `git lfs pre-push` exists.
```
$ echo hi | git lfs push origin master --stdin
WARNING: 'git lfs push --stdin' is deprecated, and will be removed in v2.0.
Run 'git lfs update' or ensure .git/hooks/pre-push uses 'git lfs pre-push'.
```
> 'smudge --info' is deprecated in favor of 'ls-files'

- README.md
Git 1.8.2 seems to be sufficent for Linux but not for macOS. 
Related change: 632f4881293d6974f169adce3a0f53b4e96393bb
> README: set minimal required Git version to 1.8.5

- commands/command_update.go
- config/config.go
- config/environment.go
- config/fetcher.go
- config/git_environment.go
- config/git_fetcher.go
- config/map_fetcher.go
- config/os_fetcher.go
- test/git-lfs-test-server-api/main.go
- transfer/custom.go
I thought it'd be cool to decouple some things from a `*config.Configuration`, specifically `cfg.Endpoint()`. When converting a raw url to an `Endpoint`, [`config.NewEndpointWithConfig()`](https://github.com/github/git-lfs/blob/a45eaee6fa35993763f87aa7611586faea08dfd5/config/endpoint.go#L54-L56) calls [`ReplaceUrlAlias()`](https://github.com/github/git-lfs/blob/a45eaee6fa35993763f87aa7611586faea08dfd5/config/config.go#L451-L454), which [calls `AllGitConfig()` inside `urlAliases()`](https://github.com/github/git-lfs/blob/a45eaee6fa35993763f87aa7611586faea08dfd5/config/config.go#L430-L438).
This PR adds `All()` to the `config.Environment` interface. But, it also had to add `Del(key string)` and `Set(key, value string)` because of a single spot that modifies that internal `gitConfig` map. …
> Remove `AllGitConfig()`

- commands/command_pre_push.go
- httputil/http.go
I've wanted this pre-push tracing for awhile. Makes it easier to see why pushes aren't uploading the objects you think they should.
Also, this gets rid of an extra `trace git-lfs: HTTP:` when you add `GIT_TRACE=` to any Git LFS commands that make HTTP requests.
> Pre push tracing

- git/git.go
Re-implementing #1643 since @jjgod can't sign the cla: https://github.com/github/git-lfs/pull/1643#issuecomment-260432346
> wait for remote ref commands to exit before returning

- test/testutils.go
I want to use `testutils` for testing #1650. However, it seems that `testutils.FileInput` can _only_ write LFS objects. This refactors the code into `(*FileInput) AddToCommit()`, which can eventually support writing plain git objects.
> refactor testutils.FileInput so it's a little more clear

- git/filter_process_scanner_test.go
- git/pkt_line.go
- git/pkt_line_reader_test.go
- git/pkt_line_test.go
Previously, we flushed intermediate data out of the underlying *bufio.Writer
used by the implementation of `pkt-line` in `*git.pktline` after _every_ write.
This means that we would flush after partial packets, whole packets, and after
pkt-line flush sequences. This is unnecessary.
Let us instead flush only after an entire packet has been written, after
writing the `0000` flush sequence.
/ref git-lfs/git-lfs#1640
---
/cc @technoweenie @larsxschneider
> filter-process: less flushing

- commands/command_prune.go
- commands/uploader.go
This ensures that all transfers by the `checkQueue` are set as uploaded. I thought this might also be the cause of a deadlock, but now I don't think so. Nothing is waiting for `len(missing)` items to flow through `transferc`.
> start reading off the Watch() channel before sending any input

- lfs/gitscanner_catfilebatch.go
The problem here is that `DecodePointer()` will return an error early before reading `size` bytes. The scanner needs _all_ of those bytes to be read, so the next loop starts at an object header.
> cat-file batch: read all of the bytes

- lfs/gitscanner_catfilebatch.go
> cat file --batch: read all of the bytes

- CHANGELOG.md
- config/version.go
- debian/changelog
- lfs/lfs.go
- rpm/SPECS/git-lfs.spec
- script/build.go
- script/release.go
- script/script.go
- script/windows-installer/inno-setup-git-lfs-installer.iss
This bumps the version number, and adds some code to track the sha-256 hashes of the built binaries.
> Ship 1.5.1

- script/packagecloud.rb
After shipped v1.5.1, I looked into why Fedora 24 isn't working. Turns out I just needed to add it to the list.
@JonasT: Does this work for you?
> 1.5/fedora 24

- commands/command_filter_process.go
This fixes the error reporting for https://github.com/git-lfs/git-lfs/issues/1697
> filter-process: exit with error if we detect an unknown command from Git

- commands/command_filter_process.go
> Backport #1698 for v1.5.x: filter-process: exit with error if we detect an unknown command from Git

- LICENSE.md
This PR removes the "This project is licensed under the MIT license" line from the license, and replaces it with just the license title (which itself, is optional).
This will allow GitHub to properly detect the license, because right now it doesn't know what that extra line of custom text means, or if it has any legal implications (and thus doesn't call the license MIT).
> Remove the license description from the license itself

- CONTRIBUTING.md
- README.md
Apparently the process-filter does not work with Go below version 1.7
cf. https://github.com/git-lfs/git-lfs/pull/1699#issuecomment-262303880
> GitLFS requires Go 1.7+

- LICENSE.md
This is a quick fix to get license detection working while it's fixed upstream.
The underlying copyright regex [assumes there's a copyright date](https://github.com/benbalter/licensee/blob/master/lib/licensee/matchers/copyright_matcher.rb#L8), the year field being present in the original license template.
This PR simply adds the year, so that the license matches the regex. See http://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/ for background on why that is the "proper" copyright notice (although this change should have no legal significance).
> Add copyright date to license

- commands/command_lock.go
- commands/command_locks.go
- commands/command_unlock.go
- commands/commands.go
- locking/cache.go
- locking/locks.go
Re-implementation of #1625. Based on PR feedback (except config changes which are still pending). Channel wrappers are gone & so is much of complexity, simpler for clients (and added local `Lock` struct so remove dependency on `api.Lock`). 
Merge target is `locking-master` to denote that this isn't a finished API yet but to enable reviewing in bite-size chunks.
> Locking: move lock funcs to own package

- commands/command_install.go
- commands/command_uninstall.go
- commands/run.go
- localstorage/currentstore.go
- test/test-install.sh
- test/test-uninstall.sh
Fixes #1717 by splitting `localstorage.ResolveDirs()` so that `install` and `uninstall` can do what they need if `lfs.InRepo()` is true.  This is meant to be a bug fix, and definitely doesn't try to fix any package design issues.  I want to backport this PR to v1.5.3, and explore a redesign of this code for 2.x.
> Fix Install in root problems

- git/filter_process_scanner.go
- git/filter_process_scanner_test.go
A filter process key-value pair must be split at the first '=' character
into into at most two substrings. The value *can* contain a '='
character. The key *must never* contain a '=' character.
Should fix https://github.com/git-lfs/git-lfs/issues/1730
> git: parse filter process header values containing '=' properly

- config/endpoint.go
The `url.Parse()` func on go 1.8 fails to handle ssh remotes like `git@foo.com:user/path.git`. Instead of returning a `*url.URL` where the `Path` property is the entire raw url, it now returns an error: "first path segment in URL cannot contain colon".
This now attempts to parse the bare ssh url in case `url.Parse` returns a URL, working on both go1.8 and go.1.7.
> fix ssh endpoint parsing

- git/filter_process_scanner.go
- git/filter_process_scanner_test.go
> Backport #1731 for v1.5.x: git: parse filter process header values containing '=' properly

- .travis.yml
- appveyor.yml
This pull-request uses Go 1.7.4 on all of our build services. Go 1.7.4 matches what we ship with (after bumping the build dockers) and contains security fixes over 1.7.3.
- **TravisCI**: Bumped version.
- **CircleCI**: Uses latest version from Homebrew, already upgraded.
- **AppVeyor**: Doesn't ship their workers with 1.7.4 yet, working on installing it ourselves.
---
> build: use Go 1.7.4

- commands/command_track.go
- filepathfilter/filepathfilterbench/bench_test.go
- tools/filetools.go
- tools/filetools_test.go
This is an exploration of a new `FastWalkGitRepo` api that accepts a function callback, instead of returning channels. I've been thinking about the `gitscanner` public interface for a few weeks, and I keep coming back to the fact that we should not be exposing channels to end users (even if _we_ are the end users too). I picked `FastWalkGitRepo()` as a guinea pig, since it's much simpler. 
The `commands/command_track.go` changes look much better to me. The new version is focused on what the command needs, and not reading channels concurrently.
I wrote this as a parallel implementation so I could compare the benchmark side by side, and don't see a big difference:
```
$ script/test tools -v -run Bench -bench . -count 5
BenchmarkFastWalkGitRepoChannels-8   	       1	3059166517 ns/op
--- …
```
> Fast walk no channels

- commands/command_checkout.go
- commands/command_clone.go
- commands/command_fetch.go
- commands/command_fsck.go
- commands/command_ls_files.go
- commands/command_pre_push.go
- commands/command_prune.go
- commands/command_pull.go
- commands/command_push.go
- commands/command_status.go
- commands/uploader.go
- lfs/gitscanner.go
- lfs/gitscanner_index.go
- lfs/gitscanner_log.go
- lfs/gitscanner_refs.go
- lfs/gitscanner_tree.go
- lfs/scanner_git_test.go
- test/test-fsck.sh
This changes the `gitscanner` API to use callbacks, instead of returning a `PointerChannelWrapper`. See [the fsck command](https://github.com/git-lfs/git-lfs/compare/fast-walk-no-channels...gitscanner-callbacks?expand=1#diff-3b7fa953c43592e4af73f324813e6c2fR35) for an _ideal_ usage of it:
```go
gitscanner := lfs.NewGitScanner(func(p *lfs.WrappedPointer, err error) {
// handle pointers or scan errors
})
if err := gitscanner.ScanRefWithDeleted(ref.Sha, nil); err != nil {
// handle cmd error
}
gitscanner.Close()
```
You can now pass a callback to `NewGitScanner()` for all the `.Scan*()` funcs, or pass a callback to individual functions if you want those pointers to be handled differently.
Unfortunately, this introduces some ugly code in the core push/pull/checkout related commands. A lot of …
> Gitscanner callbacks

- commands/command_checkout.go
- commands/command_clone.go
- commands/command_fetch.go
- commands/command_pull.go
- lfs/gitscanner.go
- lfs/gitscanner_tree.go
- test/test-clone.sh
This removes the inline filepathfilter checking from the `commands`, relying on the gitscanner to do it.
> Teach gitscanner how to filter in ScanTree()

- commands/command_checkout.go
- commands/command_fetch.go
- commands/commands.go
- commands/uploader.go
- lfs/download_queue.go
- lfs/transfer_queue.go
- lfs/upload_queue.go
- progress/logger.go
- progress/meter.go
- test/git-lfs-test-server-api/main.go
This replaces the argument list in the transfer queue constructors with a variadic option func arg. Both `meter` and `dryRun` are technically optional. Also, the `*TransferQueue` has that `run()` that's required.
This was mostly an experiment. I'm now thinking that `newTransferQueue(dir transfer.Direction)` is all we need if `tq.Run()` is called after the first `tq.Add(...)`. Then you wouldn't need optional args in any fashion:
```go
tq := newTransferQueue(transfer.Download)
// defaults to false
tq.DryRun = true
// defaults to progress.Noop()
tq.Meter = progress.NewMeter("...")
```
> Introduce transfer queue options

- tq/worker_queue.go
- tq/worker_queue_test.go
This pull-request implements the `*tq.WorkerQueue` type, responsible for distributing work among an available set of workers.
Functionally, this type is very similar to the existing [`*transfer.adapterBase`][1] type, but I chose to re-implement in this new package for a few reasons:
1. **Model of execution**. This implementation has slightly different conditions for deciding when workers are available, and when new work can be assigned to the queue. Since this is an "all or nothing" scenario, where these execution changes have to be implemented atomically, I figured it'd be easier to start with something similar and port over functionality as necessary.
2. **New package**. This is going in a new package, `tq`, so at the very least I'd be duplicating the `transfer.adapterBase` type as …
> tq: implement `*tq.WorkerQueue` type

- test/testhelpers.sh
This pull-request suppresses the progress output that cURL generates at the end of running the integration suite, which can get rather annoying :-).
I intentionally didn't apply the `-s` flag to other `curl` invocations in the `testhelpers` file, since I think that output is useful when going through failure logs.
---
> test: suppress cURL progress when shutting down the test server

- commands/command_lock.go
- commands/command_locks.go
- commands/command_unlock.go
- locking/cache.go
- locking/cache_test.go
- locking/locks.go
- locking/locks_test.go
- test/test-locks.sh
- tools/kv/keyvaluestore.go
- tools/kv/keyvaluestore_test.go
The next incremental rewrite of the locking work; this time we're using our key value store to locally cache locks for the current user for more efficient access. This will be used in the next PR to provide efficient support for marking files read-only on checkout if not locked.
Also adds some minor API improvements such as returning a full `Lock` structure on acquiring a lock rather than just an Id.
> Implement local lock cache, support querying it

- filepathfilter/filepathfilter_test.go
Related: #1750 
Just a tiny PR to add tests for set support in filter e.g. `[Dd]ebug`. This is supported by .gitignore even though it's not very explicit in the git docs. I thought it might be an explanation for the issue above but it wasn't, this test just proves that.
> Add test to prove set operator [] works in filter matching

- commands/command_fetch.go
- commands/command_prune.go
- commands/commands.go
- commands/uploader.go
- lfs/download_queue.go
- lfs/lfs.go
- lfs/manifest_test.go
- lfs/upload_queue.go
- test/git-lfs-test-server-api/main.go
- tq/custom.go
- tq/custom_test.go
- tq/manifest.go
- tq/transfer_queue.go
- tq/transfer_queue_test.go
- tq/transfer_test.go
This is a slightly different approach to #1766. Instead of introducing a new `tq.WithGitEnv()` option, this assumes that the caller will configure the `*tq.Manifest`, which is now a required argument for `NewTransferQueue()`. I was able to remove all `config` references inside the `tq` package except for the internal uses (which is tied to internal api methods still using it). Nothing in the exported interface uses `config` anymore though.
I like this approach, it gets us closer to @sinbad's idea of a config object per package. Could even rename `*tq.Manifest` to `*tq.Config` if you think that'd make more sense.
Notes:
* <del>Had to export `BasicTransfersOnly` and `TusTransfersAllowed` allowed, because `Unmarshal()` can only set exported properties. I'd rather not export these …
> Manifest config attempt 2

- lfs/pointer_smudge.go
This removes the only public usage of `tq.NewTransfer()`. That `multiErr` stuff should be pulled into some package....
> teach the smudge filter how to use the transfer queue directly

- lfs/pointer_smudge.go
- test/test-custom-transfers.sh
- tq/adapterbase.go
- tq/custom.go
- tq/transfer.go
- tq/transfer_queue.go
- tq/transfer_test.go
This implements my [suggested change](https://github.com/git-lfs/git-lfs/issues/1764#issuecomment-266901659) of the adapter `Begin()` interface, to accept a configuration object interface, instead of a `maxConcurrency int` argument. This gives us flexibility to add more properties if needed without breaking the public interface. If we decided to add something like `MaxSchmeckles() int`, adapters would keep working without ever having to deal with schmeckles if they don't need to.
The PR is currently based on #1772, which is about to merge. Once merged, the base will change to `tq-master`.
> Change Adapter Begin() signature to accept an AdapterConfig interface

- tq/transfer.go
- tq/transfer_queue.go
This pull-request un-exports two identifiers, `tq.NewTransfer` and `tq.Batch`, since they are not needed in the public API.
Since we got un-exported `tq.NewTransfer`, this removes the last public use of the `api` package in `tq`, meaning callers don't need to depend on `api` directly to use `tq`.
---
> tq: un-export `NewTransfer` and `Batch`

- commands/command_fetch.go
- commands/command_prune.go
- commands/commands.go
- commands/uploader.go
- lfs/download_queue.go
- lfs/upload_queue.go
- test/git-lfs-test-server-api/main.go
This pull-request moves the `lfs.NewDownloadable` and `lfs.NewUploadable` functions into the `commands` package and un-exports them.
As an aside, the `NewUploadable` alternative had to be copied into the `test` package, since it was inaccessible as a private member of the `commands` package. I think this follows the Go-ism: "A little copy is better than a little dependency."
---
> lfs,cmd: remove lfs.New{Downloadable,Uploadable}

- docs/api/batch.md
- docs/api/schemas/http-batch-request-schema.json
This pull-request makes more clear that object sizes sent to and returned from the server must be positive.
This information was originally added in https://github.com/git-lfs/git-lfs/pull/1371, but only changed the legacy and v1 schemas, which were removed as of https://github.com/git-lfs/git-lfs/pull/1641. Now they're back :-)
---
/cc @git-lfs/core #1778
> docs/api: object size must be positive

- script/install.sh.example
Implements the suggestion in #1792, using `pushd` and `popd` so the user's `pwd` doesn't change after running the command.
> ensure you're in the correct directory when installing

- script/packagecloud.rb
This pull-request adds `fedora/25` to our list of targets for Packagecloud, which will make all future builds available on the latest release of Fedora.
In addition to this, I re-built and released Git LFS v1.5.3 under the `centos_7` Docker image, and pushed that release out to just the Fedora 25 target.
---
/cc @git-lfs/core https://github.com/git-lfs/git-lfs/issues/1795
> script/packagecloud: release LFS on fedora/25

- commands/command_filter_process.go
- commands/command_smudge.go
- lfs/pointer.go
- lfs/pointer_clean.go
- lfs/pointer_test.go
- test/test-filter-branch.sh
- test/test-malformed-pointers.sh
This pull-request fixes #1729 by streaming out the entire contents of a malformed pointer, instead of truncating the first 1024 bytes.
Previously, if LFS was unable to parse file that it thought was a pointer, it would "smudge" the file by just emitting it as is. The catch, however, was that the only data that it could hold onto was the first 1024 bytes. Since `(*git.PktlineReader) Read()`s block if there is no data on the pipe, buffering a fixed amount of data was the best that we could do. There were two cases:
1. `len(pbuf) < 1024`: We received the entire contents, no join necessary.
2. `len(pbuf) == 1024`: We _might_ have received the entire contents, or there were more than 1024 bytes and we just read the first 1024 of them. 
To handle this better, I introduced …
> commands,lfs: handle malformed pointers

- commands/command_checkout.go
- commands/command_clone.go
- commands/command_fetch.go
- commands/command_pull.go
- commands/command_smudge.go
- commands/command_track.go
- filepathfilter/filepathfilter.go
- filepathfilter/filepathfilter_test.go
- filepathfilter/filepathfilterbench/bench_test.go
- lfs/scanner.go
- tools/filetools.go
- tools/filetools_test.go
This backports the `filepathfilter` package, which should improve `git lfs track` times. /cc #1750
> backport filepathfilter to v1.5.x

- script/packagecloud.rb
> Backport #1797 for v1.5.x: script/packagecloud: release LFS on fedora/25

- progress/meter.go
- progress/spinner.go
This pull-request prevents the `len(padding)` used in the progress meter from ever being less than zero. This prevents the panic from `strings.Repeat` trying to [allocate a slice][1] with a [`len < 0`][2] as seen in #1803.
Previously, LFS printed a number of number of padding characters to the terminal when displaying progress meter updates, so that the terminal's cursor would be in the correct position to fill the entire line after printing the CR character, `\r`, as such:
```
|-----------------------padding---------------------|
message                                                    
^- cursor position
```
However, if the message's length is greater than the terminal width, `width-len(str)` is a negative number, causing the panic as shown above. This check with `tools.MaxInt(0, …
> progress: guard negative padding width, panic in `strings.Repeat`

- commands/command_filter_process.go
- commands/command_smudge.go
- lfs/pointer.go
- lfs/pointer_clean.go
- lfs/pointer_test.go
- test/test-filter-branch.sh
- test/test-malformed-pointers.sh
This backports #1796.
- commands/command_filter_process.go
- commands/command_smudge.go
> Backport #1796 for v1.5.x: commands,lfs: handle malformed pointers

- filepathfilter/bench_test.go
This pull-request removes the sub-package: `github.com/git-lfs/git-lfs/filepathfilter/filepathfilterbench`, which caused builds on Debian 7 & 8 to fail under `dh_golang`.
When trying to build the v1.5.4 release of LFS, `dh_golang` would not successfully preform the `go install -v` of all Go/LFS packages necessary to build LFS. When inspecting a diff of the build log between the v1.5.3 and v1.5.4 tree, I noticed the following line:
```
go build github.com/git-lfs/git-lfs/filepathfilter/filepathfilterbench: no buildable Go source files in /tmp/docker_run/src/github.com/git-lfs/git-lfs/i386/obj-i486-linux-gnu/src/github.com/git-lfs/git-lfs/filepathfilter/filepathfilterbench
```
`go build` exits in a dirty state after trying to build a path with no source files in it, as is the case with the …
> filepathfilter: remove `*bench` subpackage

- filepathfilter/bench_test.go
> Backport #1810 for v1.5.x: filepathfilter: remove `*bench` subpackage

- commands/command_lock.go
- commands/command_locks.go
- commands/command_unlock.go
- locking/locks.go
- test/test-lock.sh
- test/test-locks.sh
- test/test-unlock.sh
This pull-request backports an internal change made to the various locking commands adding the `--json` flag.
To allow 3rd party tools written in languages that do not interoperate with Go to integrate with LFS , a `--json` flag is used to share a standard encoding format. This allows other programs to shell out to LFS and expect an exact data format in return over stdout.
As a caveat, the `Error()`'d messages are not encoded in JSON. This behavior should be OK, since programs can expect that JSON parse errors should be treated as LFS errors and can treat the contents of stdout as the error message.
---
While working on this PR, I noticed that none of the three locking commands (`locks`, `lock`, and `unlock`) have manpage documentation. Before removing the `GITLFSLOCKSENABLED` environment …
> locking: add `--json` flag

- test/test-clone.sh
> Backport #1801 for v1.5.x: clone: debug transient 'clone' failure

- test/test-lock.sh
- test/test-locks.sh
- test/test-unlock.sh
This pull-request updates the assertions added in #1814 (`assert_server_lock`, `refute_server_lock`) to include the `"$reponame"` argument, as added in #1818.
---
/cc @git-lfs/core #1820
> test/locks: update lock assertions to include missing reponame

- commands/command_lock.go
- commands/command_locks.go
- commands/command_unlock.go
- commands/commands.go
- lfsapi/auth_test.go
- lfsapi/certs_test.go
- lfsapi/client.go
- lfsapi/client_test.go
- lfsapi/endpoint_finder_test.go
- lfsapi/errors.go
- lfsapi/lfsapi.go
- lfsapi/proxy_test.go
- locking/api.go
- locking/api_test.go
- locking/cache.go
- locking/locks.go
- locking/locks_test.go
- test/cmd/lfstest-gitserver.go
This updates the locking package to use the new `lfsapi.Client` from the `api-master` branch. As a result, this removes the dependencies on the `api` and `config` packages from `locking`, while adding `lfsapi` of course.
> api refactor: locking

- lfsapi/errors.go
- test/git-lfs-test-server-api/main.go
- test/git-lfs-test-server-api/testdownload.go
- test/git-lfs-test-server-api/testupload.go
- tq/api.go
- tq/api_test.go
- tq/manifest.go
- tq/transfer.go
- tq/transfer_queue.go
This removes the last `api` dependency in `tq`.
> tq: move api.ObjectResource to tq pkg

- docs/custom-transfers.md
- test/test-custom-transfers.sh
- tq/custom.go
The message sent to terminate the custom adapter should have been named `event`, not `type`; this was left over from a terminology change and went unnoticed until it was pointed out in #1845 that it didn't conform to the docs.
This adds a test to check for that and fixes the problem. I've tested with our own Bitbucket custom adapter here and it's fine; like the test custom adapter it didn't notice this mistake because it was terminating when the I/O stream was closed anyway and there was no additional clean up.
Also includes a small tweak to the docs indicating the sequencing within a single adapter as ambiguity was pointed out in #1845.
> Custom transfer terminate

- config/environment.go
- config/fetcher.go
- config/git_environment.go
- config/git_fetcher.go
- config/map_fetcher.go
- config/os_fetcher.go
This removes some deprecated functions in the `config.Environment` interface. This was used for the code that sets the `lfs.{url}.access` key, when an LFS endpoint requires authentication. Git LFS now handles this in the [`lfsapi.EndpointFinder`](https://github.com/git-lfs/git-lfs/blob/2e213cf9c4423c75f72cb9fbdf5acb16e11ea799/lfsapi/endpoint_finder.go#L180-L216) by caching the url in-memory when it's set. This is fine, since `git-lfs` is typically a short-lived command.
> config: environments are immutable

- lfsapi/schema/fixture/invalid.json
- lfsapi/schema/fixture/valid.json
- lfsapi/schema/reader.go
- lfsapi/schema/reader_test.go
- lfsapi/schema/schema.go
- lfsapi/schema/schema_test.go
This pull-request implements @technoweenie's idea in https://github.com/git-lfs/git-lfs/pull/1846#issuecomment-271621665 to introduce an `io.Reader` implementation: `schema.Reader`, capable of validating the data it's read against a JSON schema.
This will change our testing methodology a little bit, since instead of creating valid/invalid instances of request and response types, _then_ marshaling them to JSON, we have to valid data as it is sent and received. In other words, we'd be doing validation in `*net/http/httptest.Server`s against `req.Body`, which I think is a more appropriate level to test at, anyway.
---
> lfsapi/schema: implement `schema` pkg

- commands/command_pre_push.go
- commands/command_push.go
- commands/commands.go
- commands/uploader.go
- test/test-pre-push.sh
- test/test-push.sh
- tq/transfer_queue.go
This pull-request teaches the `push` and `pre-push` commands how to use the new `gitscanner` without accumulating potentially large slices of `*lfs.WrappedPointers`.
Previously, in order to push a set of LFS objects to a remote, the pusher needed to have explicit knowledge of all objects they were going to push. In many cases, this isn't a problem, since usually the number of objects is manageable. During initial or large pushes, however, the number of objects to push can grow prohibitively large, causing a problem.
This pull-request applies the work that @technoweenie has done with the `gitscanner` type and applies it to the `push` and `pre-push` commands. Here's a breakdown of what happened:
1. 4d4f808: since the commands will now call `uploadPointers()` more than once, re-use the …
> commands: convert push, pre-push to use async gitscanner

- git/git.go
Fixes git-lfs/git-lfs#865.  These are the changes that @marcrossinyol created.  Tested against v1.5.4 on cygwin.  Can't test against master because master doesn't build on cygwin:
```
$ ./script/bootstrap
Installing goversioninfo to embed resources into Windows executables...
Creating the resource.syso version information file...
git-lfs.go:1: running "goversioninfo": exec: "goversioninfo": executable file not found in %PATH%
```
> Fixed file paths on cygwin.

- lfs/pointer_clean.go
This pull-request fixes a bug where the entire contents of a malformed pointers would be buffered in memory, as reported in #1851.
Some backstory: in v1.5.4 I merged #1796 (via #1805) which re-added support to stream the entire contents of a malformed pointer though the filter-protocol added in Git v2.11. This involved a change to the signature of DecodeFrom where instead returning a `[]byte`, containing the data it buffered, it instead returned an `io.Reader` which contained the entire contents of the pointer and could be read from by the caller.
To bring the calling code up to speed, I introduced the following line to grab a `[]byte` of the data buffered from reading the pointer:
```go
by, rerr := ioutil.ReadAll(buf)
```
This is fine for small pointers, but will exhaust system memory …
> lfs: only buffer first 1k when creating a CleanPointerError

- lfs/pointer_clean.go
> Backport #1852 for v1.5.x: lfs: only buffer first 1k when creating a CleanPointerError

- commands/command_locks.go
- locking/api.go
- locking/locks.go
- locking/locks_test.go
This pull-request reintroduces the `Committer` field on the `*locking.Lock` type.
This was the [original interface][1] of that type, but was removed in #1732 in favor of `Name` and `Email` top-level fields on the `Lock` type. Instead, let's bring back the original API which:
- has parity with how the data is sent over the network, and...
- is more direct in it's meaning. A lock has a committer, not a name and email. 
This pull-request also comes with some additional benefits:
1. Fix a bug where the `gitserver` was unable to find the fields to de-serialize the committer's name and email, thus making all locks have `""` empty-string owners.
2. Implement `fmt.Stringer` on the `Committer` type, which yields the expected format: `First Last <email@example.com>`.
---
[1]: …
> locking: reintroduce `Committer` field

- commands/command_install.go
- docs/man/git-lfs-install.1.ronn
- test/test-install.sh
- test/testhelpers.sh
It's bugged me for a while that the integration tests keep creating the `pre-push` hook in my local `git-lfs` working copy repo whenever I run them; it gets much worse when you factor in the new hooks we're starting to add. This happens even if you use `GIT_LFS_TEST_DIR`, if you run the tests from within the working copy.
Seems useful to have a `--skip-repo` option in `git lfs install` which skips the local repo changes, for when you just want to install filters. This is how our tests need to use it. 
I could have just made the tests `cd` to a non-repo folder instead but being explicit seems better.
> Add `--skip-repo` option to `git lfs install` & use in tests

- commands/uploader.go
- locking/api.go
- locking/locks.go
- locking/locks_test.go
- test/test-locks.sh
This pull-request changes all references to the `Committer` type within the `locking` package to use `*Committer`, which implements `fmt.Stringer`.
It also adds integration tests to ensure that the committer is formatted correctly when asking for a list of locks.
---
> locking: use `*Committer` to implement `fmt.Stringer`

- commands/uploader.go
- test/test-pre-push.sh
This pull-request temporarily makes failed lock searches and pushes containing modifications to un-owned locks non-fatal.
---
> commands: unhalt locking pre-push checks 

- progress/meter.go
- progress/noop.go
- progress/progress.go
- tq/transfer_queue.go
This is an attempt to fix #847. It pauses the progress meter before making the batch api request, and then starts it when it passing the batch api response to the transfer adapters. This works because:
* `(progress.Meter) Start()`, `Finish()`, and `Pause()` internally use channels and `atomic/sync`. No need for that `sync.Once` in `tq.TransferQueue`.
* The `tq.TransferQueue` only transfers items from a single batch concurrently. The sequence (Batch API -> _n_ transfer adapter workers) runs sequentially, so that the next batch (if needed) can process the retries from the previous batch.
Unfortunately, there isn't really a way to test this, since it requires interactive input.  Here's an example of this PR working (with a tiny hack to change the batch size to 2):
```
$ git lfs fetch --all …
```
> Fix clash between progress meter and credential helper

- lfsapi/body.go
- lfsapi/client_test.go
- lfsapi/endpoint.go
- lfsapi/endpoint_finder.go
- lfsapi/ssh.go
- lfsapi/ssh_test.go
- locking/api_test.go
- tq/api_test.go
I noticed a few inconsistencies with the completely rewritten API code:
1. Requests from Git LFS aren't sending a `Content-Length` request header.
2. ALL ssh auth requests send the `upload` operation, which interferes with the SSH command `ssh  user@githost.com git-lfs-authenticate user/repo {operation}`.
This PR fixes both.
> Fix lfsapi inconsistencies

- locking/api.go
Really minor tweak that ensures that Git LFS will attempt to convert `lfs.pushurl` or `remote.{name}.pushurl` to build the LFS server url.
> locking: ensure verifiable locks call is made with the correct operation

- commands/command_unlock.go
- git/git.go
- test/test-unlock.sh
A user should not have any uncommitted changes in their working copy when unlocking a file, since to relinquish the lock means that they've either finished making changes, or they don't want to keep their changes. It must be assumed that when relinquishing the lock other users are free to lock & begin making changes immediately which would clash with these outstanding changes.
`--force` overrides this check but with a warning.
This is only part of the overall solution; in future we'll also want to ensure they don't have any unpushed changes before allowing the unlock since those will have the same effect. However this will form part of #1844 which is a more complex proposal. This is an easy win in comparison and easy to understand.
> Check that files are not uncommitted before unlock

- commands/command_track.go
- test/test-track.sh
Just got a report from a Visual Studio user that `git lfs track` blows up when parsing the default `.gitattributes` that VS sets up. This fixes a bug with handling blank lines.
> commands: teach track how to handle empty lines in .gitattributes

- CONTRIBUTING.md
- config/version.go
This makes it super clear that you're not on an official LFS release.
```
$ script/run version
git-lfs/2.0-pre (GitHub; darwin amd64; go 1.7.5; git a699d202)
```
> config: bump version to '2.0-pre' 

- commands/command_smudge.go
- test/test-malformed-pointers.sh
- tools/iotools.go
This backports #1932.
- commands/command_smudge.go
- tools/iotools.go
> Backport #1932 for v1.5.x: Spool malformed pointers to avoid deadlock

- .travis.yml
- appveyor.yml
This pull request upgrades our testing infrastructure to use Go 1.8.
- Travis: bumped in the `.travis.yml` to use 1.8.
- AppVeyor: Go 1.8 isn't in on `cinst` yet, so let's install it ourselves.
- CircleCI: upgrade through https://github.com/Homebrew/homebrew-core/pull/10048
---
> all: build using Go 1.8

- commands/uploader.go
- locking/locks.go
- test/cmd/lfstest-gitserver.go
- test/test-pre-push.sh
- test/test-push.sh
- test/testhelpers.sh
This pull-request allows the LFS client to be configured in such a way that makes lock verification a no-op for servers that don't yet support the new locking API.
At face value, this also makes it very easy for users to disable lock verification to push locked files to servers that don't block pushes not owned by the lock owner. However, there's really no change before/after this PR, since all of this logic is wrapped up in a Git hook anyway, you can still just delete the hook.
Here are the rules:
- If the `.locksverify` rule is unset, make the verify API call...
- If it was successful, notify the user they should "enable" lock verification for that remote
- If it failed...
- AND the failure was a 501, disable the lock verification and move on
- OR print a warning, but still push
- If …
> pre-push: make lock verification optional for servers that don't support it

- commands/command_smudge.go
- test/test-malformed-pointers.sh
This pull request treats empty pointers as empty objects, and writes them out as such.
Previously, an empty pointer would be treated as malformed. An empty file _would_ get written out, but the file would also be marked as belonging to a malformed pointer.
With this change, LFS counts the number of bytes spooled out to Git. If there was no error in spooling, and the number of bytes written is zero (meaning that we successfully wrote zero bytes with the intent to do so), return a nil error, instead of marking it as a malformed pointer.
--- 
/x-ref https://github.com/git-lfs/git-lfs/pull/1922
> commands/smudge: treat empty pointers as empty files

- progress/copycallback.go
- progress/copycallback_test.go
- test/test-progress-meter.sh
This pull-requests fixes #1926, a bug which would cause push/pull operations with small objects to look like this:
```
~/Desktop $ git lfs clone git@github.com:larsxschneider/lfstest-manyfiles.git
Cloning into 'lfstest-manyfiles'...
remote: Counting objects: 15012, done.
remote: Total 15012 (delta 0), reused 0 (delta 0), pack-reused 15012
Receiving objects: 100% (15012/15012), 2.02 MiB | 2.25 MiB/s, done.
Checking out files: 100% (15001/15001), done.
Git LFS: (87 of 201 files) 0 B / 1.15 KB
^
```
The issue lies in the fact that `io.Reader`s, when at the end of a stream, can either return 
- `([]byte, nil)` then `(nil, io.EOF)`, or
- `([]byte, io.EOF)`
From the Go documentation<sup>[[1](https://golang.org/pkg/io/#Reader)]</sup>:
> An instance of this general case is that a Reader returning …
> progress: fix never reading bytes with sufficiently small files

- appveyor.yml
- script/bootstrap
- script/cibuild
This time for version 1.8.0, which is available now.
> AppVeyor: Again use a Chocolatey package for installing Golang

- docs/man/git-lfs-config.5.ronn
- tq/manifest.go
- tq/manifest_test.go
- tq/transfer_queue_test.go
This pull request bumps the default maximum retries LFS will make before failing an object transfer to eight, in conjunction with #1781.
---
> tq: bump 'defaultMaxRetries' to 8

- appveyor.yml
This is nicer than removing the system Go directory.
> AppVeyor: Override PATH with our Chocolatey Go version

- lfsapi/ssh.go
- lfsapi/ssh_test.go
- tools/str_tools.go
- tools/str_tools_test.go
This pull-request fixes #1895 by implementing `tools.QuotedFields`, an alternative to `strings.Fields` that respects balanced pairs of quotes.
The problem in #1895 is that a `GIT_SSH_COMMAND` with spaces inside a balanced pair of quotes would be truncated across multiple "fields", causing the arguments to be passed incorrectly.
For instance, the following string:
```
foo bar 'baz "etc"'
```
given to `strings.Fields` would return:
```go
[]string{"foo", "bar", "'baz", "\"etc\"'"}
```
whereas given to `tools.QuotedFields`, it instead returns:
```go
[]string{"foo", "bar", "'baz \"etc\"'"}
```
When trying to figure out the best way to implement this, I considered a few options:
- Instantiate the `exec.Cmd` in such a way that we wouldn't need to de-quote the input string.
- Write a `func(c …
> tools: fix truncating string fields between balanced quotes

- appveyor.yml
- docs/man/git-lfs-config.5.ronn
- test/cmd/lfstest-gitserver.go
- test/test-verify.sh
- tq/verify.go
- tq/verify_test.go
This pull-request implements `lfs.transfer.maxverifies`, a `.gitconfig` setting to retry verify requests at the end of an upload a configurable number of times.
Closes: #1781.
---
> tq: retry verify requests a configurable number of times

- commands/command_lock.go
- commands/command_locks.go
- commands/command_unlock.go
- test/test-lock.sh
- test/test-locks.sh
- test/test-pre-push.sh
- test/test-unlock.sh
- test/testhelpers.sh
This improves (IMO) some of the lock messages:
1. Use active voice for lock and unlock
2. Line up `locks` output columns
```sh
$ git lfs lock gif/dupe.gif
'gif/dupe.gif' was locked (272)
$ git lfs locks
jpg/kabuki-tattoo-left.JPG	technoweenie
gif/atom-undo.gif	technoweenie
gif/dupe.gif	technoweenie
3 lock(s) matched query.
```
```
$ git lfs lock lock.json
Locked lock.json
$ git lfs locks
jpg/kabuki-tattoo-left.JPG	technoweenie
gif/atom-undo.gif         	technoweenie
gif/dupe.gif              	technoweenie
```
> Improve lock messages

- commands/command_lock.go
- commands/command_locks.go
- commands/command_unlock.go
- errors/errors.go
- lfsapi/auth.go
- lfsapi/errors.go
- lfsapi/response_test.go
- test/test-unlock.sh
This adds `error.Cause()`, which removes all those error wrap prefixes when printing messages to stderr.
```
$ git lfs lock path/to/file
Lock failed: api: http: http: Lock exists
$ git lfs lock path/to/file
Lock failed: Lock exists
```
> Print error causes to stderr

- lfsapi/auth.go
Some of the new lock commands return 403 for legitimate reasons:
* Attempt to unlock someone else's lock.
* Attempt to create lock that already exists.
* Attempt to force unlock without proper privileges to do so.
This can also happen with the batch api, if you only have read, but not write, access to a repository.
These cases shouldn't force you to log in again. Typically, users have to confirm their settings on their git host.
> lfsapi: only reject credential helper values on 401 requests

- commands/command_locks.go
- commands/command_unlock.go
- lfsapi/errors.go
- locking/locks.go
- test/test-unlock.sh
Three small things:
1. I thought printing the doc url and request id for every error was too noisy. Especially, when some are common errors like attempting to unlock someone else's file.
2. Added IDs to the `git lfs locks` output.
$ git lfs locks
collabocats.txt	ttaylorr	ID:1
supportocat.txt	technoweenie   	ID:2
3. `git lfs unlock --id={id}` was causing Go to panic since `args` is nil. Fixed that, and updated the test that let the error slide by piping the contents to `tee`.
> More msg tweaks

- commands/command_clone.go
- commands/command_track.go
- git/git.go
- tools/cygwin.go
- tools/cygwin_windows.go
- tools/os_tools.go
This pull-request expands on #1820 by spiking out some functions in the `tools` package to convert Windows paths to Cygwin paths. 
This was prompted by https://github.com/git-lfs/git-lfs/issues/865#issuecomment-281044331, which was comparing the Windows path from `os.Getwd()` with the Git working dir in Cygwin format from `config.LocalWorkingDir`.
Since we don't have integration tests on Cygwin (though we should look into that) I'm leaving this as a [WIP] until we can verify that it works as expected.
> Cygwin tools

- test/test-post-checkout.sh
- test/test-post-commit.sh
- test/test-post-merge.sh
- test/test-track.sh
- test/testhelpers.sh
This is the only way I could get the rpm docker builds to pass :( These tests have been working in CI for weeks, but the first attempt to build with `./docker/run_dockers.bsh centos_6` failed:
```
test: post-merge ...                                               FAILED
-- stdout --
set up remote git repository: test-post-merge
Initialized empty Git repository in /tmp/docker_run/src/github.com/git-lfs/git-lfs/rpm/BUILD/git-lfs-2.0.0/test/remote/test-post-merge.git/
clone local git repository test-post-merge to test-post-merge
Cloning into 'test-post-merge'...
...
Downloading file1.dat (23 B)
Downloading file2.dat (23 B)
Downloading file3.big (15 B)
Downloading file4.big (15 B)
-- stderr --
+ set -e
++ basename test/test-post-merge.sh .sh
+ reponame=test-post-merge
+ setup_remote_repo …
```
> test: add assert_file_writable() and refute_file_writable()

- docs/man/git-lfs-config.5.ronn
Seems like this isn't mentioned anywhere else except in the git-lfs tutorial. Feel free to nit on the wording.
> Mention `.lfsconfig` in the `git-lfs-config` documentation

- test/cmd/lfstest-gitserver.go
- test/git-lfs-test-server-api/testdownload.go
- test/git-lfs-test-server-api/testupload.go
- test/test-push.sh
- tq/basic_download.go
- tq/basic_upload.go
- tq/custom.go
- tq/transfer.go
- tq/transfer_queue.go
- tq/tus_upload.go
- tq/verify.go
This pull-request teaches the `tq` package how to fallback to the deprecated `_links` property if it is given instead of `actions` in a batch response. It is intended to address https://github.com/git-lfs/git-lfs/issues/2003.
This functionality is implemented through a new, private type: `multiActionSet`, which behaves like `io.Multi{Reader,Writer}`, except that it instead implements the `ActionSet` interface. When the `HybridActions()` function is called, a `multiActionSet` is composed together, making both `actions` and `_links` accessible.
Unfortunately, the public interface for `tq.Transfer` now includes:
- `tq.Transfer.Actions`
- `tq.Transfer.Links`
- `tq.Transfer.HybridActions()`
Which, to me, feels bloated. `Actions` and `Links` are necessarily left public so as to allow the …
> tq: fallback to _links if present

- lfs/diff_index_scanner.go
- lfs/gitscanner_index.go
This pull request extracts a `DiffIndexScanner` type that will be used by the `status` command to yield more helpful information about why certain files are modified.
Since both the proposed changes to the status command _and_ the `ScanIndex()` operation of the new gitscanner require scanning the output of the `diff-index` command, this PR is only mean to extract that common functionality.
---
> lfs: extract `DiffIndexScanner`

- test/test-custom-transfers.sh
- test/test-resume-tus.sh
- tq/custom.go
- tq/tus_upload.go
This pull request fixes a bug introduced in https://github.com/git-lfs/git-lfs/commit/0677bdd06a97b60455dac2cfa19d54ff697a1e17 (via: [this blame view][1]) where un-initialized `lfsapi.Client` instances were used in place of the [real one][2].
Previously, this wasn't a problem, but since I added #1971 (which uses the API client), this caused a nil pointer de-reference `panic()` on pushes with verify actions using the Tus and custom transfer adapters.
@git-lfs/releases I think that this warrants being backported and released as v2.0.2. In the interim, or if we decided that this isn't worth it, we can always have users set the `lfs.basictransfersonly`. What do you think?
---
/cc @git-lfs/core https://github.com/git-lfs/git-lfs/issues/2046
[1]: …
> tq: use initialized lfsapi.Client instances in transfer adapters

- commands/command_prune.go
- commands/command_status.go
- lfs/diff_index_scanner.go
- test/test-status.sh
This pull-request brings us another step closer to adding additional information to the output of the `status` command by using the new `*lfs.DiffIndexScanner` instead of the `gitscanner`.
By doing so, we give the status command direct access to the `*lfs.DiffIndexScanner` instance, which will eventually receive methods that can answer and provide additional information about why certain files are modified. 
---
> status: use DiffIndexScanner to populate results

- commands/command_status.go
- test/test-status.sh
This pull request updates our unique-ness check in the `git lfs status` command to correctly display partially staged files.
Here's an example. When `git status` shows:
```bash
~/g/git-lfs-test (master!) $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
(use "git reset HEAD <file>..." to unstage)
modified:   gif/droidtocat.gif
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:   gif/droidtocat.gif
```
`git lfs status` used to show:
```bash
~/g/git-lfs-test (master!) $ git lfs status
On branch master
Git LFS objects to be pushed to origin/master:
Git LFS objects to be committed:
Git LFS objects not staged for commit: …
```
> commands/status: show partially staged files twice

- commands/command_clone.go
- docs/man/git-lfs-clone.1.ronn
- test/test-clone.sh
- test/testhelpers.sh
This pull request closes #2064 by installing repo-level hooks after a `git lfs clone` command. It respects the `--separate-git-dir` and `--skip-repo` (from: https://github.com/git-lfs/git-lfs/pull/1868) flags.
If/when this merges, I'll backport this PR to the `release-2.0` tree for release with v2.0.2.
---
> commands/clone: install repo-level hooks after `git lfs clone`

- commands/command_clone.go
- docs/man/git-lfs-clone.1.ronn
- test/test-clone.sh
- test/testhelpers.sh
> Backport #2073 for v2.0.x: commands/clone: install repo-level hooks after `git lfs clone`

- commands/command_status.go
- lfs/gitscanner_catfilebatch.go
- lfs/gitscanner_catfilebatchscanner_test.go
- lfs/gitscanner_tree.go
- test/test-status.sh
This pull-request makes it easier to diagnose why certain files are modified by LFS by adding blob info to each status line entry in the `git lfs status` command.
Here's what the output looks like:
```
On branch master
Git LFS objects to be committed:
file2.dat (LFS: eeaf82b)
file3.dat (LFS: a12942e)
Git LFS objects not staged for commit:
file1.dat (LFS: 1307990 -> Git: 8735179)
file3.dat (Git: 0dc8537)
```
The `()` shows some meta information about each entry's source and destination. For each end, it shows whether the file is tracked by Git or LFS, and the contents SHA of each. The contents SHA is either the `shasum -a 256` of the blob's contents (NB: _not_ the blob SHA itself), or the pointer's OID (if the file is tracked by LFS).
The extra info contained between the `()` comes from …
> commands/status: add blob info to each entry

- lfs/lfs.go
- test/test-custom-transfers.sh
- test/test-resume-tus.sh
- tq/adapterbase.go
- tq/custom.go
- tq/tus_upload.go
I'm tired of seeing these detailed transfer queue trace messages. Most of these are only relevant if you're debugging a transfer queue bug. This PR disables most of it (unless it's reporting an error) unless `GIT_TRANSFER_TRACE` is set.
```
$ rm -rf .git/lfs/objects && GIT_TRACE=1 git lfs fetch --all
10:31:09.552814 git.c:600               trace: exec: 'git-lfs' 'fetch' '--all'
10:31:09.553235 run-command.c:350       trace: run_command: 'git-lfs' 'fetch' '--all'
trace git-lfs: run_command: 'git' config -l
Scanning for all objects ever referenced...
trace git-lfs: run_command: git rev-list --objects --all --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
✔ 7 objects found
Fetching objects...
trace git-lfs: run_command: 'git' …
```
> Introduce GIT_TRANSFER_TRACE for detailed transfer queue msgs

- config/version.go
- rpm/SPECS/git-lfs.spec
- versioninfo.json
This pull-request bumps the version on master to `v2.1.0-pre`, which should remain in place until we release `v2.1.0`, at which point we should remove the `-pre` suffix.
---
> version: bump to 2.1.0-pre

- test/test-custom-transfers.sh
- test/test-resume-tus.sh
- tq/custom.go
- tq/tus_upload.go
> Backport #2047 for v2.0.x: tq: use initialized lfsapi.Client instances in transfer adapters

- commands/command_track.go
- commands/command_untrack.go
- test/test-batch-error-handling.sh
- test/test-batch-transfer.sh
- test/test-checkout.sh
- test/test-chunked-transfer-encoding.sh
- test/test-clone.sh
- test/test-credentials.sh
- test/test-custom-transfers.sh
- test/test-fetch-paths.sh
- test/test-fetch-recent.sh
- test/test-fetch.sh
- test/test-happy-path.sh
- test/test-ls-files.sh
- test/test-pre-push.sh
- test/test-prune-worktree.sh
- test/test-prune.sh
- test/test-pull.sh
- test/test-push.sh
- test/test-resume-http-range.sh
- test/test-resume-tus.sh
- test/test-smudge.sh
- test/test-track-wildcards.sh
- test/test-track.sh
- test/test-untrack.sh
- test/testhelpers.sh
This pull request extracts two functions: `escapeTrackPattern()` and `unescapeTrackPattern()` which correctly handles both spaces (`" "` -> `"[[:space]]"`) and the pound symbol (`"#"` -> `"\#"`).
It also fixes an incorrect regex in `assert_attributes_count` and un-escapes patterns when calling `git lfs untrack`, so that instead of:
```bash
$ git lfs untrack " "
Untracked [[:space:]]
```
you get instead:
```bash
$ git lfs untrack " "
Untracked  
```
I'm thinking that we should quote the pattern that comes out to make it clear what's going on with whitespace-only patterns.
This PR also fixes https://github.com/git-lfs/git-lfs/issues/2041.
---
/cc @git-lfs/core https://github.com/git-lfs/git-lfs/issues/2041
> commands/{,un}track: extract {,un}EscapeTrackPattern()

- test/test-verify.sh
- tq/basic_upload.go
- tq/custom.go
- tq/tus_upload.go
- tq/verify.go
- tq/verify_test.go
This pull request authenticates verify requests from `tq.verifyUpload()` if the transfer is not already authenticated.
---
/cc @git-lfs/core https://github.com/git-lfs/git-lfs/issues/2016
Closes: https://github.com/git-lfs/git-lfs/issues/2016
> tq/verify: authenticate verify requests if required

- commands/uploader.go
- test/test-pre-push.sh
- test/test-push-missing.sh
- test/testhelpers.sh
- tq/errors.go
- tq/errors_test.go
- tq/transfer_queue.go
This pull request is a continuation of https://github.com/git-lfs/git-lfs/pull/2078 following up on https://github.com/git-lfs/git-lfs/pull/2078#issuecomment-289071404 with https://github.com/git-lfs/git-lfs/pull/2078#issuecomment-289078761.
Turns out that our `*tq.TransferQueue` already had some early returns built in for objects that are a) missing or b) corrupt. I taught the `*tq.TransferQueue` and the `*commands.uploader` types to recognize and log them appropriately.
From https://github.com/git-lfs/git-lfs/pull/2078#issuecomment-289078761, this allows:
> - All of the LFS objects that do exist to travel to the remote as early as possible
> - A user to see all of the missing objects in one push instead of getting one error at a time
> - A user to "fix" the missing object later, and …
> commands,tq: specialized logging for missing/corrupt objects

- debian/rules
This PR fixes debian package build errors when building on an ARM machine. Tested on armhf architecture.
> debian: Support building on armhf and arm64

- debian/rules
> Backport #2088 for v2.0.x: debian: Support building on armhf and arm64

- lfsapi/auth.go
- lfsapi/auth_test.go
This pull request fixes a regression where Git remote URLs were scheme-less and have a `:` in the first path segment. This behavior was allowed in Go prior to 1.8 (the first tag to include https://github.com/golang/go/commit/c5ccbdd22bdbdc43d541b7e7d4ed66ceb559030e), but was since corrected in order to comply with [RFC 3986 §3.3](https://www.ietf.org/rfc/rfc3986.txt):
> In addition, a URI reference (Section 4.1) may be a relative-path reference, in which case the first path segment cannot contain a colon (":") character.
Since Git hosts use the `git@host.com:repo.git` convention, this is an illegal URL according to that section of the RFC.
In Go 1.7, this used to be parsed as:
```bash
~/g/git-lfs (parse-git-remotes!) $ go version
go version go1.7.5 darwin/amd64
~/g/git-lfs …
```
> lfsapi/auth: optionally prepend an empty scheme to Git remote URLs

- lfsapi/auth.go
- lfsapi/auth_test.go
> Backport #2090 for v2.0.x: lfsapi/auth: optionally prepend an empty scheme to Git remote URLs

- docs/man/git-lfs-config.5.ronn
- lfsapi/client.go
- lfsapi/creds.go
- lfsapi/creds_test.go
- lfsapi/lfsapi.go
- lfsapi/ssh.go
- lfsapi/ssh_test.go
This is another approach to #2045. It adds implementations of `lfsapi.CredentialHelper` and `lfsapi.SSHResolver` that cache the results in-memory to prevent multiple calls over the span of a single `git lfs` call. While this is the same idea as #2045, it's implemented by wrapping some go interfaces, instead of changing `lfsapi.Client` call signatures. This is more idiomatic go, and doesn't require any changes to callers.
In the interest of testing this out for v2.0.2, the cachers are disabled until `git config lfs.cachecredentials 1` is run.
To highlight the difference, I hacked the batch size to just 1 to simulate multiple batches. Output has important lines in bold to show the difference.
Here's the uncached output for an HTTP remote `fetch`:
> $ git config --unset lfs.cachecredentials …
> ssh auth and credential helper caching

- docs/man/git-lfs-config.5.ronn
> Backport #1999 for v2.0.x: Mention `.lfsconfig` in the `git-lfs-config` documentation

- docs/api/locking.md
> Backport #2028 for v2.0.x: Some minor improvements in the locking API documentation

- docs/man/git-lfs-config.5.ronn
> Backport #2020 for v2.0.x: Add an example on how to write a `.lfsconfig` file

- locking/locks.go
- test/cmd/lfstest-gitserver.go
This pull request attaches the client-specified limit of the number of locks it'd like returned to the LFS server.
This is in conjunction with the [client-side logic]() we have to prevent returning too many locks. These two behaviors work fine together, since the client limiting wont kick in until the server sends more than the expected number of locks.
Closes: https://github.com/git-lfs/git-lfs/issues/2106
---
/cc @git-lfs/core https://github.com/git-lfs/git-lfs/issues/2106
> locking: send locks limit to server

- commands/uploader.go
- locking/locks.go
- test/cmd/lfstest-gitserver.go
- test/test-pre-push.sh
This pull request special-cases authentication errors when printing out the:
```
Remote ... does not support the LFS locking API. 
```
message.
When implementing this change, I started with a `errors.IsUserError(...)` helper function to separate the two cases:
1. The server doesn't support locking and returned an error, or...
2. The server returned an error because of a problem in the request at the client end.
`IsUserError()` felt overly generic, so I started narrowing down what cases could actually cause that, and found that authentication was the only one that came to mind. This check purposefully excludes 401s from the list of auth-based HTTP response codes.
It also checks for 404s when constructing an `errors.NewNotImplementedError(...)`, since that is a valid signal that the server …
> commands,locking: don't disable locking for auth errors during verify

- commands/command_status.go
- git/object_scanner.go
- lfs/gitscanner_catfilebatch.go
- lfs/gitscanner_catfilebatchscanner_test.go
- lfs/gitscanner_pointerscanner_test.go
- lfs/gitscanner_tree.go
This pull request makes the `*lfs.CatFileBatchScanner` type responsible for only parsing LFS-specific data, and defers reading Git object data to a new type called `*git.ObjectScanner.`
In particular, this is required for #2122 in order to read object contents without running the Git plumbing command: `git-checkout-index.1`.
---
/cc @git-lfs/core for review 👀
> git: implement `*git.ObjectScanner` type 

- docs/api/authentication.md
- docs/api/basic-transfers.md
- docs/api/batch.md
- docs/api/server-discovery.md
- lfsapi/ssh.go
- lfsapi/ssh_test.go
- test/cmd/lfstest-gitserver.go
- test/cmd/ssh-echo.go
- test/test-expired.sh
- tools/time_tools.go
- tools/time_tools_test.go
- tq/api.go
- tq/schemas/http-batch-response-schema.json
- tq/transfer.go
This pull-request implements the idea proposed in #2125 to allow an optional `expires_in` property in both the SSH auth API and the batch API. It is introduced as a non-breaking change.
Both the SSH auth response and batch API response types have been expanded as described in https://github.com/git-lfs/git-lfs/issues/2125#issuecomment-291539131:
```go
type T struct {
// ...
ExpiresAt time.Time `json:"expires_at,omitempty"`
ExpiresIn time.Duration `json:"expires_in,omitempty"` 
}
```
and have gained a new helper method:
```go
func (t *T) IsExpiredWithin(d time.Duration) (time.Time, bool) { ... }
```
which returns whether or not the action/SSH auth response is expired, and if so, when.
The behavior for the batch API remains the same, and the SSH auth behavior only changes when …
> lfsapi,tq: relative expiration support

- commands/command_lock.go
- test/test-lock.sh
This pull request normalizes the paths of locked files across platforms to fix the issue described in https://github.com/git-lfs/git-lfs/issues/2138.
Since Windows's `cmd.exe` [uses `\` as the path separator](https://github.com/golang/go/blob/go1.8/src/os/path_windows.go#L8) ([as opposed to `/` on non-Windows systems](https://github.com/golang/go/blob/go1.8/src/os/path_unix.go#L10)), all of the `path/filepath` operations worked as expected, except the output was a Windows-style path.
By using a `path/filepath.ToSlash()` call, we can normalize that away<sup>[[1](https://golang.org/pkg/path/filepath/#ToSlash)]</sup>:
> ToSlash returns the result of replacing each separator character in path with a slash ('/') character. Multiple separators are replaced by multiple slashes.
Where Go defines …
> locks: cross-platform path normalization

- commands/command_smudge.go
- tools/iotools.go
This pull-request expands the `tools.Smudge()` signature to include a temporary directory under which to create the spool file, and updates the call-site in the `smudge` plumbing command to use the localstorage directory and not the top-level `/tmp` directory.
Since we're still using the `io/ioutil.TempFile()` function, temporary files are created with the `os.O_EXCL` flag and are re-created with a re-seeded random number generator if a conflict exists, so files are guaranteed to be unique.
---
> smudge: use localstorage temp directory, not system

- .travis.yml
- README.md
- appveyor.yml
This pull request resolves https://github.com/git-lfs/git-lfs/issues/2141 by building Git LFS on Go 1.8.1.
In terms of CI, we have:
1. Travis, which was upgraded in the `.travis.yml`.
2. CircleCI, which receives whatever the latest `golang` bottle is on Homebrew, which was updated in https://github.com/Homebrew/homebrew-core/pull/12201.
3. AppVeyor, which @sschuberth pointed out is 👍 to go via https://github.com/git-lfs/git-lfs/issues/2141#issuecomment-292698702.
I also noticed that our README recommends that you have a Go higher than 1.7.3. I think this is technically correct, since we don't use any of the latest Go APIs, but I think now is as good a time as any to bump that version.
Closes https://github.com/git-lfs/git-lfs/issues/2141.
--- …
> all: build on Go 1.8.1

- config/url_config.go
- config/url_config_test.go
This pull request teaches the `*config.URLConfig` type to fetch multiple values matching a given `prefix.<url>.key`.
This is supporting work for the http.extraHeaders support as defined in #1500.
Right now, it's based off the work done in https://github.com/git-lfs/git-lfs/pull/2152. Once that branch gets merged, this diff should become more readable. In the meantime, **here's an inter-diff**: https://github.com/git-lfs/git-lfs/compare/fetcher-get-all...url-config-many-headers.
To implement this, I changed the `get` function to `getAll`, which replaces the internal `c.git.Get()` with `c.git.GetAll()` calls, which will return _all_ matching values for a given config key, if any were found. What this means for behavior, is that the public `config.URLConfig.GetAll()` function will return …
> config: support multi-value lookup on URLConfig

- commands/command_env.go
- config/config.go
- config/config_test.go
- config/version.go
- lfs/lfs.go
- lfsapi/client.go
- lfsapi/lfsapi.go
- test/git-lfs-test-server-api/main.go
This pull request removes a dependency drawn from the `github.com/git-lfs/git-lfs/config` package to the `github.com/git-lfs/git-lfs/lfsapi` package, where several of the `Endpoint()`-related functions returned `lfsapi.<T>` types.
This work supports the proposal in #1500, where I need to import the `config` package from `lfsapi` in order to maintain an instance of the `*config.URLConfig` type.
---
> config: remove dependency on lfsapi package

- config/url_config.go
- config/url_config_test.go
This pull request fixes an oversight I made in https://github.com/git-lfs/git-lfs/pull/1912 where the prefix of a `*config.URLConfig` lookup wasn't passed correctly into the `getAll()` function.
This pull request is based off of #2156, which should be merged into master before this branch. __In the meantime, here's an inter-diff__: https://github.com/git-lfs/git-lfs/compare/lfsapi-config-cycle...url-config-prefix.
I snuck a second change in here, to reorder the arguments from:
```diff
-func (c *URLConfig) Get(prefix, key string, rawurl string) (string, bool) {
+func (c *URLConfig) Get(prefix, rawurl, key string) (string, bool) {
```
Which more closely matches the `{prefix}.{url}.{key}` ordering that is actually present in the config entry.
---
> config: add prefix to URLConfig type

- config/url_config.go
- lfsapi/client.go
- lfsapi/lfsapi.go
- test/test-extra-header.sh
This pull request resolves the proposal made in #1500 by implementing support for `http.<url>.extraHeader`.
This pull request is based off of https://github.com/git-lfs/git-lfs/pull/2158, and that should be merged before this one. In the meantime, __here's an inter-diff__: https://github.com/git-lfs/git-lfs/compare/url-config-prefix...lfsapi-extra-headers.
When making any HTTP(S) request from the lfsapi package, LFS will first look for matching `http.{url}.extraHeader` config entries, where `url` is the request URL. LFS currently adds one extra header to each request it makes, which is the `User-Agent: ` header. The `lfsapi` package looks for `extraHeaders` _before_ adding the User-Agent header, so it cannot be overridden.
As per https://github.com/git-lfs/git-lfs/pull/2152 & …
> lfsapi: support for http.<url>.extraHeader

- lfsapi/certs.go
This pull request updates all remaining `http.{url}.*` key lookups to use the new `*config.URLConfig` type.
I did a search via:
```bash
~/g/git-lfs (master) $ find . -type f | grep -v "\.\/vendor" | grep "\.go$" | xargs ack 'http\.'
```
and trimmed those down which yielded the changes made in this pull request. The only other `http.*` key lookup we have is [here](https://github.com/git-lfs/git-lfs/blob/v2.0.2/lfsapi/proxy.go#L51) for the `http.proxy` config, but Git itself does not support per-host/url `http.proxy`-ing.
---
> lfsapi/certs: use *config.URLConfig to do per-host config lookup

- lfsapi/endpoint_finder.go
This pull request replaces all call-sites for `lfs.{url}.access` with a call to `Get()` using the `*config.URLConfig` type.
---
> lfsapi: support URL-style lookups for `lfs.{url}.access`

- commands/uploader.go
- commands/uploader_test.go
- docs/man/git-lfs-config.5.ronn
- test/test-pre-push.sh
This pull request implements support for URL-style lookups for the `lfs.{url}.locksverify` config value and resolves https://github.com/git-lfs/git-lfs/issues/2093.
When writing this, I was wondering if we should change the suggested `git config` commands to use a site's host, instead of the fully qualified path. @technoweenie wisely points out that we can't accurately determine whether or not the hostname is the "root" of the LFS API, so the messages were left unchanged.
To partially mitigate this, I added a `hostsWithKnownLockingSupport`, which skips printing out the suggested `git config` message if it's known that a host supports the LFS locking API. I skipped testing this in the integration suite since there's not an accurate way to do this without making a network call to one of the …
> commands: support URL-style lookups for `lfs.{url}.locksverify`

- commands/commands.go
This pull request addresses the second and third points of https://github.com/git-lfs/git-lfs/issues/2076:
> (2) On Windows, checking this logfile with an application that does not support Linux-style line endings results in this, which is unusual even for cross-platform systems:
This one required some investigation. I originally thought that the goal here was to replace all instances of printing LF (`\n`) characters sent to the terminal, but the actual fix is to just print platform-specific line ending sequences to _files on disk_, not the terminal.
To determine this, I wrote two files to my `~/github/share` directory, which is accessible via my Windows VM. Each had the words "foo" and "bar". One was separated by a LF character, and the other by a CRLF, as follows:
```
~/g/git-lfs …
```
> commands: cross-platform log formatting to files

- commands/command_track.go
- docs/man/git-lfs-track.1.ronn
- test/test-track-attrs.sh
- test/test-track.sh
This pull request adds a `--no-modify-attrs` flag to the `git lfs track` command to "touch" matched tree entries while leaving `.gitattributes` unchanged.
The motivation (which has additional background in https://github.com/git-lfs/git-lfs/issues/2065) is that for files that you wish to "convert" to LFS, this should be a lightweight alternative to the destructive `migrate` command proposed in #2146.
Closes: https://github.com/git-lfs/git-lfs/issues/2065
---
/cc @git-lfs/core https://github.com/git-lfs/git-lfs/issues/2065
> commands/track: teach --no-modify-attrs

- commands/command_checkout.go
- commands/command_pull.go
- commands/command_smudge.go
- commands/command_track.go
This pull request resolves the first concern raised in https://github.com/git-lfs/git-lfs/issues/2076:
> (1) Requiring the user to check the logfile before seeing the full text of an error seems like an unnecessary extra step that prevents quick troubleshooting. This slight obfuscation of underlying cause of errors also likely leads to vague issue reports, which is harder on the maintainers.
I was looking into the cause of this and found that the callsites in question were using the function `commands.LoggedError()`, which has the signature:
```go
func LoggedError(err error, format string, args ...interface{}) { /* ... */ }
```
What this does is effectively:
1. `fmt.Fprintf(os.Stderr, format, args...)`, (write the format string to stderr) and
2. `LogError(os.File, err)` (log the error to …
> commands: include error in `LoggedError()`

- test/test-batch-retries.sh
- test/test-push.sh
- tq/transfer_queue.go
This pull requests expands the amount of information we trace (`GIT_TRACE=1`) when transferring objects and dealing with failed/retried transfers.
There are two occasions upon which the `*tq.TransferQueue` will retry transfers:
1. Failed/un-parseable batch API request/response<sup>[[1](https://github.com/git-lfs/git-lfs/blob/v2.0.2/tq/transfer_queue.go#L341-L345)]</sup>.
2. Error(s) during upload/download itself (or faked transfers results for missing objects)<sup>[[2](https://github.com/git-lfs/git-lfs/blob/v2.0.2/tq/transfer_queue.go#L490)]</sup>.
This pull requests follows the same thought pattern as #2179 and adds the shorthand error to the trace output via the `%s` format string.
This should help surface underlying transfer issues like those occurring in …
> tq: trace retriable errors

- script/changelog
This pull request updates the `git-rev-list(1)` command used to generate release changelogs to only visit the `--first-parent` of each merge.
This way, we avoid inner-merges when merging master back into a feature branch before merging _that_ back into master.
---
> script/changelog: rev-list through --first-parent only

- commands/uploader.go
- test/test-pre-push.sh
Fixes #2166, and reverses #1885 (which was needed because users were inadvertently running on a pre-release version of LFS, which blocked their pushes because no File Locking API implementations existed in the wild yet.
Question: should `locksverify` [automatically be enabled](https://github.com/git-lfs/git-lfs/blob/ab50944e2632844770c4cbf4ef8b79d5ffcfaa81/commands/uploader.go#L141-L145) if it's currently `NULL`, and the locks verify api call returned a valid result? I'm leaning towards "yes." I think our approach in LFS v2.0 is a bit too cautious. I think #2162 is a good step towards improving this situation for public LFS servers that implement the file locking API. But I think auto-enabling after successful results will remove an explicit opt-in step when using internal or custom LFS …
> Fail push if locks verify is enabled, and any locked files are updated

- commands/command_pull.go
- commands/command_status.go
- lfs/extension.go
- lfs/gitscanner_catfilebatch.go
- lfs/gitscanner_tree.go
This pull request represents a complete audit of all calls to the `exec` standard library package as well as the `github.com/git-lfs/git-lfs/subprocess` package to ensure that no subcommands are orphaned when LFS quits.
There are two cases where we can leak processes:
1. Forgetting to call (or not having) a `(*T) Close() error` function to free resources and kill commands.
2. `defer`-ing that call, and not having the defer execute because of a `commands.Exit` or `commands.Panic`.
The issue with calling those `commands.*` helpers is that they use `os.Exit()` calls underneath, which causes an immediate termination of all goroutines, which prevents the calling function from returning thus the scheduler never executes the deferred function calls. From the …
> commands,lfs: prevent process leaks

- commands/run.go
- docs/man/git-lfs-config.5.ronn
- lfsapi/client.go
- lfsapi/lfsapi.go
- lfsapi/stats.go
- lfsapi/stats_test.go
- lfsapi/verbose.go
- locking/api.go
- tools/math.go
- tq/api.go
- tq/basic_download.go
- tq/basic_upload.go
- tq/tus_upload.go
- tq/verify.go
This updates the http logging enabled by `GIT_LOG_STATS=1`:
* Updated the format to include more relevant info, including connection, dns, and tls timings. Uninteresting things like header sizes are left out.
* Instead of tracking requests in per-client slices protected by a mutex, the `*httpTransfer` types are passed around in the request context.
* The log is written to in real time, instead of at the end of the command.
> Streaming log stats

- config/version.go
- rpm/SPECS/git-lfs.spec
- versioninfo.json
This pull request bumps the version identifier to be `Git LFS v2.2.0-pre` in all places that we can.
Since we [released v2.1.0](https://github.com/git-lfs/git-lfs/releases/tag/v2.1.0), the next major version on master will be 2.2.0.
---
> version: bump to 2.2.0-pre

- config/url_config.go
- config/url_config_test.go
- test/test-pre-push.sh
LFS 2.1.0 added the ability to specify some `lfs.*` and `http.*` values with a URL. You can set `lfs.*.access` based on the Endpoint URL:
```sh
$ git lfs env
git-lfs/2.2.0-pre (GitHub; darwin amd64; go 1.8.1; git 68340281)
git version 2.11.0
Endpoint=https://github.com/git-lfs/git-lfs.git/info/lfs (auth=none)
$ git config lfs.https://github.com/git-lfs/git-lfs.git/info/lfs.access basic
```
Most Git hosts don't require the `.git` extension, so you'd _think_ you could use that url in the config:
```sh
$ git remote get-url origin
https://github.com/git-lfs/git-lfs
$ git config lfs.https://github.com/git-lfs/git-lfs.access basic
$ git lfs env
git-lfs/2.2.0-pre (GitHub; darwin amd64; go 1.8.1; git 68340281)
git version 2.11.0
Endpoint=https://github.com/git-lfs/git-lfs.git/info/lfs (auth=none) …
```
> support lfs.<url>.* values where url does not include .git

- commands/uploader.go
- docs/man/git-lfs-config.5.ronn
- test/test-pre-push.sh
- test/test-push.sh
This pull request allows the uploader to push ranges with incomplete or missing/corrupt LFS objects as given by the `lfs.allowincompletepush` configuration value.
Closes: #2063.
---
/cc @git-lfs/core @allaryin https://github.com/git-lfs/git-lfs/issues/2193 https://github.com/git-lfs/git-lfs/issues/2063
> commands/uploader: allow incomplete pushes

- git/git.go
- git/git_test.go
When push to a scp style url, like:
git push git@github.com:git-lfs/git-lfs.git HEAD
Git-lfs will complain about bad url.  This is because golang 1.8 has
changed the implement of `url.Parse` method.  It will fail with a nil
pointer and an error if the remote url is a scp style URL.
Make a golang compatible test, I.E. check null pointer, then check u.Scheme.
Signed-off-by: Jiang Xin <xin.jiang@huawei.com>
> Bugfix: cannot push to scp style URL

- debian/rules
Sorry for the delay on this - I've had it on my todo list for months but hadn't gotten around to it.
The fix was to skip the `dh_golang` step which is used to add the `Built-using` field to the resulting deb.  The field is only used to track the version of go used to build a package so omitting it shouldn't be a problem.  In the commit at https://anonscm.debian.org/cgit/collab-maint/dh-golang.git/commit/script/dh_golang?id=7c3fbec6ea92294477fa8910264fe9bd823f21c3 the dh-golang maintainers changed the logic used to determine the version of go used to check the installed package.  This fails because git-lfs gets built using a manually installed version of go.
This fixes #1472.
> Fix debian 9 (stretch) builds

- commands/uploader.go
- test/test-pre-push.sh
The quoted syntax doesn't work on Windows. Probably a bash vs Windows cmd thing.
/cc https://github.com/git-lfs/git-lfs/issues/2204#issuecomment-299907812
> remove quotes from git config syntax

- commands/run.go
This pull request resolves https://github.com/git-lfs/git-lfs/issues/2207 by printing command help text/manpages to `os.Stdout` instead of `os.Stderr` for consistency with the behavior of Git.
For instance:
```
~/g/git-lfs (help-to-stdout) $ git help 2>/dev/null
usage: git [--version] [--help] [-C <path>] [-c name=value]
[--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
[-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
[--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
<command> [<args>]
```  
and before:
```
~/g/git-lfs (master) $ git lfs help 2>/dev/null
```
after:
```
~/g/git-lfs (help-to-stdout) $ git lfs help 2>/dev/null
git lfs <command> [<args>]
```
Closes: https://github.com/git-lfs/git-lfs/issues/2207
---
/cc @git-lfs/core @lyosha …
> commands/help: print helptext to stdout for consistency with Git

- docker/run_dockers.bsh
- script/packagecloud.rb
This pull request expands on #2203 to include Debian 9 in the build matrix, and distribute packages to Linux distributions built on/with Debian 9.
---
> build: publish Debian 9-compat packages

- script/packagecloud.rb
Apparently I misspoke in #2205
While Mint 18 Sarah and 18.1 Serena are based on Ubuntu Xenial 16.04, it turns out Xenial is actually based on Debian Stretch 9[[1](https://askubuntu.com/a/445496)]. And I use Mint 18...
> Update Xenial is to use stretch packages

- script/packagecloud.rb
This pull request adds a "Debian 9" entry to the list we generate at the end of running `script/packagecloud.rb`. I noticed that I missed this from #2205.
---
> packagecloud: add Debian 9 entry to formatted list

- config/config.go
- config/config_test.go
This pull request allows the ability to use multiple environments given an ordering when calling `config.Configuration.Unmarshal`.
For instance, the following code _would_ have `panic()`'d in previous versions of LFS:
```go
type T struct {
X string `os:"X" git:"lfs.x"`
}
```
In this pull request, calling `config.Configuration.Unmarshal()` on the above code will produce the following behavior:
1. Try and find a value of `X` in the OS environment.
2. If the above value could not be found, try and find it in the Git environment.
3. If the above value is still missing, use the value of X itself (to allow for defaults).
Unfortunately, this required parsing struct tags ourselves, because the `reflect.StructTag` type does not specify an ordering, and rather is defined as: `type reflect.StructTag …
> config: allow multiple environments when calling config.Unmarshal

- config/config.go
- config/config_test.go
> Backport #2216 for v2.1.x: config: allow multiple environments when calling config.Unmarshal

- tq/basic_download.go
This pull request fixes a potential nil-pointer dereference as described in https://github.com/git-lfs/git-lfs/issues/2222.
The issue is that when the `basic_download` adapter tries to issue a "resume download" request to the server and there was an error sending or receiving that request, the client tries to clean up the resources that it held _if_ the response code is 416.
However, this check occurs in an `if err != nil { ... }` block, meaning that the `*http.Request`, `req` can be nil. To solve this, first guard that `res != nil && ...` to prevent a nil-pointer dereference.
My additional concern when I wrote this was that other transfer adapters were affected. I checked all of our transfer adapters, and found that the only time that `req` is ever referenced inside an `if err != nil { …
> tq/basic_download: guard against nil HTTP response

- commands/commands.go
This pull request fixes an error I noticed in our `LoggedError` and `logPanic` functions that format variables like `"%+v"` weren't being formatted correctly when viewing the output of `git lfs logs last`.
This problem was introduced in https://github.com/git-lfs/git-lfs/pull/2178.
---
> commands: fix logged error not interpolating format qualifiers

- commands/commands.go
> Backport #2228 for v2.1.x: commands: fix logged error not interpolating format qualifiers

- tq/basic_download.go
> Backport #2227 for v2.1.x: tq/basic_download: guard against nil HTTP response

- lfsapi/ssh.go
- lfsapi/ssh_test.go
- test/cmd/lfs-ssh-echo.go
- test/cmd/lfs-ssh-proxy-test.go
- test/test-env.sh
- test/test-ssh.sh
- test/testenv.sh
This fixes an issue where SSH options can be parsed out of `ssh://` urls. For example, the url `ssh://-oProxyCommand=gnome-calculator` will exec the following command:
```sh
$ ssh -p 12345 -oProxyCommand=gnome-calculator git-lfs-authenticate ...
```
SSH will run the command from the `-oProxyCommand` flag, which is not what we want.
This PR fixes it by inserting `--`, which disables SSH options after it.
```sh
$ ssh -p 12345 -- -oProxyCommand=gnome-calculator git-lfs-authenticate ...
```
LFS does support `plink` and `tortoiseplink`, which don't have anything like `--`. So instead, LFS will remove any leading `-`'s from the `user@host` components of the `ssh://` url.
> sanitize ssh options parsed from ssh:// url

- lfsapi/ssh.go
- lfsapi/ssh_test.go
- test/cmd/lfs-ssh-echo.go
- test/cmd/lfs-ssh-proxy-test.go
- test/test-env.sh
- test/test-ssh.sh
- test/testenv.sh
> Backport #2241 for v2.1.x: sanitize ssh options parsed from ssh:// url

- lfsapi/client.go
- lfsapi/client_test.go
> Backport #2235 for v2.1.x: lfsapi: support cross-scheme redirection

- debian/rules
- docker/run_dockers.bsh
- script/packagecloud.rb
This pull request is a manual backporting of the 4 pull requests involved in supporting building/releasing on Debian 9:
- https://github.com/git-lfs/git-lfs/pull/2203 (@ssgelm): fix building on Debian 9
- https://github.com/git-lfs/git-lfs/pull/2205 (@ttaylorr): publish Debian 9 packages
- https://github.com/git-lfs/git-lfs/pull/2211 (@ttaylorr): add Debian 9 to release notes
- https://github.com/git-lfs/git-lfs/pull/2212 (@andyneff): fix broken publishing rules
---
> release: backport Debian 9-related changes

- commands/command_fetch.go
- commands/command_pull.go
- test/test-pull.sh
> Backport #2237 for v2.1.x: Make pull return non-zero error code when some downloads failed

- docs/man/git-lfs.1.ronn
- Add missing trailing periods
- Add quotes around "locked" for consistency
> Minor cleanups in help index

- commands/command_clone.go
- test/test-clone.sh
This pull request closes https://github.com/git-lfs/git-lfs/issues/2249 by adding the shorthand `-v` flag to be the equivelant of `--verbose` when calling `git lfs clone`.
This more closely matches the behavior of the builtin `git-clone(1)`:
> ```
> --verbose, -v
>    Run verbosely. Does not affect the reporting of progress status to the standard error stream.
> ```
While looking through the man pages for `git-clone(1)`, I double checked to make sure that none of the other wrapped clone flags that we provide were missing shorthand, single `-` flags.
Closes https://github.com/git-lfs/git-lfs/issues/2249.
---
> commands/clone: support shorthand --verbose '-v' flag

- commands/command_clone.go
- git/git.go
This pull request updates our wrapped clone command to include new flags added since Git 2.9, namely:
<details>
<summary><code>--reference[-if-able] <repository></code></summary>
<pre>
--reference[-if-able] <repository>
If the reference repository is on the local machine, automatically setup
.git/objects/info/alternates to obtain objects from the reference repository. Using an already
existing repository as an alternate will require fewer objects to be copied from the repository
being cloned, reducing network and local storage costs. When using the --reference-if-able, a
non existing directory is skipped with a warning instead of aborting the clone.
NOTE: see the NOTE for the --shared option, and also the --dissociate option.
</pre>
</details>
<details> …
> commands/clone: add new flags since Git 2.9

- git/rev_list_scanner.go
- git/rev_list_scanner_test.go
- lfs/gitscanner_refs.go
This pull request extracts the internal `lfs.revListShas()` function into a new type, `*git.RevListScanner` capable of scanning revision ranges for objects and commits.
This work is required for the migrate command (proposed in #2146) in order to avoid implementing a topological sorting algorithm in Go that is functionally equivalent to a [`sort_in_topological_order` call](https://github.com/git/git/blob/v2.13.0/commit.c#L646-L758). Instead, we will opt to use the builtin `git-rev-list(1)` given a `--topo-order` flag and a left/right refspect.
As a first step, we extract that type from its original home in `lfs.revListShas()` so that it can be expanded in a follow-up pull request in order to support the use-case above.
---
> git,lfs: extract git.RevListScanner

- git/rev_list_scanner.go
- git/rev_list_scanner_test.go
This pull request expands the `RevListOptions` type to include an `Order` field, and teaches the `RevListScanner` type how to add flags to `git-rev-list(1)` accordingly.
We require a `--topo-order`-sorted list of commits in order to create a parallel DAG efficiently when performing a migrate (see: #2146 for discussion), so this pull request is required for that.
When I first implemented this, I instead added a `TopoOrder bool` field to the `RevListOptions` type, but felt that this approach was too fragile in case we need to add support for other orderings. Git allows for `--date-order`, `--author-date-order`, and `--topo-order` (in addition to its default with none of these flags given), so I added a constant type to represent this and have support for all four. Since the zero-values of …
> git: allow custom `--<t>-order` in RevListScanner

- .travis.yml
- appveyor.yml
This pull request upgrades our CI services to build using Go 1.8.3, which was released today on the golang-announce mailing list [[source]](https://groups.google.com/forum/#!topic/golang-announce/q8Ddz0ZgAQw).
Similar to our discussion in https://github.com/git-lfs/git-lfs/issues/2141, I would like to stay on the latest version of Go to minimize the change between versions if we ever were affected by a security vulnerability and needed to upgrade.
Here's a breakdown of our different CI services and how they're affected:
- CircleCI: uses Homebrew to install Go, so it's always on the latest of what's offered on `homebrew-core`. That repo was updated today in https://github.com/Homebrew/homebrew-core/pull/13905.
- TravisCI: uses the `.travis.yml`, which was updated in this pull request via …
> all: build on Go 1.8.3

- git/rev_list_scanner.go
- git/rev_list_scanner_test.go
This pull request teaches the `*git.RevListScanner` the ability to not traverse the object graph if asking for `CommitsOnly`.
This is needed for the `migrate` command (see: #2146 for discussion), which requires a topologically ordered list of just commits, not objects.
Since the default value of `bool` is `false`, this imposes no behavior changes on existing code.
---
> git/rev_list_scanner: teach CommitsOnly option

- git/odb/object_db.go
This pull requests fixes an issue where no data would be copied to disk when writing loose objects from the `*git.ObjectDatabase` type.
Here's a brief overview of what was going on: In order to create a "full" Git object, you need:
1. The object type
2. The object's encoded contents
3. The length of the encoded contents (zlib inflated)
In order to determine the third item, we write a temporary buffer containing the encoded contents. Once this is done, we then take the length and the object type, write a header, and then rename the object into place in your `.git/objects` directory.
To do this, however, we were using an `*os.File`, since we may encounter large blobs which exceed the available RAM on a computer running `git-lfs-migrate(1)`. The problem is that since `*os.File` implements …
> git/odb: rewind temporary buffer before saving to disk

- git/odb/file_storer.go
This pull request fixes an issue in the `git/odb` package that caused a panic when new objects are written to directories that don't have a prefix that has been created.
This is due to how Git partitions objects in the `.git/objects` directory. For instance:
```
~/g/git-lfs (master) $ tree .git/objects | head
.git/objects
├── 00
│   └── 21dd014660145da7cb00c2477359b82cf98dd3
├── 01
│   ├── 091f55ffa8b31575f351e1ede0549cea86058d
```
For an object with the OID `0021dd014660145da7cb00c2477359b82cf98dd3`, Git first places that in a directory called `00`, and then takes the remaining 38 ASCII-encoded hex SHA1 characters as the filename for that object.
Prior to this pull request, if the `git/odb` package tried to write an object that began with a two character combination that did _not_ yet …
> git/odb: ensure that object directory exists before moving into it

- git/git.go
- git/git_test.go
This pull request implements both `git.UpdateRef` and `git.UpdateRefReason` to perform an execution of `git-update-ref(1)`.
This is required work to update changes out to the ref tips for the migrate command (see discussion: #2146).
---
> git: teach UpdateRef, UpdateRefReason

- git/git.go
This pull request teaches the `git` package how to execute a `git-checkout(1)` command via a new helper, `git.Checkout()`.
Although `git-checkout(1)` accepts a wide range of arguments and flags, this pull request starts with the most essential options for the work required by the `migrate` command (see discussion: #2146).
While working on the migrate command, the issue is that as changes get propagated into the `HEAD` ref, the working copy does not get checked out, which causes the file to show as modified. This will allow the migrate command to force a manual checkout after updating a ref (using `git.UpdateRef`) and will leave the repository in a clean state.
---
> git: teach Checkout()

- tools/cygwin_windows.go
Git LFS commands like `git lfs track` hang forever on MSYS2 setup on Windows because of `git --git-dir` returning cygwin path which `ioutil.ReadFile()` can't handle.
This is related to #865 issue which is fixed by #1820. Although the fix in #1820 does not work under MSYS2 as `uname` there returns `MSYS_NT-10.0` (and the code only checks for `CYGWIN`).
So this fix just adds check for `MSYS` string inside of `tools.isCygwin()`.
> Fix tools.TranslateCygwinPath() on MSYS

- commands/uploader.go
This pull request disables the locks verification check if `lfs.<url>.locksverify` is set to a false-y value, as per discussion in https://github.com/git-lfs/git-lfs/issues/2269.
For servers that send a 401 instead of a 403 for invalid credentials against the locks verification endpoint, this can cause an infinite loop when requesting locks verification. Prior to this pull request, disabling locks verification would _still_ make the request, causing an infinite loop in the credential helper.
Closes: https://github.com/git-lfs/git-lfs/issues/2269.
---
/cc https://github.com/git-lfs/git-lfs/issues/2269
> commands/uploader: don't verify locks if verification is disabled

- git/odb/memory_storer.go
- git/odb/memory_storer_test.go
- git/odb/object_db.go
- git/odb/object_db_test.go
- git/odb/object_reader.go
This pull request teaches the `*git/odb.ObjectDatabase` type to read "missing," or (more accurately) packed objects from the Git object database.
When an object becomes packed by Git (before a push, after a `git-pack-objects(1)`, or `git-gc(1)`) they are no longer accessible inside of `.git/objects/xx/yyyy`. Instead, they are delta compressed and stored inside of `.git/objects/pack/pack-nnn.pack` (and the corresponding `.git/objects/pack/pack-nnn.idx`).
Since the `git/odb` package doesn't currently know how to read packed objects, this pull request teaches it to fallback to the `*git.ObjectScanner` (which internally uses `git-cat-file(1) --batch` to "unpack" the objects before streaming their contents back to `git/odb`.
Here's a quick breakdown of what happened:
- 70818eb: Introduce an …
> git/odb: read packed objects through *git.ObjectScanner

- git/rev_list_scanner.go
- git/rev_list_scanner_test.go
This pull request teaches two minor options to the `*git.RevListScanner`: `WorkingDir` and `Reverse`.
- `WorkingDir`: this option is given to provide a working dir not equal to `os.Getwd()`, in case we're operating on a Git repository that isn't in the current working directory. This isn't the case for `git lfs migrate` usage, but when testing using bare `.git` fixtures, this is required instead of stubbing out `git-rev-list(1)`.
- `Reverse`: this option is one I missed in #2263, and is needed for the `migrate` command (see discussion: #2146). In order to rewrite commits, we must see parents before children when visiting a repository's history in topological ordering. By default `--topo-order` gives us _children_ first, but we want _parents_ first. `--reverse` does that via the `Reverse` …
> git: teach opt.{Reverse,WorkingDir} to RevListScanner

- git/odb/file_storer.go
- git/odb/object_db.go
- git/odb/object_db_test.go
This pull request teaches the `*git/odb.ObjectDatabase()` to return the `Root()` path on disk (fully-qualified) that it is operating in. It depends on 23173cf from https://github.com/git-lfs/git-lfs/pull/2286.
This is required work for testing a new type I'm working on `*git/odb.HistoryRewriter`, which requires that the `*git.RevListOperator` (used by the `*HistoryRewriter` to determine which commits to rewrite) work in a directory outside of `os.Getwd()`. This is a result of using bare repositories as fixture data on disk in a different path than the current working directory.
In pursuit of the `git-lfs-migrate(1)` command (see discussion: #2146).
From the documentation:
> ```go
> // Root returns the filesystem root that this *ObjectDatabase works within, if
> // backed by a fileStorer …
```
> git/odb: teach *ObjectDatabase.Root() to return filesystem root

- git/githistory/rewriter.go
- git/githistory/rewriter_test.go
This pull request improves the path qualification for the `BlobCallbackFn` when using the `*git/githistory.Rewriter` to be `"/"` instead of `""` for the root tree in a repository.
This is done in order to improve the path for the next PR in this series, which includes a `TreeCallbackFn`. Instead of recognizing an empty string `""` as the root tree, it will now be the OS's path separator (`os.PathSeparator`).
---
> git/githistory: make path include absolute root

- git/odb/file_storer.go
- git/odb/memory_storer.go
- git/odb/memory_storer_test.go
This pull request fixes some behavior where objects that already exist would cause the `*MemoryStorer` and `*FileStorer` to `panic()` and return an error, respectively.
Except in the case of SHA1 collisions, these calls should be an effective no-op.
Required work for the `git-lfs-migrate(1)` command (see discussion: #2146), and to unblock the work ongoing in #2300.
---
> git/odb: don't rewrite objects that already exist

- git/githistory/rewriter.go
- git/odb/object_db.go
This pull request fixes two instances where we closed the underlying file descriptor feeding the `*git/odb.Blob` type incorrectly.
1. 1d5ef4c: when decoding a loose object, the `git/odb` package expected (prior to 1d5ef4c) the implementing `Object` type to exhaust the `io.Reader` feeding it, so that it could safely call `Close()`. This is the case in `*git/odb.Tree`'s `*git/odb.Commit`'s, where the `io.Reader` is drained completely in order to decode the object.
In `*git/odb.Blob`'s, however, the reader is _not_ drained completely, as the blob may be too large to fit in memory. Instead, a `*bufio.Reader` is used to buffer the file contents, and the `Close()` is delayed. If the Blob's `Size` is less than 4096 (the amount buffered by default in the `*bufio.Reader`), this problem does not …
> git/{odb,githistory}: close blob appropriately

- git/odb/tree.go
- git/odb/tree_test.go
This pull request fixes a bug when reading loose trees longer than 4096 bytes.
The issue is caused by reading a tree entry whose SHA lies across a multiple of 4096 bytes (the buffer size of `*bufio.Reader`. When reading, we do the following:
```go
var sha [20]byte
if _, err := buf.Read(sha[:]); err != nil {
// ...
}
// ...
```
The issue lies in the fact that `*bufio.Reader.Read()` will make _at most_ one call to the underling `io.Reader.Read()`<sup>[[1](https://golang.org/pkg/bufio/#Reader.Read)]</sup>:
> Read reads data into p. It returns the number of bytes read into p. The bytes are taken from at most one Read on the underlying Reader, hence n may be less than len(p). At EOF, the count will be zero and err will be io.EOF.
If the buffer is exhausted part of the way through reading a …
> git/odb: use io.ReadFull instead of *bufio.Reader.Read

- git/odb/commit.go
- git/odb/commit_test.go
This pull request fixes a bug caused by parsing commits with a message that begins with either `tree` or `parent`.
The issue is that we still allow `tree` or `parent` as the first field to indicate a commit header, so we try and parse the remaining substring as ASCII-encoded hex. In the overwhelming majority of cases, this is possible, and therefore causes a panic.
For instance, the test added in this pull request fails before 7fa88dc:
```
=== RUN   TestCommitDecodingWithMessageKeywordPrefix
--- FAIL: TestCommitDecodingWithMessageKeywordPrefix (0.00s)
Error Trace:    commit_test.go:104
Error:          Received unexpected error "encoding/hex: invalid byte: U+003C '<'"
Error Trace:    commit_test.go:110
Error:          Not equal: "tree <- initial commit" (expected)
!= "" (actual)
```
This …
> git/odb: fix parsing commits with special keyword prefixes

- git/githistory/rewriter.go
- git/githistory/rewriter_test.go
- git/rev_list_scanner.go
- git/rev_list_scanner_test.go
- lfs/gitscanner_refs.go
This pull request makes the signature(s) of `*git.RevListScanner` mirror more closely the behavior described by `git-rev-list(1)`:
> ```
> GIT-REV-LIST(1)                   Git Manual                   GIT-REV-LIST(1)
>
> NAME
>        git-rev-list - Lists commit objects in reverse chronological order
>
> SYNOPSIS
>        git rev-list [ --max-count=<number> ]
>                     # ...
>                     <commit>... [ -- <paths>... ]
> ```
Where instead of including `left` and `right` commitish's (indicating that rev-list will scan between those two boundaries), this pull request changes that behavior to `Include, Exclude []string`. Each entry in each slice represents a reference to include, or exclude, respectively.
In other words, from the documentation:
```go
// NewRevListScanner …
```
> git,lfs: make *git.RevListScanner take Include, Exclude []string

- commands/command_prune.go
- tools/humanize/humanize.go
- tools/humanize/humanize_test.go
- tools/humanize/package.go
This pull request introduces a new package: `github.com/git-lfs/git-lfs/tools/humanize` designed to format and parse byte amounts as human readable text.
This will be used in #2313 in order to parse the `--above=<size>` flag, as well as the output of the command (ref: #2146).
---
> tools: implement and use 'humanize' package

- commands/command_fetch.go
- commands/command_pull.go
the are some strange messages when we fetching objects (not pushing they).
fixed this misunderstanding
> commands: typo fix for fetch errors messages

- errors/types.go
- errors/types_test.go
- tq/transfer_queue.go
git-lfs could fail randomly on "i/o timeout" error. This is especially
annoying with very long running transfers. This change recognises
Timeout or Temporary errors and retries them.
---
Tested by doing git lfs smudge on a file in lfs repository, where `lfs.url=http://localhost:9000` and  `nc -v -l 9000` was listening locally.
Without the fix git-lfs client aborted instantly, with the fix it retried.
> Retry on timeout or temporary errors

- commands/command_migrate.go
- commands/command_migrate_info.go
- docs/man/git-lfs-migrate.1.ronn
- test/test-migrate-fixtures.sh
- test/test-migrate-info.sh
- tools/math.go
- tools/math_test.go
- tools/str_tools.go
- tools/str_tools_test.go
This pull request adds documentation and an implementation for the 'info' subcommand of the `git-lfs-migrate(1)` suite.
The 'info' subcommand is designed to gather statistics regarding the size of data stored in Git per filepath extension. The output of the command looks as follows:
```
~/g/git-lfs (migrate-subcommand-info) $ git-lfs migrate info \
--include-ref=refs/heads/migrate-subcommand-info \
--exclude-ref=refs/heads/master \
--top=3
*.go 2.0 MB
*.sh 325.3 KB
*.md 225.6 KB
``` 
The following arguments are permitted:
- `--include-ref`: a set of references of which commits reachable by those refs are included in the traversal.
- `--exclude-ref`: a set of references of which commits reachable by those refs are excluded in the traversal.
- `--include`: a filepath filter include set
- …
> commands: add git-lfs-migrate(1) 'info' subcommand

- git/odb/blob.go
- git/odb/blob_test.go
This pull request introduces a new `*git/odb.Blob` constructor that returns a blob whose contents is equal to the give `[]byte`.
---
/cc @git-lfs/core  
/ref #2146
> git/odb: introduce 'NewBlobFromBytes'

- commands/command_migrate.go
- commands/command_migrate_info.go
This pull request inverts the argument order for the `*git/odb.ObjectDatabase` argument so that it can be passed into the `migrate()` function.
This is required so that we can add arbitrary blobs to the object database, such that they are valid tree entries (for instance, adding/modifying a tree's `.gitattributes`).
---
/refs #2146
> commands: invert *odb.ObjectDatabase argument to migrate()

- commands/command_migrate.go
- commands/command_migrate_info.go
- docs/man/git-lfs-migrate.1.ronn
- test/test-migrate-info.sh
- tools/humanize/humanize.go
- tools/humanize/humanize_test.go
This pull request teaches the `--unit` flag to the 'info' subcommand of `git-lfs-migrate(1)`.
Previously, the behavior of the command was to find the largest storage unit that could represent the number of bytes counted as a whole number. Now, if instead the `--unit` flag is given, that unit is used to format the bytes with at most one decimal place.
Here's a summary of what happened:
- 06fde60 & 40e833d: implement and use `ParseByteUnit` so that we can parse the string `--unit` given.
- cb5baef & 8d09c7e: implement and use `ForamtBytesUnit` so that we can format storage quantities with arbitrary units.
- d1037fc: use the above two utilities to format the bytes accordingly.
Here's a sample from the manpage:
> ```
> * `--unit=<unit>`
>     Format the number of bytes in each entry as a …
```
> commands: teach --unit to 'info' subcommand of 'git-lfs-migrate(1)'

- git/git.go
This pull request teaches a new function to the `git` package, `AllRefs()` which returns a listing of all references in a repository.
This is required for the `import` subcommand of `git-lfs-migrate(1)` which needs a listing of all references in order to move references from the old graph onto the migrated one. Ideally this could come from `git-rev-list(1)` (which we already run to generate a listing of commits to migrate), but tricking the output to be machine readable is difficult to do without switching to `git-log`, which doesn't have great machine-readable output either.
---
/cc #2146
> git: teach AllRefs()

- git/git.go
This pull request teaches a variant of the `git.UpdateRef()` function that takes a custom working directory, different than `os.Getwd()`.
This is required for the `*git/githistory.Rewriter` tests, which move refs in a directory outside of the working directory.
---
/cc #1497
> git: teach UpdateRefIn()

- commands/command_migrate.go
- git/githistory/log/log.go
- git/githistory/log/log_test.go
- git/githistory/log/percentage_task.go
- git/githistory/log/percentage_task_test.go
- git/githistory/log/task.go
- git/githistory/log/waiting_task.go
- git/githistory/log/waiting_task_test.go
- git/githistory/rewriter.go
- test/test-migrate-info.sh
This pull request introduces a new package, `github.com/git-lfs/git-lfs/git/githistory/log` for Git-style progress based logging, like this:
This pull request is based off the `migrate-subcommand-info` branch, since I wanted to use the `info(1)` subcommand to test out the logger in a real-world setting. Once #2313 is merged, I'll change the base of this pull request to `master`.
The API works as follows: given a `*log.Logger` with a `sink io.Writer`, ask for one of two types of logging tasks:
- `*WaitingTask` (via `(*log.Logger) Waiter()`): a task for which the upper bound of items to process is not known. Logged as `message: ...` and `message: ..., done`. 
- `*PercentageTask` (via `(*log.Logger) Percentage()`): a task for which the upper bound of items is known. Logged as `message:   1% …
> commands: add logging to git-lfs-migrate-info(1)

- git/githistory/log/log.go
- git/githistory/log/log_test.go
- git/githistory/log/percentage_task.go
- git/githistory/log/percentage_task_test.go
- git/githistory/log/task.go
- git/githistory/log/waiting_task.go
- git/githistory/log/waiting_task_test.go
This pull request teaches a new `Task` type to the `github.com/git-lfs/git-lfs/git/githistory/log` package: `DurableTask`.
A `DurableTask` ensures that all log `<-Update()` reads are logged to the `sink io.Writer`, regardless of throttling conditions. This required for multi-line log updates (like output from `git-ref-update(1)`) where all log lines are important.
---
/refs #2146 #2329
> git/githistory/log: teach Durable() to Task

- git/githistory/log/list_task.go
- git/githistory/log/list_task_test.go
- git/githistory/log/log.go
This pull request provides a new `Task` implementation, `ListTask`, which is used to log line-delimited lists of data using the `git/githistory/log.Logger` type.
This is required work for the `import` subcommand of `git-lfs-migrate(1)` which will print out one line for each ref updated by the migrator.
--- 
/refs #2146 #2329 #2334
> git/githistory/log: implement ListTask type

- filepathfilter/filepathfilter.go
- filepathfilter/filepathfilter_test.go
This pull request teaches a new function to the `filepathfilter.Filter` type: `AllowsPattern()`. `AllowsPattern()` has the same semantics as `Allows()`, but also returns the pattern that caused the given filename to be accepted or rejected.
The `git-lfs-migrate(1)` 'import' subcommand needs to modify `.gitattributes` with the pattern(s) that matched a given filename, i.e.: if we cleaned `a.dat` and `*.dat` was given as a pattern, make sure we add `*.dat` to the `.gitattributes`, not `a.dat`.
I'm not totally sold on the name `AllowsPattern()`: @technoweenie do you have ideas here?
---
/refs #2146
> filepathfilter: teach AllowsPattern()

- git/githistory/rewriter.go
- git/odb/object_db_test.go
- git/odb/tree.go
- git/odb/tree_test.go
This pull request removes the `Type git/odb.ObjectType` member field from `*git/odb.TreeEntry` and replaces it with `git/odb.TreeEntry.Type() git/odb.ObjectType`.
This is done because the type is not a top-level property of the `*TreeEntry` type. `Type()` is a property inferred from the value of `Filemode`. Type can be determined by examining the bits underneath `syscall.S_IFMT` by `entry.Filemode & syscall.S_IFMT`.
This is dependent work for the following pull request, which introduces an implementation of `sort.Interface` that sorts `[]*TreeEntry`'s in subtree order. [source](https://github.com/git/git/blob/v2.13.0/fsck.c#L492-L525)
To avoid relying on an optional property, we move `Type` into a function so we can call that function instead.
---
/cc #2146
> git/{githistory,odb}: make Type() a function of *TreeEntry

- git/githistory/rewriter.go
- git/githistory/rewriter_test.go
This pull request teaches the `git/githistory.Rewriter` type to return a copy of the filepath filter it's using, or nil.
This is required by the 'import' subcommand of the `git-lfs-migrate(1)` which needs to do filepath pattern matching in order to determine which entries to add to the repository's `.gitattributes` file. Instead of constructing the filepathfilter twice, we use `Filter()` to return a reference.
---
/refs #2146
> git/githistory: teach Filter() to access filepathfilter used

- tools/ordered_set.go
- tools/ordered_set_test.go
This pull request introduces a new type in the `tools` package: `*tools.OrderedSet`.
An `*OrderedSet` is identical in interface to the `*tools.StringSet`, but maintains insertion order when asked for elements in the set.
This is required by the 'import' subcommand of the `git-lfs-migrate(1)` suite, which builds up a listing of tracked patterns over time and adds them to the root tree's `.gitattributes` entry. `tools.StringSet` does not allow for this behavior, since order is not guaranteed, therefore random diffs may appear throughout history on the `/.gitattributes` file.
---
/refs #2146
> tools: introduce tools.OrderedSet

- commands/command_migrate.go
- commands/command_migrate_info.go
This pull request cleans up and makes more flexible the conventions for calling `migrate()` from inside the `commands` package. Here's what happened:
1. 186d916: invert `*githistory.Rewriter` so that callers can have a handle on the `Rewriter`'s `Filter()` function (see: https://github.com/git-lfs/git-lfs/pull/2347)
2. 0dde5c8: realize that `cmd` is no longer used, remove that.
3. 7f22ed9: pass in `*githistory.RewriteOptions` so that callers can control the `UpdateRefs` property (`false` in the 'info' command, `true` in the 'import' command)
---
/refs #2146
> commands: invert (& clean up) `migrate()` arguments

- git/odb/tree.go
- git/odb/tree_test.go
This pull request provides an implementation of `sort.Interface` that sorts `[]*TreeEntry`'s in subtree order, required to write valid trees to the object database.
Right now, there are no call sites in Git LFS that modify (append/delete/re-order) the set of `Entries` on the `*git/odb.Tree` instance.
However, the 'import' subcommand of the `git-lfs-migrate(1)` suite will conditionally append a `.gitattributes` tree entry into the root tree. In doing so, we may potentially create an out of order tree, which causes Git to behave in undefined ways. (I found this out during some testing today where Git would persistently mark a file as modified even though it wasn't. `git-fsck(1)` gave further details).
The following pull request will introduce an `Append(entries ...*TreeEntry)` method to …
> git/odb: teach SubtreeOrder to sort tree entries

- git/odb/tree.go
- git/odb/tree_test.go
This pull request teaches the `Merge(others ...*TreeEntry)` operation on `*git/odb.Tree`'s.
`Merge`-ing a tree with a set of other `*TreeEntry`'s involves one of two actions for each given `*TreeEntry`:
1. If given entry "e" already exists within the existing `*Tree` with the same name and filemode, replace the old `OID` with the one given by "e".
2. If the given entry "e" does not already exist within the existing `*Tree`, append it to the end of the tree and sort it into subtree order.
I debated between the `O(n*log(n))` `sort.Sort` operation vs. a linear pass to add the new elements in subtree order, and summarized my decision in a comment above the sort operation:
> ```go
> // Call sort afterwords, as a tradeoff between speed and spacial
> // complexity. As a future point of …
```
> git/odb: teach Merge(...*TreeEntry) operation on *Tree's

- commands/command_migrate.go
- git/githistory/fixtures_test.go
- git/githistory/ref_updater.go
- git/githistory/ref_updater_test.go
- git/githistory/rewriter.go
- git/githistory/rewriter_test.go
This pull request introduces a new type and option: `*refUpdater` and `UpdateRefs bool`, respectively.
In normal migrations up to this point ('info', so far) no commits are re-written, therefore no references need to be moved. However, 'import' (and 'export') migration will rewrite commits, and therefore the references in the original graph must be moved to their corresponding locations in the new graph.
The `*refUpdater` performs this transition. Given:
- `Refs []*git.Ref`: A set of references to move (currently all references in the repository, see #2338 for discussion), and
- `CacheFn func(old []byte) ([]byte, bool)`: A function to return the migrated location of a given commit SHA1, or nil if the SHA1 was unmoved.
the `*refUpdater` iterates through all `Refs` given, and updates each …
> git/githistory: introduce `*refUpdater` to update references

- test/test-track-attrs.sh
This pull request skips the `track (--no-modify-attrs)` test on Git versions earlier than 2.1.0, as the cause of failure is currently unknown.
I opened up https://github.com/git-lfs/git-lfs/issues/2357 to track.
---
> test: skip test "track (--no-modify-attrs)" on Git <2.1.0

- commands/command_migrate_info.go
- docs/man/git-lfs-migrate.1.ronn
- test/test-migrate-info.sh
This pull request removes info entries in the `git lfs migrate info` command for entries that have no files above the given (or default) `--above` threshold.
For example, the following output would have been generated before this PR on a file a.txt whose size is 10 bytes.
```
$ git lfs migrate info
*.txt      0 B   0/1 files    0% 
```
Will now show:
```
$ git lfs migrate info
```
Giving `--above=0b` (or `--above=0`, as of #2355) will show the file again.
---
/refs #2146
> commands: show no output for entries with no matching files

- .travis.yml
- circle.yml
- commands/command_clean.go
- commands/command_filter_process.go
- commands/command_migrate.go
- commands/command_migrate_import.go
- docs/man/git-lfs-migrate.1.ronn
- filepathfilter/filepathfilter.go
- filepathfilter/filepathfilter_test.go
- git/githistory/ref_updater.go
- test/test-migrate-fixtures.sh
- test/test-migrate-import.sh
- test/test-track-attrs.sh
This pull request implements the `git-lfs-migrate(1)` 'import' subcommand.
The 'import' subcommand is designed to convert large blobs stored in Git history to LFS pointer files based on the `--include`, `--exclude`, and `--include-ref`, `--exclude-ref` flags. It works by calling the `commands.clean()` function with the blob loaded in memory, and then a) storing that blob's contents in `.git/lfs/objects` and b) writing out an LFS pointer file in its place in the githistory.
Regarding some of the notes from #2146 about when/where to insert .gitattributes changes @technoweenie:
> > When is `.gitattributes` built? I think it'd be cool to slip into the first commit or something.
> 
> Right now I'm adding a `.gitattributes` entry into the first commit that has any paths matching those in the …
> commands: add git-lfs-migrate(1) 'import' subcommand

- commands/command_clone.go
Running `git lfs clone` always passes the `--jobs` option to `git clone`. This won't fly if you have git < 2.9:
```
error: unknown option `jobs'
usage: git clone [<options>] [--] <repo> [<dir>]
```
Fixes #2366 by setting the flag default to -1.
> commands: only pass --jobs to 'git clone' if set

- lfs/pointer_smudge.go
Newer versions of cheggaaa/pb no longer expose FormatBytes as a public function (see https://github.com/cheggaaa/pb/commit/104771963e724f4f3087d03be7ccd1e19b92ab84).  This presents a challenge when submitting git-lfs to debian as debian uses a newer version of some dependencies.  Given that this function was already copied to humanize it makes sense to me to just use that.
> Use FormatBytes from git-lfs/tools/humanize instead of cheggaaa/pb

- config/version.go
- rpm/SPECS/git-lfs.spec
- versioninfo.json
This pull request bumps the version on the `release-2.2` branch to '2.2.1-pre', which will be the next version released from this branch.
To my memory, we haven't done `-pre` version tag bumps on the `release-*` branches before, but I think that this is a good pattern to start, since it will make it easier to distribute builds outside of the release cycle.
If this seems 👎, though, I'm happy to pass on it.
---
> all: bump version to '2.2.1-pre'

- git/odb/file_storer.go
- git/odb/object_db.go
This pull request prevents a [cross-volume link error][1] that can occur when committing objects to the object database when a repository is on a non-default volume. This was pointed out in: #2381.
In order to save an object to the database, we do these things:
1. Write a non-zlib compressed copy of the objects body into a temporary buffer (`*bytes.Buffer` for Trees, Commits, `*os.File` for blobs).
2. Create a new buffer on disk with the object header and length, still uncompressed.
3. Stream the above buffer through a `crypto/sha1` Hash to calculate the SHA1 of the object contents.
4. Compress the above.
5. Link the compressed file into the `.git/objects` directory of the repository.
The issue occurs in step 5. If we created a file on a different volume than the on the repository is …
> git/odb: prevent cross-volume link error when saving objects

- config/version.go
- rpm/SPECS/git-lfs.spec
- versioninfo.json
This pull request bumps the version on master to `2.3.0-pre`, since the next version released from master will be 2.3.0.
---
> all: bump version to '2.3.0-pre'

- commands/command_migrate_import.go
- git/git.go
- test/test-migrate-fixtures.sh
- test/test-migrate-import.sh
This pull request skips the final `git-checkout(1)` that we do on repositories after migrating them via `git-lfs-migrate(1) import`.
This was pointed out in https://github.com/git-lfs/git-lfs/issues/2380#issuecomment-313148926.
Before this PR:
```
~/D/foo.git (master) $ git rev-parse --is-bare-repository
true
~/D/foo.git (master) $ git lfs migrate import
migrate: Sorting commits: ..., done
migrate: Rewriting commits: 100% (1/1), done
master        85d2a9aa2e1fa73548092096f563688e6cd3f2c6 -> a65ddcf4418a78b9e414ead8a5c86c4aebfbb0e1
migrate: Updating refs: ..., done
Error running git [checkout --force]: 'fatal: This operation must be run in a work tree' 'exit status 128'
```
Here's a quick look at how things went down:
1. 2a2a76c: teach `git.IsBare()` to determine if a repository is bare …
> migrate: don't checkout HEAD on bare repositories

- git/githistory/rewriter.go
- test/test-migrate-info.sh
This pull request fixes a hang that occurs when the set of commits to migrate is empty, as pointed out in #2380.
In `*git/odb.Rewriter.commitsToMigrate()`, we store a set of `[][]byte`, where each `[]byte` entry is a commit's SHA1 which should be migrated. Our logic looks something like this:
```go
func (r *Rewriter) commitsToMigrate(opt *RewriteOptions) ([][]byte, error) {
waiter := r.l.Waiter("migrate: Sorting commits")
scanner, err := git.NewRevListScanner(...)
var commits [][]byte
for scanner.Scan() {
if len(commits) == 0 {
waiter.Complete()
}
commits = append(commits, scanner.OID())
}
return commits
}
``` 
This has the behavior of flashing a `"migrate: Sorting commits"` message to the terminal, appending `"..., done"` when the first result was received from `git-rev-list(1)`. If, …
> git/githistory: fix hanging on empty set of commits

- git/odb/object_db.go
This pull request changes an `*os.File.Close()` call into an `os.Remove()` call to avoid keeping many objects in `.git/lfs/tmp` after migrations (as pointed out in: https://github.com/git-lfs/git-lfs/issues/2380#issuecomment-313134306).
EDIT: I deliberately skipped checking the return value from `os.Remove()`, since the presence of files in the `.git/lfs/tmp` directory doesn't affect the migration, so it's non-fatal if they can't be removed.
---
/cc https://github.com/git-lfs/git-lfs/issues/2380#issuecomment-313134306
> git/odb: remove temporary files after migration

- commands/command_status.go
- test/test-status.sh
> git lfs status --json only includes lfs files

- lfs/pointer_smudge.go
> Backport #2377 for v2.2.x: Use FormatBytes from git-lfs/tools/humanize instead of cheggaaa/pb

- git/odb/file_storer.go
- git/odb/object_db.go
> Backport #2382 for v2.2.x: git/odb: prevent cross-volume link error when saving objects

- git/odb/object_db.go
> Backport #2388 for v2.2.x: git/odb: remove temporary files after migration

- commands/command_migrate_import.go
- git/git.go
- test/test-migrate-fixtures.sh
- test/test-migrate-import.sh
> Backport #2389 for v2.2.x: migrate: don't checkout HEAD on bare repositories

- lfs/hook.go
- lfs/setup.go
This pull request adds tracing output to the `git lfs install`, `git lfs uninstall`, and `git lfs upgrade` commands when installing `.git/hooks`, similar to that suggested in: https://github.com/git-lfs/git-lfs/issues/2363#issuecomment-311985990 & https://github.com/git-lfs/git-lfs/issues/2363#issuecomment-311994628.
This should make it easier to diagnose situations where hooks aren't being installed correctly, as we'll now have information about:
1. Which files are being `stat(1)`-ed
2. Which directories are being created
3. Which files are being written
4. Whether files that do exist are marked as upgrade-able.
---
/cc https://github.com/git-lfs/git-lfs/issues/2363
> lfs: trace hook install, uninstall, upgrade

- lfs/hook.go
> Backport #2393 for v2.2.x: lfs: trace hook install, uninstall, upgrade

- config/version.go
- rpm/SPECS/git-lfs.spec
- versioninfo.json
This pull request bumps the version tag to `2.2.2-pre` as in #2385. It is intended to be merged after #2402 in anticipation of a potential v2.2.2 release.
---
> all: bump to 'v2.2.2-pre'

- commands/command_install.go
- docs/man/git-lfs-install.1.ronn
This pull request follows up on a comment left by @technoweenie<sup>[[1][1]]</sup>:
> Also, `git lfs install --manual` doesn't work. I think it just needs [this `update` flag](https://github.com/git-lfs/git-lfs/blob/2fe41e90149a8d02c8d33e4b25f2a314bda1e346/commands/command_update.go#L62).
This teaches the `--manual` mode to `git lfs install`, by hijacking flags owned by the `git-lfs-update(1)` command (since `git-lfs-install(1)` runs `updateCommand()` to implement itself).
I've added a note that this should be addressed in the future, but I think that this is ship-able today.
---
[1]: https://github.com/git-lfs/git-lfs/pull/2392#issuecomment-314495588
> commands/install: teach --manual to `git-lfs-install(1)`

- .gitignore
See subject.  There are a few files that are sometimes created when building debs (I think relating to newer versions of debian tools?)
> Update gitignore to add some temp files that get created when building debs

- git/odb/pack/errors.go
- git/odb/pack/errors_test.go
- git/odb/pack/index.go
- git/odb/pack/index_decode.go
- git/odb/pack/index_decode_test.go
- git/odb/pack/index_entry.go
- git/odb/pack/index_test.go
- git/odb/pack/index_version.go
- git/odb/pack/index_version_test.go
This pull request introduces the `*Index` type, and creates a new package `git/odb/pack` to hold it.
The goal of this new package is twofold:
1. Parse index files to find packfile offsets.
2. Parse and assemble objects within packfiles.
This pull request is the first in a series of four aimed at accomplishing the first goal. Contained in this pull request is the scaffolding necessary to get us going for parsing actual index files. That means:
- An `*Index` type, which will eventually get a `Entry([]byte) uint64, error)` method to resolve object names to their offsets in a packfile.
- An `IndexVersion` type, which will learn how to parse index entries in later pull requests in this series.
- A `DecodeIndex()` function, which will learn how to use the above `IndexVersion` instances to parse …
> git/odb/pack: introduce '*Index' type

- git/odb/pack/index_decode.go
- git/odb/pack/index_decode_test.go
- git/odb/pack/index_v1.go
- git/odb/pack/index_v1_test.go
- git/odb/pack/index_version.go
- git/odb/pack/index_version_test.go
This pull request implements object searching for v1 index files, and is the second in the series started by #2420.
The main goal of this pull request is to implement a function that the `IndexVersion.Search()` function can call into, as:
```go
func (i *IndexVersion) Search(idx *Index, name []byte, at uint64) (*IndexEntry, int, error) {
switch i {
case V1:
return v1IndexSearch(idx, name, at)
}
panic(...)
}
```
This implements the search functionality (i.e., find an object, or return a comparison value of where to search next) for V1 pack files.
I estimate that it's unlikely LFS will parse many v1 packfiles during regular usage. Git stopped writing v1 packfiles near https://github.com/git/git/commit/c553ca25bd60dc9fd50b8bc7bd329601b81cee66, which was first released in the v1.5.2 series, …
> git/odb/pack: implement v1 object searching

- config/config.go
- git/odb/pack/index_decode.go
- git/odb/pack/index_decode_test.go
- git/odb/pack/index_v2.go
- git/odb/pack/index_v2_test.go
- git/odb/pack/index_version.go
- git/odb/pack/index_version_test.go
This pull request implements object searching for v1 index files, and is the third in the series started by #2420.
It implements the v2 index lookup, similar to that implemented in https://github.com/git-lfs/git-lfs/pull/2421.
The v2 index format varies slightly from v1. Instead of placing the object offset and object name next to each other, they are split into separate "tables". v2 also knows how to store a cyclic redundancy check for each object, as well how to encode 8-byte unsigned offsets.
More specifically, the structure is as follows:
1. A magic 4-byte header
2. A 4-byte version tag (network order)
3. 256 4-byte network order unsigned integers comprising the L1 fanout table.
4. The 20-byte object names, in order.
5. 4-byte entries for each object giving the CRC in network byte …
> git/odb/pack: implement v2 object searching

- git/odb/pack/bounds.go
- git/odb/pack/bounds_test.go
- git/odb/pack/index.go
- git/odb/pack/index_test.go
This pull request uses https://github.com/git-lfs/git-lfs/pull/2421 & https://github.com/git-lfs/git-lfs/pull/2422 to implement a [binary search][1] and entry parse operation over V1 and V2 index files. This is used to determine a given object's offset in the corresponding packfile.
In https://github.com/git-lfs/git-lfs/commit/b761e15ee4eac7255721f88a21d46ef80f9fcab4, we implement a `*bounds` type, which stores a `left` and `right` index used for the binary search. This is done in order to implement the `Equal()` method on `*bounds` in order to detect infinite loops, as:
```go
var last *bounds
for bounds.Left() < bounds.Right() {
if last.Equal(bounds) {
// If the bounds are unchanged, that means either that the object does not
// exist in the packfile, or the fanout table is corrupt.
// …
```
> git/odb/pack: implement Index.Entry() to find object offsets

- git/odb/pack/index.go
- git/odb/pack/index_test.go
This pull request introduces a new API to the `git/odb/pack` package: `pack.IsNotFound(err)`.
I took this idea from the `os` package in the standard library, which returns errors from `os.Stat()` that satisfy `os.IsNotExist()`<sup>[[1](https://golang.org/pkg/os/#IsNotExist)]</sup>:
> IsNotExist returns a boolean indicating whether the error is known to report that a file or directory does not exist.
>
> It is satisfied by ErrNotExist as well as some syscall errors.
This pull request is designed to make calling `Entry()` more ergonomic. Previously, calls from another package would look like this:
```go
var idx *pack.Index
entry, err := idx.Entry([]byte{...})
if err != nil {
return err
}
if entry == nil {
return nil
}
// ...
```
Whereas now it could look like:
```go
var idx *pack.Index …
```
> git/odb/pack: use 'ErrNotFound' when index entries are missing

- git/odb/pack/index.go
- git/odb/pack/index_decode.go
- git/odb/pack/index_decode_test.go
- git/odb/pack/index_test.go
- git/odb/pack/index_v1.go
- git/odb/pack/index_v1_test.go
- git/odb/pack/index_v2.go
- git/odb/pack/index_v2_test.go
- git/odb/pack/index_version.go
This pull request applies a few cosmetic changes to the `git/odb/pack` package introduced in the last series of PRs.
Here's a quick breakdown:
- bdc9ff0: rename `f io.ReaderAt` to `r io.ReaderAt` in the `*Index` type. `f` was originally chosen because it ordinarily represents an `mmap(2)`'d file, but it can be more generally an `io.ReaderAt`.
- edd354e: un-export index offset-related constants, by prepending them with `index<t>`.
- 28ae318: fix a few places that I imported `errors` from the standard library instead of our preferred `github.com/git-lfs/git-lfs/errors` package.
---
/cc #2415
> git/odb/pack: 💅 

- git/odb/pack/index.go
This pull request addresses a potential integer overflow when performing the binary search used to find objects in pack index files. When the sum of the two boundaries is large, it can overflow the maximum size of type `int64`, causing undefined behavior.
As @peff points out in https://github.com/git-lfs/git-lfs/pull/2423#pullrequestreview-52074137:
> [...] this is subject to overflow when the size of the bounds approaches the capacity of your left/right integer types.
He suggests:
> One overflow-safe way is `bounds.Left() + (bounds.Right() - bounds.Left()) / 2`.
Since the `(bounds.Right() - bounds.Left())` sub-expression is evaluated first, that will never overflow, since they are both `int64`s.
EDIT: this was tested in the same manner as described in …
> git/odb/pack: use overflow safe midpoint calculation

- script/packagecloud.rb
This pull-request adds fedora/26 to the list of targets for Packagecloud, which will make all future builds available on the latest release of Fedora.
> script/packagecloud: release LFS on fedora/26

- git/githistory/log/percentage_task.go
- git/githistory/log/percentage_task_test.go
This pull request fixes a bug pointed out in #2450, via https://github.com/git-lfs/git-lfs/issues/2450#issuecomment-319116502:
> ```
> ~/D/harfbuzz (master) $ git lfs migrate info
> migrate: Sorting commits: ..., done
> migrate: Rewriting commits: NaN% (0/0), done
> ```
When there are zero commits to migrate, the migrator should show that it is 100% of the way done, not `NaN%`.
Since we guarantee that the `*PercentageTask` cannot be overcounted in de896f2, we guarentee that 100% is a correct value for all valid calls to the `Count()` method in 78195ec.
---
/cc #2450
> git/githistory/log: prevent 'NaN' showing up in *PercentageTask

- git/object_scanner.go
- git/odb/object_db_test.go
This pull request fixes a failing test pointed out in https://github.com/git-lfs/git-lfs/issues/2456:
> ```
> --- FAIL: TestClosingAnObjectDatabaseMoreThanOnce (0.01s)
>         Error Trace:    object_db_test.go:206
> 	Error:		Expected nil, but got: Error in git cat-file --batch: exit status 128 fatal: Not a git repository (or any of the parent directories): .git
>
> FAIL
> FAIL	github.com/git-lfs/git-lfs/git/odb	0.056s
> ```
This issue occurs in the `TestClosingAnObjectDatabaseMoreThanOnce` test, which asserts that closing an `*ObjectDatabase` twice fails when mounted in a directory `/tmp`. Since `/tmp` doesn't contain a Git repository, the first call to `Close()` calls close on the `*ObjectScanner` and returns an error caused by a non-zero exit code when killing `git-cat-file(1) …
> git/odb: fix closing object database test

- commands/command_migrate.go
- docs/man/git-lfs-migrate.1.ronn
- test/test-migrate-info.sh
- tools/humanize/humanize.go
- tools/humanize/humanize_test.go
This pull request sets the default value of `--above` in `git lfs migrate info` to be empty, which in fact means that it will be set to 0b.
As I recall, the reason we added this was to give a better sense of which files were taking up the most space in a repository, if, for instance, not all files of a given extension are uniformly large/small.
In practice, I've found that this can be potentially confusing to first-time users of the command. By setting the default to empty, we encourage a flow of:
1. Run `git lfs migrate info`, which has reasonable defaults.
2. See that a given extension(s) is/are taking up lots of space.
3. Drill down into `git lfs migrate info --include="*.ext" --above="3mb"`.
---
> commands: remove --above=1mb default from 'git lfs migrate info'

- commands/command_filter_process.go
- commands/command_smudge.go
- docs/man/git-lfs-smudge.1.ronn
- lfs/pointer.go
- lfs/pointer_smudge.go
This pull request teaches the `git lfs {smudge,filter-process}` commands to warn when smudging blobs larger than 4 GB on Windows.
From https://github.com/git-lfs/git-lfs/issues/2434#issuecomment-317582466:
> [...] I ran this by a Git core dev, and he mentioned that Git on Windows does not support files over 4GB. Unfortunately, this is not something we can fix in LFS. The best we can do now add a warning when large objects are added.
This pull request adds that warning.
Here's a quick breakdown of how things happened:
1. 3a080f9: teach `smudge()` (et. al.) to return `(int64, error)` as `io.Copy` does, to indicate the number of bytes smudged by a call to that function.
2. f6beec6: use the return value from that function to determine and potentially warn about files larger than 4gb being …
> commands: teach smudge, process-filter to warn about Windows size bug

- test/test-malformed-pointers.sh
This pull request adds additional assertions to the "empty pointers" test in test/test-malformed-pointers.sh file, following https://github.com/git-lfs/git-lfs/issues/2447 and https://github.com/git-lfs/git-lfs/issues/2449.
By checking the length of `git cat-file -p :empty.dat`, we ensure that an empty file gets cleaned as an empty pointer.
---
/cc @mathstuf
> test: ensure that empty pointers are empty

- script/build.go
This pull request teaches `script/build.go` (accessible via `script/boostrap`) how to pass `-ldflags` and `gcflags` to the Go compiler, if they are given.
This is useful for debugging the `git-lfs` binary, where DWARF tables should be included and compiler optimizations and inlining should be disabled. I originally implemented this as:
```diff
diff --git a/script/build.go b/script/build.go
index fba6292a..f42cad59 100644
--- a/script/build.go
+++ b/script/build.go
@@ -23,6 +23,7 @@ var (
BuildArch  = flag.String("arch", "", "Arch to target: 386, amd64")
BuildAll   = flag.Bool("all", false, "Builds all architectures")
BuildDwarf = flag.Bool("dwarf", false, "Includes DWARF tables in build artifacts")
+	BuildDebug = flag.Bool("debug", false, "Prepares a git-lfs binary useful for debugging") …
```
> script/build: pass -{ld,gc}flags to compiler, if given

- README.md
- docs/README.md
- docs/custom-transfers.md
- docs/man/git-lfs-config.5.ronn
- test/README.md
- test/cmd/lfstest-standalonecustomadapter.go
- test/test-custom-transfers.sh
- test/testhelpers.sh
- tq/custom.go
- tq/manifest.go
- tq/transfer_queue.go
Some custom transfer agents figure out everything by themselves and don't need
any authentication or transfer details from the API server.
Added the `lfs.standalonetransferagent` config option for specifying which
custom agent should be used directly.
> Allow using custom transfer agents directly

- commands/command_track.go
- test/test-track.sh
This pull request fixes a bug pointed out in https://github.com/git-lfs/git-lfs/issues/2452, where `git lfs track` cannot detect paths already tracked in a repository's `.gitattributes` file(s) when the current working directory is symlinked.
The issue arrises when we try and compare the attr path in `.gitattributes`, with the given argument(s). To do this, we first:
1. Relativize the result of calling `os.Getwd()` against the Git repository's root path. This will give us `/dir` for a directory `/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/dir` and a repository root of `/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs`.
2. Compare, for all arguments, all known tracked patterns in any `.gitattributes` file the fully qualified path in the file, with the relativized filepath given as …
> commands/track: resolve symlinks before comparing attr paths

- commands/command_smudge.go
- lfs/pointer_smudge.go
- progress/logger.go
- tq/transfer_queue.go
This pull request fixes a two bugs that we've had since v2.0.0 which broke `$GIT_LFS_PROGRESS` for clean/smudge operations.
The first bug affects smudging files. Since the early days, we've used the `progress.CopyCallback` type to instruct the `*progress.progressLogger` type to log updates to a file given by `$GIT_LFS_PROGRESS`. [[source][1]]. When we introduced the `tq` subpackage, we followed up with https://github.com/git-lfs/git-lfs/pull/1775, which doesn't pass the given `progress.CopyCallback` to the `*tq.TransferQueue`.
To address this, we: 
1. e031ee6: teach a new option instance that can be given to the `tq` constructor for passing `progress.CopyCallback`s around.
2. 92fdd06: pass the given `progress.CopyCallback` into the `tq`, ensuring that updates are sent to …
> progress: fix writing updates to $GIT_LFS_PROGRESS

- commands/command_unlock.go
This pull request teaches the `git lfs unlock` command to appropriately respond to errs when calling `git.IsFileModified()`.
In https://github.com/git/git/commit/b9a7d55, Git causes `git.IsFileModified()` to return an error when asked for the status of files that do not exist. Since this is correct behavior on Git's part, teach `unlockAbortIfFileModified` to ignore errors when the file does not exist and `--force` is given.
---
/cc #2470 #2466
> commands: teach 'unlock' to ignore status errs in appropriate conditions

- .travis.yml
- circle.yml
This pull request teaches CircleCI and Travis how to run CI with the version of Git present at the tip of branch 'next'.
This is useful for adding the 'delay' capability to `git lfs filter-process` (see: https://github.com/git-lfs/git-lfs/issues/2466), since the 'delay' capability is not yet in master, or a released version of Git. This will give us a chance to test the 'delay' functionality out in CI before it's released in Git.
Once Git releases a version that contains https://github.com/git/git/commit/2841e8f81cb2820024804b9341577be1d0ce1240, we can revert this pull request.
This is required work for: https://github.com/git-lfs/git-lfs/issues/2466.
---
/cc https://github.com/git-lfs/git-lfs/issues/2466
> ci: run builds on 'next' branch of git.git

- commands/command_fetch.go
- commands/command_prune.go
- commands/command_pull.go
- tq/transfer_queue.go
This pull request changes the API of package `tq` as:
```diff
diff --git a/tq/transfer_queue.go b/tq/transfer_queue.go
index 67f4e9a7..2776e83f 100644
--- a/tq/transfer_queue.go
+++ b/tq/transfer_queue.go
@@ -640,3 +640,3 @@ func (q *TransferQueue) Wait() {
// as it completes. The channel will be closed when the queue finishes processing.
-func (q *TransferQueue) Watch() chan string {
+func (q *TransferQueue) Watch() chan *tq.Transfer {
c := make(chan string, q.batchSize)
```
This is useful for supporting the 'delay' capability in the `git lfs filter-process` command. Previously, the `Watch()` channel returned an OID per completed object transfer, which we would then have to map back to a transfer name to determine which blobs were available when Git issued the `list_available_blobs` …
> tq: teach Watch() to return <-chan *tq.Transfer

- commands/command_filter_process.go
- git/filter_process_scanner.go
- git/filter_process_scanner_test.go
This pull request teaches the NegotiateCapabilities() method to return a string slice of capabilities supported by the `git-filter-client`.
Previously, we relied on an assumption that the list of required and supported capabilities negotiated between the `git-filter-client` and `git-filter-server` were constant (specifically: `capability=clean` and `capability=smudge`). Since `git` now supports the 'delay' capability, we need to be able to search through the list of capabilities supported by the `git-filter-client` to determine whether or not it is legal for `git lfs filter-process` to return a delayed checkout entry.
This is required work for: https://github.com/git-lfs/git-lfs/issues/2466.
---
/cc https://github.com/git-lfs/git-lfs/issues/2466
> commands,git: teach NegotiateCapabilities() to to return 'supcaps'

- git/filter_process_scanner.go
- git/filter_process_scanner_test.go
This pull request exposes the `*pktline.WriteList()` method as a public API through the `*git.FilterProcessScanner` type.
In implementing support for the 'delay' capability (see: https://github.com/git-lfs/git-lfs/issues/2466), I discover that we need a way to write a list of packets to the `git-filter-client` when asked for a list of available blobs, as seen below:
```go
switch req.Header["command"] {
// ...
case "list_available_blobs":
s.WriteList(pathnames(available))
}
```
This pull request exposes and tests the `(*git.FilterProcessScanner).WriteList()` method to the public so it can be used in that manner.
This is required work for: https://github.com/git-lfs/git-lfs/issues/2466.
---
/cc https://github.com/git-lfs/git-lfs/issues/2466
> git: teach WriteList() to write list packets

- git/pkt_line_writer.go
- git/pkt_line_writer_test.go
This pull request teaches the `*git/PktlineWriter`'s `Flush()` function to respond to a `nil` receiver.
This is required work for adding the 'delay' capability into LFS, as is described in https://github.com/git-lfs/git-lfs/issues/2466. When delaying a file during checkout, no data is written to the pkt-line stream ([source](https://github.com/git/git/blob/487fe1ffcd3b3a38477b7e564f235bb7d1b89ecc/Documentation/gitattributes.txt#L524-L538)), and therefore the `*git.PktlineWriter` is not initialized during that scanner cycle.
Instead of applying:
```diff
diff --git a/commands/command_filter_process.go b/commands/command_filter_process.go
index a622aaad..bb745d3d 100644
--- a/commands/command_filter_process.go
+++ b/commands/command_filter_process.go
@@ -77,6 +77,11 @@ func filterCommand(cmd …
```
> git: teach *PktlineWriter.Flush() to respond to nil receiver

- tq/transfer_queue.go
This pull request teaches `tq.(*TransferQueue).Add()` to accept new items into the `q.incoming` queue of items while a batch is processing.
This is done to improve the performance of the 'delay' filter capability (see: #2466 for more). Prior to this pull request, a delayed checkout was performed like:
1. Git and LFS handshake and negotiate supported capabilities. 
2. Git writes 100 items to LFS before LFS blocks while processing the items in the first batch.
3. If there are more items in the checkout, see step 2.
4. Checkout complete.
This means that we are doing nothing for however long it takes for Git to tell LFS about an entry in the checkout while a batch is processing. 
Instead, accept new items while a batch is processing and save the time that it takes for Git to tell LFS about …
> tq: make Add() accept new items during batch processing

- filepathfilter/filepathfilter.go
- filepathfilter/filepathfilter_test.go
- git/githistory/rewriter.go
- git/githistory/rewriter_test.go
- test/test-migrate-fixtures.sh
- test/test-migrate-import.sh
- test/testenv.sh
This pull request fixes a bug pointed out by @jlbaxter in https://github.com/git-lfs/git-lfs/issues/2482#issuecomment-320790610:
> ```
> $ git lfs migrate import --include="Pods/GoogleMaps/Frameworks/GoogleMaps.framework/googlemaps"
> migrate: Sorting commits: ..., done
> migrate: Rewriting commits: 100% (14/14), done
> 
> $ git push
> # ...
> remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
> remote: error: Trace: b86b8906dcc9cea93584324a9d38247e
> remote: error: See http://git.io/iEPt8g for more information.
> remote: error: File Pods/GoogleMaps/Frameworks/GoogleMaps.framework/googlemaps is 123.08 MB; this exceeds GitHub's file size limit of 100.00 MB
> ```
When the `*git/githistory.HistoryRewriter` traverses through …
> migrate: allow traversal into subtrees when a path prefix is present

- lfs/pointer_clean.go
- test/test-clean.sh
This pull request fixes a bug in `git-lfs-clean(1)` that was pointed out by @mohseenrm in https://github.com/git-lfs/git-lfs/issues/2487: 
> Issue: `git lfs clean` produces incorrect output for files over 1024 bytes
I introduced this bug in https://github.com/git-lfs/git-lfs/commit/482eba2176a39bfaa44f812af78b10e68015670d, wherein an optimization is introduced to combine readers when necessary to avoid blocking on `read()s` with no data when attached as a `process` filter.
482eba2176a39bfaa44f812af78b10e68015670d is implemented by passing a `fileSize` parameter, which is used to determine if all of the file has been read, or if there is more data waiting. When `git lfs clean` is invoked over `stdin`, it assumes the filesize is -1, which then fails the following check: …
> lfs: clean contents larger than 1024 bytes over stdin

- git/githistory/log/list_task.go
- git/githistory/log/list_task_test.go
- git/githistory/log/log.go
- git/githistory/log/log_test.go
- git/githistory/log/percentage_task.go
- git/githistory/log/percentage_task_test.go
- git/githistory/log/task.go
- git/githistory/log/waiting_task.go
- git/githistory/log/waiting_task_test.go
This pull request fixes #2360 by teaching `*git/githistory/log.Task` to send a message and a time.Time in a single update.
This fixes a race condition that is fairly prevalent on CI. The race occurs when CPU cycles are missed in this test code:
https://github.com/git-lfs/git-lfs/blob/d7c2c79ca6ee04a85ee87fdc32d8d3de32ed2389/git/githistory/log/log_test.go#L105-L112
Causing a greater duration than was requested to elapse. This has the downstream effect of making the logger think that enough time has passed in order to not throttle writes to the `io.Writer` sink, thus indicating to the test that the throttling mechanism is broken, which ultimately failing the test.
Instead of checking the wall clock at channel read time, we share the time as it was when the message was created, which allows …
> git/githistory/log: use *Update to share message origin time

- config/git_fetcher.go
- docs/man/git-lfs-config.5.ronn
- test/test-config.sh
This pull request addresses https://github.com/git-lfs/git-lfs/issues/2490 by adding a warning to all LFS commands when an unsafe configuration is present in a repository's .lfsconfig:
> It might be useful to:
> 
> * print a warning when a setting is ignored, and
> * update [`docs/man/git-lfs-config.5.ronn`](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn) to specify what "safe keys" can be used in `.lfsconfig`.
- 038e4a3: add a warning when unsafe keys are detected in the `.lfsconfig`
- 8970e6e: create a section in `git-lfs-config(5).ronn` containing a list of 'safe' keys.
Closes: #2490.
---
/cc @aleb
> config: warn on unsafe keys in '.lfsconfig'

- locking/locks.go
- test/test-lock.sh
- test/testhelpers.sh
This pull request fixes a bug pointed out by @jonico in https://github.com/git-lfs/git-lfs/issues/2492:
> * cd into a directory of a Git repository with a lockable file already tracked by lfs
> * call `git lfs lock` on that file, referring to it with its file name (no path) only
> * git lfs will report that it could not lock because it could not find the file
This is due to the fact that we attempt to set the write flag on a repository-relative path, which is only relative to your current working directory if you are in the root of your repository. For instance, if you lock a file `b.dat` in `sub`, in repository `/usr/local/src/repo`, the absolute lock path is `/usr/local/src/repo/sub/b.dat`, and the repository-absolute path is `sub/b.dat`.
We pass the later into the …
> locks: set write flag on absolute path, not relative

- docs/man/git-lfs-config.5.ronn
- lfsapi/client.go
- tq/manifest.go
This pull request increases the default number of `lfs.concurrenttransfers` to 8.
---
/cc #2466
> tq: increase default lfs.concurrenttransfers to 8

- docs/man/git-lfs-config.5.ronn
- lfsapi/lfsapi.go
This pull request enables the credential caching introduced in #2080 by default, as was noted (and forgotten about) in the original manpages.
---
> lfsapi: enable credential caching by default

- commands/command_smudge.go
This pull request teaches the `git-lfs-smudge(1)` and `git-lfs-filter-process(1)` commands to display the 4gb object warning on all platforms, not just `runtime.GOOS == "windows"`.
In situations where multiple collaborators are working on a repository among different operating systems, it is useful for a contributor running macOS to know that he/she/they can potentially cause an issue for another collaborator running Windows when they commit a file larger than 4gb. 
---
/cc https://github.com/git-lfs/git-lfs/pull/2459
> commands: make 4gb smudge warning show on all platforms

- test/test-post-checkout.sh
- test/test-post-commit.sh
- test/test-post-merge.sh
- test/test-track.sh
- test/testhelpers.sh
This pull request fixes a minor typo I noticed in https://github.com/git-lfs/git-lfs/pull/2514.
---
> test: Fix '{assert,refute}_file_writable' typo in testhelpers

- .travis.yml
- circle.yml
This pull request disables running our integration tests on the 'next' branch of Git.
This change was originally introduced in order to test @larsxschneider's 'delay' patch in #2511, but that has since been merged into the master branch of Git, and is already covered under an existing test runner.
To save time on CI and avoid redundancy, let's remove the extraneous branch.
---
/cc #2466
> ci: disable integration tests on 'next' branch of git

- commands/command_filter_process.go
- git/filter_process_scanner.go
- git/filter_process_status.go
This pull request makes the argument to `git.(*FilterProcessScanner)` a sentinel constant type instead of a string.
This change was promoted by https://github.com/git-lfs/git-lfs/pull/2511#discussion_r135134618, wherein @larsxschneider suggests that we should implement the `delayedStatusFromErr` by calling `statusFromErr`, and then promoting the "success" return value to "delayed".
I think this is a great idea, since it unifies the protocol-related parts of this code. However, it also tightly couples these two functions together: if `success` changes in the protocol, we have to update it not only in the `statusFromErr` function, but in the `delayedStatusFromErr` function as well.
To avoid this problem, let's introduce a sentinel type that transparently holds the protocol encoding by …
> git: make filter status a sentinel

- commands/pull.go
- git/git.go
The gitIndexer starts a new `git update-index` process when the first
file is given to it. A reference to this process is stored in the `cmd`
variable of the gitIndexer struct. This variable was always `nil` after
the refactoring in ae4d2611 ("move `git update-index` invocation to git
package", 2017-08-02). Consequently, a new `git update-index` process
was invoked for every file.
Fix this by refactoring the `git update-index` invocation, again. This
time we return the subprocess pointer. This is necessary because we
want to call `Wait()` on the process when the gitIndexer is closed.
---
I noticed the bug in #2439 and realized that I introduced it with my recent refactoring. Sorry!
Has anyone a good idea how to check the number of invoked `git update-index` processes in a test case?
> fix multiple `git update-index` invocations

- tools/time_tools.go
This pull request fixes a bug that @larsxschneider noticed in https://github.com/git-lfs/git-lfs/pull/2511#issuecomment-323599680 (and that @technoweenie explained in https://github.com/git-lfs/git-lfs/pull/2511#issuecomment-323601319):
> As for the SSH thing, my hunch is that the expiration timeout is not being respected. Is this happening at around the 10 minute mark?
> 
> [...]
> 
> - Does the Batch API try to refresh the Authorization header after it expires? I thought it recognizes that and automatically retries. Maybe there's a race condition, and it should refresh the token if expires_in is < 5 or something.
> - Does the SSH cred cacher respect the expires_in? It should be falling back to a real ssh call after expires_in seconds have passed.
I incorrectly noted that the behavior …
> tools: compare expiration to "time.Now" instead of "from"

- lfs/lfs.go
The constant was introduced in dca7f73 ("really basic pre-commit hook
that rejects commits with files > 5MB", 2013-09-23) and is not used
anymore. Cleanup the code and remove it.
> lfs: remove unused LargeSizeThreshold constant

- commands/command_clone.go
- test/test-clone-deprecated.sh
This pull request marks the `git-lfs(1) 'clone'` command as deprecated, and puts that deprecation behind a "feature flag".
Since merging #2511, `git clone` is as fast as `git lfs clone` in the majority of cases. To avoid the maintenance cost of the `git lfs clone` command, we mark it as deprecated here, and point callers in the direction of `git clone`. @technoweenie points out a great reason for doing this in https://github.com/git-lfs/git-lfs/issues/2466#issuecomment-322290355:
> > git lfs clone could certainly go 😄 ! Maybe we can mark it as deprecated with a warning on invocation in the 2.x series already?
> 
> I'm all for deprecating it. We should recommend users update Git, but keep the command around for any stragglers. Also, reject PRs for support of any _new_ `clone` flags, since …
> commands: mark 'git lfs clone' as deprecated

- commands/command_filter_process.go
- tq/transfer_queue.go
- tq/transfer_queue_test.go
This pull request teaches the `readAvailable` function, used to accumulate available pathnames during a Git checkout, to initialize the receiving slice with a capacity equal to the maximum number of objects in a transfer queue's batch.
---
/cc @larsxschneider
> commands: use transfer queue's batch size instead of constant

- git/git.go
This pull request implements `git.Fetch()`, which takes in a variable number of remotes, and performs a `git fetch` operation on them.
This is work done in anticipation of first calling `git-fetch(1)` from the migrator, to ensure that the necessary remote refs are present locally when comparing them against the output of `git-ls-remote(1)` in order to determine what should be included and not included in the migration.
---
> git: implement Fetch() to fetch remote refs

- commands/command_migrate.go
- commands/command_migrate_import.go
- commands/command_migrate_info.go
- git/githistory/rewriter.go
This pull request allows callers of the `git/githistory.NewRewriter()` function to pass in a `git/githistory/log.(*Logger)` that they created, instead of just supplying the `io.Writer` sink.
This allows callers to maintain a handle on the given logger without expanding the API of functions that `*HistoryRewriter` receives. Callers that hold a reference to the logger can add their own arbitrary tasks to it, while maintaining the same synchronicity guarentees that the `*Logger` type provides.
This is done in anticipation of the `git-lfs-migrate(1)` command being able to fetch remote refs before beginning a migration. Doing so will require the migrator to log that it is fetching so it does not appear to hang, and thus requires a change like the one presented in this pull request.
---
/cc …
> commands,git/githistory: pass *log.Logger in externally

- git/attribs.go
- test/test-post-commit.sh
This pull request fixes a bug pointed out by @mrbobbybobberson in https://github.com/git-lfs/git-lfs/issues/2497#issuecomment-324173879.
According to our wiki:
> If you'd like to register a file type as lockable, without using LFS, you can edit the .gitattributes file directly:
>
> `*.yml lockable`
>
> Once file patterns in .gitattributes are lockable, Git LFS will make them readonly on the local file system automatically. This prevents users from accidentally editing a file without locking it first.
The post-commit hook should mark those files as read-only. This is correct (and verified by the `test/test-post-commit.sh` test) when files are _also_ tracked using Git LFS. When the `post-commit` hook runs, Git LFS tries to determine a filepathfilter that matches all of the files that are …
> git: expand 'GetAttributePaths' check to include non-LFS lockables

- commands/command_ls_files.go
- docs/man/git-lfs-ls-files.1.ronn
- test/test-ls-files.sh
There was no way to conveniently display LFS pointer file properties for
debugging. Teach 'git lfs ls-files' a '--debug' option that prints all
available information following the 'git ls-files' interface [1].
[1] https://github.com/git/git/commit/84974217151a66b65ae5b173045483ce5eeb5142
--
If you like the approach of this PR, then this would this would replace #1829.
My goal here is a quick way to check the sizes of the Git LFS files in a repo.
> commands: teach 'git lfs ls-files' a '--debug' option

- docs/man/git-lfs-config.5.ronn
The locking config per-host is supposed to affect all repositories on a 
given client machine. However, the help page suggests to set this value 
for a single repository only. Improve the example by using the global 
Git config.
> docs/man: recommend global per-host locking config

- commands/command_fsck.go
I am not clear on the goal of fsck, but when I ran it on my repo it complained about missing objects that were old revisions of lfs-stored files. It then tried to move the offending objects' files to the "bad" folder and, since the files of course did not exist, it complained again.
I found this looked like a reasonable fix, and then saw #953 which seems to agree.
> fsck only scans current version of objects

- commands/command_migrate.go
- docs/man/git-lfs-migrate.1.ronn
- test/test-migrate-import.sh
- test/test-migrate-info.sh
This pull request teaches the `--everything` flag to the `import` and `info` modes of `git-lfs-migrate(1)`.
`--everything` indicates that all local references should be migrated. In other words `--everything` means "migrate the entire section of my repository's local copy that is reachable by _any_ reference". Practically, this means "migrate everything".
Previously, in order to do this, users had to do some combination of:
```sh
git show-ref --heads --tags \
| cut -d ' ' -f 2 \
| sed -e 's/^/--include-ref=/' \
| xargs git lfs migrate import
```
which is correct, but not useable. The presence of `--everything` has the same practical effect as making the included refspec the output of `git show-ref --heads --tags` (via `git.LocalRefs()`).
---
> commands: teach '--everything' to 'git lfs migrate'

- git/githistory/rewriter.go
This pull request fixes a correctness issue with ref-updating migration modes where non-local refs would be moved in certain cases.
The problem with moving non-local references is that it is only correct if a 'git push' has been accepted against the remote which owns that reference. For example, if I update my copy of `refs/remotes/origin/master`, but don't actually push `master` to that remote, my copy of `refs/remotes/origin/master` is out of sync.
This can happen when running migrations that update local references which point to the same SHA-1 as a remote reference.
- When migrating, maintain a cache of old SHA-1's to the points on the graph that they moved to (i.e., I migrated commit X to a new commit of SHA-1 "Y".)
- Once migration is complete, iterate through all references in a …
> git/githistory: only update local refs

- git/githistory/rewriter.go
- git/odb/blob.go
- git/odb/blob_test.go
- git/odb/commit.go
- git/odb/commit_test.go
- git/odb/tree.go
- git/odb/tree_test.go
This pull request teaches a typesafe `Equal()` to `*Blob`'s, `*Commit`'s, and `*Tree`'s, and uses that function in the `git/githistory` package to avoid writing unchanged objects to disk.
Previously, the `git lfs migrate` command would write the contents of every object that it examined in the migration, regardless of whether that object's contents changed. This is sub-optimal, because it involves not only marshaling the contents of unchanged objects to a buffer and performing an expensive save, but also because it effectively has the behavior of unpacking all objects in a repository. That's no good.
To address this, this pull request opts for the following option that I originally proposed in https://github.com/git-lfs/git-lfs/issues/2359:
> Teach either:
> 
> 1. [...]
> 2. Packfile APIs …
> git/{odb,githistory}: don't write unchanged objects

- git/odb/pack/chain_delta.go
Running 'go tool pprof' in CPU mode while Git LFS is running a migration
against a large repository shows that 4.73% percent of the CPU time is spent in
a function called 'runtime.memmove'. This is the function called when
append()-ing to a slice causes the slice to grow, and memory occupied by the
existing slice must be moved into a different contiguous group.
```
$ go tool pprof $(which git-lfs) git-lfs-1504820145.pprof dot
File: git-lfs
Type: cpu
Time: Sep 7, 2017 at 5:35pm (EDT)
Duration: 35.17s, Total samples = 30.42s (86.49%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) list runtime\.memmove
Total: 30.42s
ROUTINE ======================== runtime.memmove in ...
1.44s      1.44s (flat, cum)  4.73% of Total
.          .     30:// void …
```
> git/odb/pack: prevent unnecessary runtime.memmove

- commands/command_migrate.go
This pull request uses cobra's `PersistentFlags()` option to avoid looping and reassigning flags to subcommands.
`PersistentFlags` are another flag set that is merged from a command's parent into the command's own flag set when `ParseFlag()` is called<sup>[[1](https://github.com/spf13/cobra/blob/b78744579491c1ceeaaa3b40205e56b0591b93a3/command.go#L1283-L1289
)][[2](
https://github.com/spf13/cobra/blob/b78744579491c1ceeaaa3b40205e56b0591b93a3/command.go#L1261-L1269)].
By using `PersistentFlags()`, we can avoid looping through each subcommand.
---
> commands/migrate: use PersistentFlags() to share flags with subcommands

- commands/commands.go
It can be hard to trace Git LFS errors on the server without the exact
time. Fix this by adding the time in UTC to the error log output.
> commands: print current time in UTC to error logs

- commands/commands.go
It can be hard to trace Git LFS errors on the server without client IP
address. Fix this by adding the IP address to the error log output.
Is this OK from a privacy perspective? I think it is OK as we log the file to the local machine that knows the IP address anyways. A user that is concerned about the IP address could remove it from an error report. The same is already the case if the error output contains sensitive filenames of a repo.
> commands: print IP addresses in error logs

- commands/command_migrate.go
This pull request fixes some incorrect indentation that accidentally got committed through a merge conflict resolution.
> commands/migrate: format incorrect indentation

- commands/commands.go
- commands/uploader.go
- docs/man/git-lfs-config.5.ronn
- test/test-pre-push.sh
- test/test-push-missing.sh
- test/test-push.sh
This implements two fixes to make LFS pushes better:
1. `lfs.allowincompletepush` is now on by default. It's easier to push repositories when you're missing LFS content. It still warns about those missing files, but at least you're not blocked.
2. Fixed an issue where the `ensureFile()` helper wasn't obeying the `lfs.allowincompletepush`. That helper detects cases where a `.git/lfs/objects/{oid}` file is missing, and attempts to fill it in from the file in the working directory. Fails on any modified or deleted files in the current HEAD, of course.
> improve Allowincompletepush

- git/odb/pack/chain.go
- git/odb/pack/chain_test.go
- git/odb/pack/object.go
- git/odb/pack/object_test.go
- git/odb/pack/type.go
- git/odb/pack/type_test.go
This pull request introduces some of the necessary scaffolding work to support packed object reads in package `git/odb/pack`.
The eventual design goal of this package is to have a `git/odb/pack.(*Packfile)` type that given a SHA-1 `[]byte`, returns an `(*Object)`, with the following type definitions:
```go
package git/odb/pack
type Object struct { ... }
func (o *Object) Type() PackedObjectType { ... }
func (o *Object) Unpack() ([]byte, error) { ... }
```
This pull request introduces the three types necessary to support a design as described above:
1. ef50370: The `PackedObjectType`, a const type that has valid values corresponding to the different types of objects that can be packed.
2. 9ea23ca: The `Object` type, with the above methods for determining the unpacked object's type, and for …
> git/odb/pack: scaffolding for packed object reads

- git/odb/pack/chain_base.go
- git/odb/pack/chain_base_test.go
- git/odb/pack/io.go
- git/odb/pack/io_test.go
This pull request provides the first of two implementations of the `Chain` interface:
> In the following two pull requests in this series, two implementations of `Chain` will be provided: `*ChainBase` and `*ChainDelta`, which will decompress and apply patch deltas respectively.
`*ChainBase` handles the first kind of component of the delta-base chains found in Git packfiles: the base. A base encodes some base object's data in a zlib-compressed format, to which delta operations can be applied (patched).
Since the `*ChainBase` must handle zlib-compressed data, we run into the challenge of converting the `mmap(2)`'d `*os.File` (given as an `io.ReaderAt`) into an `io.Reader` that package `compress/zlib` can read from. This is done using the `*OffsetReaderAt` type, which implements the …
> git/odb/pack: implement *ChainBase for unpacking base components

- git/odb/pack/chain.go
- git/odb/pack/chain_base.go
- git/odb/pack/chain_base_test.go
- git/odb/pack/chain_delta.go
- git/odb/pack/chain_delta_test.go
- git/odb/pack/chain_test.go
- git/odb/pack/io.go
- git/odb/pack/io_test.go
- git/odb/pack/object.go
- git/odb/pack/object_test.go
- git/odb/pack/packfile.go
- git/odb/pack/packfile_decode.go
- git/odb/pack/packfile_decode_test.go
- git/odb/pack/packfile_test.go
- git/odb/pack/type.go
- git/odb/pack/type_test.go
❗️ This pull request has branches `git-odb-pack-chain-base` and `git-odb-pack-chain-delta` as parents. Until those are merged, here is an inter-diff: https://github.com/git-lfs/git-lfs/compare/4908c70...git-odb-pack-packfile.
This pull request introduces a `*Packfile` type to package `git/odb/pack` whose responsibility it is to assemble an existing delta-base chain that corresponds to the given SHA-1 object name.
This pull request comes in two parts:
1. d2e66cb: implement the `*Packfile` type.
This type is responsible for assembling a representation of the delta-base chain corresponding to a given object.
Delta-base chains work as follows:
A delta-base chain has one base component, and zero or more delta components applied on top of the base. To resolve a delta-base chain, the base is …
> git/odb/pack: introduce *Packfile type for single-pack lookups

- git/githistory/rewriter.go
This pull request changes the log message when performing "rewrites" without ref updates to "Examining commits" instead of "Rewriting commits".
For example, before this pull request:
```
~/g/git-lfs (master) $ git lfs migrate import
migrate: Fetching remote refs: ..., done
migrate: Sorting commits: ..., done
migrate: Rewriting commits: 100% (0/0), done
migrate: Updating refs: ..., done
~/g/git-lfs (master) $ git lfs migrate info
migrate: Fetching remote refs: ..., done
migrate: Sorting commits: ..., done
migrate: Rewriting commits: 100% (0/0), done
```
And with this pull request:
```
~/g/git-lfs (migrate-different-msg-no-ref-updates) $ git lfs migrate import
migrate: Fetching remote refs: ..., done
migrate: Sorting commits: ..., done
migrate: Rewriting commits: 100% (0/0), done
migrate: …
```
> git/githistory: change "Rewriting commits" when not updating refs

- filepathfilter/filepathfilter.go
- filepathfilter/filepathfilter_test.go
- test/test-migrate-import.sh
- test/test-migrate-info.sh
I noticed that `HasPrefix()` returns false if there are no _include_ patterns. I think if none of the _exclude_ patterns have rejected it, then it should return `true`.
There is one existing test case this fails on: a prefix of `foo/bar/baz/`, with an exclude pattern of `/foo/bar/baz` or `foo/bar/baz`. It's commented out.
Without this fix, `git lfs migrate` will only scan the root directory if no `--include` flag is given.
> fix filepathfilter HasPrefix()
