lfsapi/creds.go, test/cmd/lfs-askpass.go, test/test-askpass.sh
This pull request fixes a bug where program arguments would be incorrectly accepted by the `GIT_ASKPASS` parser, therefore breaking `GIT_ASKPASS` and `core.askpass` exec paths that have spaces or quotes in them.
---
/cc @git-lfs/core @joshaber
=> lfsapi: do not accept arguments to GIT_ASKPASS, core.askpass

docs/man/git-lfs-migrate.1.ronn
This updates the man page:
* Lists the `import` mode
* Reorders the sections so that `info` is described before `import`
* Add some examples of how to use `info` and `import`.
=> Migrate doc update

commands/command_track.go, test/test-track.sh
This pull request allows callers to disable the hook installation component of running `git lfs track` via an environment variable `GIT_LFS_TRACK_NO_INSTALL_HOOKS`.
If set to a truth-y value, this skips the `lfs.InstallHooks(false)` call made by `git lfs track`. It is implemented as an environment flag since this is not functionality that we are intending to expose to users, rather, this is intended to be used by other programs leveraging Git LFS. It is absent from the manpage for the same reason.
---
/cc @git-lfs/core @joshaber
=> commands: allow $GIT_LFS_TRACK_NO_INSTALL_HOOKS to disable hook installation

script/windows-installer/inno-setup-git-lfs-installer.iss
This avoids the not very telling error message
[ISPP] Actual parameter FileName is not of the declared type
when Inno Setup tries to extract version information from a non-existing
binary.
=> Make the Inno Setup installer script explicitly check for the binaries

commands/command_clone.go, test/test-clone.sh
Fixes #2592 
This currently works by checking for `HEAD` ref after a clone and quietly moving on, but I'm open to different approaches to tackling this if we want to make the actions here more resilient and less noisy for this error case.
Any pointers for adding new tests to catch this regression would also be welcome!
=> don't fetch for unborn repositories

lfsapi/creds.go, test/cmd/lfs-askpass.go, test/test-askpass.sh
This trims whitespace from passwords provided by `GIT_ASKPASS`, bringing it up to speed with the username.
=> trim whitespace from GIT_ASKPASS provided passwords

commands/command_checkout.go, commands/command_pull.go, test/test-progress.sh
Fixes 3 issues with `GIT_LFS_PROGRESS`:
1. It's reported twice for `lfs pull` or `lfs clone`, since `(*ProgressMeter) StartTransfer(string)` is called in the GitScanner before being added to the transfer queue AND in the transfer queue. https://github.com/git-lfs/git-lfs/issues/2599
2. The `checkout` never knows how many files there are, so the progress is reported as `1/1`, `2/2`, `3/3`, etc.
3. No tests :(
I'm not crazy about changing `checkout` to accumulate a `[]*WrappedPointer` slice, but it's the only way to know the total number of files to checkout before starting to check files out.
=> Fix progress

commands/command_migrate.go, commands/command_migrate_import.go, commands/command_migrate_info.go, docs/man/git-lfs-migrate.1.ronn, git/githistory/log/log.go, git/githistory/log/log_test.go, git/githistory/log/percentage_task.go, git/githistory/log/task.go, git/githistory/ref_updater.go, git/githistory/rewriter.go
This adds an option to print the commit oid and path of every migrated file.  I'm not sure if this should be default or not, so I'm playing it safe for v2.3.1.
```
$ git lfs migrate import --include="*.gem" --include-ref=master --verbose
migrate: Sorting commits: ..., done
migrate: commit 4be47bd500d595ad735e077ea7b2b1b0ff399de4: vendor/cache/yajl-ruby-0.8.0.gem
migrate: Rewriting commits:   5% (21335/454650)
```
=> Migrate verbose option

lfsapi/creds.go, test/test-askpass.sh
This matches Git's behavior. `SSH_ASKPASS` is tried after `GIT_ASKPASS` and `core.askpass`, according to https://git-scm.com/docs/gitcredentials.
=> add support for SSH_ASKPASS

lfsapi/client.go, tq/adapterbase.go
This skips the request immediately, and provides a better error message (with the problem described at the front, before the long url).
BEFORE:
```
Fetching master
Git LFS: (0 of 2 files) 0 B / 178.50 KB
batch response: Post lfs.github.localhost/technoweenie/lfs-test/objects/batch: unsupported protocol scheme ""
error: failed to fetch some objects from 'lfs.github.localhost/technoweenie/lfs-test'
```
AFTER:
```
Fetching master
Git LFS: (0 of 2 files) 0 B / 178.50 KB
batch request: missing protocol: "lfs.github.localhost/technoweenie/lfs-test"
error: failed to fetch some objects from 'lfs.github.localhost/technoweenie/lfs-test'
```
=> reject invalid urls immediately

glide.lock, glide.yaml, vendor/github.com/rubyist/tracerx/tracerx.go
This updates `tracerx` to add timestamps to tracing output to match what git does.
Fixes #2619 
```
[scott@black tracerx]$ GIT_TRACE=1 git lfs locks
12:35:03.467185 git.c:560               trace: exec: 'git-lfs' 'locks'
12:35:03.467207 run-command.c:626       trace: run_command: 'git-lfs' 'locks'
12:35:03.469551 trace git-lfs: run_command: 'git' version
12:35:03.471019 trace git-lfs: run_command: 'git' config -l
12:35:03.471975 trace git-lfs: HTTP: GET https://github.com/rubyist/tracerx.git/info/lfs/locks
12:35:03.794442 trace git-lfs: HTTP: 200
12:35:03.796144 trace git-lfs: HTTP: {"locks":[],"next_cursor":""}
```
=> update tracerx to add timestamps

commands/command_track.go, test/test-track.sh
Fixes #2214 for `git lfs track <pattern>`.
=> convert backslash to slash when writing to .gitattributes

lfsapi/creds.go, test/test-askpass.sh
Fixes #2634. May change if the consensus reached in #2634 changes.
=> only use askpass if credential.helper is not configured

commands/commands.go, commands/run.go, lfsapi/lfsapi.go, lfsapi/netrc.go
Fixes #2624 
BEFORE:
```sh
$ git lfs fetch
line 1: keyword expected; got maachine
```
AFTER:
```sh
$ script/run fetch
bad netrc file /Users/rick/.netrc: line 1: keyword expected; got maachine
exit status 2
```
This includes a bonus tweak that doesn't initialize an api client unless it's needed. So `lfs version` won't trigger the error. You'll have to run something like `git lfs fetch`.
=> better Netrc errors

lfsapi/client.go
Really tiny, and probably inconsequential optimization.
=> only copy req headers if there are git-configured extra headers

commands/pull.go, test/test-pull.sh, test/testhelpers.sh
Fixes #2639 by ensuring files are added to the git index with a path relative to the current working directory.
=> add files to index with path relative to current dir

locking/lockable.go, locking/locks.go, test/test-unlock.sh
Fixes #2640 by moving the file permission logic from `UnlockFile()` to `UnlockFileById()`. The path is taken from the `lock` property returned by the `/unlock` api endpoint.
```sh
$ GIT_CURL_VERBOSE=1 git lfs unlock --id=123
> POST /my-repo.git/info/lfs/locks/123/unlock HTTP/1.1
> Host: github.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic * * * * *
> Content-Length: 15
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.3.1 (GitHub; darwin amd64; go 1.9)
>
{"force":false}
< HTTP/1.1 200 OK
< Content-Length: 141
< Content-Type: application/vnd.git-lfs+json
< Date: Tue, 03 Oct 2017 17:11:25 GMT
< X-Frame-Options: DENY
< X-Github-Request-Id: FF7E:5D17:5AA5486:AB0C1BC:59D3C4BD
< …
```
=> ensure files are marked readonly after unlocking by ID

lfsapi/creds.go
#2508 enabled credential caching for SSH. This enables it for http requests that go through `git-credential` or GIT_ASKPASS.
The struct tag notation for git config values doesn't support setting a default value. So, this uses the `Bool()` method, which does accept a default.
=> cache http credential helper output by default

git/git.go, test/test-clone.sh, test/test-pull.sh
Brings LFS back for `git update-index` calls. This fixes issues where `git status` is unclean after a `git lfs pull` or `git lfs clone`.
/cc https://github.com/git-lfs/git-lfs/issues/2646#issuecomment-334204675
=> potentially invoke lfs for 'git update-index'

tools/filetools.go, tools/filetools_test.go
The `tools.FastWalkGitRepo()` mimics `filepath.Walk()`, with a few performance optimizations:
* Subdirectories, in groups of up to 100, are walked in goroutines.
* Files are not returned in any specific order.
* `.gitignore` patterns are respected.
This PR introduces a limit to the concurrent goroutines that can be spawned, with an arbitrary default of 20x the number of CPUs that are available. That seems to be plenty, and well within system limits. It does mean that `tools.FastWalkGitRepo()` will slow down for particularly wide or deep directory structures in a repository, but hopefully it won't crash.
FWIW, `tools.FastWalkGitRepo()` is used in the following commands:
* `git lfs track`, when it's scanning your repository for nested `.gitattributes` files
* `post-merge` and …
=> FastWalkGitRepo: limit number of concurrent goroutines

commands/command_install.go, lfs/attribute.go, lfs/setup.go, test/test-install.sh
Fixes #2670. This PR fixes two common, but not fatal, problems that can arise when running `git lfs install`:
1. The values from `git lfs install --skip-smudge` can not be upgraded with `git lfs install`
2. An unexpected config value should not be overwritten. Instead, print a warning _without changing the exit code_. This way installations don't fail, but a user is told if their config values are unexpected.
=> Install tweaks

commands/command_checkout.go, commands/command_pull.go, commands/pull.go, test/test-checkout.sh, test/test-clone.sh, test/test-pull.sh
This prevents LFS from replacing LFS pointers with the actual content if the `clean` filter is not configured. Otherwise, this leads to a dirty `git status`. Fixes #2472
=> don't replace pointers with objects if clean filter is not configured

lfsapi/lfsapi.go, lfsapi/proxy.go, lfsapi/proxy_test.go
This uses `config.URLConfig` to get host-specific proxy settings like `http.{url}.proxy`. Fixes #2644.
=> add support for url-specific proxies

test/test-migrate-fixtures.sh
This should fix the rare intermittent test failures. Sometimes `base64` generates strings that some OS's won't allow as directory names. This PR runs the content through `shasum -a 256` to ensure the random filename only consists of hex characters.
[Sample failure](https://circleci.com/gh/git-lfs/git-lfs/2489?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):
```
test: migrate info (--everything with --include-ref) ...           FAILED
-- stdout --
-- stderr --
+ set -e
+ setup_multiple_local_branches
+ set -e
+ reponame=migrate-info-multiple-local-branches
+ remove_and_create_local_repo migrate-info-multiple-local-branches
++ base64
++ head -c 8
++ sed -e 's/\///'
+ local reponame=/oxVeYF-migrate-info-multiple-local-branches
+ git init …
```
=> test: generate random repo names with fs-safe characters

lfs/gitscanner_catfilebatch.go
There's no need to close the scanner if `NewPointerScanner()` returns an error, since it returns a `nil` scanner:
https://github.com/git-lfs/git-lfs/blob/d039e3791aca6100a0e0944cc7f46d1f4d0f047b/lfs/gitscanner_catfilebatch.go#L69-L76
This also fits with common go conventions.
=> lfs: PointerScanner is nil after error, so don't close

commands/command_clone.go, commands/command_env.go, commands/command_fetch.go, commands/command_filter_process.go, commands/command_lock.go, commands/command_locks.go, commands/command_post_checkout.go, commands/command_post_commit.go, commands/command_post_merge.go, commands/command_pre_push.go, commands/command_pull.go, commands/command_push.go, commands/command_track.go, commands/command_unlock.go, commands/commands.go, commands/uploader.go, config/config.go, git/git.go, git/git_test.go, lfs/gitfilter_smudge.go, lfs/lfs.go, test/test-fetch.sh, test/test-happy-path.sh
This teaches `*config.Configuration` how to get the default remote.
1. The `CurrentRemote` property was replaced with `Remote() string` and `SetRemote(string)`
2. Behavior from `git.DefaultRemote()` was replicated in `Remote()`.
3. All traces of `git.DefaultRemote()` were removed.
Fixes #2169.
EDIT: 1 caveat: this does not work with an empty repository, since `git rev-parse` blows up:
https://github.com/git-lfs/git-lfs/blob/bee3e755e1cc2206c342344ea98bd29bb51c3235/git/git.go#L195-L200
Not sure if this should assume any default branch name. Maybe it could look for any `branch.*.remote` config keys? Or this could just require a repository with at least 1 commit.
=> Tracked remote

commands/command_pre_push.go, commands/command_push.go, commands/lockverifier.go, commands/refs.go, commands/refs_test.go, commands/uploader.go, commands/uploader_test.go, config/config.go, git/git.go, git/git_test.go, locking/api.go, locking/locks.go, locking/locks_test.go, test/cmd/lfstest-gitserver.go, test/test-pre-push.sh, test/test-push.sh
Implements 2 aspects of #2712:
* basic `push.default` support, which governs how Git chooses an implicit remote ref based on the remote and local ref being pushed.
* Verify locks on each ref being pushed.
Bonus: locks are not verified for `git lfs push --object-id` anymore. Since this push doesn't affect any Git code, there's no need to verify anything.
This also extracts a `*lockVerifier` and `*refUpdate`. There is still too much coupling, but it's better than everything being in `*uploadContext`. Baby steps....
=> verify locks against each ref being pushed

docs/man/git-lfs-ls-files.1.ronn
This functionality was introduced in https://github.com/git-lfs/git-lfs/commit/2082b26ce728bb8a960b28bcac9aaecbb6a251c1 but was not documented.
=> Added documentation for git-lfs-ls-files' */- output.

test/testhelpers.sh
Also, back off on polling a bit after the first check to reduce any I/O contention that might slow things down even more. Instead of 5 seconds, this will wait up to about 60 seconds for files created by the test server to appear. This allows very slow systems to be able to pass tests.
Finally, add a message if the file doesn't appear to make it clear what went wrong.
For example, slow builders like [aarch64](https://kojipkgs.fedoraproject.org//work/tasks/291/22880291/build.log) or [armv7hl](https://kojipkgs.fedoraproject.org//work/tasks/294/22880294/build.log) mysteriously fail right after printing git(lfs) versions without any indication why.
=> Wait longer for test lfs server to start.

docs/man/git-lfs-uninstall.1.ronn, docs/man/git-lfs.1.ronn
Includes fixes for #2713 and #2714 
- `uninstall` is added to the list of commands on the top level man page
- the `--local` option is added to the man page for `uninstall`
=> Uninstall man page improvements

lfsapi/auth.go, lfsapi/client.go, lfsapi/ntlm.go, test/test-extra-header.sh
This pull request fixes a bug pointed out in https://github.com/git-lfs/git-lfs/issues/2729 where @TingluoHuang noticed that setting `http.$url.extraHeader` in your Git config would still cause API requests needing authorization to contact your credential helper, even if the authorization header was set.
Introduced here is a mechanism to avoid contacting the credential helper if any matching `http.extraHeaders` entry contains a header with the key `Authorization: `. This intentionally does not fall back to the credential cache or other credential helpers, since we assume that if a user explicitly provided an `Authorization` header, they would like to use that.
Closes: https://github.com/git-lfs/git-lfs/issues/2729
##
/cc @git-lfs/core https://github.com/git-lfs/git-lfs/issues/2729
=> lfsapi/auth: teach DoWithAuth to respect http.extraHeaders

git/attribs.go
---
This only addresses the initial description of #2413. It does not fix `[attr]` behavior or checking for `-filter=lfs`.
=> Ignore comment attr lines

git/rev_list_scanner.go, git/rev_list_scanner_test.go
This pull request fixes an issue pointed out by @phord via https://github.com/git-lfs/git-lfs/issues/2655:
> I have a large repo with 45000 refs. When I first tried to run git lfs migrate info on it, it failed with  this error:
>
> ```
> $ git lfs migrate info
> migrate: Fetching remote refs: ..., done
> fork/exec /usr/libexec/git-core/git: argument list too long
> ```
The general problem is that when migrating a set of references who's combined string length is longer than the system argument list limit, the system will refuse to execute the `git-rev-list(1)` command because its arguments are too long.
One approach in fixing this is to process separate invocations of `git-rev-list` and merge the results back together, but this gets complicated fairly quickly when merging distinct …
=> git: prefer sending revisions over STDIN than arguments

script/integration.go
This updates `script/integration` so it waits until it sends all output from the channel to STDOUT before exiting the command. It prevents cases where the _last_ test script fails, but no output is shown for that test script.
=> Fix integration test early exit

commands/lockverifier.go, commands/refs.go, commands/refs_test.go, git/git.go, git/git_test.go, locking/locks.go, locking/locks_test.go, script/integration.go, test/cmd/lfstest-gitserver.go, test/test-pre-push.sh
Updates the `locks/verify` calls to send the full refspec. /cc #2712.
=> Locks/verify: full refspec

commands/command_migrate.go, git/git.go, git/git_test.go, test/test-migrate-import.sh, test/test-migrate-info.sh
This pull request fixes a bug pointed out by @phord in https://github.com/git-lfs/git-lfs/issues/2654 where the `git lfs migrate` suite would refuse to disambiguate confusing reference names when asked to perform migrations.
@technoweenie points out a fix that I implemented in this pull request via https://github.com/git-lfs/git-lfs/issues/2654#issuecomment-335191900:
> Ah, I think this would be solved by including the ref prefixes, disambiguating the ref names.
To accomplish this, I taught the `*git.Ref` type to `String()` itself, returning a fully-qualified reference, and collect those instead of the local reference names. This allows for references to have existing SHA-1's as their local name, and migrate will still work correctly.
Closes: …
=> commands/migrate: allow for ambiguous references in migrations

test/test-track.sh
This pull request adds a test to https://github.com/git-lfs/git-lfs/pull/2708 that ensures `git lfs track` doesn't show attributes that are commented (and would therefore not be tracked by Git LFS.)
##
/cc @git-lfs/core @mathstuf
=> test: ensure commented attr lines are ignored

commands/command_migrate.go, docs/man/git-lfs-migrate.1.ronn, test/test-migrate-import.sh, test/test-migrate-info.sh
This pull request addresses an enhancement pointed out @phord in https://github.com/git-lfs/git-lfs/issues/2656 where the `git-lfs-migrate(1)` command's use of `git-fetch(1)` would make the command un-useable offline.
Since it's been a little while since I've thought about how this works, here's a refresher for my own edification. When determining what to migrate, the tool considers first explicitly given references, or, if none were provided, the unpushed changes on the current branch (i.e., `git log <branch>..<remote-tracking-branch>`). To ensure that we get an up-to-date result and don't accidentally require a force push when the user wasn't expecting one, we always `git fetch` to grab the latest remote refs, if any of them have moved.
Prior to this pull request, there was no way to …
=> commands/migrate: add '--skip-fetch' for offline migrations

script/packagecloud.rb
This adds ubuntu/artful to the list of distros for future LFS releases.
=> release lfs for ubuntu/artful too

filepathfilter/filepathfilter.go, filepathfilter/filepathfilter_test.go
This adds support for `--include="*.*"`, which should match everything:
```
$ git ls-files ':*.*'
.gitattributes
.gitignore
.mailmap
.travis.yml
CHANGELOG.md
CODE-OF-CONDUCT.md
CONTRIBUTING.md
INSTALLING.md
LICENSE.md
README.md
ROADMAP.md
appveyor.yml
circle.yml
commands/command_checkout.go
commands/command_clean.go
commands/command_clone.go
```
This also speeds up `*` matches too. It worked previously by calling `filepath.Match()` through a `*pathlessWildcardPattern`.
=> Filepathfilter wildcard

commands/command_checkout.go, commands/command_fetch.go, commands/command_prune.go, commands/command_pull.go, commands/uploader.go, git/githistory/log/log.go, git/githistory/log/log_test.go, progress/meter.go, progress/noop.go, progress/progress.go, progress/spinner.go, test/git-lfs-test-server-api/main.go
This pull request extends the `progress.Meter` interface to implement `git/githistory/log.Task` so that the `progress.Meter` can be driven from a `*git/githistory/log.Logger`.
Being able to use the various implementations of `progress.Meter` within the `git/githistory/log` sub-package has the following benefits:
- Separating the concept of generating a message and printing it.
- Eliminating IO-races, where two things want to log at the same time and the message is garbled, or out of order.
- Consistent use of the `git/githistory/log` package, which makes changing IO behavior in this context easier.
Since it's been awhile for me, I wanted to write down some of the ideas in the `git/githistory/log` package here:
1. The `*Logger` logs `Task`s, which provide a channel of updates, and a …
=> progress: use git/githistory/log package for formatting

commands/command_status.go, test/test-status.sh
This pull request fixes an issue pointed out by @fortytwoish in https://github.com/git-lfs/git-lfs/issues/2742, where `git lfs status` would not correctly format un-pushed objects, producing the following:
> git lfs status shows
> 
> ```
> $ git lfs status
> On branch master
> Git LFS objects to be pushed to origin/master:
>
>         [...]
>         Content/Maps/Prototypes/Autorunner.umap (%!s(MISSING))
>         [...]
> ```
I broke this in https://github.com/git-lfs/git-lfs/commit/6089d1931 (via: https://github.com/git-lfs/git-lfs/pull/2042), and this issue wasn't caught since we don't have any integration tests covering `git lfs status` running on un-pushed objects. In this pull request, such a test is added, along with a fix to remove the `(%!s(MISSING))` verb issue.
Closes: …
=> status: fix incorrect formatting with unpushed objects

git/odb/commit.go, git/odb/commit_test.go
Currently `git migrate import` corrupts commit objects which contain empty committer/author names by removing the leading space from the email 
(i.e. `author 'SP' 'SP' <my@email.com> --> author 'SP' <my@email.com>`).
This causes `git fsck` to fail with a 
`missingNameBeforeEmail: invalid author/committer line - missing space before email`
error. (And, I guess, would also mangle names containing consecutive whitespace... ;) )
This PR modifies `Commit.Decode` to grab the identifiers as is, retaining all whitespace.
=> git/odb: extract identifiers from commits verbatim

tasklog/percentage_task.go
This pull request changes the behavior of `*tasklog.ProgressTask` to no longer drop updates where the channel write to `ch` would block.
I discovered this issue while tweaking some of the output in the `git-lfs-prune(1)` command to use the new utilities provided by package `tasklog`. Sometimes, when using the `*PercentageTask` implementation provided, the final line would be:
```
<prefix>:   0% (0 of 1)
```
when it instead should have been:
```
<prefix>: 100% (1 of 1)
```
This is due to the non-blocking write that is removed in this pull-request. This is an artifact left over from before https://github.com/git-lfs/git-lfs/commit/fc1faca25aa1942aef8902bd6f1b1790ca6fdfed, when the `*log.Logger` implementation was taught how to discard too-frequent updates.
The old non-blocking write would …
=> tasklog: don't drop updates in PercentageTask

tasklog/percentage_task.go, tasklog/simple_task.go, tasklog/simple_task_test.go
This pull request introduces a new `Task` implementation, `*tasklog.SimpleTask`, for logging unrelated messages.
This functionality is required in replacing the usage of `*progress.Spinner` from within the `git-lfs-prune(1)` command. Instead of building domain-specific Task implementations, this pull request proposes the introduction of a string-based Task implementation that logs (and formats) strings without formatting guidelines.
This allows for quick prototyping of new Logger use-cases without the need to build out domain-specific loggers, and is a good fit for use within the `git-lfs-prune(1)` command.
##
=> tasklog: introduce `*SimpleTask`

git-lfs.go, versioninfo.json
As of [1] goversioninfo supports specifying the icon to embed as part of
versioninfo.json. Use that new mechanism for consistency with specifying
other meta-data fields.
[1] https://github.com/josephspurrier/goversioninfo/pull/17
=> Specify the embedded Windows icon as part of versioninfo.json

commands/command_fetch.go, tasklog/percentage_task.go, tasklog/simple_task.go, tasklog/simple_task_test.go
This pull request unifies the formatting of `git-lfs-fetch(1)`'s output, similarly to https://github.com/git-lfs/git-lfs/pull/2757.
Before:
```
~/repository (master) $ git lfs fetch --all
Scanning for all objects ever referenced...
Fetching objects...
✔ 501 objects found, done
Git LFS: (291 of 291 files) 1.1 KB / 1.1 KB, done
```
After:
```
~/repository (master) $ git lfs fetch --all
fetch: Fetching all references...
fetch: 501 object(s) found, done
Git LFS: (501 of 501 files) 1.9 KB / 1.9 KB, done
```
This removes the later of the two remaining uses of the `*progress.Spinner` type, which will allow it to be removed entirely in a subsequent pull request.
Similar to https://github.com/git-lfs/git-lfs/pull/2757:
> Please let me know if you have any thoughts on the formatting of these …
=> commands/fetch: unify formatting

tasklog/log.go
This pull request adds a `Simple()` method to the `*tasklog.Logger` API, which is consistent with other existing methods, and was pointed out by @technoweenie in https://github.com/git-lfs/git-lfs/pull/2757#discussion_r154760580.
##
=> tasklog: teach *Logger how to enqueue new `*SimpleTask`'s

commands/command_migrate.go, docs/man/git-lfs-migrate.1.ronn, test/test-migrate-import.sh, test/test-migrate-info.sh
This pull request fixes a bug pointed out by @sgoo in https://github.com/git-lfs/git-lfs/issues/2688, where `git lfs migrate info --everything` would fail when run under a bare repository.
The issue occurred because `git-lfs-migrate(1)` assumed that remote references do always exist, which is not the case when operating in a bare repository. (Interestingly, this is not the first time that I have forgotten about bare repositories: c.f., https://github.com/git-lfs/git-lfs/pull/2389, https://github.com/git-lfs/git-lfs/pull/1310).
Normally, this assumption is not error-prone, when the user provides an explicit list of reference to include and not include in a migration. However, when this list is not provided, _and_ the migration is run in a bare repository, the migrator would previously (and …
=> commands/migrate: don't migrate remote references in bare repositories

git/odb/object_db.go, git/odb/object_db_test.go, git/odb/object_type.go, git/odb/object_type_test.go, git/odb/tag.go, git/odb/tag_test.go
This pull request implements support within the `git/odb` package for reading and writing loose and packed representations of annotated tags.
The process for adding a new object type to the `git/odb` package was as follows:
1. 1e239fe: add a new `ObjectType` constant for `Tag`'s, to be used as a return value for `(*Tag) Type() ObjectType`.
2. b78fa93: implement the `Object` interface on a new concrete type, in this case `*Tag`. By implementing this interface, the `git/odb/pack` sub-package can use it for free, and _automatically read packed representations of the same object type_.
3. 944eaf8: wire up the new implementation to the `*git/odb.ObjectDatabase` type to add convenience APIs for reading/writing the new object type.
##
=> git/odb: implement parsing for annotated `*Tag`'s

git/githistory/ref_updater.go, git/githistory/ref_updater_test.go, git/githistory/rewriter.go
This pull request teaches the `*git/githistory.refUpdater` to hold a reference to a `*git/odb.ObjectDatabase` in anticipation of having to rewrite (and save new) annotated tags.
##
=> git/githistory: have *RefUpdater hold *odb.ObjectDatabase reference

commands/command_migrate.go, docs/man/git-lfs-migrate.1.ronn, test/test-migrate-import.sh, test/test-migrate-info.sh
This pull request supports `git-rev-list(1)`-style `^`-prefixed refspecs to be passed as arguments to the `git lfs migrate` command(s).
=> commands/migrate: support '^'-prefix refspec in arguments

git/odb/commit.go, git/odb/commit_test.go
This pull request fixes an issue pointed out by @hagami in https://github.com/git-lfs/git-lfs/issues/2772: 
> Before execute git lfs migrate import --everything --include="*.zip", git log shows below in my repository.
> 
> [ ... ]
> 
> After execute the command, empty line between "test" disappeared.
Here's some background: when parsing a commit, the stage of the encoded commit that we are currently parsing is kept track of. This is to differentiate a line beginning with `parent` when present in a header vs. when present in a commit message. To keep track of this, we use the fact that headers are separated from the commit message by a LF character.
Previously, something like this happened:
```go
for scan.Scan() {
if len(s.Text()) == 0 {
finishedHeaders = true
continue
}
// ...
}
```
Which …
=> git/odb: retain newlines when parsing commit messages

commands/command_filter_process.go, git/git_test.go, git/odb/pack/chain_delta_test.go, script/test, test/git-lfs-test-server-api/testdownload.go, test/git-lfs-test-server-api/testupload.go, tq/transfer.go
This pull request fixes `go tool vet` violations found in Git LFS, and runs `go tool vet` on the same list of packages being tested by any invocation of `script/test`.
@technoweenie's comment in https://github.com/git-lfs/git-lfs/issues/2743#issuecomment-346107557 got me thinking:
> [ ... ]
> 
> In fact, what do you think of adding `go vet` to `script/test`? I doubt it passes now, but I'd like to start nudging lfs towards a standard go codebase.
I think that this is a good idea. `go tool vet` provides useful insight on code _correctness_, not style as opposed to `golint`. I think that correctness of this sort is useful information to know about while testing, so let's do both at the same time.
In doing so, this pull request comes in two parts:
1. …
=> script/test: run 'go tool vet' during testing

commands/command_ls_files.go, docs/man/git-lfs-ls-files.1.ronn, test/test-ls-files.sh
This pull request adds `--include`, `--exclude` flag arguments to the `git-lfs-ls-files(1)` command, as per discussion in https://github.com/git-lfs/git-lfs/issues/2761#issuecomment-347938964:
> > How about `--pattern`, which works with any pattern that `.gitignore` or `.gitattributes` supports?
> 
> @technoweenie I like this -- what about our standard `--include`, `--exclude` (which would allow searching for one or many files/directories)?
Support for this leverages upon the work done by @technoweenie's work in https://github.com/git-lfs/git-lfs/pull/1696, that one can assign a `filepathfilter.Filter` implementation to the `*lfs.GitScanner`'s `Filter` field, and it will emit only tree entires that match the filter's include and exclude rules, as:
```go
s := lfs.NewGitScanner()
s.Filter = …
```
=> commands/ls-files: add --include, --exclude

commands/command_ls_files.go, test/test-ls-files.sh
This pull request teaches `git lfs ls-files` how to behave correctly when run in a repository before an initial commit has been made.
Previously, in a repository with no commits (and therefore, no `HEAD` reference), the behavior of `git lfs ls-files` was such:
```
~/D/new-repo $ git init
Initialized empty Git repository in /Users/ttaylorr/Desktop/new-repo/.git/
~/D/new-repo $ git lfs ls-files
Git can't resolve ref: "HEAD"
```
whereas now, it behaves as follows:
```
~/D/new-repo $ git init
Initialized empty Git repository in /Users/ttaylorr/Desktop/new-repo/.git/
~/D/new-repo $ git lfs ls-files
~/D/new-repo $ 
```
The above behavior was caused by the fact that `git.CurrentRef()` would try to resolve the `HEAD` reference, when it did not in fact exist. To resolve this, we compare the state …
=> commands/ls-files: behave correctly before initial commit

commands/command_ls_files.go, lfs/gitscanner_index.go, test/test-ls-files.sh
⚠️ This pull request is based upon https://github.com/git-lfs/git-lfs/pull/2794, and an inter-diff is available [here][1].
##
This pull request teaches `git lfs ls-files` to show tracked LFS objects that are present in the index, which may or may not appear in a tree, as was suggested by @aleb in https://github.com/git-lfs/git-lfs/issues/2705:
> Currently `git lfs ls-files` by default lists the files at the current HEAD, but excluding the new files in the staging area. This is inconsistent with the behaviour of `git ls-files` which by default lists also the new files in the staging area.
> 
> It would be nice to fix this inconsistency:
To accomplish this, we print the set intersection of all LFS objects scanned from the tree (using the `gitscanner`'s `ScanTree()` method), and all LFS …
=> commands/ls-files: show cached, tree-less LFS objects

config/git_fetcher.go
LFS locking is currently only verified by the client. The server APIs just returned what paths are locked, while the client controls whether you can push or not. This change allows to set `lfs.locksverify` in a *./.lfsconfig* file which LFS will automatically pick up for all users of the repo.
Without defining `lfs.locksverify` as a safe key, the client will output a warning and simply ignore the setting.
=> Add `lfs.locksverify` to safe keys.

commands/command_ls_files.go, docs/man/git-lfs-ls-files.1.ronn, test/test-ls-files.sh
This pull request adds a new flag to the `git lfs ls-files` command, `--all` to scan for _all_ LFS objects in a repository, not just those at the given reference (or HEAD, by default).
This feature was requested by @emericv in https://github.com/git-lfs/git-lfs/issues/2575:
> There is a way to have the whole LFS object sha256 list from a git repo? (like a git-lfs ls-files, but including modified/deleted objects refs of all branchs/tags).
@technoweenie suggested in https://github.com/git-lfs/git-lfs/issues/2575#issuecomment-328909675 to use `ScanRefWithDeleted`, but I think that `--all` may be sufficient (ignoring reference arguments). That said, it might be worth expanding this to cover:
1. `--all`: the entire repository, ignoring the explicit reference argument.
2. `--deleted`: the …
=> commands: teach '--all' to `git lfs ls-files`

commands/command_push.go, commands/commands.go, commands/uploader.go, tq/meter.go, tq/transfer_queue.go
This started as a rewrite of #2774 against new master (due to lots of conflicts with the progress meter in #2762). However, I decided to keep it scoped to just running multiple transfer queues, leaving the actual refspec-sending stuff to a follow up PR. I think that'll make this easier to review.
* While `commands.uploadContext` is an internal type, I'm trying to use exported functions in `commands`, outside of the actual `uploadContext` type. Also, some functions were moved to the `uploadContext` type, instead of merely accepting one as an argument. There's certainly more to be done with `*uploadContext`, but I'd rather do that in a specific refactor PR.
* `*tq.TransferQueue` now flushes the latest update, but doesn't close the Meter's internal channel. This is so there's only 1 line in …
=> Run 1 TransferQueue per uploaded ref

tools/humanize/humanize.go, tools/humanize/humanize_test.go
This pull request adds `humanize.FormatByteRate` to the `tools/humanize` package, necessary for the progress meter changes described by @bitinn in #2802.
From @technoweenie's comment in https://github.com/git-lfs/git-lfs/issues/2802#issuecomment-355317842:
>Would it be possible to change the meter to `[Uploading | Downloading] LFS objects: 100% (63/63), 2.01 MiB | 280.00 KiB/s, done.` [...]
To format the `2.01 MiB`, we can use `humanize.FormatBytes` or `humanize.FormatBytesUnit`, but to format the `280.00 KiB/s`, we must either hack the output of one of the two former functions, or add a new one. This pull request opts for the later.
The premise of the function is as follows:
> ```go
> // FormatByteRate outputs the given rate of transfer "r" as the quotient of "s"
> // (the number of …
```
=> tools/humanize: add 'FormatByteRate' to format transfer speed

commands/command_fetch.go, commands/commands.go, commands/uploader.go, test/test-batch-transfer.sh, test/test-chunked-transfer-encoding.sh, test/test-clone.sh, test/test-credentials.sh, test/test-custom-transfers.sh, test/test-duplicate-oids.sh, test/test-fetch-include.sh, test/test-fetch-paths.sh, test/test-fetch.sh, test/test-happy-path.sh, test/test-pre-push.sh, test/test-progress-meter.sh, test/test-progress.sh, test/test-pull.sh, test/test-push-file-with-branch-name.sh, test/test-push.sh, test/test-smudge.sh, test/test-unusual-filenames.sh, test/test-zero-len-file.sh, tools/humanize/humanize.go, tools/humanize/humanize_test.go, tq/meter.go, tq/transfer_queue.go
This pull request adopts the recommendation for a new style of progress meter proposed by @bitinn and @technoweenie in https://github.com/git-lfs/git-lfs/issues/2802, and https://github.com/git-lfs/git-lfs/issues/2802#issuecomment-355317842, respectively:
> Would it be possible to change the meter to `[Uploading | Downloading] LFS objects: 100% (63/63), 2.01 MiB | 280.00 KiB/s, done.` That matches the "Writing objects" message, retains the file counts, and even shows current speed.
The style that is implemented in this pull request is exactly as @technoweenie's recommendation above:
```
~/example-repository (master) $ git lfs pull
Downloading LFS objects: 100% (501/501), 1.9 KB | 210 B/s, done
```
Here's a large overview of the changes:
1. **Remove the notion of 'skipped' files.** This …
=> tq: standardized progress meter formatting

docs/api/batch.md, docs/api/locking.md
Adds docs for the refspec api changes, as prophesized by #2712.
@ttaylorr I didn't realize you added some stuff at the end of #2773. Here's a chance to go through it all together :)
I changed some of the wording, with the intention of using Git terms, like "fully qualified refspec." Open to improvements here.
=> refspec docs

commands/command_post_checkout.go
I believe the usage documentation for `git lfs post-checkout` incorrectly states that this should be run as part of Git's `post-commit` hook, instead of the `post-checkout` hook.
=> Update usage info for post-checkout

glide.lock, vendor/github.com/xeipuuv/gojsonpointer/README.md, vendor/github.com/xeipuuv/gojsonpointer/pointer.go, vendor/github.com/xeipuuv/gojsonpointer/pointer_test.go, vendor/github.com/xeipuuv/gojsonreference/reference.go, vendor/github.com/xeipuuv/gojsonreference/reference_test.go
This pull request updates the vendored copy of `github.com/xeipuuv/gojsonpointer`.
Running `script/vendor` produces a diff in this tree without updating the hash of the lock file or the project itself.
##
=> vendor: update 'xeipuuv/gojsonpointer'

commands/command_fsck.go, lfs/gitscanner.go, lfs/gitscanner_index.go, lfs/gitscanner_refs.go, test/test-fetch.sh
If `lfs.fetchinclude` is used, then `git lfs fsck` reports errors. That might confuse users.
=> fsck: attach a filter to exclude unfetched items from fsck

commands/command_prune.go
People use 'lfs.fetchexclude' to limit the download of Git LFS content.
If a user excludes Git LFS files with 'lfs.fetchexclude' after a full 
clone, then Git LFS would not smudge the files in the working directory
but it would keep the LFS content in the LFS storage directory (usually 
.git/lfs/objects). Git LFS would keep the LFS content even after a
'git lfs prune' run. 
Change that behavior and prune all objects that match the 
'lfs.fetchexclude' pattern independent of their age.
---
⚠️  I am unfamiliar with these areas of the code. Please review carefully! All good ideas stolen from @ttaylorr 's great work in #2847 !
=> prune: always prune excluded paths

tq/meter.go
Moved int64 declarations back to the top of the Meter struct for proper memory alignment.
See: https://github.com/git-lfs/git-lfs/issues/2879
=> Issue #2879: Fix memory alignment issues on 32-bit systems.

git/odb/object_db.go, git/odb/object_writer.go, lfsapi/stats.go, tasklog/percentage_task.go
This pull request fixes an issue when using `sync/atomic` on 32-bit architectures when the structure alignment did not place numeric types at the top.
In the affected structures, we realign the fields and note that future fields should be placed at the top, if they are numeric.
I am indicating that this issue closes #2879, the remaining follow-up was to run CI on 32-bit architectures, but this is not something that TravisCI currently supports. I will follow up here if this feature is ever added upstream.
Closes: https://github.com/git-lfs/git-lfs/issues/2879.
##
/cc @git-lfs/core @jeffreydwalter
/cc https://github.com/git-lfs/git-lfs/issues/2879
=> *: fix 32-bit alignment issues with `sync/atomic`

git/githistory/rewriter.go
This pull request fixes an issue where the semantics of `range` would cause the resulting tree entries to be built incorrectly when the alias moved during the associated loop.
Since `range`'s second argument, when de-structured, is a pointer alias that moves through the array, appending it onto the end of a slice of other pointers is non-deterministic. If the memory layout changes, or the pointer changes into certain regions of the layout, the resulting tree will be built incorrectly.
To prevent this issue from occurring, introduce `copyEntry` which produces a new, heap-allocated `*odb.TreeEntry` not susceptible to the copying issue.
##
/cc @git-lfs/core @larsxschneider
=> git/githistory: copy entries from cache, elsewhere

filepathfilter/filepathfilter_test.go
This pull request fixes an error I introduced in https://github.com/git-lfs/git-lfs/commit/014fd601641cdea228b438895efb91237c12675a (see: https://github.com/git-lfs/git-lfs/pull/2875#discussion_r170778659) where the refined set of global wildcards was not being correctly tested against.
##
/cc @git-lfs/core @larsxschneider
=> filepathfilter: test correct set of global wildcards

README.md
This pull request adds a link to the 'Limitations' wiki page in the README, per the discussion in https://github.com/git-lfs/git-lfs/pull/2876, particularly https://github.com/git-lfs/git-lfs/pull/2876#issuecomment-368713449.
##
/cc @de-code @mathstuf @larsxschneider
=> README.md: hotlink to the Limitations wiki page from README

test/cmd/lfstest-gitserver.go, test/test-credentials.sh, test/test-extra-header.sh
Otherwise, when running tests in parallel, they might conflict.
Fixes #2899.
I went through all the builds in the linked issues, and every one that fails runs `test-extra-header.sh` before `test-credentials.sh`, while every one that passes does the opposite.
=> Use unique repo name for tests that require credentials.

commands/command_ls_files.go, test/test-ls-files.sh
This pull request fixes a bug pointed out by @xerus in https://github.com/git-lfs/git-lfs/issues/2930, where the following command would crash Git LFS: `git lfs ls-files -- --all`.
The issue is that the `--` separator signals that the following arguments are to be treated as-such, and not parsed as flags, so `git ls-tree` attempts to scan an object with the SHA1 "--all", which is invalid.
This issue was introduced by me in https://github.com/git-lfs/git-lfs/pull/2795, and worsened in https://github.com/git-lfs/git-lfs/pull/2796, after adding the `--all` option to `git-lfs-ls-files(1)`. To avoid observing duplicate tree entries in the output, we maintain a cache `seen : map[string]struct{}`, keyed by the object's name.
However, should there be an `err` in the callback and a nil …
=> commands/ls-files: do not accept '--all' after '--'

README.md
This pull request applies a fresh coat of paint to Git LFS's README.md, by cutting down on extra text and removing some links that are no longer active.
##
=> README.md: :nail_care:

README.md
This pull request changes the README.md by breaking the "Core Team" section into "Core Team" and "Alumni" to accurately reflect the current set of Git LFS maintainers.
This change is motivated by a few things:
1. **Usage of `@git-lfs/core`**. I mention this team anytime I introduce a change to Git LFS. As the team has grown and changed over time, I have grown worried that mentioning `@git-lfs/core` sends notifications to people who are uninterested in them.
By introducing a `@git-lfs/alumni` team and reflecting that change in the README, notifications to core go to the people who will most care about them.
2. **Accurate indication of who will provide help with Git LFS**.  I am additionally concerned that people looking to open a new issue or comment on an existing one within this …
=> README.md: reorganize into Core Team, Alumni

README.md
This pull request clarifies an issue when running `git lfs track` in a repository containing history which has already-large files in it.
The issue is that if a repository already contains `big.dat` in its history, and a user runs `git lfs track big.dat`, only future changes to that file will be tracked using Git LFS. In this case, the user would like to have already-existing `big.dat`'s migrated into Git LFS, but this is not how `git lfs track` works.
In order to accomplish this, a user must run `git lfs migrate import --include=/path/to/file`, which is the source of some confusion. In an attempt to mitigate this confusion and make the `track` command behave more ergonomically, I propose the following:
1. Mention that `git lfs migrate` is required when `track`-ing files that already …
=> README.md: mention note about `git lfs track` retroactively

commands/command_migrate_import.go, commands/command_track.go, commands/command_untrack.go, test/test-migrate-fixtures.sh, test/test-migrate-import.sh
This pull request fixes `git-lfs-migrate-import(1)` when given `--include` and/or `--exclude` filters that contain .gitattributes-unescaped sequences, such as whitespace.
When migrating, Git LFS will do either one of the following two things: (1) adopt filters from `--include`, `--exclude`, or (2) migrate all files that aren't named `.gitattributes`. When doing (1), Git LFS previously copied these filters verbatim as they were given on the command line.
This is problematic, as @mrackwitz points out in https://github.com/git-lfs/git-lfs/issues/2908:
> I passed in some quoted paths via --include, e.g. `"External/AWS iOS SDK/*"`.
> This resulted them being written to the `.gitattributes` as:
>
> ```
> External/AWS iOS SDK/* filter=lfs diff=lfs merge=lfs -text
> ```
>
> Which resulted in the …
=> commands/migrate: escape paths before .gitattributes 

commands/command_track.go, commands/command_untrack.go, commands/path.go, test/test-track.sh, test/test-untrack.sh
This pull request teaches "git lfs track" and "git lfs untrack" to perform prefix-agnostic comparisons, meaning that "./a.dat" and "a.dat" are equivalent patterns. This writes a correct pattern to a user's .gitattribute file via translating "git lfs track ./a.dat" to "a.dat filter=lfs ...".
For more:
> 1c8209ba: commands/path.go: introduce trimCurrentPrefix to remove "./"
>
> There exist cases within Git LFS where we would like to perform a
> "pseudo-clean" on a given filepath. It should behave similarly to a call
> to filepath.Clean, but should only remove the beginning "./" (macOS,
> *nix) or ".\" (Windows, etc).
>
> This patch introduces trimCurrentPrefix, which removes such prefixes.
> It will be used in subsequent patches to perform prefix-independent
> comparison against arguments …
=> commands/{un,}track: perform "prefix-agnostic" comparisons

README.md
This pull request updates the PackageCloud URL present in README.md to point at the correct organization URL, which is `github/`, not `git-lfs/`.
This is an artifact of when this repository used to live at `https://github.com/github/git-lfs`. The PackageCloud account was registered under the same namespace for consistency, but was not updated when the repository was moved.
I broke this in #2942, when I was updating the README to contain more new information.
To avoid breaking any scripts dependent on this location, and for historical purposes, let's leave the URL where it was and update the README to reflect that.
Closes: https://github.com/git-lfs/git-lfs/issues/2959.
##
/cc @git-lfs/core @necromuralist
=> README.md: note the correct PackageCloud URL

test/test-mergetool.sh
This pull request ensures that the `git-mergetool(1)` program works correctly with large files stored using Git LFS.
This is the result of spending some time doing research into and implementing a `git-lfs-mergetool(1)`, after thinking that `git-mergetool(1)` would not convert conflicts using their appropriate clean/smudge filters before sending to the designated mergetool.
(The result of that work can be viewed in [branch `mergetool`](https://github.com/git-lfs/git-lfs/compare/mergetool)).
While discussing with @peff, we noted that `git-mergetool(1)` uses `git-checkout-index(1)` to get the contents of a file before assigning it to a temporary location and attaching an environment variable to the mergetool program. For reference, that's:
- …
=> test: ensure that git-mergetool(1) works with large files

commands/run.go, test/test-version.sh
This pull request builds on https://github.com/git-lfs/git-lfs/pull/2967 by using the newly available APIs on `*cobra.Command`, `.Version`, and `.SetVersionTemplate` to introduce `git lfs --version` as a synonym for `git lfs version`.
It is based off of cobra-pflag-update, but should be merged into `master`.
Closes: https://github.com/git-lfs/git-lfs/issues/2118.
##
=> commands: make --version a synonym for 'version'

commands/run.go, git-lfs.go
This pull request teaches Git LFS to exit with code `127` when asked to invoke an unknown sub-command.
We accomplish this in two parts:
1. 3379c0c: teach `Run()` to become `Run() int`, and return the integer exit code of the status that it would like to exit with.
2. a4dfae7: teach `Run() int` to return `127` when cobra cannot invoke a sub-command.
Closes: https://github.com/git-lfs/git-lfs/issues/2253.
##
=> commands/run.go: exit 127 on unknown sub-command

lfsapi/client.go, lfsapi/endpoint.go, lfsapi/endpoint_finder.go, lfsapi/endpoint_finder_test.go
It can be used to configure a standalonetransferagent for local files,
like:
```
git config lfs.customtransfer.file.path git-lfs-standalonetransfer-file
git config lfs.file:///.standalonetransferagent file
```
Signed-off-by: Steffen Prohaska <prohaska@zib.de>
=> Map local abspath to file://<abspath> endpoint URL

commands/command_uninstall.go, test/test-uninstall.sh
This pull request fixes a bug where `git lfs uninstall --local` would produce output suggesting that it had uninstall global hooks when in fact it had not.
For example (as pointed out by @hraban in https://github.com/git-lfs/git-lfs/issues/2975):
```ShellSession
$ git lfs uninstall --local
Hooks for this repository have been removed.
Global Git LFS configuration has been removed.
```
To fix this, ensure that we're not running in `--local` mode before logging about the global Git LFS configuration. We do not treat `--system` as a special-case here, since it is not used by this command. (A future pull request will remove this from `git lfs uninstall`).
Closes: https://github.com/git-lfs/git-lfs/issues/2975.
##
=> commands/uninstall: do not log about global hooks with --local

README.md
The link that points to gitattributes' documentation appears to be broken, should've been https://git-scm.com/docs/gitattributes
=> .gitattributes link is broken

lfs/attribute.go, test/test-install.sh
This pull request teaches `git lfs install` not to treat the current, installed values of an "attribute" as upgrade-able, and therefore avoids writing over a `.gitconfig` time at each invocation of `git lfs install`.
As @niik points out in https://github.com/git-lfs/git-lfs/issues/2993, users of GitHub Desktop were noticing that their `~/.gitconfig` files were being written to every time that GitHub Desktop launched, but the contents of the file was left unchanged.
> Running git lfs install --skip-repo with the GIT_TRACE=1 environment variable yields the following
> 
> ```ShellSession
> $ GIT_TRACE=1 ./git-lfs install --skip-repo
> 16:38:58.656296 trace git-lfs: exec: git 'version'
> 16:38:58.669961 trace git-lfs: exec: git 'config' '--global' 'filter.lfs.process'
> 16:38:58.686455 trace …
```
=> lfs/attribute.go: remove default value from upgradeables

commands/command_lock.go, test/test-lock.sh
This pull request teaches the `git lfs lock` command how to follow symlinks in the current working directory so that files in symlinks can be resolved, too.
Previously, a symlink-in-symlink would cause `git lfs lock` to fail: by avoiding following the symbolically linked current working directory, the symbolically linked target of `git lfs lock` would be appended to the path, and then `stat`'d, causing the stat to fail, for the path will likely not exist.
Instead, resolve the current working directory to be absolute, and _then_ append children relative to it.
Closes: https://github.com/git-lfs/git-lfs/issues/2990.
##
/cc @git-lfs/core @jbstewart
=> commands/lock: follow symlinks before locking

CONTRIBUTING.md
The contributor's guide still linked to the now-removed CLA page. This commit removes that reference.
=> remove reference to CLA from contributor's guide

test/test-env.sh, test/test-worktree.sh
This pull request stops checking `GIT_EXEC_PATH` in the `test/test-env.sh` tests.
Git LFS will never have an `env` that contains `GIT_EXEC_PATH` in it, but recent versions of Git add this to the environment for reasons I can't precisely determine.
To avoid adding version conditionals, let's skip the check all together. This should fix the regression that we're experiencing in https://github.com/git-lfs/git-lfs/pull/3010.
##
=> test/test-env: skip comparing GIT_EXEC_PATH

lfsapi/auth.go, lfsapi/client.go, test/test-extra-header.sh
This pull request ensures that extra HTTP headers given over `http.[url.]extraHeaders` are canonicalized as proper MIME header keys before being sent over the network.
Ordinarily, any server that handles a request with a malformed HTTP header should canonicalize it without issue, so there aren't any problems with existing configurations and outgoing web requests. The problem, however, occurs when we check if the `Authorization: ` header is present by checking for the hard-coded string `"Authorization"` in package `lfsapi`.
(As an aside, this particular use-case is for figuring out whether we can skip calling out to the credential helper for an already-authenticated request).
Here's an example demonstrating the problem \[[1](https://play.golang.org/p/owfI4qv5o0L)\]:
```go
package main …
```
=> lfsapi: canonicalize extra HTTP headers

lfsapi/auth.go, lfsapi/client.go, lfsapi/client_test.go, lfsapi/ntlm.go
This pull request teaches package `lfsapi` to re-authenticate HTTP requests when the response indicates a redirection.
When an HTTP request is sent through package `lfsapi`, there are a few paths that we can take down into `do()` and `doWithRedirects()`. The one that we're concerned with involves one of two outcomes:
1. We send an HTTP request that is responded to with a 301 or 302 code. If we're within our retry limit, we construct a new request sent to the new host/path, and copy over the headers from the old request \[[1](https://github.com/git-lfs/git-lfs/blob/v2.4.1/lfsapi/client.go#L360-L368)\]. Notably, we do _not_ copy the `Authorization` header iff the new host differs from the old one, as a security concern. We retry the request.
2. Same setup as (1), except we have exceeded our …
=> lfsapi: re-authenticate HTTP redirects when needed

git/githistory/rewriter_test.go, git/odb/commit.go, git/odb/object_db_test.go
This pull request fixes an issue where the final trailing newline in a commit message would be removed, thus making migrations that should have no effect change the SHA-1s of commits.
This was caused by #2784, wherein I misunderstood the lack of `LF` at the end of the specification to mean "there is no newline here". Instead, it means that there is no newline after the `<data>` field, which itself _does_ contain a newline.
Here's a demonstration of the problem prior to e35b429:
```ShellSession
$ git commit --allow-empty -m "initial commit"
[master (root-commit) 0feac72] initial commit
~/D/example (master) $ git cat-file -p HEAD
tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904
author Taylor Blau <me@ttaylorr.com> 1528488020 -0500
committer Taylor Blau <me@ttaylorr.com> 1528488020 -0500 …
```
=> git/odb: retain trailing newlines in commit messages

commands/command_migrate.go, commands/command_migrate_import.go, docs/man/git-lfs-migrate.1.ronn, git/attribs.go, test/test-migrate-fixtures.sh, test/test-migrate-import-no-rewrite.sh
This PR adds a new `--no-rewrite` flag to the `migrate import` command. When this flag is given, `migrate import` takes a list of files as arguments and imports these files into Git LFS. It does this by rewriting the git tree in a new commit, without modifying git history.
Some of the code in this PR was based off of code previously written by @ttaylorr. Also, a big thank you to @ttaylorr for pairing with me on parts of this PR!
=> Add `--no-rewrite` flag to `migrate import` command

commands/command_checkout.go, docs/man/git-lfs-checkout.1.ronn
This pull request marks `git lfs checkout` as deprecated, indicating that it will be removed in v3.0.0.
`git checkout` benefits from the `delay=` capability introduced by @larsxschneider upstream, thus removing the need to retain this command in the future. Since we can't get rid of it between v2.4.0 and v2.5.0, let's mark that it is deprecated (similar to #2526) and schedule it for removal in v3.0.0.
One thing to consider is a feature such as `--include` or `--exclude`. `git lfs checkout` never supported these interestingly enough, so I suppose `git lfs checkout --include` was a fairly uncommon use-case. If someone so desired it, it could be accomplished by
$ git -c lfs.fetchinclude=foo checkout -- 
##
/cc @git-lfs/core @larsxschneider
=> commands/checkout: mark 'git lfs checkout' as deprecated

commands/command_checkout.go, test/test-checkout.sh, tq/meter.go, tq/transfer.go
This pull request fixes an issue where `git lfs checkout` would log a message indicating that it was "Uploading LFS objects", instead of something more appropriate, such as "Checking out LFS objects".
This issue was pointed out by @shuhrat in https://github.com/git-lfs/git-lfs/issues/3037.
The cause of this issue is interesting: since `Upload` and `Download` are defined in terms of the `iota` keyword, `Upload` (being defined closer to the top of the file) is given value `0` whereas `Download` is given value `1`. Hence, when we avoid initialization, Go steps in and gives us the zero-value of this object, which happens to be `Upload`.
To avoid this in the future, we should make the Unknown field have value zero (or avoid this altogether, and start at `iota + 1`), but this change feels …
=> commands/checkout: fix inaccurate messaging

docs/man/git-lfs.1.ronn
This pull request fixes some casing inaccuracies in `git-lfs(1)`.
##
/cc @git-lfs/core https://github.com/git-lfs/git-lfs/issues/3043
=> docs/man/git-lfs.1.ronn: update casing and missing commands

git/git.go, test/test-migrate-fixtures.sh, test/test-migrate-import.sh
This pull request passes the `--multiple` flag to `git-fetch(1)` when appropriate, i.e., when calling `git.Fetch()` with more than one remote.
When calling `git lfs migrate` (and the `--skip-fetch` option is not given) we first fetch all remote references, to make sure that we have an up-to-date copy of what is and is not present on the remote. This is done so that we can ensure that we aren't performing a migration that will later be rejected by a remote thus requiring a `--force`.
When users have multiple remotes, we will attempt to flatten that list into a single slice, and then call `git.Fetch()` once with all of the remotes. This is a correct calling convention for 0- and 1-arity arguments (none or a single remote) but is incorrect for `>1` remotes.
Specifically, if we have remotes …
=> git/git.go: pass --multiple to git-fetch(1) when appropriate

README.md
This pull request adopts a suggestion from https://github.com/git-lfs/git-lfs/issues/3069 to add a link to the installation wiki page in the relevant section in the README.md.
##
/cc https://github.com/git-lfs/git-lfs/issues/3069, @avilleret
=> README.md: add link to installation wiki page

lfsapi/proxy.go, lfsapi/proxy_test.go
This pull request changes the behavior of package `lfsapi` to prefer the HTTP(s) proxy values originating from the environment, rather than the Git configuration.
As noted in https://github.com/git-lfs/git-lfs/issues/3060, this was originally the case when it was introduced in #1358, but was changed in #1787.
From the Git documentation \[[1](https://git-scm.com/docs/git-config#git-config-httpproxy)\]:
> __`http.proxy`__
>
> Override the HTTP proxy, normally configured using the http_proxy, https_proxy, and all_proxy environment variables (see curl(1)). [...]
This is technically a breaking change, but it's one that I would feel comfortable releasing along the v2.5.0 line, since holding back such a small patch until v3.0.0 feels unwise.
Closes: …
=> lfsapi: prefer proxying from gitconfig before environment

docs/man/git-lfs-track.1.ronn, docs/man/git-lfs.1.ronn
Every time I go back to git LFS after a long break, I wonder how it
works and how to get started. The first manual page is currently a
reference to a fairly large number of other manual pages and, as the
core documentation of LFS, does not really help users in getting basic
things done.
In comparison, the LFS homepage has a good primer, so I have taken it
as an example for a basic example that would work in the manual page
to help users get out of the weeds quickly.
=> add basic example in main manpage

debian/rules
The deb packages don't currently run `go generate` when building which
means commands like `git-lfs help` don't work properly.  This changes
the packaging script to run it.
Fixes #3043
=> Run `go generate` on commands in deb build

commands/command_status.go, test/test-status.sh
This pull request teaches `git lfs status` how to work properly when invoked from a working directory other than the root of the repository upon which it is operating.
When `git lfs status` is invoked, we use `git-diff-index(1)` underneath in order to determine what paths in the index have changed, and what the nature of each change is. Unbeknownst to us, `git-diff-index(1)` reports paths in its output from the root of the repository, not relative to the current working directory.
So, this has two downstream effects:
1. When we print the name of a file that has changed in the index, it will be incorrect if we're not in the root of the repository. For this, we use the changes in 3d879fe in order to calculate and display a relative path.
2. If the file is unstaged (i.e., we have to load it …
=> commands/status.go: relative paths outside of root

docs/man/git-lfs-config.5.ronn, lfsapi/lfsapi.go, lfsapi/ssh.go
Certain LFS implementations do not return expires_in (or expires_in) from git-lfs-authenticate yet still enforce the TTL. This causes larger repositories to fail to download the LFS files if the transfer exceeds that TTL and it attempts to use the expired token. This workaround should not be necessary but I expect it's relatively common amongst implementations that support git-lfs-authenticate over SSH. The implementation that this workaround is targeting specifically is Bitbucket Server but likely affects Bitbucket Cloud as well as it is also missing the expires_in field. GitHub correctly includes the TTL which is expected as it is the reference implementation.
I understand it's not ideal to include workarounds for certain implementations but it does resolve it for Bitbucket and I cannot …
=> Support default TTL for authentication tokens acquired via SSH

commands/command_ls_files.go, fs/fs.go, fs/fs_test.go, test/test-ls-files.sh
`git lfs ls-files` lists uncommited files containing escaped runes in their pathname as **not added** even if they  will be added on commit.
````sh
git add "foo/*"
git status 
new file:   "foo/Pr\303\244sentation.txt"
new file:   foo/Regularname
git lfs ls-files
70f78f04ee - "foo/Pr\303\244sentation.txt"   <-- Error! File should be marked with * like 'Regularname
ae32d82ae1 * foo/Regularname
git commit
git lfs ls-files
70f78f04ee * foo/Präsentation.pdf
ae32d82ae1 * foo/Regularname
````
`os.Stat(path)` in `commands/command_ls_files.go(114)` does not find files when the path contains escaped runes. For example: "foo/Pr\303\244sentation.txt"
Parse escaped runes and replace with the corresponding byte value.
Check if needed in other places, where `lfs.WrappedPointer.Name` is used to access …
=> Encoded characters in pathnames

lfsapi/ssh.go
Instead of storing the ExpiresAt and ExpiresIn fields as a *time.Time,
and *int, respectively, use a time.Time and int instead.
Later, in the zero-value comparison, change from != nil to != 0 and
time.Time.IsZero(), respectively.
This has the effect of ridding the API of setting expires_in to zero,
and will fall-back to the default expiration offset, after which it will
retry, or fail the underlying request. We don't have precise
determinations on how many API requests this will affect, but it's
certainly not common usage of the specification, so the behavior change
is OK.
##
=> lfsapi/ssh.go: use zero-value sentinels

script/cibuild, test/test-ls-files.sh
This test exhibits a known failure due to the filesystem's handling of
non-ASCII characters on CircleCI.
It passes locally on macOS 10.14, as well as on our other CI providers,
so it should be OK to skip this for now on CircleCI only.
##
=> test/test-ls-files.sh: skip on CircleCI

config/config.go
In the internal function loadGitDirs, Git LFS will attempt to resolve
the working and dotgit directory by calling 'git rev-parse --git-dir
--show-top-level'.
This information is used in the output of 'git lfs env', which displays
information about the system- and repository-level configuration as it
pertains to Git LFS.
However, when 'git lfs env' is called outside of the repository, any
information that is repository-specific is left blank. For example,
$ git lfs env
git-lfs/2.4.0 (GitHub; darwin amd64; go 1.10.3)
git version: 2.18.0
LocalWorkingDir=
We ``silence'' the error coming from 'git-rev-parse(1)' in loadGitDirs
by looking for the string "Not a git repository". If we found that
string, we don't show the error message on STDERR (because it is OK not
to), but if we fail to find …
=> config/config.go: case-insensitive error search

commands/command_migrate.go, commands/command_migrate_export.go, docs/man/git-lfs-migrate.1.ronn, git/githistory/rewriter.go, git/odb/blob.go, lfs/gitscanner.go, lfs/gitscanner_refs.go, test/test-migrate-export.sh, test/test-migrate-fixtures.sh, test/testhelpers.sh
This PR implements a `migrate export` subcommand as described in #3057. The command requires a list of patterns specified with the `--include` argument and will convert any pointers matching those patterns from a Git LFS pointer to a regular Git object. Any objects that don't already exist in the cache will be downloaded before history is rewritten using the transfer queue.
I wanted to get this PR up for review now before it gets too large. I'm planning on a few more changes in subsequent PRs after this gets merged:
* Documentation
* Pruning the cache of unreachable objects
* Smarter modification of `.gitattributes` files
=> Implement `migrate export` subcommand

lfs/gitfilter_smudge.go, test/test-checkout.sh, test/testhelpers.sh
This pull request teaches the deprecated `git lfs checkout` command to
be able to checkout read-only files in the working copy.
If a file tracked with Git LFS is locked, it will not have the writing
bit unless the user themselves holds the lock. In the former case, if a
user wants to check out a locked Git LFS file--provided that they will
not push a changed version of that file--they should be allowed to check
that file out.
To do so, let's recognize when a file is marked as read-only,
temporarily grant it writing permissions, and then restore the original
permissions once we're done.
Closes: https://github.com/git-lfs/git-lfs/issues/3102.
##
=> commands/checkout: checkout over read-only files

config/config.go, fs/fs.go, test/test-alternates.sh, test/testhelpers.sh
The Git documentation also mentions that the
"$GIT_ALTERNATE_OBJECT_DIRECTORIES" environment variable is a valid way
to configure object database remotes [1]:
2. You could be using the `objects/info/alternates` or
`$GIT_ALTERNATE_OBJECT_DIRECTORIES` mechanisms to borrow objects
from other object stores.
Let's support the same by using the last commit, taking in a handle on
the operating-system configuration and using that in addition to the
list found in .git/objects/info/alternates.
[1]: https://git-scm.com/docs/gitrepository-layout#gitrepository-layout-objectsinfoalternates
=> fs/fs.go: support alternates from environment variable

config/git_fetcher.go
In config/git_fetcher.go, we have special rules to mark certain Git
configuration keys as safe or unsafe.
Particularly, we apply these rules strictly to all values fetched from
the repository-local .lfsconfig, since it is distributed to all fetchers
of a repository and provides a widely available attack-vector.
Therefore, we only allow a tiny subset of all keys via the keyIsUnsafe
function and safeKeys slice.
The 'lfs.allowincompletepush' configuration determines whether or not a
user should be allowed to push a repository that has missing LFS objects
to a remote.
Previously, it was ignored with the following message:
$ git push repo_clone repo_orig_master
WARNING: These unsafe lfsconfig keys were ignored:
lfs.allowincompletepush
In [1], Lars changed the default from 'true' to 'false'. In …
=> config/git_fetcher.go: mark 'lfs.allowincompletepush' as safe

lfsapi/creds.go, test/test-askpass.sh
When creds have already been provided to git (i.e. through a
git URL), use those instead of querying the askpass program
Closes #2894
=> lfsapi: don't query askpass for given creds

commands/command_migrate.go, docs/man/git-lfs-migrate.1.ronn, test/test-migrate-fixtures.sh, test/test-migrate-import.sh
In [1] and [2], callers of the 'git lfs migrate' command were surprised
when `--everything` did not migrate over everything, as its name
implies.
In the documentation, we specified that `--everything` applies only to
local references, as the default behavior of 'git lfs migrate' is to
never require a force-push unless asked to do so explicitly.
--everything sounds dangerous enough that it would imply that a user
wants _everything_ in their repository migrated. So, let's loosen the
requirement and make it mean that.
Alternatively, we could change the meaning of `--everything` in this
fashion and replace it with `--everything-local`. We could also
introduce `--force`, leave the meaning of `--evrything` unchanged, and
only exhibit this behavior with `--everything --force`. Both of these …
=> commands/command_migrate.go: loosen meaning of '--everything'

commands/command_push.go, config/config.go, test/test-push.sh
This PR updates pushCommand to set the `pushRemote` instead of the `remote` using the arguments passed on the command line. This ensures the provided remote will take precedence over what's in the configuration.
Closes #3133
=> Ensure provided remote takes precedence over configured pushRemote

README.md
See https://github.com/git-for-windows/build-extra/pull/110
=> README.md: Git for Windows ships LFS by default

commands/command_env.go, config/config.go, t/t-env.sh, t/t-pull.sh
Previously, origin was being explicitly excluded from the list
of remotes. This could cause the wrong remote to be used in some
cases, such as with `git lfs pull`, and for the `origin` remote to
be missed in `git lfs env`. This commit ensures that the remote
list has the correct contents, and that `git lfs pull` and
`git lfs env` now function as expected.
Closes #2915
=> config: add origin to remote list

Makefile
When building Git LFS v2.5.0, we noticed that the resource.syso was
unchanged between builds and thus retained the old version information
found in 'master' before v2.5.0.
Hence we built binaries in bin/git-lfs.exe with a commit tagged
'v2.5.0', but a version info indicating that the binary was of the
v2.4.0-era.
Let's list out the dependencies of 'resource.syso' explicitly, and thus
rebuild it when any of those change. In particular, it is unlikely the
installer icons. But, if we change the version information during a
release in versioninfo.json, we should update the resource.syso file
accordingly.
##
=> Makefile: list prerequisites for resource.syso

Makefile
This pull request silences some of the output that we have been generating in our newly minted Makefile.
The rationale for each silencing is described in depth in the patches below, but the overarching concern is that the verbosity of both the `go list` and `goimports` command-line invocation does not ever provide useful information to the caller, who is primarily interested in the `go build` invocation instead.
Therefore, let's get rid of each of them and make the `make` output a little cleaner:
```ShellSession
$ make
GOOS= GOARCH= go build -ldflags=" -X github.com/git-lfs/git-lfs/config.GitCommit=1f6d3a7f -s -w " -gcflags=" " -o ./bin/git-lfs ./git-lfs.go
```
##
=> Makefile: silence some output

docs/man/git-lfs-config.5.ronn, errors/types.go, lfsapi/errors.go, t/t-content-type.sh, t/t-push-failures-remote.sh, tq/basic_upload.go, tq/transfer_queue.go
This pull request makes the `Content-Type` detection introduced in #3137 disable-able, thus allowing uploads on implementations that don't support non-octet-stream headers.
Closes: https://github.com/git-lfs/git-lfs/issues/3158.
##
=> tq: make Content-Type detection disable-able

docs/man/mangen.go
This pull request changes the behavior of docs/man/mangen.go to not show any non-fatal output unless `--verbose` is given.
While merging #3160, I noticed that this program can be quite noisy when run normally. These patches make things a little quieter, while still retaining information that might be important, like failing to open a file, or otherwise.
##
=> docs/man/mangen.go: don't show non-fatal output without --verbose

commands/command_track.go, t/t-track.sh, t/t-untrack.sh
=> Properly `lfs track` files with escaped characters in their name - fixes #3189 

locking/lockable.go, t/t-lock.sh, tools/filetools.go, tools/filetools_test.go
This pull request teaches `git lfs lock` to continue to manage lockable files after they have been ignored by a repository's `.gitignore`.
The rationale for this issue arrises from https://github.com/git-lfs/git-lfs/issues/3183, and is explained further in a727fea2 (locking: remove write permission for ignored files, 2018-08-20).
```ShellSession
$ printf "a.txt" > a.txt
$ git lfs track --lockable "*.txt"
Tracking "*.txt"
$ git add .gitattributes a.txt
$ git commit -m ".gitattributes: track 'a.txt' as lockable"
[master (root-commit) e05e353] .gitattributes: track 'a.txt' as lockable
2 files changed, 4 insertions(+)
create mode 100644 .gitattributes
create mode 100644 a.txt
$ rm -f a.txt && git checkout a.txt
$ ls -l a.txt
-r--r--r--  1 ttaylorr  staff  5 Aug 20 07:53 a.txt
$ echo "a.txt" > …
```
=> locks: manage write permissions of ignored files

.travis.yml, appveyor.yml
Per [1], we would like to build Git LFS on Go version 1.11, following
testing over several weeks. As is done in [2], let's upgrade the version
of Go used in continuous integration (particularly on AppVeyor and
CircleCI) to match.
Since Chocolatey has not yet shipped Go 1.11 on their default channel,
we'll continue to download the binary ourselves manually. Once the
desired version of Go is available, this should be upgraded, too.
Notably, this change does not include Go Module support (as introduced
in version 1.11), so the value for $GO111MODULE is left unset, as to
avoid breaking existing checkouts of Git LFS that reside in a $GOPATH. A
subsequent change will introduce Go Module support, at which point
existing check-outs of Git LFS will need to be relocated.
##
[1]: …
=> all: use Go 1.11 in CI

Makefile
It'd be great to have linux arm64 builds available. This is about as far as I'm able to get I think. I've added the targets for other oses so that if/when go supports them all that is needed is to add to BUILD/RELEASE targets. This'll bring up the question of how to test before making said release. I don't have an easy answer for that. I think shippable has support for arm builders, but that'd bring the ci services up to 4 (if true) which seems like a pain.
The TAR_XFORM stuff maybe doesn't belong in the PR, let me know if you'd like me to drop it. I also thought about using `bsdtar` instead of `tar` which would be fine, but I don't know if that's available on the machines normally used to make releases so opted to not break your stuff.
=> Add build and releases for linux arm64

commands/commands.go, config/config.go, t/t-install-custom-hooks-path.sh, tools/filetools.go, tools/filetools_test.go
This pull request expands the value of `core.hooksPath` as read from the Git configuration, before it is evaluate by `git lfs install`.
In practice, this makes it possible to do `git config core.hooksPath ~/path/to/hooks`, and Git LFS will properly look inside `/path/to/hooks` from within `$HOME`. It also supports incantations such as `~user/path/to/hooks`.
Closes: https://github.com/git-lfs/git-lfs/issues/3211.
##
/cc @ktchen14 https://github.com/git-lfs/git-lfs/issues/3211
=> config: expand core.hooksPath

go.mod, go.sum, vendor/github.com/git-lfs/wildmatch/.travis.yml, vendor/github.com/git-lfs/wildmatch/go.mod, vendor/modules.txt
In order to prefer semantically versioned tags of our dependent
repositories over Go's date & SHA-1 format, let's tag
github.com/git-lfs/wildmatch.git at v1.0.0 (on the latest master) and
vendor it as such here.
The only change between b31c34466d64 and v1.0.0 is:
* 83d2acb (Merge pull request #9 from git-lfs/ttaylorr/go-1.11,
2018-08-31)
* 2f71dd1 (.travis.yml: build on Go 1.11, 2018-08-30)
* 4bab7d7 (go.mod: initial commit, 2018-08-30)
Which is the introduction of the go.mod file (and related changes).
Thus, there are no code changes between the two, so this is a safe
change to make.
##
=> go.mod: pin github.com/git-lfs/wildmatch to v1.0.0

lfs/gitscanner_log.go, lfsapi/auth_test.go
There are a few misformatted files in the repository.  Run these files through gofmt to reduce diff noise for future developers.
=> Tidy misformatted files

lfsapi/ssh.go, lfsapi/ssh_test.go, tools/str_tools.go, tools/str_tools_test.go
Git documents that the `GIT_SSH_COMMAND` environment variable is passed to the shell, but we're not currently doing that.  This commit fixes it so that we do pass the contents of that variable to the shell with appropriate escaping, if necessary.
This fixes #3136 and probably will fix #3131 as well.
=> Pass GIT_SSH_COMMAND to the shell

lfsapi/endpoint.go, lfsapi/endpoint_finder_test.go
Remotes with custom ssh ports look like this in .git/config:
[remote "origin"]
url = [git@example.com:2323]:path/to.git
Strip the brackets from the URL parts to support those URLs.
=> Treat [host:port]:path URLs correctly

t/Makefile
This pull request makes `t/t-*.sh` targets `.PHONY`, so that we can repeatedly invoke them as `make t-*.sh` without having to pass `-B`.
##
=> t: mark test sources as .PHONY

commands/command_migrate_import.go, t/t-migrate-import.sh
When migrating a repository to use Git LFS for the first time, a user is
also required to run 'git lfs install' inside of their newly-migrated
repository, lest they are unable to push.
This is due to the fact that 'git lfs install' writes
.git/hooks/pre-push, which Git invokes, in turn invoking Git LFS to push
Git LFS objects to the remote before sending Git objects.
Without this, we will push only plain-text pointer files, which puts the
pusher at risk of loosing data, or failing any provider-specific
verification/integrity checks.
So, let's run installHooks() to place hooks in the right place, which
makes the following command sequence possible:
$ git lfs migrate import ...
$ git push --all
Let's avoid running this in 'git lfs migrate info' and 'git lfs migrate
export', since neither …
=> commands/command_migrate_import.go: install hooks

README.md
This pull request introduces two new core team members to the Git LFS group: @bk2204 and @PastelMobileSuit.
@PastelMobileSuit and @bk2204 have both joined GitHub in recent months and are working on Git LFS as a part of their job there. They have made excellent contributions to Git LFS thus far, and I am excited that they will continue to do so.
So, please, help me welcome these two fine folks to the team!
##
=> README.md: new core team members

lfsapi/endpoint_finder.go, lfsapi/endpoint_finder_test.go, t/t-config.sh
It's very common for a user to specify an SSH remote that refers to an
alias in their gitconfig file.  For example, if a user must use
different SSH keys when pushing to different remotes, setting different
aliases that use those different keys is the simplest and easiest way to
accomplish that goal.
Unfortunately, our parsing logic was broken for SSH remotes that used
bare SSH URLs (that is, without “ssh://”) with a hostname or alias, but
without a username component.  The URL parser we used saw the hostname
portion as the scheme of a URL, and we passed through any URLs with
unknown schemes.  This led to a failure to push, since we misparsed the
URL as a non-SSH URL and gave up when it also didn't look like an
HTTP(S) URL.
If we get an unknown “scheme” when parsing a URL, check if the …
=> lfsapi: handle SSH hostnames and aliases without users

lfsapi/ssh.go, lfsapi/ssh_test.go
Git has support for specifying `core.sshCommand` in the configuration file.  Teach git-lfs support for that command, too, and ensure that it’s passed to the shell as documented.
This should fix #2215.
=> Add support for core.sshCommand

t/cmd/lfstest-customadapter.go
The custom adapter test binary wraps the HTTP API client and returns
various responses from the HTTP response to the custom transfer adapter.
This code assumes that if an error occurs, we will always have a valid
HTTP response object, but this is not the case.  If we lack such an
object, we will get a nil pointer dereference, a panic, and a segfault
in the client, causing the test to fail.
While it's currently unknown how to reproduce this issue, it has been
seen on the CI servers.  In order to improve the reliability of the
test, check to see if the response object is non-nil before
dereferencing it and produce a different but distinct error code if it
is nil.
=> t: avoid panic in lfstest-customadapter

git/gitattr/attr.go, git/gitattr/attr_test.go
This pull request teaches package `git/gitattr` to parse attributes that are "set", as in writing the attribute name, but giving no explicit value.
The Git documentation says to treat this as implicitly assigning the string "true", which we do as of 5a54097.
Previously, for example, when encountering a `.gitattributes` containing the contents:
```
*.txt filter=lfs text
```
We would crash, complaining that `text` by itself is an improper attribute. With this change applied, this is no longer the case.
Closes: https://github.com/git-lfs/git-lfs/issues/3254.
##
/cc @jackknobel, https://github.com/git-lfs/git-lfs/issues/3254
=> git/gitattr: parse 'set' attributes

CHANGELOG.md, commands/command_track.go, config/version.go, debian/changelog, lfsapi/endpoint.go, lfsapi/endpoint_finder_test.go, rpm/SPECS/git-lfs.spec, script/packagecloud.rb, t/t-content-type.sh, t/t-track.sh, t/t-untrack.sh, tq/basic_upload.go, versioninfo.json
This pull request provides an in-progress look at our next release, Git LFS v2.5.2, anticipated to land September 17, 2018.
We're publishing these changes early so that people on @git-lfs/implementers can take a look and make sure that everything is working as expected before the aforementioned date. In particular, we'd love to know that (after running `git config lfs.contentType false`) Git LFS users are able to push to the host that you represent/maintain.
Here are some advance-copy builds based on the tip of this branch (at the time: 6169805f (release: v2.5.2, 2018-09-05)):
[git-lfs-darwin-386-v2.5.2-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/2354134/git-lfs-darwin-386-v2.5.2-pre.tar.gz)
[git-lfs-darwin-amd64-v2.5.2-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/2354135/ …
=> release: v2.5.2

Makefile, t/testenv.sh
When making a complex change to Git LFS (or any other project), it is
common to write a multiple patch series.  When doing so, it's ideal to
ensure that each patch is logical and independent and that the tests
pass at each step.  Often this is done using "git rebase -x" to run the
testsuite at each step.
Make the testsuite able to be run under "git rebase -x" by unsetting
environment variables that cause the tests to fail or to operate on the
git-lfs repository itself.  In the Makefile, use a subshell with unset
because env -u is not in POSIX and is supported by neither NetBSD nor
OpenBSD.
=> t: make testsuite run under git rebase -x

docs/howto/release-git-lfs.md
This pull request takes the long-overdue step of documenting our release process in a public fashion, so that others can release Git LFS, too.
##
=> docs/howto: document our release process

lfsapi/creds.go, t/cmd/git-credential-lfstest.go, t/t-pre-push.sh, t/t-push.sh, t/testlib.sh
These are a bunch of small improvements to make troubleshooting credential-related CI failures easier.  The only user-visible change is to pass standard error through when filling credentials to make sure that we get log output from the credential helper.  This should be a net positive altogether, since it's the same behavior that Git has.
In addition, there are changes to make getting debugging output from successful tests easier and to make the lfstest credential helper log all of its operations.  Each change should be self-explanatory.
If someone has a suggestion for a better name for the environment variable in the final commit, I'm all ears.
=> CI improvements

debian/prerm
I was wondering why my ~/.gitconfig would sometimes end up being owned
by root, with 0600 permissions, making git unable to read it and thus
interfering with my normal workflow. Looking at the mtime/ctime of
.gitconfig, I finally correlated it with
2018-09-20 09:55:47 upgrade git-lfs:amd64 2.5.1 2.5.2
2018-09-20 09:55:47 status half-configured git-lfs:amd64 2.5.1
in my dpkg.log. So while the postinst script does change the global git
config, the prerm script modifies the .gitconfig of whichever user did
the "apt-get upgrade".
=> debian/prerm: add --system flag

docs/howto/release-git-lfs.md
As part of the release process, we should close the release milestone
for the version we're releasing and move other items to a future
milestone.  Add a note about this to the release howto.
=> docs: add note about closing release milestone

commands/command_lock.go
On Windows, the filesystem is typically case insensitive.  We formed the
lock path by stripping off the repo portion from the absolute pathname
using the strings package.  However, if the drive letters of the
absolute pathname and the canonicalized pathname differed in case, then
we would not strip any values off, and instead just concatenate the two
paths together.  Use the filepath.Rel function that's built into Go to
help us make the path relative in a way that is appropriate for the
operating system.
Fixes #3276
=> Canonicalize paths properly on Windows

docs/custom-transfers.md, docs/man/git-lfs-config.5.ronn, lfshttp/ssh.go, subprocess/subprocess.go, subprocess/subprocess_test.go, t/cmd/lfstest-standalonecustomadapter.go, t/t-custom-transfers.sh, tools/str_tools.go, tools/str_tools_test.go, tq/custom.go
This change splits out some helper functions involved in processing items with the shell and moves shell-related handling to the subprocess module to avoid an import loop.  Finally, we pass custom transfer args to the shell to allow the user to specify multiple arguments to the custom transfer adapter.
I will admit that I’m not super excited about the way we have to go about testing the custom transfer adapter arguments, but I haven’t come up with a better way.  Suggestions welcome.
Fixes #3249.
=> Expand custom transfer args by using the shell

Makefile
Due to changes between gzip versions, the source tarballs produced by GitHub may change.  To assist distributors, provide stable generated tarballs as part of the release process.
Fixes #2911.
=> Makefile: build source tarballs for release

commands/command_migrate.go, git/git.go, git/git_test.go, git/githistory/rewriter.go
This pull request fixes a long-standing bug wherein a reference beginning with `refs/remotes/tags` would incorrectly be round-tripped back to Git, causing `git lfs migrate` and others to complain of a reference that does not exist.
Closes: https://github.com/git-lfs/git-lfs/issues/3281.
##
/cc @zezba9000, https://github.com/git-lfs/git-lfs/issues/3281
=> commands: unambiguously resolve remote references

commands/command_checkout.go, commands/pull.go, docs/man/git-lfs-checkout.1.ronn, git/git.go, t/t-checkout.sh
When there's a conflict, it can be difficult to access the various stages of the conflict to view in a suitable diff tool.  Add the `--base`, `--ours`, and `--theirs` options to allow checking out the various stages of a conflict into different paths for easier comparison with various tools.
This fixes #3258.
=> Checkout options for conflicts

docker/README.md, docker/gpg-agent_start.bsh, docs/api/locking.md, docs/linux-build.md, docs/man/git-lfs-update.1.ronn, docs/proposals/locking.md, docs/proposals/transfer_adapters.md, rpm/INSTALL.md, rpm/SPECS/git-lfs-repo-release.spec, rpm/SPECS/ruby.spec, script/cibuild, t/git-lfs-test-server-api/README.md, t/t-post-commit.sh, t/t-track.sh
Trailing whitespace is generally considered undesirable, so clean up the existing uses of it and check for it during CI to help avoid reintroducing it.  We avoid modifying vendored code and Git objects, which are binary.
=> Clean up trailing whitespace

docs/man/git-lfs.1.ronn
The warning you get when you run `git lfs clone` is a bit misleading (see https://github.com/git-lfs/git-lfs/commit/47fa8523cda3582937077b63dd71d33db5390731#r30762174). This will remove the `git lfs clone` command from `man` (see https://github.com/git-lfs/git-lfs/commit/47fa8523cda3582937077b63dd71d33db5390731#r30753241). @PastelMobileSuit could you review this? 🍄
=> Remove `git lfs clone` command from man

commands/command_checkout.go
In 35ba22df ("docs: add --to and related options to docs", 2018-10-02),
we undeprecated the checkout command, but we neglected to remove the
deprecation notice from the binary.  Remove this notice, since the
command is no longer deprecated.
=> commands: undeprecate checkout

commands/command_env.go, lfs/lfs.go, lfsapi/auth.go, lfsapi/auth_test.go, lfsapi/endpoint_finder.go, lfsapi/endpoint_finder_test.go, lfsapi/ntlm_test.go, locking/api.go, t/cmd/lfstest-customadapter.go, t/cmd/lfstest-gitserver.go, t/t-credentials.sh, tq/adapterbase.go, tq/api.go, tq/basic_download.go, tq/basic_upload.go, tq/transfer_queue.go, tq/verify.go, tq/verify_test.go
This PR moves the responsibility to determine the URL Access Mode out of `DoWithAuth()` and into the hands of the caller. This removes our built-in assumption that all requests will be made against the LFS API endpoint, and allows other endpoints to be used for the access mode.
The transfer adapters generally don't make requests against the LFS API endpoint, generally making requests against a storage endpoint instead. This change means that requests coming from the transfer queue will now use that storage endpoint to determine the URL Access Mode instead of the LFS API endpoint.
This PR ended up being more complicated than expected, so there's a fair number of commits here. I've tried to commit atomic changes with descriptive commit messages, so I think it makes sense to review this one …
=> lfsapi/tq: Have DoWithAuth() caller determine URL Access Mode

.travis.yml, appveyor.yml
The latest release of Go, 1.11.1 was just published earlier today (on 2
October, 2018).
In the spirit of staying up-to-date with the latest version of Go (see
[1]), let's make sure that we continue to build correctly, even with the
very latest version.
[1] moved the tip to Go 1.11, so there shouldn't be anything surprising
here.
[1]: 074a2d4f (all: use Go 1.11 in CI, 2018-08-28)
##
=> all: use Go 1.11.1 in CI

commands/command_ls_files.go, docs/man/git-lfs-ls-files.1.ronn, t/t-ls-files.sh
Some users just want to have the list of LFS files. This is particularly useful when you want to programatically scan the working tree and would like to avoid additional parsing
=> Support listing only filename tracked by git lfs using --name (-n) option

config/config.go, config/config_test.go, config/util_nix.go, config/util_windows.go, lfs/extension.go, lfs/gitfilter_clean.go, lfs/util.go, t/t-umask.sh
When writing files into the repository LFS object store, Git LFS uses a temporary file and then renames it into place.  For security reasons, temporary files are created with 600 permissions; however, this causes problems in repositories accessed by multiple users, since neither the umask nor `core.sharedRepository` are honored.
This series introduces support for umask and `core.sharedRepository` into Git LFS.
This fixes #2015 and also fixes #2992.
=> Honor umask and core.sharedRepository

docs/proposals/ssh_adapter.md
There has been a significant amount of interest in a purely SSH-based protocol for Git LFS.  Add a proposal for an SSH-based protocol based on Git's pkt-line and protocol v2, while still mapping cleanly onto HTTP for ease of implementation on the server-side.  Implementers will likely have all of this machinery (either now or in the future) available, so this should be fairly easy to implement.
This is merely a proposal, not a commitment to implement.  Implementers who prefer to use HTTP may continue to do so.  Not specified yet is a technique to discover the SSH-based protocol, although it will probably be overloaded onto `git-lfs-authenticate`.
Comments and suggestions welcome.
/cc #1044
=> RFC: SSH protocol

commands/command_migrate_import.go, config/config.go, config/config_test.go, t/t-migrate-import-no-rewrite.sh
We accidentally wrote ill-formed commit headers when writing commits for `git lfs migrate import --no-rewrite` because the author and committer fields lacked timestamps.  In addition, we could write empty email addresses if the user did not have a `user.email` field set but instead used the `EMAIL` environment variable to set their email.
Correct both of these issues and honor the distinction between author and committer.  Note that due to limitations of the Go standard library, this series does not honor `GIT_AUTHOR_DATE` and `GIT_COMMITTER_DATE` even though it honors the name- and email-related environment variables; this will be tracked in #3312.
This fixes #3310.
=> Ensure correct syntax for commit headers in lfs migrate import

config/config.go, config/config_test.go
Git can use these environment variables to take a date for creating
commits.  Teach Git LFS these variables as well.
Note that because Go's time library doesn't parse Unix timestamps, we
need to parse Git's native format ourselves.
Fixes #3312.
=> config: honor GIT_AUTHOR_DATE and GIT_COMMITTER_DATE

CONTRIBUTING.md
This pull request compiles a few miscellaneous changes that I've been sitting on for the `CONTRIBUTING.md` document, that I had mentioned (and was reminded of) in https://github.com/git-lfs/git-lfs/pull/3317#pullrequestreview-165288499.
##
=> CONTRIBUTING.md: :nail_care:

commands/command_uninstall.go, docs/man/git-lfs-uninstall.1.ronn, t/t-uninstall.sh
This series introduces a set of improvements to `git lfs uninstall`.  First, the `--system` option is documented.  Second, we print a more accurate message about which configuration is modified when the `--system` option is provided.  Finally, we add a `--skip-repo` option for parallelism with `git lfs install`.
I will admit that there is some slight duplication in 5541da6, but I was unable to find an elegant way to avoid it.
This series fixes #3322, fixes #3323, and fixes #3324.
=> Uninstall improvements

commands/command_track.go, docs/man/git-lfs-track.1.ronn, git/attribs.go, t/t-track.sh
Currently, if a user has disabled Git LFS for a pattern in a .gitattributes file (such as in a subdirectory) by writing "-filter=lfs", we render the pattern as a tracked pattern in "git lfs track", even though those paths are not enabled for Git LFS.
Improve this situation by listing excluded patterns as well as tracked patterns.  Compute whether a pattern is excluded by looking for an attribute entry that starts with "-filter" and if so, list the entry as excluded.  Add tests for both the "-filter" and "-filter=lfs" situations.
Fix #2442.
=> commands: list explicitly excluded patterns separately

docs/man/git-lfs-migrate.1.ronn
Fix formatting of the INCLUDE AND EXCLUDE (REFS) reference chart and the results to properly display newlines in Github Markdown
=> Fix formatting of INCLUDE AND EXCLUDE (REFS)

tools/humanize/humanize.go, tools/humanize/humanize_test.go
On Windows, occasionally:
```
t := time.Now()
...
humanize.FormatByteRate(size, time.Since(t))
```
will result in time.Since returning 0. This commit clamps the duration to be at least 1 nanosecond.
=> Fix humanize's FormatByteRate() to work with 0s duration

lfs/lfs.go, tq/adapterbase.go
When something goes wrong, many users will happily provide output using
GIT_TRACE and GIT_CURL_VERBOSE.  This is very useful for Git, but Git
LFS doesn't honor the latter (since we don't use libcurl).  Instead, we
require users to set GIT_TRANSFER_TRACE.  This makes for a prolonged and
more difficult debugging experience.
Despite the fact that we don't use libcurl, honor the GIT_CURL_VERBOSE
flag and act as if the user had set GIT_TRANSFER_TRACE instead.  This
honors the intent of what the user wanted (transfer-related debugging
information) and makes debugging easier for end users and maintainers
alike.
=> tq: enable transfer debugging when GIT_CURL_VERBOSE is set

git/config.go, git/config_test.go, lfsapi/auth_test.go
I noticed that something in the testsuite was writing test entries into my `.git/config`.  I at first thought it was the integration tests, but then realized it was actually the unit tests.  We write certain entries of the form `lfs.*.access = basic` into `.git/config` in the tests for the `lfsapi` module via a call to the endpoint code.
This series introduces a new read-only config object which rejects any attempts to write to a configuration file with an error.  Fortuitously, the endpoint code ignores the return value from this attempt, meaning that we silently do nothing.  Ignoring any errors happens to be fine in this code, because we're setting a setting that we've just intuited other ways, so if the write fails for some other reason, we're no worse off.
With this change, running …
=> Keep the testsuite from writing into .git/config

lfsapi/endpoint_finder.go, lfsapi/endpoint_finder_test.go
Git understands how to specify aliases that differ between fetch and pull by using `pushInsteadOf` aliases.  This series introduces support for this type of alias in Git LFS so that we can authenticate to the right endpoint when performing a push, as the user intended.
The first patch updates various callers; the second and third patches split out functions and should have no functional changes. The fourth patch introduces the new alias support.  Note that we use the same mutex for protecting all the aliases since there's no reason to distinguish between them.
This fixes #2433.
=> Support pushInsteadOf aliases when determining endpoints

docker/run_dockers.bsh
On Linux, lookup of user information such as the home directory is
handled by the name service switch in libc.  This allows administrators
to use the mechanism of their choice (such as LDAP) for enumerating
users.  Go normally doesn't use libc on Linux, but it does when looking
up information for users, so that programs written in Go handle these
operations like other (non-Go) programs on the system do.
When our build containers run the integration testsuite on i386 Linux,
we don't actually have a 32-bit copy of libc available.  Therefore, we
must be sure not to rely on behavior that needs it, such as the name
service switch.  Our tests want to look up the user's home directory so
that we can expand the core.hooksPath variable, but we also need the
user's name in order to do that.  We …
=> Set USER environment variable in build containers

filepathfilter/filepathfilter.go, t/t-checkout.sh
The file path filter can mark a file as either accepted or rejected. However, one of the messages that says that a file was rejected is in the main code path, and is therefore always executed, even if the file is actually accepted.  This leads to contradictory messages and noisier output.
Ensure that we indicate that a file is rejected by the filter only if it is indeed rejected; otherwise, say only that it is accepted.
=> filepathfilter: don't say file is both accepted and rejected

t/Makefile, t/git-lfs-test-server-api/main.go, t/git-lfs-test-server-api/testupload.go
@Foxboron recently noticed that our server API test program didn't function in the way we expected.  It first of all didn't compile due to several refactors, and then even when fixed, it didn't pass.
This series fixes the code so that it builds, builds it as part of the integration test series to ensure we don't break it again, and fixes the reversed condition that causes it to fail.  I am fairly confident that the last patch is indeed correct, but some :eyes: on that part would be helpful.
This series fixes #3372.
=> Fix test server API

commands/command_locks.go, commands/command_unlock.go, docs/man/git-lfs-locks.1.ronn, locking/locks.go, locking/locks_test.go
.git/lfs/cache/locks stores the JSON response that we got from the remote verbatim and will be updated when "git lfs locks" is issued
Partially fixes https://github.com/git-lfs/git-lfs/issues/3107
=> locking: cache JSON response from server

commands/command_status.go, commands/commands.go, docs/man/git-lfs-status.1.ronn, t/t-status.sh
'git lfs status' is functional in a non-work tree repository only some
of the time. Particularly, when there is nothing to report (and
therefore no files to open), 'git lfs status' work as expected.
However, when there are files changed in the index, Git LFS tries to
open them to see what their hash was before/after the change, and in
particular, if they are/were/remain Git LFS pointers. This feature is
used to power the "Git <sha-1> -> LFS <sha-256>" output of 'git lfs
status'.
When in a bare repository and in the aforementioned scenario, the above
operation will fail to open a file that does not exist, for the
repository is bare and thus does not contain a working tree.
In order to bring about a more consistent experience when using 'git lfs
status', let's match the behavior upstream …
=> commands/command_status.go: require a working copy

commands/command_status.go, go.mod, go.sum, lfs/gitscanner_tree.go, t/t-fetch.sh, vendor/github.com/git-lfs/gitobj/backend.go, vendor/github.com/git-lfs/gitobj/object_db.go, vendor/modules.txt
When a repository is cloned with --shared or --reference, it contains an alternates file with references to other repositories.  Because earlier versions of `gitobj` did not read from alternate repositories, the object scanner could finish early.  When it did so, we tried to read the error from the treeblob scanner, but there was none, and the channel would remain open since the treeblob scanner was not yet finished providing data.  Since we no longer read data from the treeblob scanner, we would deadlock, with the object scanner waiting to read the treeblob scanner's error channel and the treeblob scanner waiting to write to the now-full data channel.
Fix this by updating to a fixed `gitobj` version to avoid an early return from the object scanner and avoiding deadlock by not waiting on …
=> Avoid hang in repos cloned with --shared or --reference

docs/man/git-lfs-config.5.ronn
The documentation suggests using .lfsconfig in the repository root for configuration keys.  Only a small number of keys can be set in this file for security reasons, but we don't mention this until the end of the file, which means that users often don't notice this fact, leading to confusion when it doesn't work.
Instead, suggest primarily using the Git configuration files for storing this data, since that will always work.  State that users can use .lfsconfig, but tell them up front that it is restricted to a small number of keys, and point them farther down the page where they can find that information.  Indicate to users that this restriction is for security reasons to help them better understand the rationale.
=> docs/man: suggest using Git configuration for LFS keys

commands/uploader.go
When attempting a push, we need to ensure that we have every object we want to push.  The object scanner produces pointer objects that contain the object ID of the object we want to push plus the path at which the scanner found the object.  Before pushing, we iterate over every object we want to push and if the object is not found in the LFS object store, we attempt to read the file that is at the path in question to try to create the object.
If that attempt fails since the file is no longer present (i.e., it was present in a previous revision but has since been deleted), we produce an error message that the file could not be opened without any context, causing the user to be confused as to why we would have attempted to open a file that has since been deleted.  Improve this error message …
=> Improve error message on missing object

docs/man/git-lfs-config.5.ronn
The follow-up of #3414.
I went through the whitelisted keys and found out that the doc is outdated a bit.
=> Update the doc of whitelisted .lfsconfig keys

commands/command_checkout.go, commands/command_fsck.go, commands/command_pull.go, commands/commands.go, commands/run.go, config/config.go, config/config_test.go, fs/fs.go, fs/fs_test.go, lfs/gitfilter_smudge.go, lfs/hook.go, lfs/util.go, locking/locks.go, locking/locks_test.go, t/cmd/util/testutils.go, t/git-lfs-test-server-api/main.go, t/t-umask.sh, tools/filetools.go, tools/filetools_test.go, tools/umask_nix.go, tools/umask_windows.go, tq/basic_download.go, tq/basic_upload.go, tq/meter.go
In de1954d6384c27c63f96e9002a61497f36493fb7, we taught Git LFS how to deal with core.sharedRepository. However, in doing so, we only taught it about files, and not directories. This causes problems not only for clones, but for many situations, since we create directories on demand.
Add a new function that creates directories with the permissions specified in `core.sharedRepository` and use it throughout the codebase where we need to create a directory.
This fixes #3407.
=> core.sharedRepository improvements for directories

lfs/pointer.go
When parsing pointers, we parsed the size of the object using ParseInt with a third argument of 0. This caused the argument to be parsed as an int, which on 32-bit systems is 32 bits in size. Consequently, when we had an object larger than 4 GiB in size on a 32-bit system, we would reject the pointer file as invalid and never realize the object needed to be pushed, leading to the server side rejecting our pushes due to missing objects.
Set the size of the integer we're parsing to 64 bits to ensure that we can always parse a pointer correctly. With this change, we can handle files larger than 4 GiB on 32-bit binaries.
I have opted not to add a test to this case because the processing time to hash a 4 GiB file is significant and the test would be fairly slow, but if people feel strongly …
=> Ensure 32-bit Git LFS binaries can handle files larger than 4 GiB

Makefile
When building binaries, Go embeds the source filenames into the binaries, meaning that on most systems, the build directory is embedded into the binary. This means that binaries are not reproducible when built by other users and in addition that the layout of the building user's system is embedded into the binary.
Go provides an option to trim paths out of the ones stored in the binary, but unfortunately this only works for one path, and since git-lfs is now built outside the GOPATH to take advantage of modules, there are two paths that need to be stripped.
For the benefit of build reproducibility and general build hygiene, let's strip out the user's home directory when building the binary. This is better than the status quo, and we can improve this later if circumstances change.
=> Trim embedded paths out of binaries

errors/types.go, lfshttp/errors.go, t/cmd/lfstest-gitserver.go, t/t-batch-retries-ratelimit.sh, tq/basic_download.go, tq/basic_upload.go, tq/transfer_queue.go
Fixes #3122 
This pull request introduces a new type of error which contains information regarding "Retry-After" header when a rate limit is hit. The error then behaves similar to the is-retriable error, except that this doesn't get re-added to the queue immediately, but rather waits until the time is up.
To test this I modified the git-lfs/lfs-test-server server to rate limit requests (maybe I can clean this up and make a PR for this as well), though I guess some automatic test would be needed. What would you suggest for this?
=> Add support for retries with delays (ex. rate limiting)

commands/command_migrate_info.go, t/fixtures/migrate.sh, t/t-migrate-info.sh
Fixes #3453
It seems like to fix this, the the name to group the collection of file sizes should fall back to the file name if no extension exists. This leads to output that looks like this:
```
large5noext	315 MB	  1/1 files(s)	100%
*.c        	315 MB	  1/1 files(s)	100%
*.go       	98 KB 	11/11 files(s)	100%
LICENSE    	35 KB 	  1/1 files(s)	100%
*.sed      	25 KB 	45/45 files(s)	100%
=> Modify logic of 'migrate info' to process extensionless files

docs/man/git-lfs-migrate.1.ronn
When invoking `git lfs migrate --no-rewrite`, we take a list of files, not a list of patterns. This differs from other situations, and the examples in the man page don't make this clear, resulting in confusion on the part of users. Improve the example by making the example commit message explain the situation a bit better.
Fixes #3421.
/cc @bitinn
=> docs/man/git-lfs-migrate: make examples less confusing

commands/command_env.go, t/t-env.sh
When we attempt to look up an endpoint to push to or pull from a remote, we call the endpoint finder's Endpoint method, which honors lfs.url, not the RemoteEndpoint method, which does not. However, when enumerating remotes in git lfs env, we call RemoteEndpoint, which means we produce the wrong endpoint if the lfs.url option is set.
Update the code to call the correct method, so that we get the correct results. Since the tests check for this case and print the old information (which doesn't match what we actually do), update them as well. Now that we have several tests that produce similar output because they all use lfs.url, update one of the tests to test more useful cases by removing the use of lfs.url.
Fixes #3469.
=> command/env: ensure we honor lfs.url

docs/api/locking.md
On locks listing, the git-lfs client is not querying the `ref` parameter but the `refspec` one. Fix the documentation accordingly.
For reference: https://github.com/git-lfs/git-lfs/blame/84f47a430beb9695ceb8427443f304e091128edd/locking/api.go#156-L157
=> Fix parameter name on List Locks API Documentation

commands/command_prune.go, git/object_scanner.go, go.mod, go.sum, lfs/gitscanner_catfilebatch.go, vendor/golang.org/x/sync/AUTHORS, vendor/golang.org/x/sync/CONTRIBUTORS, vendor/golang.org/x/sync/LICENSE, vendor/golang.org/x/sync/PATENTS, vendor/golang.org/x/sync/semaphore/semaphore.go, vendor/modules.txt
When running `git lfs prune`, we spawn a large number of goroutines, each of which may spawn two processes and consume several file descriptors for the processes' pipes. This means it's very easy for us to run ourselves out of file descriptors, especially if we have a limit set with ulimit.
Use a semaphore to limit the number of processes in use at once, at least until we move the handing of this code in-process in a future commit.
In addition, if we hit this case, report errors.
Finally, close objects to release some additional file descriptors.
This fixes #3403.
=> Fix hang in prune with too few file descriptors

script/packagecloud.rb
Based on PR #2961 this should enable builds for Ubuntu Cosmic.
=> build package for Ubuntu 18.10 aka Cosmic

git-lfs.go, git-lfs_windows.go
On Windows, we want to run `goversioninfo`, which embeds certain version information into Windows binaries. However, despite compiling and running on non-Windows systems, it isn't very useful there. Move the `go:generate` comment into a separate file that's only built on Windows.
This improves the lives of packagers on Debian, where the packaging tools want to run `go generate` by default.
I've confirmed that running `go generate` produces a `resource.syso` file on Windows and does not on macOS.
Fixes #3473.
/cc @ssgelm
=> Run go generate only on Windows

commands/command_status.go, t/t-status.sh
If a had a file (either Git LFS or plain Git) that was deleted with git rm but not yet committed, git lfs status would produce an error indicating that the file could not be opened. Since this is not helpful, if the user has deleted the file, instead indicate this by showing that the behavior to be committed is a file deletion.
Note that we will only traverse this code path when the destination Git hash is all zeros (indicating a deleted or missing file).
=> status: handle deleted files gracefully

lfshttp/client.go
If a redirect occurs, we don't close the HTTP body, forcing us to leave the current connection open and causing us to eventually run out of file handles. Ensure we close the body if we're not using it so that we can reuse the connection, which is both more efficient and nicer to the remote server.
I'm not aware of a good way to test this, although I'm open to suggestions if someone has some.
Fixes #3446.
/cc @snichols and @Socolin, who saw this problem
=> lfshttp: close body on redirect

docs/man/git-lfs-fetch.1.ronn
Since [1], we have remarked that the `--include` and `--exclude` options
belonging to `git-lfs-fetch(1)` were subject to the file matching rules
of package `path/filepath`'s `Match()` implementation.
Since [2], however, this is no longer accurate: the implementation of
`filepathfilter.New()` converts its arguments to wildmatch-style
semantics, which do _not_ follow the rules of the aforementioned
`path/filepath.Match()`, and instead adhere to Git's guidelines.
The relevant call-chain is as follows:
1. `commands/command_fetch.go` calls `buildFilepathFilter`.
2. `buildFilepathFilter` calls `determineIncludeExcludePaths`, and
then calls `filepathfilter.New()`.
3. Finally, `filepathfilter.New()` calls `wildmatch.New()` after doing
some sanitization.
Since the behavior that we are deviating …
=> docs/man: update `git-lfs-fetch(1)` manpage

docs/man/git-lfs-config.5.ronn, locking/lockable.go, locking/locks.go, t/t-lock.sh
In a727fea2 ("locking: remove write permission for ignored files", 2018-08-20), we learned to set and clear the read-only attribute on ignored files that match the lockable pattern, since "git lfs lock" operates on pathspecs, not actual files.
However, in doing so, we caused a regression for people who have ignored files (such as build files) which match the lockable pattern, but should not have their permissions modified.  Since there is no easy way for us to know if the user would like their files modified, add a config option to control this behavior, and leave it at the historical (i.e., pre-a727fea2) default, off.  Add documentation accordingly.
Choosing the historical behavior is compatible with the most existing use cases and preserves the behavior people expect with Git, which is …
=> locking: add flag to control modification of ignored files

Makefile
This patch set include setting `$LDFLAGS` as a default `EXTRA_LD_FLAGS` parameter for supporting system linked flags. `trimpath` is set as a default for `BUILTIN_GC_FLAGS` so we are able to support [reproducible builds](https://reproducible-builds.org/) in the Makefile without any extra additions. Also added support for passing `-asmflags` to `go build` as we have support for `-ldflags` and `-gcflags`. This has the same variable for trimpath set as a default.
I also think enabling PIE by default with `-buildmode=pie` should be considered. However that has caused problems for other projects so it should be up to the developers if they want to support this as a default setting or not.
=> Makefile additions for reproducible builds and asmflags

commands/command_pointer.go, docs/man/git-lfs-pointer.1.ronn, t/t-pointer.sh
We have used the 'git-lfs-pointer(1)' command historically to compare
varying implementation of the Git LFS protocol. This has been done by
passing both `--file` and `--stdin` to the command, which will in turn
compare the contents of both handles and return appropriately whether
they are the same or different.
One use case that Git LFS pointer does not yet support directly is
_checking_ to see whether a given file is a valid Git LFS pointer. This
is a different use-case than before, since we aren't doing any
comparison, we're simply checking whether the official implementation of
Git LFS can parse a given stream as a pointer.
As an aside, one way to do this today is the following:
$ git lfs clean < a.txt | git lfs pointer --stdin --file my.ptr
Where we first generate a pointer of the …
=> commands/command_pointer.go: introduce `--check` option

docs/man/git-lfs-config.5.ronn, docs/man/git-lfs-filter-process.1.ronn, docs/man/git-lfs-smudge.1.ronn
Since its inception in [1], the `GIT_LFS_SKIP_SMUDGE` environment
variable has not been documented. This feature is not meant to be
hidden, so let's document how it works in `git-lfs-config.5` in case
users are interested in it.
Let's write this in `git-lfs-config(5)` since this is where environment
variables that aren't tied to a particular command go. We note its
existence in the related manual pages (e.g., `git-lfs-smudge(1)` and
`git-lfs-filter-process(1)`) but refer to the authoritative source in
`git-lfs-config(5)`.
[1]: 8cd51c00 (rename the options to SKIP_SMUDGE and --skip-smudge,
2015-09-23)
Closes: https://github.com/git-lfs/git-lfs/issues/3505.
##
/cc @mloskot https://github.com/git-lfs/git-lfs/issues/3505
=> docs/man/git-lfs-config.5.ronn: document GIT_LFS_SKIP_SMUDGE

t/t-smudge.sh
In the "smudge with skip" test (i.e., the one that tests using
$GIT_LFS_SKIP_SMUDGE), we unset the variable in the environment, and
then check that it has indeed been removed.
We expect that the 'unset' program will work without issue, so let's
remove the check that ensures it so.
As an additional benefit (and the reason for this change in the first
place) we allow this test to continue to pass even when the latest
commit message mentions the word "GIT_LFS_SKIP_SMUDGE".
On some CI systems, the commit message from HEAD is placed in the
environment variable (e.g., APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED) and
hence causes this test to fail.
##
=> t/t-smudge.sh: remove unnecessary test

.circleci/config.yml
In the latest release of Homebrew (which Circle CI has upgraded to for
us) the command `brew prune` has been removed.
In order to stop failing our Circle CI builds, let's remove this
invocation.
The recommended alternative is to run 'brew cleanup', but this is
unnecessary: Homebrew 2.0 already does this for us, so repeating it here
is unnecessary.
##
=> .circleci: don't use 'brew prune'

Makefile, docker/run_dockers.bsh, docs/howto/release-git-lfs.md, script/changelog, script/update-version, script/upload
Our current release process is highly manual and requires several individual steps to go through. This series is a first step at automating parts of this process.
Included are changes to automate most of the Windows build process, which is an area that has caused us problems in the past, a script to create a GitHub release and upload assets, and a script to bump version numbers.
The entire process is not yet complete, but since this series provides valuable improvements that we can take advantage of now, I thought I'd submit it and let us use parts of it. I've already used the Windows build process to great success in the last release.
=> Release automation

git/version.go
We use a sync.Mutex to synchronize access to the string pointer
`gitVersion`, which indicates the version of Git used by the system
running Git LFS.
Our basic usage of the sync.Mutex is not incorrect, but we can improve
the readability by instead using a sync.Once. A sync.Once determines
very quickly (and in an atomic, goroutine-safe fashion) whether or not
_any_ function has been run, and if it hasn't, run it.
By doing this, we can--at the first request--produce a value for the
result of running 'git version', and then return it later to the caller.
This has the following benefits:
- If 'git version' has already been run, we do not need to hold the
lock for the entire duration of the function.
- If 'git version' has not already been run, we only run it once,
retaining the existing …
=> git/version.go: replace sync.Mutex usage with sync.Once

CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v2.7.0, which is scheduled for Friday, February 15, 2019.
[git-lfs-darwin-386-v2.7.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/2861892/git-lfs-darwin-386-v2.7.0-pre.tar.gz)
[git-lfs-darwin-amd64-v2.7.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/2861893/git-lfs-darwin-amd64-v2.7.0-pre.tar.gz)
[git-lfs-freebsd-386-v2.7.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/2861894/git-lfs-freebsd-386-v2.7.0-pre.tar.gz)
[git-lfs-freebsd-amd64-v2.7.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/2861895/git-lfs-fre …
=> release: v2.7.0

tq/basic_upload.go
When we get an error making an API request, we check to see if the response is a 429, and if so, we attempt to back off and retry later. However, we failed to check if we actually had a response; if the response was missing (say, because we had a network issue), then we would dereference a nil pointer.
Instead, let's explicitly check for a non-nil response before querying it for a status code.
This series doesn't include a test because I'm not aware of a way to synthesize this failure. It clearly is occurring, though, and it seems fairly obvious what's going on.
Fixes #3533.
/cc @mloskot
=> Avoid nil pointer dereference on unexpected failure

docs/howto/release-git-lfs.md, script/upload
When uploading assets during releases, we'd generally like to include all of the bytes in them, including newlines. To help us do this, we use the --data-binary option for uploads. To avoid additional problems during releases and make sure that they're intact, download the assets and verify the signature and hashes as part of the upload process. This lets us be confident that we're shipping a complete release to users.
Finally, to help maintainers avoid including files in the signed manifest that shouldn't be there, we update the documentation with a suitable invocation of shasum that strips these files out. We also update the documentation to create hash files that are more easily verifiable on Windows by causing Windows systems to use binary mode for reading files.
=> Fix asset uploading during releases

Makefile
Unconditionally setting `-extldflags` to the contents of `LDFLAGS`
causes problems when `LDFLAGS` isn't defined (`-extldflags` doens't
have an corresponding value).
In out case this led to `git-lfs` aborting.
```
$ ./bin/git-lfs
Aborted
```
This change only sets `-extldflags` if `LDFLAGS` is defined.
=> Don't set -extldflags unless LDFLAGS has a value

CHANGELOG.md, config/version.go, debian/changelog, docs/howto/release-git-lfs.md, rpm/SPECS/git-lfs.spec, script/upload, tq/basic_download.go, tq/basic_upload.go, versioninfo.json
This is an in-progress look at the next release of Git LFS, v2.7.1, which is scheduled for Tuesday, February 26, 2019.
[git-lfs-darwin-386-v2.7.1-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/2895628/git-lfs-darwin-386-v2.7.1-pre.tar.gz)
[git-lfs-darwin-amd64-v2.7.1-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/2895629/git-lfs-darwin-amd64-v2.7.1-pre.tar.gz)
[git-lfs-freebsd-386-v2.7.1-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/2895630/git-lfs-freebsd-386-v2.7.1-pre.tar.gz)
[git-lfs-freebsd-amd64-v2.7.1-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/2895631/git-lfs-fr …
=> release: v2.7.1

config/config.go, t/t-worktree.sh
When using worktrees, the hooks are stored once, in the main repository, not in a per-worktree location. Install the hooks in the proper place instead of creating and populating a hooks directory that will never be used.
/cc @KalleOlaviNiemitalo and @TheClassic as reporters
Fixes #1385.
=> Install worktree hooks in the proper directory

debian/rules
This fixes #2013.  For some reason I could only reproduce the issue from within the docker builder, not when running outside of docker.  Regardless, this appears to fix the problem and is a generally cleaner
solution anyway that will continue to work if any other generate commands are added to git-lfs.
=> Switch from manually running go generate to using dh-golang to run it

lfsapi/endpoint_finder.go, t/t-config.sh
It's possible for a user to specify multiple insteadOf aliases and have all of the specified URLs map to the same rewritten URL. Make sure we do handle this correctly by iterating over the all values we read from the config, not just the last one.
Fixes #2298.
/cc @larsxschneider as reporter
=> Allow specifying multiple insteadOf aliases

commands/command_lock.go, commands/command_unlock.go, git/git.go
On Windows, there is a type of file system object called a junction point, which is a by-name reference from the junction point to a directory. Go's filepath.EvalSymlinks, which we use in the locking code, resolves these and provides a canonical path. However, Git for Windows, which provides the repository root, does not resolve them, resulting in the relative paths we generate against the repository root containing ".." components. As a consequence, the locks generated in this way are broken and cannot be unlocked.
To avoid this problem, we canonicalize the paths we get back from Git to ensure that all lock paths are relative. In addition, we check for locks containing ".." and reject them, and we allow users to force unlocking by ID, even if we think that will fail. If it does indeed …
=> Handle Windows junctions properly

t/cmd/lfstest-count-tests.go
When there's a problem with the test server, it's helpful to see the log output to help troubleshoot the issue. However, when the Stderr member of a command struct is not set, the standard error gets redirected to/dev/null, which isn't really what we want.
Since we already have a log set up for logging standard output, send standard error there as well.
(For those who are interested in the impetus for this pull request, I had a system-wide gitconfig file which attempted to include several nonexistent files, which of course made Git unhappy. Having logging on made troubleshooting this much easier.)
=> Log test server standard error to log file

commands/command_pre_push.go, t/t-pre-push.sh
In the pre-push hook, we set the remote to the remote value that has been passed to us from Git. In most cases, this works fine. However, because we're pushing and have set a remote but not specifically a push remote, if the user has a remote.pushDefault setting, we'll use that instead of honoring the remote passed into the hook. As a result, we can end up pushing LFS objects to the wrong place.
Instead, since we're pushing, set the push remote instead of the regular remote. This has no effects other than to make us not read the pushDefault setting.
Fixes #3561
/cc @rdailey as reporter
=> Set push remote for pre-push

tasklog/log.go
Some Unix emulation layers for Windows, such as Cygwin and MSYS, use pipes to create their Unix-style TTYs. These TTYs are not detected as such by Windows, which sees them as pipes. However, our isatty module has a way to detect them, and they will function just like a TTY for our purposes, so check for them as well and handle them as TTYs if present.
I haven't added tests for this since I don't think we can just install Cygwin or MSYS in CI, and even if we could, we'd still have to somehow allocate a TTY for the tests in such an environment. If someone thinks of a way to test this, I'm all ears.
Fixes #3575
/cc @kristjanvalur as reporter
=> Detect Cygwin-style pipe TTYs as TTYs

docs/man/git-lfs-config.5.ronn, t/t-pull.sh, t/t-push.sh, tq/adapterbase.go
Use insteadOf/pushInsteadOf aliases to rewrite href to upload/download LFS objects.
This is useful in situations such like you need to access the LFS server via a reverse proxy.
=> tq/adapterbase: support rewriting href

config/config.go, config/config_test.go, config/git_fetcher.go, config/git_fetcher_test.go, t/t-extra-header.sh
Git configuration options have a complicated situation with regard to case. For the most part, they are case-insensitive: you may write any case into the file, but Git interprets it as lower case. However, there are exceptions.
Because the middle component of a three-component option can be a URL, branch name, or remote name, this component (and only this component) is treated as case sensitive. Since this component can be a URL, which may (and, due to the ".git" portion, usually does) contain a dot, the first component of the config option is read up until the first dot, and the last component is read from the end to the last dot.
When git config writes a value into the file, it preserves the case the user has provided, and when it prints the config values, it canonicalizes the keys by …
=> Properly handle config options for URLs with upper case letters

CHANGELOG.md, Makefile, config/config.go, config/config_test.go, config/git_fetcher.go, config/git_fetcher_test.go, config/version.go, debian/changelog, debian/rules, rpm/SPECS/git-lfs.spec, script/packagecloud.rb, t/t-extra-header.sh, versioninfo.json
This is an in-progress look at the next release of Git LFS, v2.7.2, which is scheduled for Monday, April 8, 2019.
[git-lfs-darwin-386-v2.7.2-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3045385/git-lfs-darwin-386-v2.7.2-pre.tar.gz)
[git-lfs-darwin-amd64-v2.7.2-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3045386/git-lfs-darwin-amd64-v2.7.2-pre.tar.gz)
[git-lfs-freebsd-386-v2.7.2-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3045387/git-lfs-freebsd-386-v2.7.2-pre.tar.gz)
[git-lfs-freebsd-amd64-v2.7.2-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3045388/git-lfs-freebsd …
=> release: v2.7.2

commands/command_locks.go, commands/lockverifier.go, docs/man/git-lfs-locks.1.ronn, locking/api_test.go, locking/locks.go, locking/locks_test.go
This is the same pull request as #3455 which I had closed unfortunately (by temporarily deleting my feature branch).
=> Issue 3252: git-lfs locks should optionally denote own locks

commands/command_install.go, t/t-install.sh
This series introduces two improvements to git lfs install. The first is to return unsuccessfully (exit code 2) when the operation fails, so that scripting users can easily detect the failure. The second is to avoid printing the warning about the lack of root privileges on Windows, where we will always be unable to detect these privileges properly.
/cc r0nw as reporter
Fixes #3622
=> Improve error handling in git lfs install

Makefile, script/packagecloud.rb
There are several release-related issues that I discovered while releasing 2.7.2. The first of these, of course, is the nwe signing certificate, which requires an update to the Makefile. In addition, I discovered several issues with the PackageCloud upload script, including some syntax errors and a release that PackageCloud refused to accept. Finally, I hit an additional issue with attempting to upload existing package that I've seen repeatedly before but have just hacked around; this time I finally fixed it.
I've also added Ubuntu disco as a release target, which fixes #3621. Note that I didn't use this change in this release; I simply applied it so as to not forget about it for 2.8.0.
=> Various release updates

lfshttp/ssh.go
Some people have SSH prompt them for their passphrase when a key is used. In such a situation, the user needs to be able to enter a password on standard input so that they can use their key. When invoking ssh, pass our standard input through to the ssh process so that it can prompt the user if needed.
=> Pass standard input to ssh

docs/api/locking.md
According to `locking/schemas/http-lock-create-response-schema.json`, `owner` field is not required,
so fix locking API documentation to match schema.
In fact, GitHub LFS implementation does NOT provide 'owner' field in response to lock creation request.
=> Fix 'owner' lock field not documented as optional

Makefile, config/version.go
It's common for vendors (such as Linux distros) to want to customize the User-Agent string and version information for software they provide. This is valuable for vendors, but it also allows troubleshooting problems with custom patches that may have been applied by the vendor. Allow vendors to set a VENDOR makefile flag to set the vendor field for the User-Agent and version information.
=> Allow vendors to customize the version info

docs/api/batch.md
In some cases, it may be useful to return an error code if the number of objects in the batch response is too larger for the server to handle. Document the 413 error code for this case, since it is in use by at least one implementation for this purpose.
=> Document a new batch error code

locking/schemas/http-lock-create-response-schema.json
This commit fixes discrepancy between LFS locking spec and JSON schema.
Per discussion in #3652, spec has higher priority here.
=> Make 'locked_at' required in JSON schema

t/cmd/lfstest-gitserver.go, t/testhelpers.sh, tq/verify.go
There is one place in the code and two places in the testsuite where we fail to provide the proper Content-Type and Accept headers when making a request to the server. Correct these places and adjust the test server to always check for the Accept header and check for the Content-Type header whenever we have a JSON body (i.e., when we have a POST request).
Fixes #3662
/cc @slonopotamus as reporter
=> Ensure we always use correct Content-Type and Accept headers

git/git.go
When we look up the Git and root paths together, we canonicalize the paths on Cygwin to Windows paths. This is required because Cygwin is essentially a libc, and Go neither uses libc nor has support for Cygwin natively. Without this, we'd treat absolute Unix-style paths created by Cygwin's Git as Windows paths relative to the root of the current drive, breaking most uses of Cygwin-created repositories.
However, we do not canonicalize the paths in several other cases where we read the output from Git, such as the common directory, which is used when reading Git objects. Consequently, functionality like git lfs fsck failed on Cygwin.
To ensure things work as expected on Cygwin, canonicalize the paths in all cases where we read a directory from Git. In addition, add some error checking for …
=> Canonicalize common directory paths on Cygwin

README.md
I naively ran into this unintended consequence when first using git-lfs. I think this subtle detail should be pointed out more boldly in the README.
=> Update README to draw attention to lfs track pattern

lfshttp/proxy.go, lfshttp/proxy_test.go
Currently, we prepend "http://" to the proxy URL if it's not an HTTP or HTTPS URL. Unfortunately, that breaks support for SOCKS 5 proxies, which use URLs that start with "socks5://". Fix this by allowing URL schemes starting with "socks" in addition to those starting with "http".
Note that this does not introduce any support for socks5h proxies, since Go does not support them, but we will support them automatically once Go does.
Fixes #1424.
=> Add support for SOCKS proxies

docs/api/batch.md, docs/api/locking.md
In a couple of places in our documentation, we specified that a timestamp should be in ISO 8601 format. However, ISO 8601 specifies a large number of variants, and Go only parses a subset of those. For example, using a timestamp without the colon in the time zone offset will cause Git LFS to fail.
Be explicit about what we want as a timestamp, which is an uppercase RFC 3339-formatted timestamp with second precision. That's what Go parses, and that's what we expect. It is, in addition, a profile of ISO 8601, so other tools that can parse the entirety of ISO 8601 will still accept these date formats.
Fixes #3660
/cc @slonopotamus as reporter
=> Be more precise about what timestamps we accept

t/t-post-commit.sh, tools/filetools.go
When we're walking the tree to select objects which need permissions adjusted, don't recurse into any submodules that exist. This is not only slow, but the submodules may have their own gitattributes files which we wouldn't have honored.
Fixes #3638.
=> Don't recurse into submodules when walking repository

git/githistory/ref_updater.go, t/t-migrate-import.sh
When rewriting history, we've ignored tags pointing to other tags. This leads to problems for folks that are trying to shrink the size of their repository, since they may still have tags that point to the old history. Add additional handling for tags pointing to tags, recursively rewriting the inner tags until we reach a commit.
Fixes #3568
/cc @rcdailey as reporter
=> Migrate tags pointing to other tags

git/githistory/rewriter.go, t/t-migrate-import.sh
When we rewrite a blob, we cache certain data based on the file name and the old object ID. However, we don't consider the mode, so if we have two identical blobs with the same relative name but different modes, we'll write the mode we first saw into all subsequent blobs.
Fix this by copying the mode across from the existing blob when we rewrite the new blob.
Fixes #3691 
/cc @larsxschneider as reporter
=> Copy mode from original file when rewriting objects

debian/control, debian/rules, docker/run_dockers.bsh, script/packagecloud.rb, script/upload, t/t-install.sh
Add support for building with Go 1.12.6 and Debian 10. This will allow us to build Git LFS with Debian 10 as soon as it's announced. Drop support for Debian 7, which is end of life and whose packages can no longer be downloaded with APT.
In addition, fix a test failure that occurs when building on CentOS. Debian builds packages with fakeroot, which honors permissions, but in our CentOS containers, we build as root, which causes a permission-related test to fail.
=> Add support for Debian 10

commands/command_migrate_export.go, commands/command_smudge.go, commands/commands.go, commands/uploader.go, lfs/gitfilter_smudge.go, t/git-lfs-test-server-api/main.go, t/t-pre-push.sh, t/t-push-failures-local.sh, t/t-push.sh, tq/api.go, tq/transfer.go, tq/transfer_queue.go
A Git LFS client may not have the entire history of the objects for the repository. However, in some situations, we traverse the entire history of a branch when pushing it, meaning that we need to process every LFS object in the history of that branch. If the objects for the entire history are not present, we currently fail to push.
Instead, let's mark objects we don't have on disk as missing and only fail when we would need to upload those objects. We'll know the server has the objects if the batch response provides no actions to take for them when we request an upload. Pass the missing flag down through the code, and always set it to false for non-uploads.
If for some reason we fail to properly flag a missing object, we will still fail later on when we cannot open the file, just in a …
=> Don't fail if we lack objects the server has

commands/path.go, t/t-track.sh
We currently use core.autocrlf to guess what line endings a user might want to have for the .gitattributes file if it lacks line endings already. When the user has specified core.autocrlf=input, they have specified that they don't want line endings to be changed. This isn't explicitly an indication that they want to use CRLF line endings, especially if they are on a non-Windows system.
Therefore, if we need to guess what line endings to use with `core.autocrlf=input`, guess the system line endings, not CRLF.
Fixes #3702.
=> Use default line endings for core.autocrlf=input

go.mod, go.sum, vendor/github.com/git-lfs/gitobj/object_db.go, vendor/modules.txt
Update gitobj to v1.3.1, which fixes a file descriptor leak.
Fixes #3696.
=> Update gitobj to v1.3.1

locking/api.go, t/t-locks.sh
The locking API documentation specifies that a user need only have pull access to the repository when searching locks. However, we requested an upload token, which requires push access. Instead, ask for a download token, which requires only pull access, as documented.
Fixes #3653
/cc @slonopotamus as reporter
=> Use a download token when searching locks

docs/api/locking.md
Our locking API docs say that the path for a lock should be relative to the repository root, but we then use an absolute path in the JSON example, which is confusing. Improve this by using the same relative path for the example response as we do for the example request, so that the example is less confusing.
Fixes #3647.
=> Make API documentation lock creation example less confusing

lfshttp/ssh.go
When using SSH cloning with a ControlMaster socket and a password on a Unix system, we're unable to read from standard input and consequently the SSH process fails. The redirect from standard input was intended to fix an issue on Windows that is due to /dev/tty disappearing, but it doesn't appear to work and causes issues on Unix systems. Revert this change so we can explore other options.
Fixes #3719.
/cc @slonopotamus as submitter
=> Redirect stdin from /dev/null when running ssh

CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v2.8.0, which is scheduled for Monday, July 22, 2019.
[git-lfs-darwin-386-v2.8.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3407597/git-lfs-darwin-386-v2.8.0-pre.tar.gz)
[git-lfs-darwin-amd64-v2.8.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3407598/git-lfs-darwin-amd64-v2.8.0-pre.tar.gz)
[git-lfs-freebsd-386-v2.8.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3407599/git-lfs-freebsd-386-v2.8.0-pre.tar.gz)
[git-lfs-freebsd-amd64-v2.8.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3407600/git-lfs-freebsd …
=> release: v2.8.0

lfsapi/endpoint_finder.go, lfsapi/endpoint_finder_test.go
For a long time, the preferred way to write an SSH URL for use with Git has been with the "ssh" scheme. However, Git still accepts the "git+ssh" and "ssh+git" schemes for remotes as well, despite marking them as deprecated in the code. For compatibility with Git, accept these schemes as an alias for the "ssh" scheme.
Addresses behavior reported in #3695.
=> Accept legacy Git SSH URLs

config/config.go, config/delayed_environment.go, config/fetcher.go, config/os_fetcher.go, docker/run_dockers.bsh, docs/proposals/locking.md, docs/proposals/locking_api.md, docs/proposals/ntlm.md, git/githistory/fixtures_test.go, lfshttp/stats.go, locking/api.go, locking/cache.go, locking/locks.go, rpm/build_rpms.bsh, t/cmd/util/testutils.go, t/t-credentials.sh, t/t-duplicate-oids.sh, tasklog/log.go, tools/stringset.go, tq/custom.go
:blue_heart: Fix typos across **git-lfs repository**
<details><summary>See all fixed files</summary>
<p>
```
git-lfs/config/config.go:142:7: "Enviornment" is a misspelling of "Environment"
git-lfs/config/delayed_environment.go:10:22: "equivelant" is a misspelling of "equivalent"
git-lfs/config/fetcher.go:4:43: "enviornment" is a misspelling of "environment"
git-lfs/config/os_fetcher.go:15:49: "enviornment" is a misspelling of "environment"
git-lfs/docker/run_dockers.bsh:8:10: "Environmet" is a misspelling of "Environments"
git-lfs/docs/proposals/locking.md:367:55: "succesful" is a misspelling of "successful"
git-lfs/docs/proposals/locking_api.md:72:8: "repsonse" is a misspelling of "response"
git-lfs/docs/proposals/locking_api.md:96:4: "Repsonse" is a misspelling of "Response" …
```
=> Fix typos across git-lfs repository

commands/pull.go
Fixes #3732 
Stderr logging is reduced and logging to `.git/lfs/logs` is eliminated
=> Do not log skipped checkouts to file

lfs/gitfilter_smudge.go, tools/kv/keyvaluestore.go, tq/tus_upload.go
os.SEEK_XXX is now deprecated and we can use io.SeekXxx instead.
https://golang.org/pkg/os/#pkg-constants
```go
// Seek whence values.
//
// Deprecated: Use io.SeekStart, io.SeekCurrent, and io.SeekEnd.
const (
SEEK_SET int = 0 // seek relative to the origin of the file
SEEK_CUR int = 1 // seek relative to the current offset
SEEK_END int = 2 // seek relative to the end
)
```
https://golang.org/pkg/io/#pkg-constants
```go
// Seek whence values.
const (
SeekStart   = 0 // seek relative to the origin of the file
SeekCurrent = 1 // seek relative to the current offset
SeekEnd     = 2 // seek relative to the end
)
```
=> NON-ISSUE Replace deprecated SEEK_SET, SEEK_CUR usage.

commands/command_smudge.go, commands/command_standalone_file.go, docs/man/git-lfs-standalone-file.1.ronn, git/git.go, lfsapi/endpoint_finder.go, lfshttp/endpoint.go, lfshttp/standalone/standalone.go, t/t-env.sh, t/t-standalone-file.sh, t/t-worktree.sh, tools/cygwin_windows.go, tq/custom.go, tq/manifest.go
One commonly requested feature for Git LFS is support for local files. Currently, we tell users that they must use a standalone transfer adapter, which is true, but nobody has provided one yet. Since writing a simple transfer adapter is not very difficult, let's provide one ourselves.
Introduce a basic standalone transfer adapter, git lfs standalone-file, that handles uploads and downloads. Add a default configuration required for it to work, while still allowing users to override this configuration if they have a preferred implementation that is more featureful. We provide this as a transfer adapter instead of built-in because it avoids the complexity of adding a different code path to the main codebase, but also serves as a demonstration of how to write a standalone transfer adapter for …
=> Support for file URLs

commands/uploader.go, git/rev_list_scanner.go, git/rev_list_scanner_test.go, lfs/gitscanner.go, t/t-pre-push.sh
We have an optimization that means we avoid traversing objects that exist in the remote tracking branches of named remotes. We assume that the server already has the LFS objects referred to by those Git objects.
However, this doesn't work for URL remotes, since there are no remote tracking branches for them. Instead, let's make sure that we don't traverse Git objects that are included in the old value of the ref, which we know the server must have.
Note that this will not help the case where someone is pushing a new branch to a URL remote; in that case, the old value is the all-zeros value and we'll still have to traverse the entire history since we haven't learned anything about what the server has.
Fixes #3661
=> Optimize traversal of Git objects with URL remotes

.travis.yml
Because the quotation mark was missing for the variable `GIT_EARLIEST_SUPPORTED_VERSION`, we never checked out the older version and built it. Instead, we always checked out the latest master and built it twice, resulting in us never testing version 2.0.0 as we had wanted.
=> Make Travis run tests on the proper version

commands/command_track.go, docs/man/git-lfs-track.1.ronn, t/t-track.sh, t/testhelpers.sh
Normally, the arguments to `git lfs track` are taken as glob patterns. This is generally useful, but sometimes there are filenames that contain special characters. Add a `--filename` option that forces arguments to be taken as literal paths instead of glob patterns to make handling these files easier.
In the test helpers, pass -F to grep so that our unusual file names don't trigger undesired pattern matching. This has no effect on other tests, as they all pass a literal filename here.
Fixes #3506.
=> Provide an option to track to handle paths literally

script/packagecloud.rb
Add Scientific Linux, Fedora 30, and Ubuntu eoan to the list of distros we can build packages for.
Fixes #3750
/cc @skymoo as reporter
=> Add several additional distros for packagecloud.io

config/config.go, t/t-smudge.sh
We currently have code that determines which remote to us automatically. For example, if there is only one remote, we want to use it, no matter what it's named, because there's no other logical choice.
However, if we were not on any branch, we'd always end up picking "origin", even if that remote didn't exist. This appears to have been because we wanted to avoid a lookup with an empty branch name in the configuration. Doing so is harmless, though, so let's simply check that the branch name isn't empty before we execute that condition, and fall back to the rest of the checks if it is. This ensures that we always pick the only remote when there's just one.
Fixes #3730.
/cc @flokli and @gwerbin as reporters
=> Fix remote autoselection when not on a branch

commands/command_ls_files.go, commands/command_status.go, docs/man/git-lfs-ls-files.1.ronn, lfs/gitscanner.go, lfs/gitscanner_refs.go, t/t-ls-files.sh
Add an option to the `ls-files` command where the user can specify a commit range. This will return all the lfs files which changed between those two commits.
This change is based on the aborted pull request #3151 by @larsxschneider. I finished implementation and added unit tests and documentation.
As background information, the reason for this option is that I have a script that creates a git bundle. To workaround the missing bundle support in lfs (see #1755), I want to know which lfs objects were changed/created in the commit range of the bundle. Currently, in the script, I walk over all commits in the range and do a compare of the `ls-files` output. This is very slow however, so if `ls-files` has support for a commit range that would help me a lot.
=> ls-files: add support for reference range

commands/command_checkout.go, commands/command_fetch.go, commands/command_fsck.go, commands/command_ls_files.go, commands/command_migrate.go, commands/command_migrate_export.go, commands/command_prune.go, commands/command_pull.go, commands/command_status.go, commands/uploader.go, git/config.go, git/object_scanner.go, go.mod, go.sum, lfs/gitscanner.go, lfs/gitscanner_catfilebatch.go, lfs/gitscanner_index.go, lfs/gitscanner_refs.go, lfs/gitscanner_tree.go, lfs/scanner.go, lfs/scanner_git_test.go, t/t-alternates.sh, vendor/github.com/git-lfs/gitobj/backend.go, vendor/github.com/git-lfs/gitobj/backend_nix.go, vendor/github.com/git-lfs/gitobj/backend_windows.go, vendor/github.com/git-lfs/gitobj/object_db.go, vendor/modules.txt
There are two ways to specify an alternate in Git: via the repository file or via the environment. We've long supported the former, but not the latter. Add support for the environment variable form to ensure that all the standard use cases work.
During the writing of this series, I discovered an existing integration test for alternates that wasn't being run because it was named differently than the other tests. It's been renamed and adjusted so it now runs automatically and it's the basis for the test for this series.
Fixes git-lfs/gitobj#14.
/cc @rsrchboy as reporter
=> Support GIT_ALTERNATE_OBJECT_DIRECTORIES

lfs/gitfilter_smudge.go
On Windows, paths are limited to 260 characters with two exceptions: manifested applications on Windows 10 may use long path, and all systems may use UNC paths, which must be absolute. Since we are not currently using a manifest, use an absolute path when smudging to make so that we can take advantage of UNC paths on Windows.
Fixes #3772
=> Use an absolute path for smudging

commands/command_dedup.go, docs/man/git-lfs-dedup.1.ronn, t/t-dedup.sh, tools/util_darwin.go, tools/util_darwin_test.go, tools/util_generic.go, tools/util_linux.go, tools/util_test.go
Implements and closes https://github.com/git-lfs/git-lfs/issues/3740.
This PR depends https://github.com/git-lfs/git-lfs/pull/3745 (merged).
Formatted doc is here https://github.com/kazuki-ma/git-lfs/blob/dedup/docs/man/git-lfs-dedup.1.ronn
Request of information
=======
- Fixed.
- Fixed. Using `! git.IsWorkingCopyDirty()` 
Can I skip it?
=> Add new command `git lfs dedup` for file system level de-duplication.

commands/command_track.go, t/t-track.sh
When using "git lfs track --filename" with a filename with spaces, the brackets surrounding the character class for representing spaces were also escaped, leading to the space not being interpreted correctly.  Update the escaping function we use to handle all of our escaping needs, performing the escaping in the correct order so that we can handle spaces correctly.
/cc @gdlxn-ibm as reporter
=> track: make --filename work with spaces

tools/util_generic.go, tools/util_windows.go, tools/util_windows_test.go
ReFS ([wikipedia](https://en.wikipedia.org/wiki/ReFS)) is filesystem on Windows OS and it's support copy-on-write / file cloning since v3.2.
ReFS v3.2 is available since Windows Server 2016, Windows Server 2019 and Windows 10 also supports format & read-write.
I think many asset heavy product CI system and developer start using ReFS if git-lfs support dedup on it.
Reference:
* https://docs.microsoft.com/en-us/windows/win32/fileio/block-cloning
This closes https://github.com/git-lfs/git-lfs/issues/3791
=> Add clonefile on Windows over ReFS support.

tools/util_linux.go
Sorry it's my miss-understanding that we should use `FICLONE` first and fallback to `BTRFS_IOC_CLONE`. Actually, `FICILONE` is equal to `BTRFS_IOC_CLONE`.
So we already support copy-on-write on XFS not only Btrfs.
In this commit, let me use standarized name `FICILONE` instead of `BTRFS_IOC_CLONE`.
FICILONE definition:
----
`#define FICLONE                _IOW(0x94, 9, int)`  in https://github.com/torvalds/linux/blob/v5.2/include/uapi/linux/fs.h#L195
BTRFS_IOC_CLONE definition:
----
`#define BTRFS_IOC_CLONE        _IOW(BTRFS_IOCTL_MAGIC, 9, int)` in https://github.com/torvalds/linux/blob/v5.2/include/uapi/linux/btrfs.h#L850
and
`#define BTRFS_IOCTL_MAGIC 0x94` in https://github.com/torvalds/linux/blob/v5.2/include/uapi/linux/btrfs.h#L25
=> NON-ISSUE Use FICLONE instead of BTRFS_IOC_CLONE.

.github/workflows/ci.yml, commands/command_status.go, script/build-git, script/cibuild, t/Makefile, t/cmd/git-credential-lfstest.go, t/cmd/lfstest-realpath.go, t/t-credentials.sh, t/t-custom-transfers.sh, t/t-env.sh, t/t-fsck.sh, t/t-submodule.sh, t/t-worktree.sh, t/testhelpers.sh
Currently, we have three different CI systems that handle our CI: Travis for Linux, CircleCI for macOS, and AppVeyor for Windows.  This results in widely varying performance across systems and the need to maintain code that works differently across different CI systems.
In addition, we'd like to use GitHub Actions to automate the release process, so it makes sense to use it for CI as well.  Switch over by adding a CI workflow that runs our existing jobs.
There are several causes of flaky tests that are also fixed in this series, plus some workarounds for the fact that `cygpath` on the Windows Actions servers produces a short path (`C:\Users\RUNNER~1` instead of `C:\Users\runneradmin`).  This latter issue is heavily exacerbated by the fact that we cannot canonicalize a Windows-style path …
=> Use GitHub Actions for CI

tq/transfer_queue.go
When we are cloning or checking out a repo, the filter-process smudge filter sends the transfer queue data by calling the Add method.  This method inserts items into the incoming channel, which is then processed by the collectBatches function.  This function accepts items, downloads a batch worth, and splits the remainder into the next and pending queues, and then, if there are any items in either of these queues, goes around again.  If there are no items, it exits the download queue.
Unfortunately, this algorithm has a problem.  If the filter-process portion is slow and does not provide us enough data, we can end up with both the next and pending queues empty, but the incoming channel still open, waiting for the filter-process end to send more data.  In such a case, we stop downloading …
=> Avoid a hang when Git is slow to provide us data

commands/command_status.go, t/t-status.sh
Currently we fail with an error when a file has been replaced by a directory. Handle this more gracefully by treating it as a normal deletion (which, in the index, it is).
Fixes #3766
=> status: gracefully handle files replaced by directories

config/config_test.go, config/git_fetcher.go
git config allows "." in subsection name but not in key name.
while splitting key with "." into parts, config key name should be the last part and subsection name should be parts from the second to the second-to-last joint by ".".
=> Fix Remote Name Parsing Bug

tq/basic_download.go
When several git-lfs processes use the same LFS storage simultaneously,
there's a race condition between checking whether LFS file exists and renaming temporary
file to final name in LFS storage. When rename fails, check that target file exists.
If it does, pretend that download has finished successfully.
Fixes #2825
----
I'm not sure how to write a test for this.
=> Do not fail when multiple processes download the same lfs file

go.mod, go.sum, vendor/github.com/git-lfs/wildmatch/wildmatch.go, vendor/modules.txt
Update wildmatch to v1.0.4 to fix an issue with matching non-ASCII patterns.
Note that the version number is v1.0.4 instead of v1.0.3 because the master branch of wildmatch contains changes which are valuable but not currently compatible with Git LFS and v1.0.3 was mistakenly tagged from these changes.  These changes would break semantic versioning, so the tag was deleted and v1.0.4 was tagged with only compatible changes.
We can adopt these incompatible changes in the future, but it's better to fix this bug now since it is causing pain for multiple users rather than wait to address these changes until the new wildmatch can be included.
Fixes #3814.
=> Update wildmatch to v1.0.4

.github/workflows/ci.yml
In Git for Windows 2.23, the /dev and /dev/fd directories did not get created.  As a result, it's not possible to use a process substitution in bash, which breaks a significant portion of the test suite.  In the mean time, let's downgrade Git for Windows to 2.22.0, which is what Actions used to use and worked for us.  We can remove this hack when the next Git for Windows release occurs.
Fixes #3828.
=> ci: force Windows Git version to 2.22.0

lfs/util.go, tools/filetools.go, tq/basic_download.go
1. git-lfs now only writes to unique temp files created with `ioutil.TempFile`
that are open with `O_CREATE|O_EXCL`
2. Partially-downloaded file is now atomically borrowed and returned back via `os.Rename`
3. `.part <-> .tmp` and `.tmp -> final` renames are allowed to fail and are handled appropriately
This is a continuation of #3813
Fixes #2825
There are several error codepaths where we borrow .part file but remove it instead of returning back.
I believe that it is OK and in those erroneous cases it is better to restart download from scratch
instead of attempting to use possibly-corrupt .part file.
=> More robust handling of parallel attempts to download the same file

README.md
We're no longer using Travis, CircleCI, or AppVeyor, so remove their status badges and add one for actions.
=> README: update status badge

lfshttp/certs_dragonfly.go
I've tested this patch on the latest DragonFly BSD (development version as of 2019-09-17) and git-lfs works well.
The added `lfshttp/certs_dragonfly.go` is the same as `lfshttp/certs_freebsd.go`.
Please review this patch.  Thanks.
=> Support DragonFly BSD

go.mod, go.sum, lfshttp/client.go, lfshttp/cookies.go, t/cmd/lfstest-gitserver.go, t/t-clone.sh
This allows Git LFS to use the same cookies as configured for Git
(http.cookieFile). Those cookies may be needed for e.g. Gcloud Identity-Aware
Proxy.
Cookies are sent only over HTTPS.
Fixes #3824
=> Let git-lfs HTTPS transport send cookies

.github/workflows/release.yml, Makefile, docker/run_dockers.bsh, docs/howto/release-git-lfs.md, script/upload, t/cmd/lfstest-realpath.go
Currently, our release process is highly manual and doing a release can consume a significant amount of a maintainer's day.  Automate the process of doing a release by building and uploading assets on GitHub Actions.
There's a lot of code here; the series is best explained by reading the commit messages, which cover the changes better than this summary ever could.
=> Use GitHub Actions for release automation

fs/cleanup.go, fs/fs.go, git/attribs.go, git/ls_files.go, locking/lockable.go, t/t-lock.sh, tools/filetools.go, tools/filetools_test.go, tools/iotools.go
This is a rough cut of addressing #3797 by replacing FastWalkGitRepo with `git ls-files`. For my use case, it cuts post-hook execution time down from ~40 seconds, to a few hundred ms.
At this point, I am looking for a high-level review of the changes, and direction on wether I should proceed w/ completing this change.
There are a few things that need to be addressed:
1. The new code needs tests.
2. Some existing tests are failing.
3. The new behavior needs to be verified against the old behavior on more repos.
I am also requesting any feedback that anyone familiar w/ the code might have. As it stands, git-lfs is unusable for our project without this (or a similar) fix, and I would like to verify that this fix is sound before we use it internally.
=> Reworked to use git ls-files in some circumstances instead of FastWalkGitRepo

git/attribs.go, git/ls_files.go, script/cibuild, tools/filetools.go, tools/iotools.go
Sometimes we get contributions from folks who aren't very familiar with Go.  This is great, but since they aren't familiar with Go, they don't know to use go fmt or goimports to tidy files.  This leads to files that are misformatted, which then causes problems when users who do have these tools are doing development.
Let's help people check formatting automatically by running it as part of the CI job.  We already check for trailing whitespace, which is complementary (since it looks at non-Go files as well), and that check has been effective, so likely this one will be as well.
There is one potential downside: sometimes output changes between versions of Go.  This is unfortunate, but we'll need to just pin to whatever version GitHub Actions uses.
=> Check for code formatting in CI

docker/run_dockers.bsh, rpm/SPECS/rubygem-hpricot.spec, rpm/SPECS/rubygem-mustache.spec, rpm/SPECS/rubygem-rdiscount.spec, rpm/SPECS/rubygem-ronn.spec, rpm/build_rpms.bsh, script/packagecloud.rb, script/upload
Build packages for CentOS 8.  Add it to the list of containers we build for and the list of packages we have downloads available for.
In the gem spec files, use a different tooling on CentOS 8, since the old method no longer works there.  Build using a more standard gem build process so that RPM does the abstraction for us now that it's capable of it.  Stop deleting the root in the install step since we may have installed things there by that point, and RPM has handled this properly for many versions.
Since the syntax "%{?el8}" expands to "1" on CentOS 8 and nothing on earlier versions, add a 0 in front of it any time we use the macro so that we don't end up with an empty conditional on earlier versions. "01" is still true and "0" is false, so the logic works out.
It's been verified that …
=> Add support for CentOS 8

docs/man/git-lfs-ls-files.1.ronn
I've fixed some minor formatting on the man page of the `git lfs ls-files --all`.
I believe it may be worth adding a sentence along the lines of "This will include previous versions of LFS objects that are no longer found in the current tree." to make its use clearer. Should I add that to this PR?
Context - I've been providing support for LFS for a while but have only just found out about the --all flag introduced in https://github.com/git-lfs/git-lfs/pull/2796 ."How do I find the object IDs of old versions of LFS files?" is a common support request.
I also plan to add that flag to the tutorial - https://github.com/git-lfs/git-lfs/wiki/Tutorial
=> ls-files --all man patch

commands/command_fetch.go, docs/man/git-lfs-fetch.1.ronn, t/t-fetch.sh
I’m currently working on an automation that synchronizes Git repositories between remotes, some of which use Git LFS. Compared to `git lfs fetch --all`, I’d like to fetch all objects referenced in the entire commit history but, and here comes the difference, not for all refs but *only a specific set of refs.*
For this reason, I’d like extend `git lfs fetch` to support downloading all objects referenced by any commit reachable from a user-defined set of refs.
I suggest allowing `git lfs fetch` to accept a combination of the `--all` option and a list of refs specified as positional command-line arguments. This would then instruct Git LFS to download all objects referenced by any commit reachable from any of the specified refs (but no other objects).
For example, the call
```sh
$ git lfs …
```
=> Support fetching entire history of specific refs

lfs/gitfilter_smudge.go
Because it:
1. Doesn't add any value
2. Introduces a source of race conditions to download logic when multiple git-lfs instances share LFS storage
3. Forces git-lfs to oscillate between two strange states when empty file is downloaded from LFS server. See #3863
=> Do not delete zero-sized file from LFS storage

CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, script/update-version, versioninfo.json
This is an in-progress look at the next release of Git LFS, v2.9.0, which is scheduled for Thursday, October 17, 2019.
[git-lfs-darwin-386-v2.9.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3731430/git-lfs-darwin-386-v2.9.0-pre.tar.gz)
[git-lfs-darwin-amd64-v2.9.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3731431/git-lfs-darwin-amd64-v2.9.0-pre.tar.gz)
[git-lfs-freebsd-386-v2.9.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3731432/git-lfs-freebsd-386-v2.9.0-pre.tar.gz)
[git-lfs-freebsd-amd64-v2.9.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3731433/git-lfs-fr …
=> release: v2.9.0

.github/workflows/ci.yml, .github/workflows/release.yml, script/build-git
For an unknown reason, sometimes libintl.h is missing on macOS when it should not be.  Try harder to fix this by reinstalling the packages which are already allegedly installed and forcing an unlink and re-link.
In addition, address a problem in Windows CI where `%PATH%` is for some reason no longer recognized.  Since it's not strictly necessary to set the path in such a case, stop setting it.
=> Fix several causes of CI problems

.github/workflows/ci.yml, .github/workflows/release.yml, script/build-git, tools/util_darwin.go, tools/util_generic.go, tools/util_linux.go, tools/util_windows.go, tools/util_windows_test.go, tq/basic_download.go
On Windows, there is no way to replace file atomically. Instead, MoveFileExA:
1. Calls CreateFileA(access=Delete, shareMode=Delete)
2. Calls SetRenameInformationFile to rename file
3. Calls CloseFile
The problem is that if parallel process attempts to open destination file for reading between
steps 2 and 3, it will try to do that without shareMode=Delete and will hit a SHARING_VIOLATION error.
In practice, this race condition results in:
Smudge error: Error opening media file.: open .git\lfs\objects\<sha>: The process cannot access the file because it is being used by another process.
There are two solutions here:
1. Do not overwrite file if it already exists
2. Retry reading from file if got a SHARING_VIOLATION
This commit implements option 1.
Fixes #2825 (for Windows, other OSes are …
=> Stop replacing files in LFS storage when downloading them concurrently on Windows

lfsapi/auth.go, lfshttp/certs_test.go, lfshttp/client.go, lfshttp/client_test.go
There are some servers that cannot speak HTTP/2 in all cases and demand to fall back to HTTP/1.1 with a `HTTP_1_1_REQUIRED`.  Notably, this happens with IIS 10 when using NTLM.  Go's HTTP library doesn't seem to like this response and aborts the transfer, leading to a failure.
Fortunately, Git has an option (`http.version`) to control the protocol used when speaking HTTP to a remote server.  Implement this option to allow users to set the protocol to use when speaking HTTP and work around these servers.
/cc @YawJatah as reporter
=> Allow specifying HTTP version to use

.github/workflows/ci.yml, .github/workflows/release.yml
When proposing a PR that purports to fix a user problem, it's helpful if we can provide test binaries that they can use to see if the PR fixes their issue.  To do so, build binaries as part of the CI process and upload them as artifacts.
=> Build artifacts during CI for easier testing

t/t-clone.sh, t/t-fetch.sh, t/t-pull.sh
When we download objects, it's possible that one or more messages may not be printed because the transfer meter is paused.  This is not normally a problem for production use, since we'll print a later update out, but in our tests, we check for specific success messages, which leads to flaky tests when those exact messages happen to be skipped. Since our CI hosts are very fast and good at triggering race conditions, we see this frequently there.
Instead of checking for these exact messages, let's instead check that the objects we want to have downloaded have in fact been downloaded and that git lfs fsck passes, which are more reliable indicators of a successful download.  In many cases, we're already doing one or more of these, so we already have confidence that everything's working …
=> t: fix flaky tests in CI

creds/netrc.go
We run into concurrent map read/write error.
Here is a snippet of the stack trace:
`
goroutine 664 [running]:
runtime.throw(0x9e69e2, 0x21)
/usr/local/go1.12/src/runtime/panic.go:617 +0x72 fp=0xc0004e9430 sp=0xc0004e9400 pc=0x42dc92
runtime.mapaccess1_faststr(0x9343c0, 0xc00017b950, 0xc000216308, 0x13, 0x0)
/usr/local/go1.12/src/runtime/map_faststr.go:21 +0x469 fp=0xc0004e94a0 sp=0xc0004e9430 pc=0x413fc9
github.com/git-lfs/git-lfs/creds.(*netrcCredentialHelper).Fill(0xc00018b0c0, 0xc00094a420, 0x0, 0xc00094a540, 0x40deb8)
work/git-lfs/git-lfs/creds/netrc.go:69 +0xbc fp=0xc0004e9558 sp=0xc0004e94a0 pc=0x75000c
github.com/git-lfs/git-lfs/creds.(*CredentialHelpers).Fill(0xc00094a510, 0xc00094a420, 0x0, 0x18, 0xc000216302)
work/git-lfs/git-lfs/creds/creds.go:441 +0x29b fp=0xc0004e9630 …
=> synchronize access to netrcCredentialHelper.skip

subprocess/subprocess.go
According to [1], Git-LFS requires "a reasonably modern version of Go".
Go 1.6 was released 3.5 years ago, time to move on.
I failed to find exact info on oldest supported Go version.
[1]: https://github.com/git-lfs/git-lfs/wiki/Installation#source
=> Drop pre-1.6 Go compatibility code

git/git.go, t/t-push.sh
This change makes it possible to run `git lfs push` with any local reference, regardless of whether it’s stored in the conventional places (`refs/heads` and `refs/tags`) or not. This is to bring the behavior of `git lfs push` in line with `git push`, which doesn’t limit source references in refspecs to the `refs/heads` and `refs/tags` scopes either.
The other reason I’m suggesting this change is to enable usage of `git lfs push` with custom local references. I’m working on an automation that fetches tags from multiple remotes. In order to avoid collisions, I store tags from `remote-a` in a custom scope of the form `refs/custom/remote-a/tags`, whereas tags from `remote-b` would go into `refs/custom/remote-b/tags`.
Prior to this change, calls like `git lfs push remote-b …
=> Accept all local references with git lfs push

git/pkt_line_reader.go, lfs/gitfilter_clean.go, t/t-filter-process.sh
When we use git hash-object --stdin with the --path option, Git applies filters to the object, so Git LFS is invoked.  However, if the object provided is less than 1024 bytes in size, we would hang.  This occurred because of our packet reader didn't quite implement the io.Reader interface completely: if it returned a non-zero value and io.EOF, the next call to Read would not return 0 and io.EOF.  Instead, it would try to read from stdin, which would not be sending us more data until we provided a response, so we would hang.
To solve this, keep track of the EOF and always return it on subsequent Read calls.  In addition, don't process the callback to write the file in this case, since we don't actually want to write into the working tree.
Fixes #3884.
/cc @rivuonna as reporter
=> Avoid hang when using git hash-object --stdin --path

git/git.go, git/gitattr/tree_test.go
This PR picks up four `err` variables that were being dropped in the `git/gitattr` package.
=> git/gitattr: fix dropped test errors

lfs/pointer.go, t/t-migrate-export.sh
If a file that was being handled by git lfs migrate export contained the text "git-lfs", but was not a pointer file, we would abort.  This occurred because the error was not of a type that indicated that the file was not a pointer, so we treated it as an unrecoverable error instead of a recoverable one.
Wrap the error in an appropriate type so that we can recover from this and treat it as not being a pointer.  Add tests for both error branches in the function to ensure we recover from them.
Fixes #3908.
/cc @benblo as reporter
=> Allow migrate export to handle non-pointer files gracefully

t/t-standalone-file.sh, tq/manifest.go
Currently, if you have a remote with a file URL but have `lfs.url` set to point to a non-file URL, your transfers will fail.  This occurs because we look up whether to use a transfer adapter based on the remote URL, but we also look up whether to default to the built-in transfer adapter based on the remote URL, not the endpoint URL.  We then attempt to pass the HTTP URL to the standalone transfer adapter, which doesn't work.
Look up the endpoint URL as well and pass that to the code which determines whether we should use the builtin transfer adapter.  If the actual endpoint is not a file URL, then we won't suggest the builtin transfer adapter.
As a note to the harried reviewer, the `Endpoint` function looks up all LFS endpoints and is more complete than the `RemoteEndpoint` function, …
=> Honor lfs.url when deciding on transfer adapters

commands/command_migrate_export.go, t/t-migrate-export.sh
When we export LFS files, we currently set the text attribute.  This is unhelpful if the objects we're checking out are binaries, since they'll become corrupt due to automatic EOL handling.  Since we don't want that, leave the option unspecified so that the default behavior occurs.
We could also change this to use `text=auto` if folks think that's a better option.
Fixes #3909 
/cc @benblo as reporter
=> Reset the text attribute on export

lfsapi/endpoint_finder.go, lfsapi/endpoint_finder_test.go, lfshttp/endpoint.go, t/t-standalone-file.sh
Currently, we only support local remotes using file URLs, but not local paths.  This is a highly requested feature, however, so implement support for local paths as remotes.
First, fix the handling of local paths we already have: the handling of absolute Unix-style paths.  Instead of checking for the remote to contain a file URL to determine whether to append "info/lfs" to the URL, look to see if the URL we're using is a file URL, which will catch local paths which will have been rewritten as such by this point.
If we get something that looks like it's not a URL, check if it's a file on the file system, and if so, don't attempt to interpret it as an SSH URL.  This fixes the confusion with Windows paths, which resemble SSH-style locations with a single-letter alias as the host name. …
=> Add support for local paths

docs/man/git-lfs-track.1.ronn
It's a surprise to many users that bracket characters are treated specially in the shell, especially Windows users or other users who are not intimately familiar with the various peculiarities of shell.  As a consequence, users are also surprised when putting brackets into a `git lfs track` pattern doesn't work as expected.
Let's help these users out by explaining exactly what characters are special and what are ignored, since folks don't always dive into the Git attribute documentation.  Let's also provide an example of tracking a file with brackets in the name to reinforce the use of the `--filename` option as well.
Fixes #3784.
=> docs: explain shell metacharacters better

commands/command_status.go, git/git.go, lfs/diff_index_scanner.go, lfs/gitscanner_index.go, t/t-status.sh
When running `git lfs status`, we perform a `git diff-index`.  However, we don't update the index first, so any changes, such as permissions changes due to locking, cause the file to be listed as modified.  Since these changes don't represent actual changes that we're interested in, refresh the index before running diff-index so that it doesn't produce spurious output.
Fixes #3412
=> Update index before showing status

README.md
git lfs migrate import does nothing when given no refs to work on.  Add a command line argument to process all refs in the README example.
Fixes #3883 
/cc @alan23273850 as reporter
=> README: correct git lfs migrate import invocation

tools/os_tools.go
It looks like there are situations in which some Git for Windows installations don't have the cygpath binary.  In that case, we end up picking an empty string, which leads us to install hooks and LFS objects in the current directory.  Fix this by looking for the cygpath binary and if it's missing, disabling Cygwin path canonicalization on Windows.
/cc #3898 
/cc @StarWars999123
=> Handle missing cygpath gracefully

.github/workflows/ci.yml, .github/workflows/release.yml, rpm/build_rpms.bsh, script/packagecloud.rb
Currently we only build Linux packages during the release process.  This means that there is a significant period of time during which unrelated changes could silently break the Linux package build.  This happened the other day with CentOS 8 and a tar update.
Since having this happen is a hassle resulting in the maintainer doing the release having to build the packages by hand, we should check this process during CI to ensure that any errors are caught early.  In addition, we should allow the building of prerelease tags so that any problems with the release can be caught before the main release is built.
We additionally fix the tar issue in this series, plus the lack of a shebang on the packagecloud script.
Note that the Windows build already takes longer than the newly added Linux …
=> Fix more Linux package issues

config/config.go, t/t-install-custom-hooks-path.sh
Git specifies that relative hook paths are specified relative to the working tree in a non-bare repository.  However, we were interpreting it relative to the working directory, which meant that we could install hooks in an undesired place if the user was in a subdirectory of the repository.  Fix this by installing relative to the root of the working tree as Git does.
Fixes #3802
=> Interpret relative hook paths as relative to working tree

rpm/SPECS/rubygem-hpricot.spec, rpm/SPECS/rubygem-mustache.spec, rpm/SPECS/rubygem-rdiscount.spec, rpm/SPECS/rubygem-ronn.spec
We need to have different %setup invocations on CentOS 8 and older CentOS versions.  Originally, CentOS 7 was thought to behave like CentOS 8, but the fact that it behaves like CentOS 6 was hidden by the container images building the RPMs against Git LFS 2.4.0 as part of the setup process.  As a consequence, we never built the RPMs using the new versions of the spec files in master, and we never noticed that they failed in this case.
Since we're no longer building RPMs against an ancient version of Git LFS as part of the setup process, adjust the Ruby RPMs to call the correct %setup invocation on CentOS 7.  Note that like the code with `%{?el6}`, `%{?el7}` will expand to either 1 or nothing, so the condition will be true (nonzero) for CentOS 6 or 7 and false (zero) for 8.
=> rpm: use old setup code on CentOS 7

.github/workflows/ci.yml, .github/workflows/release.yml
When building artifacts during CI, we need the tags in order to be able to use `git describe`.  The master version of the checkout action provides only the one ref we've checked out, but the v1 provides us with a full clone.  Use the v1 clone so that we can ensure that our CI works as expected.
The original recommendation for Actions was `actions/checkout@master` (when I wrote the CI scripts), and then the recommendation changed to use tagged versions, but I neglected to update things.
=> Use actions/checkout v1 in CI

git/git.go
In Git 2.25, git rev-parse --show-toplevel will fail when not in a work tree.  This currently causes our test suite to abort because there are myriad places that we use bare repositories, in addition to the user impact.  Fix this by adjusting our code to fall back to querying just the Git directory if we get an exit code of 128 from Git, which indicates that Git called die().
The alternative would be to inspect the error message, which should theoretically be stable, since it comes from die() (it will at least not be localized), but that is potentially brittle.  We can revisit this decision in a few Git releases if it remains stable.
Fixes #3939.
=> Don't abort with newer Git when in a bare repo

tq/transfer_queue.go
If the batch operation fails due to an error instead of a bad HTTP status code, we'll abort the batch operation and retry.  This appears to be a regression from 1412d6e4 ("Don't fail if we lack objects the server has", 2019-04-30), which caused us to handle errors differently.
Since there are two error returns from enqueueAndCollectRetriesFor, let's wrap the batch error case as a retriable error and not abort if we find a retriable error later on.  This lets us continue to abort if we get a missing object, which should be fatal, but retry in the more common network failure case.
/cc #3929
/cc @bluekeyes as reporter
=> Retry batch failures

tq/basic_download.go
If os.OpenFile() returns error then variable "f" is nil, so support this case
=> Add nil-check on defer block of DoTransfer()

docs/spec.md
Document that pointer files are unique; that is, there is exactly one valid encoding for a given pointer file.
We've seen several issues where invalid pointer files cause problems, notably with Git marking files as modified due to the pointer files being rewritten into the "correct" format internally.  Because it's always been intended that pointer files are unique and having multiple encodings with pointer files intrinsically causes problems with Git, let's document the common understanding explicitly.
We also now explicitly specify the format of the hash encoding.
Fixes #3899
=> Better document pointer format constraints

.github/workflows/ci.yml, CONTRIBUTING.md
Our documentation was conflicting on the versions of Go we support.  Update the contributing documentation to reflect that we support the latest version of Go, although we try not to break support for older versions if it's easily avoidable.  This helps set folks' expectations for backwards compatibility.
In addition, since our CI currently depends on both Go 1.12 (the default on Ubuntu) and 1.13 (the default on macOS) working, let's explicitly specify those in the CI system.  This way, we'll make an explicit decision to change Go versions.
Fixes #3945
=> Document and test Go versions explicitly

.github/workflows/ci.yml
Now that Git for Windows 2.24.0 is available with a fixed version of bash, we can revert the changes to CI that pinned it to 2.22.0 and have things work properly.
This reverts commit 52257344da89a7ba0891d49ac4d60a8e04563aad.
=> Revert "ci: force Windows Git version to 2.22.0"

.github/workflows/ci.yml, .github/workflows/release.yml, CHANGELOG.md, config/version.go, debian/changelog, git/git.go, rpm/SPECS/git-lfs.spec, rpm/SPECS/rubygem-hpricot.spec, rpm/SPECS/rubygem-mustache.spec, rpm/SPECS/rubygem-rdiscount.spec, rpm/SPECS/rubygem-ronn.spec, rpm/build_rpms.bsh, script/packagecloud.rb, tools/os_tools.go, tq/basic_download.go, tq/transfer_queue.go, versioninfo.json
This is an in-progress look at the next release of Git LFS, v2.9.1, which is scheduled for Thursday, December 12, 2019.
[git-lfs-darwin-386-v2.9.2-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3941566/git-lfs-darwin-386-v2.9.2-pre.tar.gz)
[git-lfs-darwin-amd64-v2.9.2-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3941567/git-lfs-darwin-amd64-v2.9.2-pre.tar.gz)
[git-lfs-freebsd-386-v2.9.2-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3941568/git-lfs-freebsd-386-v2.9.2-pre.tar.gz)
[git-lfs-freebsd-amd64-v2.9.2-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/3941569/git-lfs-f …
=> release: v2.9.2

commands/command_status.go, t/t-status.sh
Resolve git-lfs/git-lfs#3552
The `git lfs status` command shows objects that pertain to both
`git lfs` as well as regular `git` objects. This commit modifies
the output of `git lfs status` to better reflect that
=> Clarify output shown by `git lfs status`

debian/control
Since we now require Go 1.12 to build, let's bump the version in the debian/control file so that others using our packages have their dependencies properly satisfied.
=> debian: bump version of golang-go

README.md
Before this commit, clicking on a CI badge would just open badge image.
Instead, now it will navigate user to CI page.
=> Add CI link to CI badge in README

git/git.go, t/t-install.sh
As of 2.9.2, if run outside of a repository, Git LFS will produce an error if `git lfs install` is run outside of a repository.  This occurs because we look for a specific string in the error message to detect if the directory is not a repository, but that message was no longer included since the standard output of `git rev-parse` is not included.
Include the standard error output in the message so that we correctly detect whether the directory is a repository or not and avoid printing an error message in this case if it is not.
Fixes #3964.
=> install: don't print error if run outside repository

lfshttp/proxy.go, lfshttp/proxy_test.go, vendor/golang.org/x/net/http/httpproxy/proxy.go, vendor/modules.txt
Currently, our proxy support has some limitations.  Notably, we don't handle wildcards in the no_proxy environment variable.
Unfortunately for us, there's no standard as to how these environment variables are supposed to be handled, so any attempt we made to handle this ourselves would likely be incomplete.  However, fortunately for us, our needs are simple: we need standard behavior except that a user can use a proxy for localhost, and we need to be able to read from a source other than the environment.
The solution is to use the Go extension httpproxy module along with a little bit of custom configuration and URL rewriting, which means we don't have to worry about maintaining the complexity of parsing proxy support.  This also means we can drop a large amount of complex (and subtly …
=> Improved proxy support

t/t-duplicate-oids.sh
In awk, strings start at position 1, not position 0, according to POSIX. While using 0 does the right thing for some awk versions, it fails with the version of mawk in Debian unstable.  Since it's easy to invoke this in a way that works for all awk versions, let's do so.
=> t-duplicate-oids: use correct awk indexing

Makefile, script/upload
These have been requested and it's trivial to build them.  In addition, they're supported by Debian, so presumably they have a reasonable number of users.  Let's build them.
/cc #3982
/cc @james-crowley as reporter
=> Include ppc64le and s390x Linux builds in releases

commands/uploader.go, lfs/gitscanner.go, lfs/gitscanner_refs.go, t/t-push.sh
This PR optimizes pushes for multiple refs by using all the remote sides as bases for crawling `git rev-list`.
Fixes #3976.
=> Optimize pushes for multiple refs

.github/workflows/ci.yml, .github/workflows/release.yml
There's a bug with Actions right now that causes the path to be set incorrectly, and as a result, this causes Windows binaries to be executed in some cases instead of the binaries that come with Git Bash. This shows up in our test suite as a hang during the execution of t-credentials.sh.
Since we can't build or release software while the Actions workflows aren't working, let's adjust the path temporarily so that things work as expected.
=> .github/workflows: temporarily fix path on Windows

CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v2.9.1, which is scheduled for Tuesday, January 21, 2020.
[git-lfs-darwin-386-v2.10.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/4074030/git-lfs-darwin-386-v2.10.0-pre.tar.gz)
[git-lfs-darwin-amd64-v2.10.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/4074031/git-lfs-darwin-amd64-v2.10.0-pre.tar.gz)
[git-lfs-freebsd-386-v2.10.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/4074032/git-lfs-freebsd-386-v2.10.0-pre.tar.gz)
[git-lfs-freebsd-amd64-v2.10.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/4074033/git- …
=> release: v2.10.0

commands/command_track.go, t/t-track.sh
When we add a pattern with `git lfs track`, we inform the user if the pattern is already supported.  However, we fail to do so when the `--filename` argument is passed, due to not having encoded the pattern at that point.
To solve this problem, hoist the code that encodes the filename as a pattern so it happens before we check if we already have such a pattern.
Fixes #3998.
/cc @mitar as reporter
=> track: detect duplicate patterns with --filename

commands/command_filter_process.go, docs/man/git-lfs-config.5.ronn
Git on Windows is currently incapable of handling files larger than 4 GiB in size.  This is because Git uses "unsigned long" for numerous types of variables representing files, which on a Unix system is an appropriate way to specify a pointer-sized integer, since Unix systems are either ILP32 or LP64.  However, Windows is LLP64, meaning that a variable of type unsigned long is always 32 bits.
We warn about this case to help alert users to potential corruption when they're working across platforms.  However, there are some users and projects who don't use Windows and therefore don't have this problem. For those users and projects, this warning is not helpful.  Let's add an option to control that warning so folks who don't wish to see it can disable it.
=> Add an option to control warning about files larger than 4 GiB

commands/command_migrate_export.go, commands/command_smudge.go, commands/commands.go, commands/uploader.go, lfs/gitfilter_smudge.go, t/git-lfs-test-server-api/main.go, t/t-fetch.sh, tq/transfer_queue.go
When we have an error creating the local storage directory, such as if the permissions are wrong, we fail to produce a helpful error message, since we fail to check the error we produce.
Let's take the error we get in such a case and pass it through to the transfer queue, where we can handle it as any other error.  This means that if only one directory has a problem, we can transfer the rest of the objects and fail for only the one problematic object.
Fixes #4015.
/cc @leonid-s-usov as reporter
=> Check error when creating local storage directory

commands/command_filter_process.go, t/t-cherry-pick-commits.sh
**Describe the bug**
You can receive the `panic: send on closed channel` error while cherry-pick several commits and lfs files are not presented in the cache.
The current `filter-process` realisation assumes that when the `list_available_blobs` command is received from GIT `smudge` command won't be  issued:  
https://github.com/git-lfs/git-lfs/blob/c3b776db6ee273a6c231f9d5922e3aa3421b7b3e/commands/command_filter_process.go#L124
But cherry-picking of several commits with LFS files demonstrate different behavior. It seems that GIT creates single long running process filter which is used for the entire life of a single Git command:
https://git-scm.com/docs/gitattributes#_code_filter_code
As a result GIT LFS can receive several `smudge` commands within single `filter-process`. The panic error …
=> commands/command_filter_process: cherry-pick of several commits cause panic error

.github/workflows/ci.yml, .github/workflows/release.yml, tools/util_generic.go, tools/util_linux.go
This series allows us to stop using cgo on amd64 Linux, which makes our binaries static and therefore portable to musl-based systems.  The commit messages explain more in detail.
The constant was generated using a throwaway C program.
Fixes #4025.
=> Stop using cgo on amd64 Linux

docs/man/git-lfs-migrate.1.ronn
We've long had the option "--yes" to migrate noninteractively, but have never documented it.  Document what it does, and warn users that reckless use may cause data loss to avoid potential user sadness.
Fixes #4021
/cc @woopla as reporter
=> docs: document git lfs migrate --yes

README.md
Some folks aren't familiar with the signed SHA-256 sums file we use, or aren't sure how to get the keys to verify releases.  To help them, point them to the tag we've created that contains the keys (similar to the way Git does this) and add an explanation to the README to help them verify the releases.
Currently, I'm the only core team member with keys, so I'm the only one with keys in the tree.  If other folks add keys to their GitHub profile, ping me and I'll rewrite the tag.  I've opted to use a tree instead of the blob that Git uses (git/git's `junio-gpg-pub`) because I can't find a way to let people download a tagged blob from GitHub, while tagged trees do work.
Fixes #4018
=> README: explain how to verify releases

t/cmd/lfstest-gitserver.go, t/t-upload-redirect.sh, tools/copycallback.go, tq/basic_upload.go
In our infra, there is this peculiar situation where lfs upload request would be redirected to our lfs server. 
Even though redirect requests are handled by git-lfs by rewinding request body and creating a new http request for retry, the underlying http module closes the file handle upon request completion. 
So, retry would always fail with error like
`
< HTTP/1.1 307 Temporary Redirect
< Content-Length: 0
< Authorization: dontcare
< Content-Type: application/octet-stream
< Cookie: hadoop.auth="u=git-lfs&p=git-lfs@kerberos.gerrit.inc&t=kerberos-dt&e=1582650048997&s=N9xsabgxNkzMjXH0lWKuzK8646A="
< Date: Tue, 25 Feb 2020 07:13:38 GMT
< Location: http://ubuntu:14000/webhdfs/v1/user/git-lfs/a9/e0/a9e064317304049e503f0a7906d573695d4cbf7c89e7b2059117e72eae3fac77/?op=CREATE&data=true&replication= …
=> fix upload retry 'file already closed' issue'

docs/man/git-lfs-config.5.ronn
The LFS extension keys are not considered safe by Git LFS so attempting to put them in `.lfsconfig` results in such warnings:
```
WARNING: These unsafe lfsconfig keys were ignored:
lfs.extension.gzip.clean
lfs.extension.gzip.smudge
```
=> Removed lfs.extension.* from list of supported keys for .lfsconfig

commands/command_dedup.go, docs/man/git-lfs-dedup.1.ronn, t/t-dedup.sh
We add checks to the `git lfs dedup` command and its `-t` test option variant which cause the command to exit immediately with an explanatory message if any Git LFS extensions are configured.
This is because extensions normally cause the LFS storage object files to be altered in some way (for example, by compressing them), and so the object storage files can not be used as one-to-one copy-on-write clones (via filesystem reflinks) in the working tree, or else users would see unexpected file contents.
Fixes #4043.
/cc @swisspol as reporter
=> fail dedup command with explanation when LFS extensions configured

Makefile, docs/man/git-lfs-post-commit.1.ronn, docs/man/git-lfs.1.ronn
Add a man page for `git-lfs-post-commit(1)` which largely parallels the `git-lfs-post-merge(1)` one, as they have similar purposes for Git LFS, namely, to ensure all tracked lockable files are marked read-only in the working copy.
This PR also updates the list of porcelain and plumbing commands in the main Git LFS man page, adding those which were missing (except for the deprecated `git-lfs-clone(1)`), including the `git-lfs-post-commit(1)` command.
Fixes #4048.
/cc @swisspol as reporter.
=> add man page for the post-commit hook command

subprocess/subprocess.go, t/t-submodule-recurse.sh
Users of the Git configuration option **`submodule.recurse = true`** currently get errors when working in repositories with **at least one Git-LFS-enabled submodule.**
I suggest fixing this by **removing the `GIT_INTERNAL_SUPER_PREFIX` environment variable** from the environment that Git LFS passes to Git child processes.
Git’s configuration option `submodule.recurse` makes it more convenient to use submodules. If set to `true`, top-level checkouts will recurse into all submodules. Additionally, Git will pass an environment variable called `GIT_INTERNAL_SUPER_PREFIX` to the respective submodule’s path relative to its parent repository to each child process, including `git lfs filter-process`.
In turn, Git LFS spawns a couple of Git processes, for instance, when checking the minimum …
=> Support submodule.recurse = true

commands/run.go
If the user invokes "git-lfs --help", we tell them that there's no usage text found for "--help".  This isn't very helpful.  Since what the user probably wanted was to invoke the general help output, let's do that by rewriting the command to "git-lfs", which is the topic for the general help output.
Fixes #4057
/cc @austintraver as reporter
=> commands: print help output with --help

lfshttp/client.go
There are some TLS servers that want to perform a renegotiation to request users use a client certificate.  Allow us to use renegotiation as a client when making a TLS connection.  The DoS potential for this is low, since the server must not only perform another key exchange, but must re-sign the request, leading to a larger performance impact on the server than the client.
Fixes #4062 
@manishgo, can you please test this commit and see if it works for you?  If you need binaries, they should be available for download from the CI builds.
=> lfshttp: allow renegotiation

.github/workflows/ci.yml
When we build artifacts on Windows, we invoke make with -B, which runs all targets regardless of whether they're up to date.  With the upgrade to Go 1.14 on our GitHub Actions services, it looks like for some reason that we can't overwrite the generated man page file in our generate command.  When this occurs, the output looks like so:
```
go generate github.com/git-lfs/git-lfs/commands
Failed to create go file: open ..\commands\mancontent_gen.go: Access is denied.
exit status 2
commands\commands.go:28: running "go": exit status 1
```
The exact reason for this is unknown, since it doesn't appear on a test VM.  It also didn't appear in older builds using Go 1.12.7, but it's unclear if this is due to the Go version or just an upgrade of the Actions VMs that included some other change. …
=> workflows/ci: delete inaccessible file

script/packagecloud.rb
Add several new distros and remove several EOL distros from the versions we upload packages for.
Fixes #4056.
=> Update list of distros for packagecloud.io

commands/command_clone.go, commands/command_fetch.go, commands/command_ls_files.go, commands/command_migrate.go, commands/command_pull.go, commands/commands.go, commands/commands_test.go, t/t-ls-files.sh
Currently, if a user runs `git lfs ls-files` with lfs.fetchexclude set to `*`, then all files are excluded from the output.  This doesn't make much sense, since the lfs.fetchinclude and lfs.fetchexclude options are documented to work only on fetches.  Let's ensure that we don't load the fetch filters by default when performing a non-fetch operation so that `git lfs ls-files` isn't affected by these exclusions.
I'm leaving this as a draft for the moment because our CI is temporarily broken on Windows; I'll rebase onto `master` once the PR fixing it is merged.
Fixes #4081
/cc @billsacks as reporter
=> commands: don't honor lfs.fetch* for ls-files

Makefile, lfsapi/endpoint_finder_test.go, lfshttp/endpoint.go, lfshttp/standalone/standalone.go, t/cmd/util/testutils.go
The PR attempts to refine a number of related issues with the Go test suite and the `make test` Makefile target.
The `make test` target is adjusted so that it depends on the local `bin/git-lfs[.exe]` binary being built first, and then the Go tests are run with `-count=1` so no caching of results is done between invocations.  (A developer wishing for Go's default caching of package list results can use `go test ./...` instead of `make test`.)
The common test utility package in `t/cmd/util/testutils.go` is given an `init()` function which attempts to ensure that the first path in the `PATH` environment variable's list is an absolute path to the working tree's `bin` directory.  This prevents the tests, when they run `git-lfs` as a system command, from accidentally using whatever `git-lfs` …
=> make Go tests run consistently using local binary

commands/command_migrate_import.go, t/t-migrate-import.sh
When we specify the --exclude option to git lfs migrate import to exclude certain patterns, we currently specify the files as text. However, in many cases, the files are not text, so it doesn't make sense to set them that way.
Let's set the text attribute to unspecified instead and let Git automatically figure out whether the file should be treated as text or binary.  That's at least less likely to result in silent breakage and will likely be less surprising to the user.
Fixes #4067 
/cc @woopla as reporter
=> migrate import: set text to unspecified for excluded fields

git/git.go, t/t-migrate-fixup.sh
When invoking "git lfs migrate import --fixup", we call Git to fetch the remote branches and tags.  However, we mark both as having the type remote branch, so when we look up the local copies for them, we try to use the tag name as the name of a remote tracking branch, which fails.
Instead, let's mark them as remote tags, which means we won't try to rewrite them into branches at all.  This ensures the operation can succeed.
Fixes #3818
=> git: avoid trying to rewrite remote tags as remote branches

.github/workflows/ci.yml, .github/workflows/release.yml, docker/run_dockers.bsh, rpm/build_rpms.bsh
At the moment, we're running out of disk space when building packages in Docker containers.  This is because our CI VMs have only 14 GB of storage.  To help deal with this problem, let's add an option to the run_dockers.bsh script to prune images after using them so we can free some of that disk space and let the remaining jobs complete.
=> CI: prune unused Docker images after use

git/rev_list_scanner.go, git/rev_list_scanner_test.go, t/t-pre-push.sh
If a user attempts to force-push over a ref and we don't currently have the object that the reference currently points to, our pre-push hook will fail with a message like the following:
```
ref foo:: Error in git rev-list --stdin --objects --not --remotes=origin --: exit status 128 fatal: bad object 1aabb695d63c4d4afe731ab69573893390526896
```
This occurs because we pass the existing object name to git rev-list as something to exclude.  Normally, this is a good idea, since it means we can short-circuit the traversal since we already know what the other side has.  However, in this case, it causes unwanted problems.
What we really want is for Git to just ignore an object if it's bad, and fortunately the rev-list `--ignore-missing` object does exactly this, so let's use it.  Note that we …
=> git: avoid "bad object" messages when force-pushing

script/build-git
Due to recent Homebrew changes, our CI builds of Git [failed](https://github.com/git-lfs/git-lfs/pull/4109#issuecomment-619814598) with a [missing](https://github.com/git-lfs/git-lfs/runs/621615779) `gettext` dependency.  While the upstream [issue](https://github.com/Homebrew/homebrew-core/issues/53485) may have been [resolved](https://github.com/Homebrew/homebrew-core/pull/53489), we can simply avoid the problem entirely by building Git without `gettext`.
See also https://lore.kernel.org/git/20200426200932.3769-1-tboegi@web.de/
=> script/build-git: compile without gettext on macOS

commands/command_pre_push.go, git/git.go, git/git_test.go, t/t-pre-push.sh
Some users use tools like JGit, which use URLs instead of named remotes when invoking the pre-push hook.  This is problematic because we use remote-tracking branches to optimize our ref walk and when a user is using a URL, we can't apply that optimization since we don't know which named remote is being used.
However, if we have a named remote with only one URL, we can apply this optimization by looking up the remote name and using that as our remote instead.  We do this only in the pre-push hook, since this is the major time that we need to walk the history.
Add some unit and integration tests for this and also update one of the existing integration tests which was relying on the previous behavior by switching it to use an equivalent URL instead of the actual remote URL.
=> pre-push: find named remote for URL if possible

commands/command_migrate.go
Default hint ([Y/n]) wasn't being honored - 'y' is now default.
=> commands/command_migrate.go: fix bug

CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v2.11.0, which is scheduled for Friday, May 8, 2020.
[git-lfs-darwin-386-v2.11.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/4587976/git-lfs-darwin-386-v2.11.0-pre.tar.gz)
[git-lfs-darwin-amd64-v2.11.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/4587977/git-lfs-darwin-amd64-v2.11.0-pre.tar.gz)
[git-lfs-freebsd-386-v2.11.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/4587979/git-lfs-freebsd-386-v2.11.0-pre.tar.gz)
[git-lfs-freebsd-amd64-v2.11.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/4587981/git-lfs-f …
=> release: v2.11.0

commands/command_lock.go, locking/locks.go, t/t-lock.sh, t/t-unlock.sh
The lockPath sanitization was slightly amended to allow os.Stat() to fail. All other conditions, such as testing to see if it's a directory were retained.
If a lock is obtained, attempting to set it writable only occurs if the file exists.
=> Allow locking and unlocking non-existent files

Makefile, t/testenv.sh
In several places in our test suite, we have behavior such that our tests fail either due to the global or system config or the locale in use.  Adjust our integration tests to run in the `C` locale and our unit tests to set the environment appropriately so that they are no longer affected by global or system config.
Fixes #4121 and fixes #4122 
/cc @slonopotamus as reporter
=> Improve test suite robustness via environment

git/githistory/ref_updater.go, t/t-migrate-import.sh
We avoid rewriting references that we've already seen, since in some cases we will need to order references to properly handle tags pointing to tags.  However, we use ref.Name for this, which is the short name, not the full refspec.  Consequently, if we've already seen a ref with the same short name (e.g., a branch when we're processing a tag), we end up skipping the second ref.
This is not what we want, so let's use the full refspec when populating the set of items we've already seen.
Fixes #4120
/cc @karlhendikse as reporter
/cc #3238, which may be fixed by this
=> git: consider full refspec when determining seen refs

locking/lockable.go, t/t-post-checkout.sh
When we get paths from git.GetAttributePaths, the paths are in the system native format; that is, they use the system native path separator.  However, when creating patterns, we always want to use a slash.  As things stand right now, lockable patterns that use a slash never match on Windows.
Convert the patterns to use a slash so that lockable patterns work as expected on Windows.
Fixes #3781.
=> locking: make patterns with slashes work on Windows

.github/workflows/ci.yml, .github/workflows/release.yml, Makefile, docs/man/mangen.go, script/macos/manifest.json
Apple complains if a binary is downloaded from the Internet but has not been signed and notarized as of macOS Catalina.  Because this is an impediment for users, let's fix that.
This series contains several different patches:
1. We now build with Go 1.14 in CI in addition to other versions.
2. We no longer build i386 Darwin binaries since we can't notarize those.
3. We build the Darwin release assets as a zip file, since we can't notarize a tarball.
4. We build Darwin binaries on Darwin instead of Linux for releases.
5. We sign and notarize binaries.
Each patch contains a description of what it does and why it's valuable.
Currently we use my (GitHub) Apple ID as the actor for notarization plus an app password.  This value will be stored in the secret store for Git LFS so it can be changed …
=> Sign and notarize binaries on macOS

Makefile
As a followup to commit 1d4e46b311a3 in PR #4132, we ensure any files created during the `make test` build can be fully deleted by setting the user write permission bit.  Otherwise, at least on macOS, some Go modules' files are installed in directories with read-only permissions, and the final `rm -fr` cleanup is then unable to remove those files, leading to lots of spurious error messages.
=> Makefile: ensure temp Go modules can be deleted

commands/command_install.go, commands/command_uninstall.go, config/config.go, docs/man/git-lfs-install.1.ronn, docs/man/git-lfs-uninstall.1.ronn, git/config.go, lfs/attribute.go, t/t-install-worktree-unsupported.sh, t/t-install-worktree.sh, t/t-install.sh, t/t-uninstall-worktree-unsupported.sh, t/t-uninstall-worktree.sh, t/t-uninstall.sh
We add support for the `--worktree` option in the Git LFS installation and uninstallation commands, when it is supported by [`git-config(1)`](https://git-scm.com/docs/git-config) (i.e., with Git version 2.20.0 and higher).
Note that when used in a single working tree environment, `--worktree` has the same effect as `--local`; this is due to the way `git-config(1)` handles the option.
We add tests for a variety of conditions such as repositories with single and multiple working trees, and with and without the [`extensions.worktreeConfig`](https://git-scm.com/docs/git-worktree#_configuration_file) Git configuration setting.  We also expand and align some of our existing installation and uninstallation tests to make them more complete and consistent with each other.
Of note, we also change …
=> add --worktree option to install and uninstall commands

filepathfilter/filepathfilter.go, locking/lockable.go, t/t-unlock.sh
Whenever we use a file path filter and there are no included patterns, we default to assuming the files match.  For many cases, this is fine, but this is not useful for checking whether a file is lockable: if no files are listed as lockable, then no files are lockable.
Let's add an option for our filters to specify the default value if no patterns match.  If that default is false, like it should be for locking, then skip traversing the exclude patterns altogether, since anything that's not included cannot change the result.  We test both the case that lockable patterns are present and absent in our test.
Fixes #4169
=> Don't mark unlocked files that aren't lockable as read-only

t/t-install-worktree.sh, t/t-uninstall-worktree.sh
In some of our worktree code, we use configuration options under the extensions hierarchy.  In upstream Git, unknown extensions are rejected if the repository format version is 1; this format version is otherwise identical to version 0.
Until recently, Git would accept extensions with a repository format version of 0, but fail to reject unknown extensions.  However, this could cause serious problems with the repository, so it was recently fixed to ignore all extensions in repository format 0.
These tests set extensions.worktreeConfig without setting the repository format version, and consequently they fail with the latest versions of Git.  Let's set the version appropriately so that our tests continue to work.
I just happened to see the relevant patch series hit the main branch upstream …
=> t: use repo v1 with extensions

git/config.go, subprocess/cmd.go, subprocess/subprocess.go
Trace all command execution at the time when the command starts. Previously, only "simple" execution created trace entries, leading to mysterious gaps in trace logs where time passed but it looked like nothing was happening.
An alternate approach might be to log the trace line when the `subprocess.Cmd` is created. in `newCmd`. If commands are always executed right after creation, that might be enough and it avoids overriding the additional methods from `os/exec.Cmd`.
=> subprocess: trace all command execution

git/git.go, lfs/gitscanner_remotes.go
When repositories have a large number (hundreds of thousands) of refs, Git LFS adds noticeable overhead on the time taken by `git show-ref` and `git ls-remote`. To reduce this overhead:
* Avoid regular expressions when parsing lines of Git command output. Regexp evaluation was the most expensive part of this process in profiling.
* Minimize the number of loops when computing skipped refs by combining the missing and skipped checks and converting the list of remote refs into a pre-filtered set.
In a repository with ~300k remote references, these changes reduce the time spent in the `pre-push` command from 8.26s to 6.31s. The individual optimizations were identified and verified with pprof.
I'm happy to break these up into two separate PRs or commits if that's preferred.
=> git: improve performance of remote ref listing

.github/workflows/ci.yml, git/git.go
By replacing a call to `os.ProcessState.ExitCode()`, which is only available in Go 1.12, with a slightly more complicated use of `os.ProcessState.Sys()` and `syscall.WaitStatus.ExitStatus()`, we can still support Go 1.11.  Therefore we also add 1.11 to the set of Go versions we build in CI (on Linux only, though).
Because `syscall.WaitStatus.ExitStatus()` is available on both Unix and Windows, we should not lose any OS support with this change; see also this answer to a related Stack Overflow [question](https://stackoverflow.com/questions/10385551/get-exit-code-go).
Note that an alternative, which simply sets our minimum Go version in `go.mod` to 1.12, is proposed in #4182.  We should adopt either this PR or that one, but not both.
Fixes #4179.
/cc @andrewarchi as reporter (and who …
=> allow Go 1.11 builds by using WaitStatus.ExitStatus()

.github/workflows/ci.yml, docs/man/git-lfs-config.5.ronn, script/cibuild
This series addresses a couple of problems with our CI system.
* First, our trailing whitespace check was not functional, so there's a commit to remove the trailing whitespace that's crept it and one to fix the check.
* Second, Git for Windows 2.27.0 introduced a bug that, with the configuration used by GitHub Actions, causes all symlinks to be perpetually marked modified, causing our formatting check to fail.
The commits are, as usual, logical and bisectable with sane commit messages.
=> Fix Windows CI

config/config.go, docs/man/git-lfs-config.5.ronn, git/config.go, t/t-config.sh
Currently we only read .lfsconfig from the working tree.  This is better than nothing, but it means that if there's an LFS file that starts with a name earlier than .lfsconfig, we won't read the proper config file, and we won't use any LFS remote URLs that are located in that file.
If the file is missing, let's additionally read from the index, if there's a working tree, and then from HEAD.  If the repository is bare, let's just read from HEAD.  This is very similar to what Git does for .gitmodules.
It does, however, differ in one significant way: Git will read from the index first if it's doing a checkout, since that might have newer information.  We don't do that here, since it's not totally clear that we can articulate all the cases where that occurs in Git LFS, but we explicitly allow …
=> config: optionally read .lfsconfig from the repository

fs/cleanup.go, tools/filetools.go
If the user tries to run certain commands, such as `git lfs track`, in a repository where they lack sufficient permissions, we can hang when attempting to clean up temporary files if the temporary directory is missing and we lack permissions to create it.  Let's fix that hang by closing the channel we're waiting on when there's an error, and let's clean up the error message that comes up if the temporary directory doesn't exist.
The commit messages for each commit describe the situation in more detail.
There are no tests for this case because it's difficult to do without having multiple users, and of course we don't want to assume that the test suite has root privileges to do that.
Fixes #4205
/cc @rphodges as submitter
=> Fix hang when the user lacks permissions

docs/api/locking.md
=> docs/api/locking: add an explicit <br>

CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v2.12.0, which is scheduled for Monday, August 31, 2020.
[git-lfs-darwin-amd64-v2.12.0-pre.zip](https://github.com/git-lfs/git-lfs/files/5131258/git-lfs-darwin-amd64-v2.12.0-pre.zip)
[git-lfs-freebsd-386-v2.12.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/5131261/git-lfs-freebsd-386-v2.12.0-pre.tar.gz)
[git-lfs-freebsd-amd64-v2.12.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/5131262/git-lfs-freebsd-amd64-v2.12.0-pre.tar.gz)
[git-lfs-linux-386-v2.12.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/5131265/git-lfs-l …
=> release: v2.12.0

.github/workflows/ci.yml, .github/workflows/release.yml, Makefile
In general, it would be nice to include pre-built manual pages in the release archives, both in the normal troff format and as HTML.  They're already baked into the binary as help output, but for some folks, `man` is easier to use.
This PR includes the manual pages in the archives and sets up the CI system to make sure Ruby and `ronn` are installed so we can build the release assets on every platform.  During the Windows CI run, we don't explicitly run `make release`, so call `make man` so we test that they can be built there.
Fixes #4228
/cc @lunaryorn as submitter
=> Add manual pages to release assets

t/t-env.sh, tools/os_tools.go
When we look up the repository path from Git, we pass it through cygpath -w to canonicalize it into a Windows path, since Cygwin's Git will give us a Unix-style path.  We perform path canonicalization not only on Cygwin, but also on MINGW as well, which include Git Bash, since we want to accept and canonicalize Unix-style paths there as well.
Normally, this works great.  However, if invoked not from Git Bash, but via the Git for Windows bash.exe command, no locale is set in the environment, despite the locale binary indicating UTF-8 locales.  As a result, if non-ASCII character exist in the path name, it tries to encode them in ISO-8850-1.
On a standard Unix, where paths are always bytes, defaulting to ISO-8859-1 might be fine, because regardless of the encoding, paths are always bytes …
=> tools: always force a UTF-8 locale for cygpath

README.md, SECURITY.md
Following the GitHub [template](https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository#about-security-policies) for adding security policies for open-source projects, we add a `SECURITY.md` file which describes the relevant policy for the Git LFS client, as well as providing links to related resources and general information.
In order to facilitate reports of security vulnerabilities via secure email, we also add to the core team roster on our home page links to the PGP keys of each active team member.
Note that once we adopt this PR into this main `git-lfs/git-lfs` repository, we may also want to consider adding a slightly modified version of `SECURITY.md` to our other repositories for Go module dependencies of the main project …
=> add documentation of security bug report process

CONTRIBUTING.md, README.md
We have some frequently asked questions that we get, so I've written up a FAQ on the wiki.  Let's add a link to the FAQ in the README and CONTRIBUTING documentation to help users find it more easily.
In addition, rephrase a part of the contributing documentation which uses language similar to a well-known political campaign.  We don't want people to associate our project with any political campaign, since such associations are irrelevant and distracting.
=> Add FAQ to README and CONTRIBUTING

go.mod, go.sum, tools/util_darwin.go
Previously, trying to compile `util_darwin.go` against a recent version
of `golang/sys` library failed with:
```
util_darwin.go:127:3: undefined: unix.SYS_CLONEFILEAT
```
Go v1.12 removed the ability to use direct syscalls. The clonefile
system calls was added to the latest `golang/sys` in
https://github.com/golang/go/issues/41366, so we can use that now.
=> tools/util_darwin.go: Remove use of direct syscalls

script/build-git
GitHub Actions ships its own version of the openssl Homebrew package that fails to reinstall with an EPERM error.  Since the reason we did these contortions was to relink gettext and we finally gave up and disabled gettext, let's just go back to a brew link --force and stop trying to reinstall.
=> ci: don't reinstall openssl with Homebrew

lfshttp/proxy.go, lfshttp/proxy_test.go
Go currently doesn't support the socks5h protocol, but it does know how to handle it if given a URL starting with socks5:// instead.  Let's rewrite the URLs internally to make things just magically work.
Fixes #4258.
=> lfshttp: add support for socks5h proxies

.github/workflows/ci.yml
We'd like to make sure that our code works with SHA-256 Git repositories, so when we build with the latest Git, let's test with SHA-256 repositories.
=> workflows/ci: build latest Git with SHA-256

commands/command_pre_push.go, docs/man/git-lfs-config.5.ronn, docs/man/git-lfs-pre-push.1.ronn, t/t-pre-push.sh
As described in #3721, it is sometimes useful to allow temporarily disabling Git LFS functionality when doing `git push`, for example when pushing to a remote that doesn’t support Git LFS.
This pull request also slightly improves the documentation on the `pre-push` Git LFS hook.
Fixes #3721.
=> Add GIT_LFS_SKIP_PUSH to allow skipping the pre-push hook

script/upload
Ruby's `URI.escape` is now deprecated because different components of a path require different escaping rules.  However, we still want to perform a similar escaping style, so let's do it ourselves with a `String#gsub` call.  We could use `CGI.escape`, but that encodes spaces as plus signs and it's unclear whether that's a desirable change to make here.  Note that there are no negative consequences for encoding more data than we need to, since the server will decode it for us.
Fixes #4226
=> script/upload: avoid using Ruby's URI.escape

config/url_config.go, config/url_config_test.go
When Git performs a lookup for a key with urlmatch semantics, it matches the default port if none is specified in the URL.  However, our code currently doesn't do that, instead having a missing port match only another missing port entry.
Let's fix the behavior to match Git's by mapping a missing port to the default port.  We add tests for checking both URLs (the config one and the one we're sending data to) to make sure that our code is robust.
Fixes #4281
/cc @slietzau as reporter
=> config: map missing port to default for HTTP key lookups

commands/command_checkout.go, commands/command_clone.go, commands/command_dedup.go, commands/command_env.go, commands/command_fetch.go, commands/command_fsck.go, commands/command_install.go, commands/command_ls_files.go, commands/command_migrate.go, commands/command_migrate_export.go, commands/command_pull.go, commands/command_status.go, commands/command_track.go, commands/command_untrack.go, commands/command_update.go, commands/commands.go, commands/run.go, git/git.go, lfs/lfs.go, subprocess/subprocess.go, subprocess/subprocess_nix.go, subprocess/subprocess_windows.go, t/t-checkout.sh, t/t-untrack.sh, tools/filetools.go
Currently, we don't honor GIT_WORK_TREE like Git does.  Git implicitly changes into the working tree of the repository if this variable is set, but we currently don't do that.
Let's fix that by mimicking Git's behavior so this works correctly, which necessitates transforming the various environment variables we pass to Git so that they are valid when we change directories.
These commits are logical, bisectable, and independent and have sane commit messages.
Fixes #4213
/cc @Mr-Tao as reporter
=> Honor GIT_WORK_TREE

commands/pull.go, t/t-pull.sh
When a merge conflict occurs, it obviously isn't possible to check out the file using git lfs checkout or git lfs pull, since it's unclear which revision the user wants.  git lfs checkout handles this gracefully by just ignoring the conflict, whereas git lfs pull causes a full logged error, which is excessive.
Let's make git lfs pull match the behavior of git lfs checkout here by having it ignore malformed pointer files just like it ignores files that are not pointers.
Fixes #1608
=> pull: gracefully handle merge conflicts

tools/robustio_windows.go
Use ERROR_SHARING_VIOLATION defined in the golang.org/x/sys/windows
package instead of duplicating it in robustio_windows.go.
=> tools: use ERROR_SHARING_VIOLATION const from golang.org/x/sys/windows

commands/command_migrate.go, commands/command_migrate_import.go, docs/man/git-lfs-migrate.1.ronn, t/fixtures/migrate.sh, t/t-migrate-import.sh
The purpose is to allow users to tell git-lfs to migrate
all files over a particular threshold without having to determine
the various paths and patterns that would. This is very useful
for large code bases with inconsistent history of adding large
files in different places. This option makes it possible to
supply `git-lfs migrate import --everything --above=1Mb` and
have git-lfs do the convenient thing and rewrite history. 
Issue #4275
=> Add --above parameter to 'migrate import'.

filepathfilter/filepathfilter.go, git/attribs.go, t/t-migrate-import-no-rewrite.sh
Currently we use a slightly different algorithm for matching certain wildmatch patterns for backwards compatibility with earlier versions of Git LFS.  However, that algorithm causes some problems with not matching various patterns that Git does match.  To improve our correctness here, let's introduce a strict mode and use it when we're reading patterns from .gitattributes.
This series contains [logical, bisectable commits](https://git-scm.com/docs/SubmittingPatches#separate-commits) with [descriptive commit messages](https://git-scm.com/docs/SubmittingPatches#describe-changes).  Note that you may want to review with whitespace changes disabled, since there are some indentation-only changes.
Fixes #4203.
=> Fix pattern matching for .gitattributes

.github/workflows/ci.yml, .github/workflows/release.yml
We had these commands to work around a problem with an earlier GitHub Actions image not finding the expected Git binaries, but they are no longer necessary.  In addition, GitHub Action now fails our commands because honoring these options causes a security problem, so our CI jobs are failing.  Let's remove them since they're no longer needed nor useful.
=> .github/workflows: remove special ::add-path commands

fs/fs.go, t/t-push.sh
Previously, we'd panic when trying to slice into the object ID if the user provided a too-short object ID on the command line.  Instead, let's fix this so we reject too-short object IDs with an error.
Fixes #4303 
/cc @sluongng as reporter
=> fs: don't panic when using a too-short object ID to push

commands/command_migrate_import.go, t/fixtures/migrate.sh, t/t-migrate-import.sh
Currently, if we have a file and it contains an extension, we'll add that extension to the list of paths that should be placed in .gitattributes.  However, if the file does not contain an extension, it won't be listed at all.  As a result, we may convert a file flagged by the --above option but never cause Git to filter it properly.
Let's fix this by writing an attribute into the repository with the path relative to the root if we don't contain an extension.  This means that people can store typical Unix binaries, which lack extensions, as LFS files more easily.
In addition, there is a commit to clean up a thinko in the existing test.
/cc @ansman as reporter
Fixes #4312
=> Make git lfs migrate import handle missing extensions

docker/run_dockers.bsh, script/packagecloud.rb, script/upload
This PR drops support for CentOS 6 and Debian 8, which are no longer publicly supported upstream.  While various versions do have extended security support available, we can't access it, and it doesn't seem like a good idea (or responsible to the rest of the Internet) for us to continue to build packages on versions that are known to be insecure.
This also makes our CI runs significantly faster, since we currently build many packages for CentOS 6 that we can now avoid building.  We've shaved 15 minutes off of our build time for Linux packages.
We also add some additional distros that are not in the file.  Note that we don't support Fedora 33 because packagecloud.io does not list it as a supported version at this time.
=> Drop obsolete OS support

CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v2.12.0, which is scheduled for Thursday, December 10, 2020.
[git-lfs-darwin-amd64-v2.13.0-pre.zip](https://github.com/git-lfs/git-lfs/files/5655390/git-lfs-darwin-amd64-v2.13.0-pre.zip)
[git-lfs-freebsd-386-v2.13.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/5655391/git-lfs-freebsd-386-v2.13.0-pre.tar.gz)
[git-lfs-freebsd-amd64-v2.13.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/5655392/git-lfs-freebsd-amd64-v2.13.0-pre.tar.gz)
[git-lfs-linux-386-v2.13.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/5655393/git-l …
=> release: v2.13.0

Makefile
zip has an interesting feature: if there is nothing to do, it exits 12. Since in our macOS release CI target, we build the same asset multiple times due to using two separate invocations of make, we end up with a case where zip exits 12 unexpectedly.
Ideally make would realize that our assets don't need to be rebuilt, but as long as we're going to rebuild them, let's remove the existing file so zip doesn't get bent out of shape about the fact that our operation isn't doing anything useful.
This caused the v2.13.0 release job to fail, so I'll need to do a v2.13.1 with this change.
=> Makefile: don't fail the second time macOS builds are built

CHANGELOG.md, Makefile, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v2.12.0, which is scheduled for Friday, December 11, 2020.
I'm not providing binaries here because this is a very simple bug fix for a CI problem that prevented us from releasing v2.13.0.  Therefore, it should not function any differently from v2.13.0 other than containing a different version number.
The CI system will produce artifacts for Windows, Linux, and macOS if you need some test binaries.
/cc @git-lfs/implementers
/cc @git-lfs/releases
=> release: v2.13.1

Makefile
We recently fixed a problem with the macOS target to make it possible to build a second time after running `make release`, but we forgot a Windows target as well.  Let's make it possible to run that command twice in a row.
=> Makefile: allow make release to be run twice in a row

lfshttp/client.go, t/cmd/lfstest-gitserver.go, t/t-push.sh
Since we're uploading and downloading a large amount of data, we may prefer to use transport compression.  Currently, Go will do this for us automatically unless we ask it not to.  Let's detect this case and add a trace output so people can find it and we can add a test that it continues to work.
Note that it's not possible to detect this using the headers since Go adds the headers on the request and strips the headers on the response as part of making the request, so it's not readily apparent to users without this trace output.
=> Add test for download gzip transport compression

docs/man/git-lfs.1.ronn
When the file is rendered in the browser the numbers in the numbered list are automatically corrected, while when the file is shown in the command line the numbers are wrong.
=> Fix numbered list in git lfs examples

go.mod, go.sum, vendor/github.com/git-lfs/gitobj/v2/SECURITY.md, vendor/github.com/git-lfs/gitobj/v2/commit.go, vendor/github.com/git-lfs/gitobj/v2/pack/index.go, vendor/github.com/git-lfs/gitobj/v2/pack/index_v1.go, vendor/github.com/git-lfs/gitobj/v2/pack/index_v2.go, vendor/github.com/git-lfs/gitobj/v2/pack/packfile.go, vendor/github.com/git-lfs/gitobj/v2/tree.go, vendor/modules.txt
Bump the revision of gitobj to v2.0.1 to pick up the fixes in git-lfs/gitobj#23.
=> gitobj 2.0.1

commands/command_prune.go, docs/man/git-lfs-prune.1.ronn, lfs/config.go, t/t-prune.sh
Some users really want to minimize the amount of data they store on the local system, especially for large checkouts.  Let's add two options, --recent and --force, the former which ignores the recency settings and the latter which additionally prunes objects which are currently checked out.  We will never prune objects that are unpushed, even with these options, including stashed objects.
Add tests and documentation for both of these options.
Fixes #4367
/cc @Pierre-Bartet as reporter
=> prune: add options to be more aggressive about pruning

.github/workflows/ci.yml
Git for Windows 2.27.0 had a bug where symlinks would appear perpetually modified when core.fscache was enabled, causing our CI job to fail because it looks for modified files after running the formatter. However, a newer version of Git is now available and our old code is failing, so let's remove it and use the newer version of Git that's shipped by default.
=> .github/workflows: don't try to install older Git

lfshttp/proxy.go, lfshttp/proxy_test.go
If a user has a proxy using HTTP but a URL using HTTPS, we fail to honor the http.proxy configuration setting because we check the scheme of the proxy URL, not the scheme of the request URL.  Let's fix this by deciding which proxy variable to set based on the request URL, as was probably intended, rather than the proxy URL.
Add some tests for this case, as well as the case that we correctly ignore the HTTPS_PROXY environment variable if the scheme of the request URL is HTTP, which we were previously lacking.
/cc @bhilton (as submitter)
Fixes #4392
=> Consider scheme of request URL, not proxy URL, when choosing proxy

lfs/gitscanner_log.go, t/t-prune.sh
Certain file paths are associated with diff textconv patterns with Git for Windows, and these are invoked by default when using git log. However, when we're using git log to scan data to find LFS objects, we don't want to invoke those programs.
Let's fix this by passing appropriate options to disabled these invocations.  In the test, we set the driver to false, since Git will fail if the process it calls also fails.
Fixes #4401
=> lfs: don't invoke diff drivers when pruning repositories

lfsapi/endpoint_finder.go, t/t-env.sh
Currently, we warn about aliases (e.g., `url.*.insteadOf`) when there's already an alias for the same URL; that is, when the `insteadOf` entry matches an existing one.  However, in some environments, multiple aliases are defined, but all to the same root URL (the one in the key).
In such a case, don't warn, since these aliases are already identical. Do continue to warn if the root URL is different at all, since these are different aliases for the same URL, and add a test for both of these cases.
/cc @kaelig as reporter
Fixes #4412
=> lfsapi: don't warn about duplicate but identical aliases

LICENSE.md, commands/command_lock.go, commands/commands.go, debian/copyright, lfshttp/standalone/standalone.go, tools/filetools.go, tools/filetools_nix.go, tools/filetools_windows.go
Git consistently uses canonicalized paths internally.  This is for many reasons, but mostly to verify that a single path is within a repository. In order to interoperate properly with Git, we need to canonicalize paths and do it in the same way as Git.
On Unix systems, to canonicalize a path, it is sufficient to make the path absolute and then resolve any symlinks.  Go provides two functions to do these two steps, filepath.Abs and filepath.EvalSymlinks, and they work as advertised.
Windows, however, has much more complex path handling and these functions do not handle all cases.  The typical way to canonicalize paths on Windows is using GetFinalPathNameByHandle, and this is the technique Git uses.
Go, however, does not provide a general API to canonicalize paths, unlike Rust's …
=> Canonicalize Windows paths like Git does

git/config.go, t/t-config.sh
Per `git-config`'s man page, `include.*` directives are not respected by default when asked to evaluate a specific file (whether via `--global`, `--file /path/to/.gitconfig`, or `GIT_CONFIG=/path/to/.gitconfig`).
This patch ensures that, if `GIT_CONFIG` is set in the environment when e.g. `git-lfs-push` is invoked, config directives from included files are evaluated.
This is important if, for example, an included file contains a `url.<foo>.insteadOf` directive or `lfs.<foo>.locksverify` directive that's shared between many repositories.
Before this change, with the following setup:
```
% git config --file /tmp/a.config -l
...
remote.origin.url=https://my-server-alias/foo/bar.git
include.path=/tmp/b.config
% git config --file /tmp/b.config -l
... …
```
=> invoke git-config with --includes to ensure it always evaluates include.* directives

lfs/pointer.go, lfs/pointer_test.go
This prevents a potential parameter injection that might result from
decoding an LFS pointer file with trailing characters in the OID.
=> Tighten LFS pointer regexp

CONTRIBUTING.md, README.md
This introduces two new pieces to our common Markdown files.
The first one covers uninstalling Git LFS, since that's a question that a lot of users have.  We now have an entry for it in the FAQ as well, so hopefully that documentation should be easier to find.
The second piece encourages users to use the discussions functionality for things that aren't bug reports or feature requests.  As outlined in the commit message, that allows askers to easily mark a correct answer, which both helps future users and also prevents those users from popping up in an issue asking for the canonical answer when one has been given.
Fixes #4426
=> Update README and Contributing docs

lfs/gitfilter_clean.go
When the `"clean"` filter processes a pre-existing LFS pointer blob, the `copyToTemp()` function returns a `CleanPointerError`; it does this when `DecodeFrom()` successfully reads and parses the pointer blob and when the entirety of the blob's contents have been read (i.e., there is no additional blob data to be read).
This latter check was originally introduced in commit e09e5e1000bdc890ff8b27f6f330bbdb980f232b in PR #271, when the relevant code was in the `Clean()` method in the `pointer/clean.go` file; it used the same 512 byte maximum to [determine](https://github.com/git-lfs/git-lfs/blob/e09e5e1000bdc890ff8b27f6f330bbdb980f232b/pointer/clean.go#L39-L42) if all the blob content had been read.  This was aligned with the size of the byte array …
=> Use blobSizeCutoff in clean pointer buffer length check

commands/command_migrate_info.go, t/fixtures/migrate.sh, t/t-migrate-import.sh, t/t-migrate-info.sh, tools/math.go, tools/math_test.go
This PR addresses some internal bugs and oversights in the `git lfs migrate info` command's handling of its `--top` option, and adds some tests to verify the correctness of these changes.
First, the `tools.ClampInt()` function does not always return a value between its `min` and `max` arguments because it reverses their meaning, and the relevant tests in the corresponding `tools/math_test.go` file do not report the problem because they do not execute when the `go test ./tools` command is run.  The latter bug is a result of the test functions lacking the necessary `Test*` prefix to be recognized by the Go `test` command.
After we fix the `ClampInt()` function, we rename all the test functions in tools/math_test.go to follow the `Test*()` naming scheme, which ensures they now run properly. …
=> Fix up handling of the "migrate info" command's --top option

lfs/gitscanner_catfilebatch.go, lfs/pointer.go
The `blobSizeCutoff` limit is [defined](https://github.com/git-lfs/git-lfs/blob/e2531f0e342bfc55320f50b9068fe83262f4cd16/lfs/scanner.go#L9-L11) such that "any file with a size _below_ this cutoff will be scanned" [emphasis added] when looking for LFS pointer blobs.  In general this is true, but there are few instances where the check is applied such that blobs matching the cutoff limit are also scanned.
We therefore adjust these to match the same comparison logic used elsewhere with this limit.
Two of [these](https://github.com/git-lfs/git-lfs/blob/e2531f0e342bfc55320f50b9068fe83262f4cd16/lfs/gitscanner_catfilebatch.go#L136-L139) [checks](https://github.com/git-lfs/git-lfs/blob/e2531f0e342bfc55320f50b9068fe83262f4cd16/lfs/gitscanner_catfilebatch.go#L153-L162) are in the …
=> Make all checks of blobSizeCutoff consistent

docs/man/git-lfs-clone.1.ronn, docs/man/git-lfs-fetch.1.ronn, docs/man/git-lfs-pull.1.ronn
Note in the documentation that -I and -X override their respective configuration settings so it's clear what behavior people can expect. Mention that setting either value to an empty string clears the value.
Fixes #4425
=> docs: note that -I and -X override configuration settings

lfs/gitscanner_log.go, t/t-prune.sh
When looking for Git LFS pointers in the Git stash in order to avoid pruning the corresponding local objects during a `git lfs prune` command (functionality which was added in #4209), we want to avoid looking further back in the Git log file than necessary; otherwise, we may potentially find many LFS object references which we should prune but incorrectly consider to be part of the stashes.
We therefore proceed in two steps; first looking solely at each stash entry's WIP merge commit using the command `git log -m --first-parent <stash-sha>^..<stash-sha>`, and then looking at each entry's index merge commit and possible additional untracked files merge commit using the command `git log <stash-sha>^..<stash-sha>`.  By limiting these commands' commit ranges to just the stash merge commits, …
=> Parse stash log entries parsimonously in prune command

docs/man/git-lfs-migrate.1.ronn, docs/man/mangen.go
We add a lengthy description section to the `it-lfs-migrate` man page to order to provide some context and general guidance on how and when the command should be used, as well as trying to explain several potentially non-intuitive concepts and encourage users to check their repositories thoroughly before and after attempting an import or export operation.
We also adjust some formatting details in the page, fix some typos, and make other minor revisions to suggest using the `--all` option when force-pushing after importing with `--everything`, stop implying that only large files are ever imported or exported, and avoid stating that a single use case is definitely more prevalent than all others.
And we allow man page headers to include parentheses so that the specialized headers in the …
=> Update git-lfs-migrate man page and add description section

config/config.go
If a `SIGINT` is delivered before the `commands.cfg` `Configuration` structure is initialized then when the goroutine which responds to the signal runs the `commands.Cleanup()` method, it panics after dereferencing a null pointer to the `Configuration` structure while trying to acquire the `loading` mutex that protects the struct's `fs` member.
We can resolve this by simply testing for a `nil` `Configuration` structure pointer in the `config.Cleanup()` method and returning immediately in that case.
Fixes #4450.
/cc @KalleOlaviNiemitalo as reporter.
=> Avoid panic on SIGINT by skipping cleanup when config uninitialized

config/git_fetcher.go, docs/man/git-lfs-config.5.ronn
This option can't be used to do anything dangerous.
Fixes #4467
=> Mark skipdownloaderrors as safe

lfs/gitfilter_smudge.go
Before this commit, loop over errors didn't actually loop
and instead returned only the first error
----
I have to idea how to test this change. I found it because GoLand was complaining that condition `multiErr != nil` inside loop over errors was always false.
=> Fix downloadFile in gitfilter_smudge.go to actually propagate all errors

lfshttp/certs_freebsd.go, lfshttp/certs_linux.go, lfshttp/certs_nix.go, lfshttp/certs_openbsd.go
Currently, we have a large number of identical cert files for various platforms, all of which are non-macOS Unix systems.  These files all simply provide the default system configuration and nothing else.
We recently noticed by looking at the NetBSD pkgsrc repository, which, despite its name, can be used on many systems, that there is a patch to support Solaris.  Unsurprisingly, it duplicates this same file.
Since using the default system behavior is the prudent thing to do if we don't have anything else to do, let's make our project more portable by simply using this same file for all systems other than macOS or Windows. That way, we'll work on Solaris and NetBSD, among other systems, and any other Unix systems which support Go in the future will also magically work.
Fixes #4475
=> Make lfshttp package builds more portable

config/config.go, config/config_test.go, docs/man/git-lfs-config.5.ronn
Currently, if there's no default remote for the current branch set, we look for the name of any single remote, and if not, we fall back to "origin."
However, some people prefer to use a different name for their remotes, such as "upstream".  We don't really want to mandate that users provide a specific name for their remotes, so let's add two variables, `remote.lfsdefault` and `remote.lfspushdefault`, that control the default remote and the default push remote, respectively.  Let's document them, and the lookup order, as well, so folks can reason about the behavior adequately.
Fixes #4464 
/cc @dflems as reporter
=>  Add config variables for default remotes

Makefile
I was trying to [cross-compile git-lfs to macOS for arm64](https://github.com/desktop/dugite-native/pull/354) from an x86_64 machine and I noticed that just [passing a `GOARCH=arm64` variable to `make`](https://github.com/desktop/dugite-native/pull/354/files#diff-b079a6aebd2c75ac12727b1cfcf5ffb9ddf9055a823e3015d7c729fac1628f93R81) would cause a failure like this:
```
go generate github.com/git-lfs/git-lfs/commands
fork/exec /var/folders/4d/hy7gsq2n22jccp96wdbpt3100000gn/T/go-build614314336/b001/exe/mangen: bad CPU type in executable
commands/commands.go:28: running "go": exit status 1
make: *** [commands/mancontent_gen.go] Error 1
```
I don't understand _why_ exactly, but [overriding `GOARCH` with _nothing_](https://github.com/desktop/dugite-native/pull/354/files#diff-b079a6aebd2c75ac12727 …
=> Use host architecture and OS when running `go generate`

commands/command_migrate.go, commands/command_migrate_info.go, docs/man/git-lfs-migrate.1.ronn, lfs/pointer.go, t/fixtures/migrate.sh, t/t-migrate-info.sh
The output of the `git lfs migrate info` command, when the repository history contains existing Git LFS pointers, treats those pointers as regular files and counts only the size of the pointer, not the referenced object.  This can result in misleading output for repositories where there is a potential use case for the `git lfs migrate import --fixup` command and option, among others.
This PR adds a `--pointers` option to the `git lfs migrate info` command, which accepts one of three values, `ignore`, `follow`, or `no-follow` (the default).  The latter is the default only because it ensures we maintain backwards compatibility with the output of the command in previous Git LFS versions.
The `--pointers=ignore` option simply skips any existing Git LFS pointers when calculating the totals for …
=> Allow reporting of LFS pointers separately in migrate info command

docs/man/git-lfs-migrate.1.ronn
Note in the `git-lfs-migrate` man page that it is not abnormal for the import process to leave Git LFS pointers in the working directory and that these can be updated with `git-lfs-checkout`.
=> docs/man: add note re post-import use of checkout

commands/command_migrate_import.go, t/t-migrate-import.sh
The `--above` option is supposed to only affect individual files, but in its current configuration, the entry added to the `.gitattributes` file is a wildcard pattern for the entire extension.  This is a problem because other files with the same extension won't necessarily be converted, leading to the dreaded message that some files "should have been pointers, but weren't".
Let's fix this by doing what the documentation says: only adding individual files themselves.  That fixes this problem and also the inconsistency in our documentation.
Fixes #4511
=> migrate import: make --above affect only individual files

locking/api.go
If the server responds with a JSON response with neither a valid lock nor a valid message, we can end up performing a NULL pointer dereference.  Let's detect this case and return an error that indicates that the server has sent an invalid response.
I haven't added tests here because I think this is extremely unlikely to happen in practice and the consequence here is very minor, but if folks feel it's better to add one, I can do so.
Fixes #4508
=> locking: avoid nil pointer dereference with invalid response

README.md
The `README` currently makes a lot of assumptions about the requirements to build from source.  Let's explain to the user what those requirements are and to invoke `make`, since we tend to build things differently from most other Go projects.
Fixes #4522
/cc @matthiasbeyer as reporter
=> README: improve steps for building from source

rpm/build_rpms.bsh, script/packagecloud.rb
This seems to be the change necessary to let almalinux-based system to be treated the same way as Red Hat Enterprise Linux or CentOS.
Workaround: set `os=el` in the environment
=> Let packagecloud.io recognize almalinux

commands/command_lock.go, commands/command_unlock.go, t/t-lock.sh, t/t-unlock.sh
Currently, we accept multiple paths for `git lfs lock` and `git lfs unlock` and then promptly ignore all of them other than the first.  Let's reject these paths instead of silently ignoring them.
Also, we currently accept absolute paths and then produce a bizarre and incorrect relative path from it when using these commands.  Let's fix this as well.
Both commits have sane commit messages explaining the changes in full.
Fixes #4529
=> Fix locking with multiple paths and absolute paths

lfs/gitscanner_refs.go, t/t-batch-transfer.sh, tq/basic_download.go, tq/basic_upload.go, tq/custom.go, tq/ssh.go, tq/transfer.go, tq/transfer_test.go, tq/tus_upload.go
This PR follows up on some notes from a [conversation](https://github.com/git-lfs/git-lfs/pull/4446#discussion_r665860126) in PR #4446, specifically the fact that the `ClearTempStorage()` method of the transfer `Adapter` interface is never utilized, and the current implementations in the basic and SSH transfer adapters would be dangerous if they ever were called.  We therefore remove the method from the interface and drop its implementations from the various transfer adapaters.
(The reason the current implementations are potentially dangerous is that they perform `os.RemoveAll(a.tempDir())` where `tempDir()` is an internal method of each adapter that tries to create a temporary directory within the local Git repository, but if it fails, just returns `os.TempDir()`, and also does not cache …
=> Drop unused ClearTempStorage() transfer adapter method and tune stale comments

commands/command_clean.go, commands/command_filter_process.go, commands/command_smudge.go, commands/commands.go, t/t-repo-format.sh
We've had several proposals to change how data is stored on disk, such as by compressing files when stored inside the .git directory. Unfortunately, those proposals are incompatible with how data is stored now and we would likely break older clients if we implemented them.
To make it possible for us to implement them in the future, let's do what Git does and add support for a repository format version.  We read the configuration option `lfs.repositoryFormatVersion` from the local configuration, and if it is nonzero, we exit with an error.  We also assume that if the value is not set, then it is implicitly 0 and set it if possible.  We ignore any errors when writing to allow working with read-only repositories in the limited circumstances where that can be valuable.
The plan in the future …
=> LFS repository format version

go.mod, go.sum, vendor/github.com/git-lfs/gitobj/v2/tree.go, vendor/modules.txt
Bump gitobj to v2.0.2 to fix support for zOS, which has different stat constants than most other Unices.
=> go.mod: bump gitobj to v2.0.2

README.md, go.mod
Although we utilize Go modules in our build system and therefore have a `go.mod` file with a defined module path (`github.com/git-lfs/git-lfs/v2`), Git LFS is intended to be used only as a compiled binary and so we add comments and cautions to the effect that Go developers should not import our main Go module or expect it to provide a stable API or ABI (as discussed in https://github.com/git-lfs/git-lfs/pull/4575#issuecomment-896527279).
While we're at it, let's also correct the link to one GPG key on our `README` page as well.
Resolves #4574.
=> Add cautions about unstable Go API and fix GPG key link

t/cmd/lfstest-gitserver.go, t/t-batch-retries-ratelimit.sh, t/t-batch-storage-retries-ratelimit.sh, tq/transfer_queue.go
This MR corrects the handling of `429` retry-after HTTP errors for the *LFS batch API* endpoint and adds the matching integration tests. Said functionality was already working for the *storage API* endpoint and was also covered by integration tests.
Receiving `429` retry-after HTTP errors also for the *LFS batch API* endpoint is a likely scenario when using a Git-server with shared rate-limit bucket like GitLab or reverse HA-Proxy and project with multiple LFS files.
**Scenario before 5b6a929**
``` txt
21:45:55.453201 trace git-lfs: tq: sending batch of size 1                            
21:46:06.460290 trace git-lfs: HTTP: PUT http://127.0.0.1:50427/storage/5404ee773986b403c227c48c61913b32109d8b2aa512b6fba044acc14cfe30a5
LFS: Errorading LFS objects: 100% (1/1), 17 B | 0 B/s …
```
=> Fix 429 retry-after handling for LFS batch API endpoint

lfs/gitscanner_log.go, t/t-fetch-recent.sh, t/t-prune.sh
If a user has set the Git `color.diff` configuration option to `always` then commands such as `git lfs fetch --recent` and `git lfs prune` may fail because the `fileHeaderRegex` [regular expression](https://github.com/git-lfs/git-lfs/blob/314c30dfc0b54da612ea8f21d7a7f113f310bed0/lfs/gitscanner_log.go#L220) incorrectly captures ANSI escape sequences into the file paths it tries to parse from lines beginning with `diff --git`.
We first alter some existing tests of those Git LFS commands to make sure we demonstrate the problem reliably; then we add the `--color=never` option to all invocations of `git log -p`, which resolves the issue, because we never supply the `--line-prefix` option, and those are the only two possible prefixes to `diff --git` …
=> Disable ANSI color codes while log parsing and anchor diff regular expressions

.github/workflows/ci.yml, .github/workflows/release.yml, Makefile, git-lfs_windows.go, git-lfs_windows_arm64.go, script/windows-installer/inno-setup-git-lfs-installer.iss
Follow-up PR on #4584
Go 1.17 added support for the Windows ARM64 build target. This PR adds that support to Git LFS, including the required CI + installer logic.
The installer correctly recognizes ARM64 and writes to the `Program Files` folder (not `Program Files (x86)`):
The installed executable is native ARM64 indeed:
```
PS C:\Program Files\Git LFS> .\git-lfs
git-lfs/2.13.0 (GitHub; windows arm64; go 1.17)
```
=> Add support for Windows ARM64

Makefile, docker/gpg-agent_start.bsh, docker/run_dockers.bsh, rpm/build_rpms.bsh, t/testhelpers.sh
Debian has recently deprecated the which utility and will remove it in a future version, since POSIX specifies `command -v` for finding the location of a path and has for some time.  In addition, which has started complaining loudly to standard error, so it causes test and makefile output to be hard to read.
Let's switch to the preferred invocation, `command -v`, in the Makefile, build tooling, and test suite.
=> Switch from which to command -v

config/url_config.go, config/url_config_test.go
Currently, we don't anchor the regexp for matching keys.  That means that if we have a value of http.URL.sslCert and http.URL.sslCertPasswordProtected, the latter can be read when when looking up the former.  To avoid that, let's anchor the regexp properly against the key at the beginning and end.
Fixes #4597
=> urlconfig: anchor regexp for key matching

subprocess/path.go
It's common for Windows machines to have trailing empty PATH components and users there don't expect that to mean "." like it does on Unix.  To avoid unexpected behavior and somewhat improve security, treat the empty PATH component differently on Windows.
=> subprocess: don't treat empty PATH component as . on Windows

commands/command_lock.go, commands/command_unlock.go, t/t-lock.sh, t/t-unlock.sh
We've seen a request to lock and unlock multiples files on the command line.  This has been difficult due to the need to change the JSON output format, which was a backwards incompatible change.  Since we're introducing a new major version, we can now make that change, and it's done here.
=> Support for locking and unlocking multiple files

debian/rules, docker/run_dockers.bsh, script/packagecloud.rb, script/upload
Debian 11, bullseye, has been released on August 14, 2021.  Add support for it when building Linux packages.
Fixes #4589
=> Add support for Debian 11

script/packagecloud.rb
Remove Ubuntu impish and AlmaLinux because they are not supported by packagecloud.io.  Add Debian bookworm, which is currently testing, and SLES 15.3, which is the latest version.
Fixes #4602
=> Update OS versions

script/packagecloud.rb
corrected debian 11 & 12  derived variants - bullseye (debian 11) and bookworm (debian 12) - for the packagecloud deployment
debian versions synced with the list on the [packagecloud](https://packagecloud.io/docs#anchor-debian)
=> corrected debian 11 & 12  derived variants

docs/api/batch.md, docs/proposals/ssh_adapter.md, t/cmd/lfstest-gitserver.go, t/t-batch-transfer.sh, tq/api.go, tq/api_test.go, tq/ssh.go
To future-proof ourselves against the need to change hash algorithms in the future, let's advertise the hash algorithm to the remote side.  If the value is not `sha256` or absent (which is treated as the same thing), we fail.
=> Advertise hash algorithm supported in batch request

CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v3.0.0, which is scheduled for Friday, September 24, 2021.
We're publishing these changes early so that folks on @git-lfs/implementers can check that things work with their various platforms.  Note that as a major release, this contains several incompatible changes, most of which are outlined in the changelog.  For that reason, I've opted to push out the release a little longer.
[git-lfs-darwin-amd64-v3.0.0-pre.zip](https://github.com/git-lfs/git-lfs/files/7157182/git-lfs-darwin-amd64-v3.0.0-pre.zip)
[git-lfs-darwin-arm64-v3.0.0-pre.zip](https://github.com/git-lfs/git-lfs/files/7157183/git-lfs-darwin-arm64-v3.0.0-pre.zip) …
=> release: v3.0.0

.github/workflows/ci.yml
When using Go 1.12, we need to download some of the HTTP/2 code as part of the build process.  However, that code uses the Go 1.13 errors package and expects errors.Is to work, which it does not.  Since this isn't really practically avoidable and Go upstream is not going to care about getting those older Go versions to work, let's drop support for Go before 1.13.
Note that we only guarantee compatibility with the latest Go version, so this doesn't violate our support policy.
I'm not including newer versions of Go because they are extremely picky about the build process and things are currently broken on at least 1.16, and my goal here is to unbreak the build system as quickly as possible.
=> Stop supporting Go older than 1.13

.github/workflows/release.yml, git-lfs_windows_arm64.go, script/windows-installer/inno-setup-git-lfs-installer.iss
Fixes #4642
This PR does the following:
- Fix Windows arm64 build as reported in https://github.com/git-lfs/git-lfs/issues/4642. The problem was that `go generate` didn't have a GOARCH set, so it used the host architecture (amd64) to build `resource.syso`. That in turn caused the `unknown ARM64 relocation type 7` error. Also, once the `resource.syso` file was generated, GNU Make wouldn't update it for other architectures as it can't recognize if GOARCH has changed.
- Build arm64 `resource.syso` instead of arm (32-bit). While 32-bit arm does work on arm64, Git LFS only supports arm64, so we can safely go with that one.
- Fix small typo in InnoSetup configuration from my previous PR (https://github.com/git-lfs/git-lfs/pull/4586)
- Don't install `windows-sdk-10.0` in the CI release process …
=> Fix Windows arm64 release

commands/command_smudge.go
**Short:** The bound was `> 4GB` when it should be `≥ 4GiB`.
**Long:** It is documented in the git-lfs manpages that the largefilewarning should be triggered for files “4GiB or larger” but the code triggered the warning for files “strictly larger than 4GB”. Thus, the warning triggered more often than it should. This is, of course, assuming that the documentation is correct and the code incorrect and not vice versa. This, however, seems to be the case when reading up on the underlying problem, e.g. [in this e-mail thread](https://public-inbox.org/git/93ccf86d-0090-a311-9825-7e23fd6a4141@web.de/t/).
(Yes, I have enough files between 4GB and 4GiB that I was sufficiently annoyed to create this PR.)
=> Fix bound for largefilewarning

commands/command_dedup.go, commands/command_fsck.go, commands/command_prune.go, fs/fs.go, lfs/pointer.go, t/t-fetch.sh, t/t-prune.sh, t/t-pull.sh
If the object has a size of zero, then we already have its object: it's the empty file, and we shouldn't need to download it from anywhere.  If we inquire if it exists, then say it does, and say its location is the system's equivalent of `/dev/null`.
The only tricky case is if we're de-duplicating, linking, or writing to a file, in which case we should not try to use a link or replace on the file, since we neither want to link nor replace the system's `/dev/null`.
Fixes #4645
=> fs: specify a file as existing if it's empty

.github/workflows/ci.yml, .github/workflows/release.yml, CHANGELOG.md, commands/command_dedup.go, commands/command_fsck.go, commands/command_prune.go, config/version.go, debian/changelog, fs/fs.go, git-lfs_windows_arm64.go, lfs/pointer.go, rpm/SPECS/git-lfs.spec, script/windows-installer/inno-setup-git-lfs-installer.iss, t/t-fetch.sh, t/t-prune.sh, t/t-pull.sh, versioninfo.json
This is an in-progress look at the next release of Git LFS, v2.13.3, which is scheduled for today, Tuesday, September 28, 2021.
[git-lfs-darwin-amd64-v3.0.1-pre.zip](https://github.com/git-lfs/git-lfs/files/7244625/git-lfs-darwin-amd64-v3.0.1-pre.zip)
[git-lfs-darwin-arm64-v3.0.1-pre.zip](https://github.com/git-lfs/git-lfs/files/7244626/git-lfs-darwin-arm64-v3.0.1-pre.zip)
[git-lfs-freebsd-386-v3.0.1-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/7244627/git-lfs-freebsd-386-v3.0.1-pre.tar.gz)
[git-lfs-freebsd-amd64-v3.0.1-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/7244628/git-lfs-freebsd-amd64-v3.0.1-pre.tar.gz)
[git-lfs-linux-386-v3.0.1-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/7244629/git-lfs-linux- …
=> release: v3.0.1

config/config.go, errors/types.go, git/config.go, git/git.go, t/t-env.sh
There are a couple different cases in which we can get errors when running `git lfs env` outside of a repository.  One of these can also cause us to fail to load Git configuration, which makes the output confusing, and another only shows up when the user (like the author) is using a non-English language.  Let's fix these issues and add a test to be sure we don't regress the behavior.
Each commit contains an explanatory commit message.  Note that this PR is probably best reviewed with whitespace differences turned off.
Fixes #4712
=> Avoid errors in git lfs env

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, docker/run_dockers.bsh
Users have recently requested packages for arm64, which is an increasingly popular architecture.  In addition, it is the architecture used on newer Macs and some Windows systems, which may commonly run Linux VMs or WSL.
However, GitHub Actions does not support arm64 natively, so we must build in emulation.  This is extraordinarily slow, so we'll build only for the latest Debian release.  All Debian-based images use our Debian images, and Debian is by far the most portable mainstream Linux distribution in terms of architecture support, so the cost to add additional architectures should be extremely minimal.  Users who would like versions for older releases may build their own packages with our tooling.
Build these packages in both CI and for releases.
Fixes #4546
=> Add support for ARM64 Debian packages

ssh/ssh.go, ssh/ssh_test.go, t/cmd/lfs-ssh-echo.go, t/t-ssh.sh
In Git LFS version 3.0, we added support for understanding the GIT_SSH_VARIANT environment variable and its corresponding configuration option.  When we did so, we dropped the special-casing for program names and instead always used the -- setting for the default variant, "ssh". This variant represents OpenSSH, which as a program with normal POSIX option handling, supports -- just fine.
Unfortunately, not all clients do.  TeamCity's SSH client doesn't set the variant and also doesn't understand --.  We need to handle this case to prevent option injection in case someone tries to use a URL like "ssh://-oProxyCommand=exploit/", which could otherwise lead to arbitrary code execution.
However, we don't have to add this all the time, but only when the user-and-host portion starts with a dash. …
=> ssh: avoid using -- where possible

commands/command_migrate.go, commands/commands.go, docs/man/git-lfs-migrate.1.ronn, t/fixtures/migrate.sh, t/t-migrate-import.sh
The `--include` and `--exclude` (`-I` and `-X`) options to the `git lfs migrate` command allow the user to specify filepath filters which select matching files to migrate and which are also used to populate any `.gitattributes` files written by the import or export operations.
This latter functionality implies that we need to parse any filepath patterns supplied by these options using `gitattributes(5)` rules, since the patterns will be copied directly into `.gitattributes` files.  (See the [use](https://github.com/git-lfs/git-lfs/blob/283d21ef896231e6c83fd961ac0d66ea129257e4/commands/command_migrate_import.go#L132) of the [`trackedFromFilter()`](https://github.com/git-lfs/git-lfs/blob/283d21ef896231e6c83fd961ac0d66ea129257e4/commands/command_migrate_import.go#L291-L306) and …
=> use gitattributes filepath matching for migrate filter options

git/attribs.go, git/ls_files.go, locking/lockable.go, t/t-post-checkout.sh, t/t-track.sh
Git doesn't know about untracked files, so we should avoid modifying them when we adjust permissions in the post-checkout hook.  Add an option to our invocation of git ls-files that controls the use of the `--others` flag (which controls listing untracked files), and disable it when we're looking for files to process with the post-checkout hook.
Fixes #4757
/cc @rainwf as reporter
=> post-checkout: don't modify permissions of untracked files

creds/creds.go
If `SSH_ASKPASS` is unset on Windows, it's possible that the invocation of `cygpath -w` can fail, since we'd pass it an empty string, which it doesn't like.  Let's fix this by first checking for an empty string and only if it is not empty, passing it to cygpath.
=> creds: gracefully handle lack of askpass helper

.github/CODEOWNERS
Currently, when someone opens a PR, they either have to ping the @git-lfs/core team as reviewers or hope that someone sees the PR.  Let's help the users out by automatically pinging the team for review by adding a CODEOWNERs, which we can then work into our branch protection rules.
=> Add CODEOWNERS to automatically ping on review

commands/command_migrate_import.go, docs/man/git-lfs-migrate.1.ronn, t/t-migrate-import.sh
The `--include`, `--exclude`, and `--fixup` options don't work properly with `--above`, so let's print an error instead of silently doing the wrong thing.  Document this fact as well to make sure that people aren't surprised.
=> migrate import: don't allow path filters with --above

t/git-lfs-test-server-api/main.go
Or else `apiClient` might not have an `Endpoints` attribute and just be `nil` when accessed
=> Move `err` checking to before the value was used

commands/command_filter_process.go, docs/man/git-lfs-config.5.ronn, docs/man/git-lfs-smudge.1.ronn
In Git for Windows 2.34.0 and the upcoming Git 2.35.0, the issue that's caused corruption on Windows has been fixed.  Let's avoid warning users that there's a problem if they're using 2.34.0 or newer unless they've specifically set the option to true.  Note that we only consider 2.34.0 and not 2.35 since Unix has never had this issue.  Update the documentation as well to reflect the new default.
Fixes #4744
=> filter-process: don't print large file warning on fixed versions

script/packagecloud.rb
Remove Fedora 32 and 33, which are EOL.  Add Fedora 35, which is the latest version.  Add the latest versions of Ubuntu and Linux Mint, and remove EOL versions of Ubuntu.  Fix the alignment of the comments.
Fixes #4767
=> script/packagecloud: update for latest distros

.github/workflows/ci.yml, .github/workflows/release.yml
The actions/checkout workflow looks like it may have had a security-sensitive change to it in the latest v2.  It doesn't look like it affects us, but let's update to be safe.
Switch to actions/checkout@v2 everywhere and use the fetch-depth: 0 argument, which makes us fetch the entire history.  This is the main reason we stuck with v1 for so long, and it's required for certain parts of our build and release process to function correctly.
Fixes #4789
=> .github/workflows: switch to actions/checkout@v2

commands/command_migrate_export.go, commands/command_migrate_import.go, commands/command_migrate_info.go, git/githistory/rewriter.go, git/githistory/rewriter_test.go, t/t-migrate-import.sh
When we cache files, do so on the full path instead of just the directory entry.  This means that when we have an identical file with the same name in two different direectories, we distinguish between the two paths and ensure both are added to .gitattributes.
This is an alternate solution to #4671 which should perform better.  For compmarison, with a clone of Git's main repository with the following command, we get:
`git lfs migrate import --everything --include="*.h"`:
* v3.0.1      (broken):  608s user,   53s system,    5:34 total
* v3.0.2      (fixed): 13435s user, 1255s system, 1:43:17 total
* this commit (fixed):   716s user,   67s system,    6:59 total
This is a much better performance characteristic for equivalent results.
Preserve the integration from the earlier attempt at …
=> Fix migrate import speed regression

creds/access.go, lfsapi/auth.go, lfsapi/auth_test.go, lfsapi/lfsapi.go, lfshttp/client.go
The Negotiate authentication scheme can support multiple different types of authentication.  The two most popular are NTLM and Kerberos.  When we supported NTLM, we'd first try Kerberos, and if it failed, fall back to NTLM.
However, we no longer support NTLM, but some people still have server configuration that uses NTLM via Negotiate.  For these people, authentication may be broken.  Let's fall back to Basic in such a case by keeping track of which authentication mechanisms we've tried, keeping only the supported mechanisms if we got a response, and stripping out failing mechanisms, falling back to Basic.
To help with servers that support both Negotiate and Basic, we specifically consider SPNEGO (Negotiate) errors as authentication errors.  This is because if the server supports Kerberos …
=> Fall back from Negotiate to Basic

go.mod, go.sum, t/fixtures/migrate.sh, t/t-migrate-export.sh, t/t-migrate-import.sh, vendor/github.com/git-lfs/gitobj/v2/tree.go, vendor/modules.txt
We currently generate incorrect duplicate `.gitattributes` entries when performing an import or export migration if an existing `.gitattributes` file has execute file permissions and we intend to merge new attribute filter lines into that file.
We first add a pair of tests for this condition, one each for the migration import and export operations, which each check for a single `.gitattributes` file after migration and therefore will fail with the current behaviour.
We then bump our `git-lfs/gitobj` module to v2.1.0, as it fixes merges of tree entries where an existing tree entry has a different file permissions mode than the tree entry being merged with it.  This should resolve the problem and allow our new tests to pass.
We also revise the names used for several test repositories …
=> fix merging of `.gitattributes` with execute file mode during migration

commands/command_migrate_import.go, commands/command_migrate_info.go, docs/man/git-lfs-migrate.1.ronn, git/gitattr/tree.go, t/fixtures/migrate.sh, t/t-migrate-export.sh, t/t-migrate-fixup.sh, t/t-migrate-import.sh, t/t-migrate-info.sh
As [discussed](https://github.com/git-lfs/git-lfs/issues/4796#issuecomment-1015782841) in issue #4796 and PR #4835, we add checks to the `git lfs migrate` command so that in all of its modes, if a symbolic link named `.gitattributes` is encountered, the migration halts with an error.  This will occur regardless of whether the migration would normally modify a `.gitattributes` file in the same location.
We add tests for the `import`, `export`, and `info` sub-commands which exercise this new behaviour, including with and without the `--fixup` option for the `import` and `info` sub-commands.
Note that this is an unexpected condition because `.gitattributes` tree entries should never be symbolic links; Git itself will complain about them with `"Too many levels of symbolic links"` warning …
=> halt migration when `.gitattributes` symbolic link encountered

commands/command_fsck.go, commands/command_lock.go, commands/command_locks.go, commands/command_ls_files.go, commands/command_pre_push.go, commands/command_push.go, commands/command_unlock.go, commands/commands.go, commands/lockverifier.go, commands/uploader.go, git/githistory/rewriter.go, git/refs.go, git/refs_test.go, git/rev_list_scanner.go, git/rev_list_scanner_test.go, lfs/gitfilter.go, lfs/gitscanner.go, lfs/gitscanner_refs.go, t/t-fsck.sh
As described in https://github.com/git-lfs/git-lfs/issues/4855#issuecomment-1030769273, the `git lfs fsck --objects` command currently handles refs expressed on the command line in two-dot range notation backwards, so we resolve that problem, add tests to confirm it is working as intended, and also revise some internal variable and function names to remove the ambiguity of the terms "left" and "right" as they apply to Git ref names.
This PR is probably most easily reviewed in a commit-by-commit manner, although it should be feasible to review it as a single diff as well.
The unintended reversal of the ref names in a `git lfs fsck --objects A..B` command is due to the fact that we [pass](https://github.com/git-lfs/git-lfs/blob/12a957202906667343ef9fc62b312ee53353f266/commands/command_fsck.g …
=> fix `git lfs fsck --objects A..B` handling and drop all left/right ref terminology

CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v3.1.0, which is scheduled for Monday, February 14, 2022.
We're publishing these changes early so that folks on @git-lfs/implementers  can check that things work with their various platforms. Note that as a major release, this contains several incompatible changes, most of which are outlined in the changelog. For that reason, I've opted to push out the release a little longer.
[git-lfs-darwin-amd64-v3.1.0-pre.zip](https://github.com/git-lfs/git-lfs/files/8035611/git-lfs-darwin-amd64-v3.1.0-pre.zip)
[git-lfs-darwin-arm64-v3.1.0-pre.zip](https://github.com/git-lfs/git-lfs/files/8035612/git-lfs-darwin-arm64-v3.1.0-pre.zip) …
=> release: v3.1.0

.github/workflows/release.yml
A key for the steps is required.
=> .github: fix syntax error in release workflow

docs/howto/release-git-lfs.md
The syntax error which occurred most recently for v3.1.0 could have been detected by looking at the Actions tab.  Let's suggest to the core team member doing the build that they inspect this to prevent any future problems.
=> docs/howto: remind core team member to check Actions workflows

.github/workflows/release.yml, CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v2.13.3, which is scheduled for today, Monday, February 14, 2022.
[git-lfs-darwin-amd64-v3.1.1-pre.zip](https://github.com/git-lfs/git-lfs/files/8063197/git-lfs-darwin-amd64-v3.1.1-pre.zip)
[git-lfs-darwin-arm64-v3.1.1-pre.zip](https://github.com/git-lfs/git-lfs/files/8063198/git-lfs-darwin-arm64-v3.1.1-pre.zip)
[git-lfs-freebsd-386-v3.1.1-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/8063199/git-lfs-freebsd-386-v3.1.1-pre.tar.gz)
[git-lfs-freebsd-amd64-v3.1.1-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/8063200/git-lfs-freebsd-amd64-v3.1.1-pre.tar.gz)
[git-lfs-linux-386-v3.1.1-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/8063201/git-lfs-linux-38 …
=> release: v3.1.1

.github/workflows/release.yml
Install the packagecloud gem for the cross-build packages so that we can properly upload them.
=> .github/workflows: install packagecloud gem

.github/workflows/ci.yml, .github/workflows/release.yml
actions/checkout@v2 "helpfully" overwrites the tag with the data from the ref, erasing the annotated tag, and therefore breaking git describe, which by default only checks annotated tags.  Note that every tag except the one for the current head is preserved, so git describe uses an annotation that is based off the most recent tag.  This behavior is described in actions/checkout#290.
The original reporter claiming that a security fix had been applied has not provided details, and the behavior described should not be a vulnerability in a single-tenant Actions VM.  Therefore, revert to actions/checkout@v1 to preserve functionality at the expense of a behavior which does not appear to describe an actual vulnerability.
This reverts commit e3893b1402349b9481ccd8e1cd876d9e355cf848, reversing …
=> Revert "Merge pull request #4795 from bk2204/actions-checkout-v2"

README.md
While it is the user's responsiblity to read the documentation and know
what impact a command will have that they choose to run on their
machine, I believe it would be helpful to draw more attention to the
destructive commands that are featured in the README that cause Git to
rewrite its commit objects.
Many users will only skim the README, and the migration command that
addresses a common use case should be called out more than it is for its
side effects, in my opinion.
=> Call out destructive command in README

.github/workflows/ci.yml, .github/workflows/release.yml, CHANGELOG.md, config/version.go, debian/changelog, lfs/hook.go, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v3.1.2, which is scheduled for tomorrow, Wednesday, February 16, 2022.
[git-lfs-darwin-amd64-v3.1.2-pre.zip](https://github.com/git-lfs/git-lfs/files/8074298/git-lfs-darwin-amd64-v3.1.2-pre.zip)
[git-lfs-darwin-arm64-v3.1.2-pre.zip](https://github.com/git-lfs/git-lfs/files/8074299/git-lfs-darwin-arm64-v3.1.2-pre.zip)
[git-lfs-freebsd-386-v3.1.2-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/8074300/git-lfs-freebsd-386-v3.1.2-pre.tar.gz)
[git-lfs-freebsd-amd64-v3.1.2-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/8074301/git-lfs-freebsd-amd64-v3.1.2-pre.tar.gz)
[git-lfs-linux-386-v3.1.2-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/8074302/git-lfs-lin …
=> release: v3.1.2

Makefile, debian/git-lfs.manpages, rpm/SPECS/git-lfs.spec
We currently build our manual pages and the HTML versions of them into a single `man` directory, which results in release package archives on GitHub that contain all of these files interleaved with each other in that one directory.
When we build Linux RPM and Debian packages, though, the man pages are installed into their conventional locations under `/usr/share/man/man{1,5}`.  (The HTML versions are not included at all.)
For those downloading the release package archives and not using the RPM or Debian packages, we can improve their experience by placing the roff man pages into `man/man1` and `man/man5` subdirectories corresponding to their respective sections of the manual, and the HTML versions of the pages into a `man/html` subdirectory.
(A test run of the release Actions workflow …
=> Build man pages into per-section subdirectories

docs/man/git-lfs-push.1.ronn
As the `git lfs push --all` command does not (when used without other arguments) push any objects not reachable from local refs, i.e., specifically only those under `refs/heads` and `refs/tags`, we note that this behaviour differs from that of `git lfs fetch --all` and that users wanting to migrate repositories with these commands may need to make additional pushes of non-local refs.
=> note `git lfs push --all` only pushes local refs in man page

script/upload
Because CentOS 8 is now EOL, we've switched to Rocky Linux for building RHEL 8-compatible packages.  However, those packages don't end up containing the ".el8" segment, so the link is broken.  Fix this by removing that segment from the URL.
Fixes #4934
=> script/upload: correct RHEL 8 package repo

Makefile
Before Go 1.13, it was possible to trim paths with GC flags and ASM flags.  In Go 1.13, it became possible to simply specify -trimpath, at which point all the old behaviour became unnecessary.
Since we require Go 1.13 in our code due to the use of the errors package, let's simplify our code by always using the -trimpath flag and omitting the old forms.  The old forms additionally were broken when using a path with a space, which could happen on Windows if the current user's username contained a space (which is not uncommon).
=> Makefile: remove legacy trimpath code

commands/commands.go
The `PipeCommand()` function was added in commit 8b18f62242426ab9352925929ad0fbbee0edd51b in the initial prototype work on this project in order to run the original `bin/git-media-{clean,smudge`} programs.  The `PipeMediaCommand()` function was then added in commit 9cff651e5073f29c28ed418ba721731e7bbee848 to abstract the addition of the `bin/` prefix to the program names into a single function.
As of commit 24b1939d45cc59dd1cd3ad7cb4657289a60ad595 in 2014, however, which was also part of that early prototyping phase, the `bin/git-media-{clean,smudge}` programs were replaced with `git media clean|smudge`, precursors of our contemporary `git lfs clean|smudge` programs, and the `Pipe[Media]Command()` functions stopped being used to communicate with the programs.
No other users of these …
=> remove unused `Pipe[Media]Command()` functions

commands/commands.go, git/git.go
In commit d91980f2dad3c7620feaa5ae6d5cf90ef0603330 of PR #1822 the `GetFilesChanged()` function was updated to use `git diff-tree` rather than `git diff`.  However, the relevant error messages were not updated at the same time, so we do that now.
Also, we convert a message that is output when uninstalling Git hooks back to using a capitalized "Git" project name instead of the lowercase variant.  This message was accidentally changed in commit 04abbd843622600279baeb31c92862c4d73e419e in PR #4846 when making it into a translatable string.
=> Update and correct several error message strings

Makefile
The Git LFS signing certificate for Windows binaries has changed, so we update the default signing certificate SHA-1 hash in the `Makefile`.
(The last update was in 2019 in PR #3623.)
=> Update Windows signing certificate SHA hash in `Makefile`

.github/workflows/ci.yml, .github/workflows/release.yml, CHANGELOG.md, commands/commands.go, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, t/Makefile, t/cmd/lfstest-badpathcheck.go, t/t-path.sh, t/testenv.sh, versioninfo.json
This is an in-progress look at the next release of Git LFS, v3.1.2, which is scheduled for today, Tuesday, April 19, 2022.
The CI system will produce artifacts for Windows, Linux, and macOS if you'd like to use those for testing.
/cc https://github.com/orgs/git-lfs/teams/core
/cc https://github.com/orgs/git-lfs/teams/implementers
/cc https://github.com/orgs/git-lfs/teams/releases
=> release: v3.1.4

t/Makefile
On Windows, it is convenient to have the `.exe` file extension added to our compiled test helpers when running tests manually, so we use the `X` variable to do so in the same manner as in the primary `Makefile`.
Also, we add a `test-commands` target in `t/Makefile` which is convenient when rebuilding just the test helpers.
=> Build test helper commands with `.exe` file extension on Windows

commands/command_prune.go, lfs/gitscanner_log.go, t/t-fsck.sh, t/t-migrate-fixup.sh, t/t-prune-worktree.sh, t/t-prune.sh, t/testhelpers.sh
In preparing a PR to address #4945 and adding tests to ensure that issue does not recur, a number of problems with our tests, test helpers, and the implementation of the `git lfs prune` command were exposed by the new tests and checks.  These will be resolved in a series of forthcoming PRs.
As preparation, we first make a number of small adjustments to our test suite, adding additional checks to the `"fsck detects invalid objects"` test in `t/t-fsck.sh`, removing whitespace and revising comments for greater clarity, and changing the `assert_pointer()` and `revise_pointer()` test helper functions to be consistent with each other again and to apply a stricter match for file paths.  We also remove one unused function from the Go codebase.
This PR may be most easily reviewed commit-by-commit, …
=> Adjust test helpers and tests related to path filtering

t/t-prune.sh
In PR #742 the `git lfs prune` command was introduced along with accompanying tests, one of which is the `"prune keep unpushed"` [test](https://github.com/git-lfs/git-lfs/blob/54f101f87e1294e5a20b364702640bf143d77225/t/t-prune.sh#L98-L206) that checks whether Git LFS objects referenced by not-yet-pushed commits are always retained by `git lfs prune`.
In commit 978899e3b538bdd7df0873c2b50d229d5748605d of that PR the initial version of the `prune` tests included some fixture data with commits that were referenced via a tag only, not via a branch ref.  However, the test never confirmed that the Git LFS objects in these commits were retained by the `prune` command.
This initial test was then refactored into several tests in commits 03b85e08acf727428c4e9c0d805f5a8a3da501e7 and …
=> Add test to check `prune` command retains tagged unpushed objects

t/t-prune-worktree.sh, t/t-prune.sh
Several existing tests ensure that the `git lfs prune` command always retains Git LFS objects referenced by unpushed commits, stashes, and worktrees.
However, none of these tests perform checks of the appropriate behaviour when files matching an `lfs.fetchexclude` filter option are involved.  Support for pruning Git LFS objects referenced by files matching the `lfs.fetchexclude` filter was added in PR #2851.  (Support for retaining objects referenced by stashes was added later, in PR #4209).
We therefore expand these tests to check for the expected behaviour, which varies depending on the specific case.
For Git LFS objects referenced only by files in unpushed commits or any type of stash (normal, index, or untracked), we now confirm that even if the files' names match a pattern in …
=> Update tests to check `prune` command excludes `lfs.fetchexclude` paths

commands/command_checkout.go, commands/command_dedup.go, commands/command_fetch.go, commands/command_ls_files.go, commands/command_prune.go, commands/command_pull.go, lfs/gitscanner.go, t/t-prune.sh
In PR #2851 the `git lfs prune` command was changed to respect the `lfs.fetchexclude` configuration option such that objects would always be pruned if they were referenced by files whose paths matched one of the patterns in the configuration option (unless they were referenced by an unpushed commit).
However, this filter is applied [using](https://github.com/git-lfs/git-lfs/blob/0df26c176a2f345d547b77f46ec2e18f40da6cf7/commands/command_prune.go#L355) the `GitScanner.ScanRef()` method, which [indirectly](https://github.com/git-lfs/git-lfs/blob/0df26c176a2f345d547b77f46ec2e18f40da6cf7/lfs/gitscanner.go#L177) [utilizes](https://github.com/git-lfs/git-lfs/blob/0df26c176a2f345d547b77f46ec2e18f40da6cf7/lfs/gitscanner_refs.go#L103) the internal `scanRefsToChan()` …
=> Avoid pruning when identical files both match and do not match `lfs.fetchexclude`

commands/command_filter_process.go, commands/command_fsck.go, commands/command_prune.go, commands/command_smudge.go, docs/man/git-lfs-clone.1.ronn, docs/man/git-lfs-config.5.ronn, docs/man/git-lfs-fetch.1.ronn, docs/man/git-lfs-filter-process.1.ronn, docs/man/git-lfs-fsck.1.ronn, docs/man/git-lfs-prune.1.ronn, docs/man/git-lfs-pull.1.ronn, docs/man/git-lfs-smudge.1.ronn, t/t-filter-process.sh, t/t-fsck.sh, t/t-prune-worktree.sh, t/t-prune.sh, t/t-smudge.sh
The `lfs.fetchinclude` and `lfs.fetchexclude` Git configuration options, if set, are used to control the action of a number of Git LFS commands.  Since PR #4556, the `git lfs clone`, `git lfs fetch`, and `git lfs pull` commands have strictly applied `gitignore(5)`-style matching rules to these configuration options.
However, other commands including `git lfs filter-process` and `git lfs smudge` now apply `gitattributes(5)`-style matching rules to these same configuration options, leading to confusion.
We therefore revise all remaining uses of these configuration options to also use `gitignore`-style matching rules.
We also add new tests for the `git lfs filter-process` and `git lfs fsck` commands and adjust or expand existing tests for the `git lfs prune` and `git lfs smudge` commands in …
=> Use `gitignore`-style path matching for additional commands

.github/workflows/ci.yml, .github/workflows/release.yml, Makefile
Right now, extracting one of our archives (except for the source archives) causes all files to be extracted in the current directory. This is commonly referred to as a tarbomb, and is generally unwelcome.
Instead, let's create a top-level directory in each of our archives named the same way as we currently name our source tarballs: the string "git-lfs-" and then a version number without the initial "v".  This is the same algorithm GitHub would use to create its autogenerated archives.
Because we can no longer use zip's -j option to strip off path components (since we now want to preserve at least some of them), using zip becomes tricky.  Instead, let's use the BSD (libarchive) tar, which is natively available on Windows, macOS, and FreeBSD as the system tar implementation, and which can …
=> Tarballs, not tarbombs

README.md, script/hash-files, script/upload
Right now, we provide signed SHA-256 hashes for our releases.  This is fine and sufficient, and also cryptographically secure.  However, many distributors use other algorithms, and it would be convenient if we could provide easy access to those hashes as well.  For example, NetBSD uses SHA-512 and BLAKE2s.
Let's add an additional file, hashes.asc, which contains a general set of hashes in the BSD format. The advantage of the BSD format over the traditional GNU format is that it includes the hash algorithm, which allows us to distinguish between hashes of the same length, such as SHA-256, SHA-512/256, and SHA3-256.  It is generated by shasum, sha*sum, sha3sum, and b2sum with the --tag format, and all of these programs accept it for verification with no problems.
Using the BSD format means …
=> Multiple hash support

lfshttp/client.go, locking/api_test.go
git-lfs uses the same constant value for the `Content-Type` and `Accept` request HTTP headers:
```
POST /objects/batch/
Accept: application/vnd.git-lfs+json; charset=utf-8
Content-Type: application/vnd.git-lfs+json; charset=utf-8
...
```
But `charset` [isn't valid syntax for `Accept`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept). This change splits out the constant to fix this:
```
POST /objects/batch/
Accept: application/vnd.git-lfs+json
Content-Type: application/vnd.git-lfs+json; charset=utf-8
...
```
=> lfshttp: fix invalid Accept header syntax

.github/workflows/ci.yml, .github/workflows/release.yml
In commit f4ab4e7445c04fe5d663fc79ddb2ebf30a5a870f of PR #4883 we noted that the `gem install ronn` step in our Windows CI workflows currently fails on newer Windows Server 2022 GitHub Actions runners, due to possibly some missing C headers or libraries.
While this could be resolved by upgrading to the `ruby/setup-ruby@v1`  action from the deprecated `actions/setup-ruby@v1` one, that introduced a series of issues with `PATH` lookups as documented in ruby/setup-ruby#293.
We therefore chose to continue using Windows 2019 runners until a resolution or workaround was found.
Fortunately, as of commit 912b607acb162ea324d0ff00fea1a1f47657e1d4 in PR #4992 we are now using the `ronn-ng` Ruby gem instead of the unmaintained `ronn` gem, and the `gem install ronn-ng` workflow step succeeds on Windows …
=> Build CI on Windows 2022

Makefile, commands/command_merge_driver.go, docs/man/git-lfs-merge-driver.1.ronn, docs/man/git-lfs.1.ronn, subprocess/subprocess.go, subprocess/subprocess_test.go, t/t-merge-driver.sh
Sometimes users have text files that they'd like to be able perform merges on that they also want to store in Git LFS.  Let's add a custom merge driver that users can use to merge these text files, either with Git, or with a custom merge tool like the one shipped with Unity.
There's no code to wire this up automatically.  We can decide to support that in a future revision if users would find that valuable.
Fixes #4820 
/cc @dr-dime as reporter
=> Add a merge driver

commands/command_track.go, t/t-track.sh
We want a machine readable output for git lfs track, so add a `--json` flag to add this.
Fixes #4921
=> Add --json output for git lfs track

script/packagecloud.rb
Remove several distro versions which are now EOL.  In addition, add a new version of Linux Mint and OpenSUSE, and update the EOL date for some distros.
Note that we have not added Fedora 36 or Ubuntu kinetic because they are not yet available on packagecloud.io.
Fixes #4988
=> Update distros for packagecloud.io

.github/workflows/release.yml, Makefile
Upon testing our release process, I noticed that there were a few bugs on Windows.  Items fixed include:
* Using the correct location for `signtool.exe`;
* Specifying the path to the BSD tar binary on Windows since the default under Git for Windows is GNU tar; and
* Avoiding `bsdtar -s` on Windows, since that doesn't work.
Each commit has its own commit message explaining the rationale.
=> Apply several Makefile fixes for Windows

script/upload
When we're verifying with multiple programs, it can be hard to read the output between GnuPG and the hashes.  Produce nicer output by printing intermediate messages to break up the text.
=> script/upload: improve readability of asset verification

commands/command_migrate.go, commands/commands_test.go
This PR implements @bk2204 's suggestion in #4810 to only exclude special git refs.
=> Change git-lfs migrate import --everything to migrate everything except for special git refs

script/windows-installer/inno-setup-git-lfs-installer.iss
This addresses the issue raised in https://github.com/git-lfs/git-lfs/discussions/5031.
/cc @chrisd8088
=> installer: handle `BashOnly` Git for Windows gracefully

t/testhelpers.sh
Previously, we used a template to set the default HEAD ref to "main" so that our branch would be correct.  It appears that Git has changed things so that that no longer works, so set init.defaultBranch as well to make sure we initialize new repositories properly.
=> t: set init.defaultBranch

commands/command_filter_process.go, config/config.go, docs/man/git-lfs-config.adoc, git/git.go, lfs/gitfilter_smudge.go, t/t-multiple-remotes.sh
This fixes issue #3835. LFS could not derive the right remote endpoint under certain circumstances. For example, in a detached state, a simple heuristic was used to derive the remote (i.e. branch.*.remote, remote.lfsdefault, any other single remote, origin). This fails if there are multiple remotes in play. This patch derives the corresponding remote from the commit hash / treeish.
Thanks to @stanhu for providing the first version which this PR is based on.
=> Allow alternative remotes to be handled by LFS

docs/proposals/locking_notes.md
This is a PR with the proposal for enhancing the Git LFS REST API to capture additional notes on the locks.
=> Adding locking_notes.md

t/t-multiple-remotes.sh, t/testhelpers.sh, tools/cygwin_windows.go
The cygpath binary from Git for Windows has a bug: when the path contains braces, apostrophes, or certain other special characters, it strips them out when called from Go, but not from the command line.
This results in us having broken behaviour with those characters in the current working directory.  To address this, no longer consider MINGW to be a Cygwin-like environment.
Fixes #5105
Fixes #4829
=> tools: don't match MINGW as Cygwin

.github/workflows/ci.yml, .github/workflows/release.yml, commands/command_lock.go, commands/command_post_checkout.go, commands/command_pre_push.go, commands/command_push.go, commands/command_status.go, commands/path_windows.go, config/config.go, config/environment.go, git/filter_process_scanner.go, git/git.go, git/githistory/rewriter.go, lfsapi/auth.go, lfshttp/endpoint.go, locking/locks.go, tasklog/list_task.go, tools/filetools.go, tools/str_tools.go, tq/transfer_queue.go
As our official [policy](https://github.com/git-lfs/git-lfs/blob/52d47f085ba5ae534dd26ba76d010a537ddbdc8e/CONTRIBUTING.md#prerequisites) is to support the latest version of Go, we upgrade our CI and release workflows to version 1.19, which was recently released.
Because Go version 1.19 [adds](https://tip.golang.org/doc/go1.19#go-doc) more support for documentation comments and now also reformats such comments automatically, we update a few of them to meet the new [standards](https://tip.golang.org/doc/comment).
=> Update to Go version 1.19

go.mod, go.sum
Bump gitobj to a version which addresses a misparsing in commit headers.
Fixes #4709
=> Bump gitobj to v2.1.1

Makefile
087db1de (#4911) bumped the git-lfs Go package version to v3, but the variables being set in the Makefile for `GitCommit` & `Vendor` didn't change, which meant setting them had no effect. Fix this by updating the variable paths.
In addition, quote the `Vendor` variable so it can have spaces in it.
Before (main@ d3716c90):
```console
$ make bin/git-lfs VENDOR=WorldOfGooCorp
...
GOOS= GOARCH= go build -ldflags="-X github.com/git-lfs/git-lfs/config.Vendor=WorldofGooCorp -X github.com/git-lfs/git-lfs/config.GitCommit=d3716c90 -s -w " -gcflags=" " -trimpath -o ./bin/git-lfs ./git-lfs.go
$ bin/git-lfs version
git-lfs/3.2.0 (GitHub; darwin arm64; go 1.19.1)
$ make bin/git-lfs "VENDOR=World of Goo Corporation"
...
GOOS= GOARCH= go build -ldflags="-X github.com/git-lfs/git-lfs/config.Vendor=World …
```
=> Fix setting commit & vendor variables via make

Makefile, lfshttp/ssh.go, ssh/connection.go, ssh/ssh.go, ssh/ssh_test.go, t/cmd/lfs-ssh-echo.go, tq/manifest.go
Right now, we try to spawn multiple SSH connections using ControlMaster when making multiple requests.  However, if multiplexing is not enabled, we can spawn multiple actual connections, which can be expensive and require lots of authentication requests.
Instead, let's make sure we don't enable multiple connections if multiplexing is not enabled, since this may cause the user to be prompted for multiple SSH key connection attempts (say, if they're using a security key) and is substantially more heavyweight than simply spawning a new process over the same connection.
Fixes #5064
=> ssh: disable concurrent transfers if no multiplexing

docker/run_dockers.bsh, rpm/SPECS/git-lfs.spec, rpm/SPECS/rubygem-asciidoctor.spec, rpm/build_rpms.bsh, script/packagecloud.rb, script/upload
RHEL 9 recently came out.  Let's use Rocky Linux 9 to build packages for RHEL and RHEL-equivalent versions so that users have packages to work with.
Each step has its own commit and description.
Fixes #5107
=> Add support for Rocky Linux 9

README.md
Fixed broken link for git-lfs-migrate
=> Fixed broken link for git-lfs-migrate

commands/uploader.go, lfs/gitscanner_catfilebatch.go, lfs/scanner.go
This PR updates several stale comments that relate to scanning Git blob objects to find valid Git LFS pointers and to validating that objects have corresponding local file copies before uploading them.
In commit e3fcde746a04c26f33ac866f39d54b7cbcf2d933 of PR #3236 the `ObjectScanner` type was updated to use an internal `ObjectDatabase` from the `github.com/git-lfs/gitobj` package rather than invoking an external `git cat-file --batch` command.  However, the comments for the `catFileBatch()` and `runCatFileBatch()` functions were not updated at the same time and still state that they cause a `git cat-file --batch` command to run, so we update them now.
And in commit 338ab406ba35a0645bc660f8cb24dad8913f9490 of PR #1812 the `prepareUpload()` function was refactored so that it no longer …
=> Update stale comments relating to object scanning and uploading

docs/man/git-lfs.adoc
The command `git lfs install` will install Git LFS in the Git user scope by default. However, our help files indicate that the setup is repository scoped.
Adjust the setup instructions to match what the command is doing.
The `git lfs install` command has flags to install Git LFS repository scoped (`--local`) and machine scoped (`--system`). However, I think we should not clutter the setup instructions with these details.
---
Fixes #5041
=> docs/man: clarify Git LFS setup instructions

docker/run_dockers.bsh, script/packagecloud.rb, script/upload
Update our packagecloud.io script to include some new distro versions that have come out as well as fixing some minor typos here.  In addition, drop support for Debian 9, which is explained fully in the commit message.
Fixes #5108
=> Distro update for v3.3.0

git/gitattr/macro.go, git/gitattr/macro_test.go, t/t-attributes.sh, t/t-fsck.sh
In commit 1ff52542da97d6418689a5528112b57e37536014 of PR #3391 we introduced the `MacroProcessor` type and methods to support the use of macro attributes in `.gitattributes` files.
However, we do not currently support the case where a macro attributes is specified with a `!` prefix, which Git handles by setting all attributes defined by the macro attribute back to the unspecified state.  (Note that the `-` prefix is not supported by Git for macro attributes, only the `!` one.)
To mimic the same behaviour in Git LFS we add a check for a macro attribute with its `Unspecified` `bool` set to `true`, and when this is detected we iterate through the set of attributes defined by the macro attribute and set them all to the same unspecified state.
We also add tests to confirm this new handling …
=> Handle macro attribute references with unspecified flag

CONTRIBUTING.md, Makefile, README.md, commands/run.go, debian/git-lfs.manpages, docs/man/git-lfs-faq.adoc, rpm/SPECS/git-lfs.spec
Right now, people have to read the FAQ on the wiki, which makes it hard to discover or to use offline.  We want people to have a copy of it installed as part of the documentation for ease of discovery.  Add it to the repository, and add a couple of missing entries to help explain some situations we haven't mentioned yet.
Fixes #5034
=> Add the FAQ in the repository

commands/command_pull.go
Users could confuse the previous error message with a shell path issue, as though it could not resolve the installation of git-lfs. The proposed message in this commit offers additional insight by:
- Detailing that LFS has not been installed for this repository.
- Offering a fix (git lfs install) for the error.
Relate issue #3048. Judging by the continued addition of upvotes, even after the issue has been closed, users are still running into this problem.
Passing local test through the use of `make test`.
=> Add information to ambiguous error message.

git/ls_files.go
When lfs is used with a huge mono repository with sparse-checkout, the lfs post-commit command took a long time. Per default git ls-files, which excute during the post-commit, retrieves all file paths, irrespectevly of the sparse set. When sparse-index is used ls-files respects the --sparse parameter, which omits the irrelevant files that are not in the sparse set, resulting in a performance improvement.
=> Use --sparse parameter for ls-files for performance optimization

CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v3.3.0, which is scheduled for Wednesday, November 30, 2022.
[git-lfs-windows-arm64-v3.3.0-pre.zip](https://github.com/git-lfs/git-lfs/files/10107793/git-lfs-windows-arm64-v3.3.0-pre.zip)
[git-lfs-windows-amd64-v3.3.0-pre.zip](https://github.com/git-lfs/git-lfs/files/10107794/git-lfs-windows-amd64-v3.3.0-pre.zip)
[git-lfs-windows-386-v3.3.0-pre.zip](https://github.com/git-lfs/git-lfs/files/10107795/git-lfs-windows-386-v3.3.0-pre.zip)
[git-lfs-v3.3.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/10107796/git-lfs-v3.3.0-pre.tar.gz)
[git-lfs-linux-s390x-v3.3.0-pre.tar.gz](https://github.com/git-lfs/git-lfs/files/10107797/git-lfs-linux-s390x-v3.3.0-pre.tar.gz) …
=> release: v3.3.0

docs/man/git-lfs-faq.adoc, docs/man/git-lfs-install.adoc
We've recently some some problems where Jenkins sets `core.hooksPath` to an invalid value (on Windows, notably this is `NUL:`).  Let's address this with a FAQ entry to explain how to work around that if necessary.
Also, in the course of writing this, it's been noted that the `--skip-repo` option is confusing with regards to `--local`.  These options are orthogonal and can be used together, so indicate that and update the documentation to better describe what the `--skip-repo` option does and how it can be used.
Fixes #5171
=> Add a FAQ entry on Jenkins problems

locking/ssh.go
Fix typo in the command name.
Fixes: c07c98a755c9 ("locking: provide a pure SSH transport")
Signed-off-by: Ayman Bagabas <ayman.bagabas@gmail.com>
CC/ @bk2204
=> fix: pure SSH list lock command name

ssh/ssh.go
OpenSSH complains if the control path is too long (>=104) On Darwin, os.MkdirTemp is too long, use /tmp instead.
ControlPath too long ('/var/folders/v3/5pnzpycs0pzdpytmgfzc7tj80000gn/T/sock-96855798/sock-b677e145501e220cfb5583ba1638a77ffe779df9' >= 104 bytes)
=> fix(ssh): use /tmp to place control dir on darwin

.github/workflows/ci.yml, .github/workflows/release.yml
We upgrade our CI and release GitHub Actions workflows to use the latest Ubuntu runners, which run Ubuntu LTS 22.04 at present, and the latest available versions of all Actions steps.
As testing the `release.yml` workflow is not convenient without generating a release, it has instead been run successfully on a separate, private repository cloned from this one.
In commit d6b34fa4355bd4891294eeb69ff05bb43977f385 of PR #4437 we switched our CI and release GitHub Actions workflows to explicitly use the then-latest Ubuntu LTS version 20.04 in order to support ARM64 builds, as these required a version of Go (specifically 1.16) which was not available on the `ubuntu-latest` Actions runners at the time because they still ran Ubuntu LTS version 18.04.
However, `ubuntu-latest` Actions runners now …
=> Upgrade workflows to latest Ubuntu and Actions versions

commands/commands.go, lfs/hook.go, t/t-install.sh, t/t-update.sh
In some cases, users may use `core.hooksPath` to locate their hooks in a different location.  However, right now, our hook and installation instructions mention only `.git/hooks`.
We can update the instructions without a problem, but we don't want to hard-code the hook path into the hooks themselves because of things like symlinks and moved repository, plus the fact that we can't update a hook automatically unless it's identical minus some whitespace changes.  To avoid spuriously failing to update a hook, let's print the right location with the instructions, and just mention `core.hookspath` and `.git/hooks` in the message, leaving it to the user to discover.
While we're at it, fix a small portion of the test which wasn't testing what we thought it was in a preparatory commit.  The gory …
=> Make hooks refer to `core.hookspath`

INSTALLING.md, README.md
Today I wanted to install Git LFS on a Linux-based system.
Unfortunately I had a hard time to find the complete installation instructions. 😩
1. I first opened [git-lfs.com](https://git-lfs.com/) on my macOS machine and I did _not_ see any link to installation instructions for Linux: <img width="1840" alt="image" src="https://user-images.githubusercontent.com/6301/213690713-265201a9-71c6-4560-9ada-928fb5492e88.png">
2. I then went to [GitHub's documentation for installing Git LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage) which besides pointing to [git-lfs.com](https://git-lfs.com/) (where I was already unsuccessful) it also points to the [README's Getting Started](https://github.com/git-lfs/git-lfs#getting-started) …
=> Simplify and deduplicate installation instructions

commands/command_lock.go, commands/command_unlock.go, t/t-locks.sh
On an error, we call `os.Exit(2)`.  However, the defer for the locking client that saves the local locks is not called in such a case, which can leave the locks out of sync even if some of the operation fails. If we're going to exit early, be sure we close the lock client to avoid this problem.
Fixes #5055
=> locks: ensure local locks are synced on error

lfshttp/standalone/standalone.go, t/t-standalone-file.sh
If `git rev-parse --git-dir` fails, Git doesn't think that the destination is a valid repository for whatever reason.  One of the most common reasons for that is that the repository is owned by another user.
In such a case, we want to show the error message from Git, since we really have no other indication that this is the case.  It could be just that the destination isn't a repository at all.  Regardless, the error message would be useful to the user to determine the problem, so let's return it if standard error isn't empty.
We also have an initial commit that sets up the error message processing.
Fixes #5081
=> standalone: print an error if the destination isn't a Git repository

ssh/connection.go, tq/ssh.go, tq/transfer_queue.go
In some cases, we can end up with a panic due to a pure SSH transfer lacking any connections, but it's not clear what those cases are.  Let's add some explicit checks that our connection is functional and return an error if not, and let's also add some defensiveness to make sure that if we encounter an unexpected case that we return a better error message.
=> Improve error handling for pure SSH protocol

t/t-attributes.sh, t/t-checkout.sh, t/t-fetch.sh, t/t-migrate-import.sh, t/t-post-commit.sh, t/t-pre-push.sh, t/t-standalone-file.sh, t/t-track.sh
When `set -e` is enabled, not all commands trigger an error exit if they return false.  For example, it's clear that commands in an `if` or `while` statement don't cause an error if they are false.
What is less obvious, however, is that negated commands and negated pipelines also have no effect on `set -e`.  From POSIX 1003.1-2017 (on `sh -e`):
When this option is on, if a simple command fails for any of the
reasons listed in Consequences of Shell Errors or returns an exit
status value >0, and is not part of the compound list following a
while, until, or if keyword, and is not a part of an AND or OR list,
and is not a pipeline preceded by the ! reserved word, then the
shell shall immediately exit.
As such, writing something like `! grep` will never fail.  Fortunately, we can append `&& …
=> t: avoid incorrect negated commands

Makefile
The Git LFS signing certificate for Windows binaries has changed, so we update the default signing certificate SHA-1 hash in the Makefile.
(The last update was in commit 16eec1724ef916ef1e9eb4be585c2dc27b7a7270 of PR #4946 in 2022.)
The commands used to generate this hash were:
```
$ openssl pkcs12 -info -in codesign.pfx -out codesign.pem
$ openssl x509 -text -in codesign.pem -fingerprint | \
grep Fingerprint | sed 's/^SHA1 Fingerprint=//' | \
sed 's/://g' | tr [:upper:] [:lower:]
```
=> Update Windows signing certificate hash

commands/command_track.go, commands/command_untrack.go, commands/path.go, git/attribs.go, t/t-track.sh, tools/filetools.go
As some have recently noticed, our Windows CI has been broken due to the `t/t-track.sh` test failing, which has been caused by a change to our CI in Go 1.20 wherein it always “helpfully” includes a dot component for relative paths with no other directory.  This is not very helpful in our case, and patch 2 here fixes that problem.
Patch 3 also fixes a problem that had gone unnoticed by our testsuite but that is related.
As usual, these commits all have their own reasonable commit messages and explain independently why they're valuable.
=> Fix Windows CI with Go 1.20

commands/commands.go, commands/lockverifier.go, commands/pull.go, commands/uploader.go, lfs/gitfilter_smudge.go, lfs/lfs.go, t/git-lfs-test-server-api/main.go, t/git-lfs-test-server-api/testdownload.go, t/git-lfs-test-server-api/testupload.go, t/t-filter-process.sh, tq/api.go, tq/basic_download.go, tq/basic_upload.go, tq/custom.go, tq/manifest.go, tq/ssh.go, tq/transfer_queue.go, tq/tus_upload.go
When a user invokes `git archive` with LFS files, `git lfs filter-process` is invoked to smudge the LFS files.  However, currently when we instantiate the manifest object as part of that, an attempt is made to connect to the remote using SSH, which we don't want to do unless necessary.  For example, if the user already has all the files locally, the network connection is needless and serves only to waste resources.
Adjust our manifest types to introduce a lazy manifest that only spawns the SSH connection on demand.  Further description is available in the commit messages.
Fixes #5307
=> Avoid needlessly spawning SSH connections with `git archive`

commands/run.go, go.mod, go.sum
Fixes #5104. Currently still WIP - completions work correctly for a command named 'git-lfs', but not for 'git lfs'. Need to figure out how to modify the generated script to complete the subcommand correctly.
=> [WIP] Add shell completion generation

docs/README.md
In commit 2f5b120dba77dfb2e2d03422864d7462717f1347 of PR #682 a link to a YouTube video on the "GitHub Training & Guides" channel was added to the `docs/README.md` file.  The video was named "Git Large File Storage - How to Work with Big Files".
However, this YouTube channel has now been decommissioned by GitHub and the video is no longer available, so until a replacement is available, we remove the link to the old video.
For reference, the video is available from the Internet Archive's page [capture](https://web.archive.org/web/20160120103000/https://www.youtube.com/watch?v=uLR1RNqJ1Mw).
Fixes #5320.
/cc @KyrieLii as reporter.
=> Remove stale video link

.github/workflows/ci.yml, .github/workflows/release.yml
As our official policy is to support the latest version of Go, we upgrade our CI and release workflows to version 1.20, which was recently released.
We also drop support for versions older than 1.19 as they are not supported by upstream Go.
Note that several older required CI jobs will not run for this PR, and the newer jobs should be marked as required after this PR is merged.
=> Update to Go version 1.20

docs/man/git-lfs-migrate.adoc
When using the `git lfs migrate` command with its `--everything` option, all commits reachable from any refs, local or remote, are considered for migration; however, per PR #2559, only local refs are updated after the migration to avoid desynchronizing remote refs with the origin.
We therefore clarify this distinction in the command's manual page, as well as clarifying that the `git push` command's `--all` option refers only to local branches.
Resolves the documentation issue noted in #5316.
=> Clarify `git lfs migrate` handling of local and remote references

t/cmd/lfstest-gitserver.go
Some time back, Git added support for protocol version 2 over HTTP. This is announced by the `Git-Protocol` header, the value of which Git expects to see as the `GIT_PROTOCOL` environment variable.  If it receives that value, then it switches into protocol v2 mode.
While this is a nice to have in general, it's presently important to fix our testsuite in CI when testing in SHA-256 mode.  In that mode, we set `GIT_DEFAULT_HASH=sha256` to specify the default hash algorithm.  In protocols v0 and v1, Git does not send a capabilities line by default (although one is accepted) in an empty repository, and if no such line is present, it's not possible to discern the hash algorithm in use.
Git recently (after 2.40) added a patch that resulted in empty repositories that are cloned not honouring …
=> Fix CI by enabling Git protocol v2

commands/command_install.go, commands/command_uninstall.go, git/config.go, lfs/attribute.go, t/t-install-worktree.sh, t/t-install.sh, t/t-uninstall-worktree.sh, t/t-uninstall.sh
There are actually two possible global configuration files, `$HOME/.gitconfig` and `$XDG_CONFIG_HOME/git/config`.  However, the `--global` file by default modifies only the former if it's present. Add a `--file` option to `git lfs install` and `git lfs uninstall` so that users can choose which of those files they'd like to use.
Fixes #4947
=> Add a `--file` option to install and uninstall

tools/robustio_windows.go
I failed to find which Go version git-lfs declares as oldest supported. CI runs against 1.19 and 1.20. But anyway, 1.12 became EOL back in 2020.
=> Drop pre-1.13 Go compatibility code

docs/man/git-lfs-faq.adoc
We've gotten a couple of inquiries about archiving subdirectories such that the LFS files are included.  Let's add a FAQ entry on why this doesn't work by default and how people can make it work.
Fixes #5343
=> FAQ: add entry on archiving subdirectories

commands/command_fetch.go, commands/command_migrate.go, commands/command_migrate_export.go, commands/command_prune.go, git/githistory/rewriter.go, tasklog/log.go, tasklog/percentage_task.go, tasklog/percentage_task_test.go, tasklog/waiting_task.go
This PR revises our handling of structures that implement the `Task` [interface](https://github.com/git-lfs/git-lfs/blob/1efc16b424ea1f88bfbcfe81a667bcfb2cdba3d5/tasklog/task.go#L5-L17) of the `tasklog` package so that in all cases we always immediately register a deferred call to their `Complete()` method after allocating and initializing a new structure.  This ensures that the channels created for the structures are always closed, which prevents `Logger` instances waiting on those channels from hanging indefinitely following a panic or other exceptional error condition.
As well, we simplify some instances of the construction of these types of structures, and clean up some details in the implementation of the `tasklog` package.
---
In the case of the `PercentageTask` …
=> Ensure all logging tasks are closed and simplify log task dispatching

creds/creds.go, creds/creds_test.go, creds/netrc.go, creds/netrc_test.go, lfsapi/auth.go, lfsapi/auth_test.go, lfshttp/certs.go, t/cmd/git-credential-lfstest.go, t/cmd/lfstest-gitserver.go, t/t-credentials.sh
Git recently added a new field to the credential helper, `wwwauth[]`, which may be repeated and includes all of the `WWW-Authenticate` headers so that the credential helper may choose an appropriate set of credentials and extract any sort of necessary data from the field (such as challenge).
In Git LFS, we also want to do this with the `LFS-Authenticate` headers as well, since those are often used for the same purpose, so include both these headers in that field when passing them to `git credential fill`.
Note that `git credential fill` only honours this value and passes it to the credential helper in Git 2.41 and newer (including the latest `HEAD`).  However, just to be safe, let's add an undocumented and experimental option (`credential.*.skipwwwauth`) that users can use to control …
=> Add support for `wwwauth[]` to credential helpers

commands/command_unlock.go, t/t-unlock.sh
When unlock is called with the JSON flag and ID, the response is empty.
The current behavior:
git lfs lock --json <SOME_PATH>
[{"id":"103","path":"<SOME_PATH>","owner":{"name":"<Author>"},"locked_at":"2023-06-06T10:44:37Z"}]
git lfs unlock --json --id=103 
[]
The expected behavior:
git lfs lock --json <SOME_PATH>
[{"id":"103","path":"<SOME_PATH>","owner":{"name":"<Author>"},"locked_at":"2023-06-06T10:44:37Z"}]
git lfs unlock --json --id=103 
[{"id":"103","unlocked":true}]
=> Unlock by ID with JSON Flag returns empty array

commands/command_checkout.go, commands/command_dedup.go, commands/command_fetch.go, commands/command_fsck.go, commands/command_ls_files.go, commands/command_prune.go, commands/command_pull.go, commands/command_status.go, commands/uploader.go, lfs/gitscanner.go, lfs/gitscanner_catfilebatchcheck.go, lfs/gitscanner_log.go, lfs/gitscanner_refs.go, lfs/scanner_git_test.go
The `GitScanner` [structure](https://github.com/git-lfs/git-lfs/blob/29dc7cc12772e9f89ff29ec3645cbc5274d95860/lfs/gitscanner.go#L22-L35) was originally introduced in PR #1670 and has been expanded organically over time since then.  This PR addresses a number of inconsistencies in the current design, removing unused or unnecessary logic and revising the internal implementation some of the scanning functions.
It should be easiest to review this PR commit-by-commit, as each commit has a detailed description and should be logically independent and bisectable.
---
This PR is motivated principally by the desire to remove the structure's `Close()` [method](https://github.com/git-lfs/git-lfs/blob/29dc7cc12772e9f89ff29ec3645cbc5274d95860/lfs/gitscanner.go#L50-L62), whose presence implies that it …
=> Refactor `GitScanner` and simplify implementation

.github/workflows/ci.yml, .github/workflows/release.yml
Running `refreshenv` in CI produces this message:
```
RefreshEnv.cmd does not work when run from this process. If you're in PowerShell, please 'Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1' and try again.
```
Since it's not really working in this case, let's just remove it.
=> workflows: remove refreshenv

lfsapi/endpoint_finder.go, t/t-standalone-file.sh
When we want to handle a local path, we must rewrite it internally into a `file:///` URL, because we dispatch our standalone transfer agent based on the URL scheme.  However, once we've looked up an appropriate URL and formatted it as the scheme prefers, if it contains a trailing slash, we ignore the entire lookup and replace the URL with the raw one given, but without the trailing slash.
This behaviour seems a bit bizarre, and it causes us to take a local path with a trailing slash and treat it not as the `file:///` URL it needs to be, but as a raw local path, which gets refused.  Let's avoid this problem by looking at the rewritten URL, and modifying that instead if we find its trailing slash to be offensive.
Fixes #5400
/cc @ebardsley as reporter
=> Handle local paths with trailing slashes

docs/man/git-lfs-logs.adoc
In PR #5054 we converted our manual pages to the AsciiDoc format, and in doing so, one entry in the manual page for the `git-lfs-logs(1)` command lost the relevant `<file>` option parameter from the ronn [version](https://github.com/git-lfs/git-lfs/blob/370b8d8f1932d47bca1f84a82c1d79bed84ec893/docs/man/git-lfs-logs.1.ronn?plain=1#L28), so we restore it now.
=> Fix missing parameter in `git lfs logs` manual page

git/git.go, t/t-track.sh
Right now, when we run `git lfs track`, we warn the user if the pattern they've provided matches an existing file name.  However, when we invoke that command with `--filename` and a pattern with brackets on Windows, we get an error because the escaped pattern contains backslashes, which results in broken behaviour on Windows.
The real cause of this problem, however, is that we're ultimately asking for a file name and not a pattern.  Our invocation happens to work on Unix, but we need it to also work on Windows.  To solve this, let's instead ask for ignored cached files and specify a single pattern. Since we've asked for a pattern, this results in a different behaviour from before and avoids the error.
We would have caught this on Windows if our weird file name code had worked there, but …
=> git: match patterns, not file names, for tracked files

CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v3.4.0, which is scheduled for Wednesday, July 26, 2023.
Note that this release will be made by a different member of the core team than the person who performed many of the past releases, and thus this release will be signed with a different OpenPGP key.  Please follow [the steps in the README to download all of the keys for the core team](https://github.com/git-lfs/git-lfs#verifying-releases) to verify this release.
[git-lfs-darwin-amd64-v3.4.0-pre.zip](https://github.com/git-lfs/git-lfs/files/12113934/git-lfs-darwin-amd64-v3.4.0-pre.zip)
[git-lfs-darwin-arm64-v3.4.0-pre.zip](https://github.com/git-lfs/git-lfs/files/12113935/git-lfs-darwin-arm64-v3.4.0-pre.zip) …
=> release: v3.4.0

docker/run_dockers.bsh, script/distro-tool, script/lib/distro.rb, script/packagecloud.rb, script/spec/distro_spec.rb, script/upload
Right now, we have multiple different locations for our distro information.  This is suboptimal in many ways because it requires developers to keep multiple sources of information in sync.
To solve this, let's write a Ruby script that contains our single source of truth.  It contains all of the existing data we have now in an easily processable format.  It uses a style which is called a _modulino_ in the Perl community, which is essentially a script which can also be required as a library for testing purposes.
Since we can require any file which ends in `.rb`, create the script as a library with this trailing suffix and require it in the RSpec tests we're adding so that we can test it produces the expected results. These tests can be run with a simple `rspec script/spec` using a standard …
=> Add a single source of truth for distro info

commands/command_push.go, t/t-push.sh
Right now, a user can invoke `git lfs push` with a remote and no refs. Surprisingly for some users, this pushes nothing, since no refs were given.
To help users invoke the command in a useful way, if there are no arguments on the command line and `--all` was not specified, then complain, unless we're reading from standard input.  The reason we allow empty lists of arguments with standard input is that this makes scripting easier by not forcing scripts to specifically consider whether the input is empty.
As well, allow users to specify an empty list of object IDs in `--stdin` mode as well.
Note that it should be fine to leave this until after the v3.4.0 release.
Fixes #5430
=> Print an error when pushing with no refs

docs/man/git-lfs-faq.adoc
Lots of people have questions about how to use proxies with Git LFS. Document that they can be used in the same way as with Git, except that we only support Basic authentication.  Tell people how to format the value.
Finally, indicate to users that their proxy must not modify the data in any way and that we don't encourage the use of TLS MITM proxies.  As has been documented in multiple scientific papers, including those below, these have been shown to be the cause of substantial security issues:
* https://arxiv.org/abs/1809.08729
* https://jhalderm.com/pub/papers/interception-ndss17.pdf
Fixes #5362
=> FAQ: add an entry about proxies

CONTRIBUTING.md
The `vendor` directory is `.gitignore`d, and vendoring as a process was fully removed in #4903.
=> Remove vendoring instructions from contributing docs

docs/howto/release-git-lfs.md
This PR updates and expands the "how-to" [documentation](https://github.com/git-lfs/git-lfs/blob/cbd62023ca389f3ddc4b08293dd8cd2785d8e02d/docs/howto/release-git-lfs.md) of the steps we follow to release a new Git LFS version.
The primary changes in this PR are:
- Making our terminology more generic and consistent throughout, such as by adopting the version placeholders `vM.N.P` instead of the legacy `v2.n.m`.
- Adjusting the suggested time scales for the different types of releases to reflect the current, more attenuated development process now that the project is more mature.
- Updating the [list](https://github.com/git-lfs/git-lfs/blob/cbd62023ca389f3ddc4b08293dd8cd2785d8e02d/docs/howto/release-git-lfs.md#release-artifacts) of release artifacts to reflect the current set we publish.
- …
=> Update and expand documentation of the Git LFS release process

lfs/gitfilter_smudge.go, t/Makefile, t/cmd/lfstest-nanomtime.go, t/t-pull.sh
When a user performs a `git lfs pull`, we update all of the files in the working tree that are pointers (and aren't excluded) to have their correct content.  However, if the files are empty, they don't need a change, and some users find the fact that we update the mtime of the file to be undesirable.
Let's avoid this by explicitly checking to see if the file is empty and if it's supposed to be and not updating it.
Fixes #5113
=> Avoid modifying the mtime of empty files

README.md
As discussed in #5498, Windows users in particular may need to restart their command shell after installing a Git LFS binary in order for any changes to `$PATH` to take effect, so we add a note to our installation instructions on this point.
/cc @zpostfacto as reporter.
=> Add installation note about restarting shells on Windows for PATH changes

commands/command_track.go, t/t-track.sh
If the user requests a pattern that matches `.gitattributes` and that's the only pattern, we currently return a zero exit status, even though we've failed.  Similarly, if an error occurs, we fail to exit nonzero. In both of these cases, switch to exiting nonzero to indicate that the operation was unsuccessful.
However, continue to return successfully if the reason we didn't process any patterns was because they're already matched, since what the user wanted is already done.
/cc #5511
/cc @RuRo as reporter
=> track: reject attempts to modify `.gitattributes`

go.mod, go.sum, lfs/gitfilter.go, lfs/util.go, lfs/util_test.go
In commit 00f1e9521ab5d39aab393796745189d39c27b9a0 of PR #5504 we added the `TestCopyCallbackFileThrottle()` [test function](https://github.com/git-lfs/git-lfs/blob/cb27449f5c44aeda48af90962ee80832c5c42064/lfs/util_test.go#L72-L110) to confirm that the `CopyCallbackFile()` [method](https://github.com/git-lfs/git-lfs/blob/cb27449f5c44aeda48af90962ee80832c5c42064/lfs/util.go#L35-L71) of `GitFilter` structure in the `lfs` package now throttled its output of progress messages into a log file so that, in general, no more than one message was written during the interval defined by the `tasklog.DefaultLoggingThrottle` [value](https://github.com/git-lfs/git-lfs/blob/cb27449f5c44aeda48af90962ee80832c5c42064/tasklog/log.go#L18).  This new throttling behaviour was added in commit …
=> Mock time in copy callback log file test

tq/transfer.go
SSH connections that return id and/or token from batch require these fields for get-object and put-object. Properly copy them when making a copy of a transfer in newTransfer().
=> tq/transfer: copy Id and Token

locking/locks.go, t/t-unlock.sh
This PR cherry-picks the key change from PR #5376, authored by @bogomolets-owl, which revises the internal `lockIdFromPath()` [method](https://github.com/git-lfs/git-lfs/blob/6fc7893e4205b5bfcdbfd7065b269df15fc0f6d0/locking/locks.go#L391-L419) of the `Client` structure in the `locking` package so that the current refspec is always sent to the Git LFS File Locking API when querying for a lock ID corresponding to a given file path, and adds and expands our test suite to confirm this change is effective when the API service tracks locks using refspecs and causes no problems when the API service does not do so.
The `lockIdFromPath()` method is only [called](https://github.com/git-lfs/git-lfs/blob/6fc7893e4205b5bfcdbfd7065b269df15fc0f6d0/locking/locks.go#L157) by the `UnlockFile()` method, and …
=> Include reference specifier in unlock requests

tq/manifest.go
The `findStandaloneTransfer()` function of the `tq` package was updated in commit 28f9b73d2f2bc529ce4385d372ab900e3763b854 of PR #3905 to determine whether to use the built-in file standalone transfer adapter based on the actual endpoint URL, taking into account settings like `lfs.url` which override the endpoint URL we would otherwise construct from the current remote's URL.  However, the code still checked the `lfs.<url>.standaloneTransferAgent` setting using the URL constructed from the remote's URL, and so [called](https://github.com/git-lfs/git-lfs/blob/28f9b73d2f2bc529ce4385d372ab900e3763b854/tq/manifest.go#L120-L121) both the `Endpoint()` and `RemoteEndpoint()` methods of the `EndpointFinder` interface.
Then in commit 594f8e386cce3441e06c9094ab5e251f0e07ca1f of PR #4446, when the …
=> Retrieve endpoint URL only once when checking standalone transfer adapter configurations

lfs/pointer.go
We should use `(*regexp.Regexp).MatchString` instead of `(*regexp.Regexp).Match([]byte(...))` to avoid unnecessary `[]byte` conversions and reduce allocations. A one-line change for free performance gain.
Example benchmark:
```go
func BenchmarkMatch(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := oidRE.Match([]byte("2a3b6578c2de07a35b2f2d9bf1869d437aed2e5b8f1c96a0df9d9be3c05a4a8a")); !match {
b.Fail()
}
}
}
func BenchmarkMatchString(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := oidRE.MatchString("2a3b6578c2de07a35b2f2d9bf1869d437aed2e5b8f1c96a0df9d9be3c05a4a8a"); !match {
b.Fail()
}
}
}
```
Result:
```
goos: linux
goarch: amd64
pkg: github.com/git-lfs/git-lfs/v3/lfs
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkMatch-16          	 1044811	      1202 ns/op …
```
=> lfs: avoid unnecessary byte/string conversion

.github/workflows/release.yml, Makefile, script/notarize
As of November 1, 2023, Apple will no longer accept notarized apps using altool, which is used by https://github.com/mitchellh/gon, which we've been using.  Port this code to notarytool, which is Apple's preferred command-line tool.
The secrets have been placed in the regular and CI test secret stores already and this has worked successfully on a test build of the release workflow.
Fixes #5394
=> Update notarization to use `notarytool`

commands/command_track.go, t/t-track-attrs.sh
In `--dry-run` mode, we're documented to not modify the disk, which means users will not expect us to be modifying `.gitattributes`.  Fix this by setting the `--no-modify-attrs` flag implicitly if `--dry-run` is set.
Fixes #5557
/cc @GTP95 as reporter
=> track: don't modify `.gitattributes` with `--dry-run`

docs/proposals/ssh_adapter.md
- Remove duplicate invalid definition of `error-message`
- Fix typo `status-error-response`
=> doc: update ssh_adapter.md

docs/man/git-lfs-config.adoc, lfsapi/endpoint_finder_test.go, lfsapi/lfsapi.go, lfshttp/client.go, lfshttp/endpoint.go, t/t-locks.sh
Some people have very slow SSH round trips and the extra time to attempt a failed git-lfs-transfer operation is bothersome.  Let's add an option to allow users to use either the pure SSH protocol or the older hybrid protocol based on the URL in question to let them choose the right value if they know what it should be.
=> Allow configuring the SSH protocol

commands/command_lock.go, commands/command_locks.go, commands/command_unlock.go, git/git.go, lfsapi/endpoint_finder.go, locking/locks.go
When performing locking for multiple files, we can spend a lot of time repeating the same operations once for each file.  In most cases, we don't need to do that, and we can get better performance by doing the operation only once.  This is going to be especially noticeable on Windows, where spawning a process is more expensive.
This PR contains independent, logical, bisectable commits each with their own commit message, and as such is best reviewed commit by commit.
=> Improve locking performance

config/url_config.go, docs/man/git-lfs-config.adoc
The anchors in [git-config](https://git-scm.com/docs/git-config) have changed.
=> Fix git-scm.com links

CHANGELOG.md, config/version.go, creds/creds.go, creds/netrc.go, debian/changelog, lfsapi/auth.go, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v3.4.1, which is scheduled for Wednesday, December 13, 2023.
Note that this release will be made by a different member of the core team than the person who performed many of the past releases, and thus this release will be signed with a different OpenPGP key.  Please follow [the steps in the README to download all of the keys for the core team](https://github.com/git-lfs/git-lfs#verifying-releases) to verify this release.
[git-lfs-darwin-amd64-v3.4.1-pre.zip](https://github.com/git-lfs/git-lfs/files/13642027/git-lfs-darwin-amd64-v3.4.1-pre.zip)
[git-lfs-darwin-arm64-v3.4.1-pre.zip](https://github.com/git-lfs/git-lfs/files/13642028/git-lfs-darwin-arm64-v3.4.1-pre.zip) …
=> release: v3.4.1

docs/howto/release-git-lfs.md, script/changelog
When we prepare a patch release of Git LFS, we cherry-pick specific merged changes from the `main` branch onto a `release-next` branch using the `git cherry-pick` command with the `-m1` option, which flattens all the commits unique to the merge on the `main` branch into a single non-merge commit on the release branch.
As a result, when we run our `script/changelog` script to generate a summary of the changes for the patch release, the `git rev-list` command it [executes](https://github.com/git-lfs/git-lfs/blob/7832469836703657c55b85e9cba1b2f7809dfc12/script/changelog#L24) returns nothing because it uses the `--merges` option, and the flattened commits on the release branch are not actual merge commits.
We therefore add a `--patch` option (as suggested by @bk2204) to our script which runs …
=> Update release documentation and changelog summary script for patch releases

t/t-path.sh
In commit 10c4ffc6b888eee8f2134a7009a0db1bc393e17b we added the `does not look in current directory for git with credential helper` [test](https://github.com/git-lfs/git-lfs/blob/2db011fb5e5685e8bf150c5dafa50ecae067462c/t/t-path.sh#L27-L120) in order to validate changes made to remediate the issues reported in CVE-2021-21237, and revised it as part of our response to CVE-2022-24826 in commit 11092ef2b17eaa67f3363edc68b59331b979f7ee.  This test checks that Git LFS will not run a potentially malicious Git executable found in the working tree of a repository.
As noted in commit 7e8d3ba84ad8ee5314cb74a32b80622b919163fe, in order to avoid invoking this executable while setting up the test conditions we generally remove it from the working directory as soon as possible, but we have to at least …
=> t/t-path.sh: avoid flaky test setup failure on Windows due to new Go path security checks

t/t-clean.sh, t/t-fsck.sh, t/t-malformed-pointers.sh
The `base64(1)` binary provided with macOS does not accept a bare input file name, unlike any of the GNU coreutils implementations of `base64(1)` or either the older Fourmilab or newer `bintrans(1)` BSD implementations.  Instead, it appears to be a version unique to OS X which requires an `-i` option before a file name to be used for input.
(See, for reference, the manual pages for the OS X [version](https://www.unix.com/man-page/osx/1/base64/), the GNU coreutils [version](https://man7.org/linux/man-pages/man1/base64.1.html), the Fourmilab BSD [version](https://www.fourmilab.ch/webtools/base64/), and the `bintrans(1)` BSD [version](https://man.freebsd.org/cgi/man.cgi?query=base64&manpath=FreeBSD+15.0-CURRENT).)
With the Xcode developer tools for macOS installed, along with Go, Git, etc., …
=> t: pipe random data to `base64(1)` to be compatible with macOS

t/t-credentials.sh, t/testhelpers.sh
We've noticed that this test has become flaky sometimes and fails in CI. More recently, a distributor noticed that this test fails consistently when run with 4 jobs at a time with `prove`.  Not all of the tests fail every time, but at least one of them does.
Part of the relevant difference is that our netrc tests use `localhost` as the machine name instead of the default 127.0.0.1.  This is helpful, because it means we don't call the credential helper, when we really want to fall back to the askpass code.  That's because we use different credentials for the `netrctest` remote, so if there were credentials available for `localhost`, we'll fail since we'll provide the wrong ones.
The reason, therefore, that this test is flaky is that the clone code creates an entry for the credential helper …
=> Fix flaky test `t-credentials.sh`

.github/workflows/release.yml, Makefile
It will soon be the case that all private keys used for signing Windows binaries must be stored in an HSM.  To make that possible, let's use Azure Code Signing to generate a temporary certificate which is backed by an HSM and use that to sign the data.
I've successfully tested this on our internal CI repo, where I've verified that the intermediate assets are all correctly signed (using `osslsigncode`).
This PR contains independent, logical, bisectable commits each with their own commit message, and as such is best reviewed commit by commit.
=> Use Azure Code Signing for Windows release binaries

locking/ssh.go, ssh/connection.go, tq/ssh.go
Right now, we spawn potentially several connections without necessarily needing to.  For example, if we're transferring two objects, we can practically use at most three connections: one for the batch and one for each object.
Instead of spawning all the workers up front, let's change how we do things and simply pass in the worker number at first.  Then, acquire the connection when we're uploading or downloading so that the connection is only spawned on demand.  This means that we spawn fewer workers in case there are few objects.
/cc #5622
=> Initialize sessions lazily

lfs/attribute.go
If someone has a system configuration set up for Git LFS, such as with their package manager, `git lfs uninstall` will not be effective unless the user has specified that file and has privileges to edit it.  In such a case, let's warn the user so that they know that their attempt at uninstalling might not have been effective.
Fixes #5588
=> attribute: warn if config exists after uninstalling

commands/command_push.go, t/t-fetch.sh, t/t-fsck.sh, t/t-migrate-export.sh, t/t-migrate-import.sh, t/t-migrate-info.sh, t/t-push.sh
As @philip-peterson described in PR #5295, the `git lfs push` command does not currently report an error when given an invalid ref, unlike a number of our other commands, so we update the command to output an error message in this situation, and we add a test to confirm the new behaviour works as expected.
The `git lfs fetch`, `git lfs fsck`, and `git lfs migrate` commands, in contrast, do detect invalid refs provided as command-line arguments and report them as errors, but since we do not have tests for this behaviour, we add some now.
Note that this PR's changes should suffice to meet the intent of PR #5295, and incorporates work from that PR.
/cc @philip-peterson as reporter and author of PR #5295
=> Report invalid ref in `git lfs push` command

commands/command_fsck.go, commands/command_ls_files.go, commands/command_prune.go, commands/command_status.go, git/git.go, git/git_test.go, lfs/diff_index_scanner.go, lfs/gitscanner.go, lfs/gitscanner_index.go, t/cmd/util/testutils.go, t/t-prune-worktree.sh, t/t-prune.sh
This PR should fix https://github.com/git-lfs/git-lfs/issues/5636
Running git lfs prune right after git add will prune the indexed files from the LFS cache so that any commit will result in a rightfully rejected push. Even worse, doing multiple commits on changes of the same file will permanently delete LFS data that is not recoverable.
This change retains all files that are in the index by diffing the index against the HEAD.
=> Fix git lfs prune is deleting staged files in the index

script/lib/distro.rb
Update our distros to remove old, EOL versions and add new versions.
As part of this work, move our SLES and OpenSUSE 15 RPMs to use the Rocky 8 versions in preparation for a future CentOS 7 EOL.
/cc #5627
=> Distro updates for v3.5

.github/workflows/ci.yml, .github/workflows/release.yml
We want to support and test the latest versions of Go.  Now that Go 1.22 is out, let's test against 1.22 and 1.21 instead of 1.21 and 1.20.
=> workflows: update to Go 1.22

commands/command_ls_files.go, t/t-ls-files.sh
As reported in https://github.com/git-lfs/git-lfs/issues/1189#issuecomment-1950664657, the `git lfs ls-files` displays incorrect file status information when it is run from within a subdirectory of the Git repository's working tree rather than in the root directory.
Specifically, in the command's normal, compact output format, the `-` indicator is shown for all files, even if they exist in the working tree and should be listed with the `*` indicator.  This problem also affects the  value of the `checkout` fields in the output when the `--debug` or `--json` options are used, with the `false` value always shown for all files.
We resolve this problem by prepending the full, canonicalized path (as provided by the `cfg.LocalWorkingDir()` function) to the individual file paths before their …
=> Display correct status information when `git lfs ls-files` run in subdirectory

lfshttp/certs.go, lfshttp/client.go, t/t-clone.sh, t/t-fetch.sh, t/testhelpers.sh
Git accepts paths for SSL keys and certs starting with a tilde to expand to the user's home directory.  This is very useful for configuration which must be shared across systems.  Let's add support for the same thing here and add a test to make sure it works.
In addition, avoid crashing on invalid data by verifying our PEM block before attempting to decode it.
Fixes #5652
=> Add support for homedir expansion in SSL key and cert paths

.github/workflows/ci.yml, .github/workflows/release.yml
As of Git for Windows v2.44, the `msgfmt.exe` binary is no longer installed by default and is therefore not available in the GitHub Actions runners we use for our CI and release jobs.  We instead use the `git-for-windows/setup-git-for-windows-sdk` Action to install the SDK for Git for Windows, which includes `msgfmt.exe`.
This should resolve one of the problems noted in https://github.com/git-lfs/git-lfs/pull/5660#issuecomment-1969919567.
h/t @dscho for the advice to use the SDK!
=> Install msgfmt on Windows in CI and release workflows

script/packagecloud.rb
We need an instance to call `distro_name_map`, so make sure we properly instantiate one by calling `new`.
=> script/packagecloud: instantiate distro map properly

.github/workflows/release.yml
Due to the issue noted in https://github.com/golang/go/issues/65705, we don't want to build our release assets with 1.22.0, since this can cause deadlock in the HTTP client.  Instead, let's keep testing with both 1.21 and 1.22 in our CI jobs, but build with 1.21 for release.
In the future, once that bug is fixed and an updated version is released, we can move back to 1.22.
=> Build release assets with Go 1.21

.github/workflows/release.yml
Now that Go 1.22.1 is out with a backport to fix https://github.com/golang/go/issues/65705, revert the change that forced us to build with Go 1.21 to avoid the problem.
=> Build release assets with 1.22

script/windows-installer/inno-setup-git-lfs-installer.iss
The Windows installer expands the path to the `C:\Program Files` directory using the standard casing for this.  However, our `PATH` value does not need to contain the same case, since on Windows this directory is case insensitive, and as a result, if the two differ in case, we don't correctly detect that the Git executable is in `PATH`.
Let's fix this by lowercasing both versions of the text.  Note that instead of using the `Lowercase` function, which deals only with ASCII characters, we use `AnsiLowercase`, which, despite its name, uses the current Windows locale.
This is not guaranteed to produce correct results in all cases because the file system's case folding is done in the kernel in a locale-insensitive way based on the tables created when the file system was created, but there's …
=> Match `PATH` case insensitively in Windows installer

script/windows-installer/inno-setup-git-lfs-installer.iss
In commit a5b751f541abb52e30b60aebe530f9dbd72838df of PR #4925 we introduced an advisory check into the Windows installer for Git LFS which notifies the administrator if a `git.exe` file is found outside of the `C:\Program Files` directory and would, according to the order of elements in the `PATH` and `PATHEXT` environment variables, be found and run by Git LFS during the installation process.
Git LFS [searches](https://github.com/git-lfs/git-lfs/blob/add64b8f91827db7922c8a4f6574b019b7cedfb8/subprocess/path.go#L39-L70) for executables using logic imported and modified from the Go standard libraries into our `subprocess` package, because until Go v1.19, the `os/exec` package would search first in the current working directory, which allowed was a security vulnerability.  Hence Git LFS …
=> Use lower-case file extensions in Windows installer path checks

commands/pull.go, git/git.go, t/t-checkout.sh
Right now, when someone deletes a pointer from the index with `git rm` and then runs `git lfs checkout`, the operation fails with a message of "Could not update the index" because our invocation of `git update-index` is missing the `--add` flag.
Obviously, the user does not expect an error in this case, and `git checkout` simply ignores files staged for deletation, so let's do the same thing.  If a file on disk is deleted, check the index with `git diff-index` to see if it's deleted from `HEAD`.  If so, ignore the file, just like Git does. Note that we use `git diff-index` specifically because it doesn't refresh the index and is therefore much cheaper than alternatives, such as `git status`, which might do that.
Fixes #5669
=> checkout: gracefully handle files deleted from the index

.github/workflows/ci.yml
When we're building with the earliest or latest Git, it's not guaranteed that Go is installed.  Notably, in the latest version of the macos-latest runners, Go is not installed by default.  Fix this by explicitly setting up Go before running further commands.
=> .github/workflows: use actions/setup-go everywhere

git/git.go, lfs/gitscanner_log.go, subprocess/subprocess.go
When we're running our log scanning code, we can end up with a deadlock if there is lots of output on standard error because we either don't read standard error at all or we only read it when we're done reading standard output.  To fix this, let's add and use some functions that either discard standard error if we're not using it, as well as making sure we read standard error in a separate goroutine so the child process doesn't block.
Fixes #5720
=> Avoid deadlocking on log scanning with lots of output on stderr

docs/api/basic-transfers.md, docs/api/batch.md, docs/api/locking.md
Since at least commit 099adaaa5e59be83ee9f3079398c4398fd282e50 in 2013 the Git LFS client has included a `charset=utf-8` parameter in some or all of the `Content-Type` headers it sends to server API endpoints.
As noted in #5775, we do not at present mention this parameter in our API documentation, and the `charset` parameter is not required by any IETF RFCs for MIME types other than `text/*` types, so we update our documentation to mention that servers should be prepared to accept this header parameter but that it is not required.
Thanks to @KalleOlaviNiemitalo for the suggestion!
=> docs/api: note API clients may send `charset` parameter in `Content-Type` header

creds/creds.go, lfsapi/auth.go, t/cmd/git-credential-lfstest.go, t/cmd/lfstest-gitserver.go, t/t-credentials.sh, t/testhelpers.sh
Git recently learned to announce capabilities for credential helpers and this functionality will be in Git 2.46.  One of the capabilities is the ability for credential helpers to specify arbitrary HTTP credential schemes and the credentials for these schemes.  This allows users with a suitable credential helper to implement support for, say, Bearer authentication where the credentials come from a credential helper.
With this capability, Git LFS will advertise the `capability[]=authtype` line, and a suitable version of Git will pass this along to the helper, which can then return something like `authtype=Bearer` and `credential=my-bearer-token` to provide a `Authorization: Bearer my-bearer-token` header.  It can also return other schemes as well, and the `credential` field can include any …
=> Support arbitrary HTTP credential schemes for authentication

creds/creds.go, go.mod, lfsapi/auth.go, lfsapi/auth_test.go, t/cmd/git-credential-lfstest.go, t/cmd/lfstest-gitserver.go, t/t-credentials.sh
In 2.46, Git will support multistage authentication from credential helpers.  This will allow Git and Git LFS to implement functionality like NTLM and Kerberos in the credential helper, which lets this functionality to work even if Git LFS doesn't support it natively.
This requires two separate pieces of data.  First, it involves a `state[]` field, which each credential helper can add to keep track of state.  Second, it allows the usage of a boolean `continue` field, which indicates that the response is multistage and this is not the final stage.
In order to make this work, we adjust a few things.  First, we advertise the `state` capability.  Additionally, we save and pass back the `state[]` fields that the credential helper may send to us.  We also don't change the authentication scheme …
=> Support multistage authentication with a Git credential helper

script/build-git
This PR resolves a problem which is causing our `Build with earliest Git` CI [jobs](https://github.com/git-lfs/git-lfs/blob/fc61febe9cc2d9ddc6ffe3e8d1ae546512632552/.github/workflows/ci.yml#L152-L175) to [fail](https://github.com/chrisd8088/git-lfs/actions/runs/10859593753/job/30144599507) at present on macOS.  The failures are due to a regression in the system-installed version 8.7.1 of libcurl currently available on macOS.
We therefore revise our scripts to ensure we build Git so it links against the newer version of libcurl we [install](https://github.com/git-lfs/git-lfs/blob/fc61febe9cc2d9ddc6ffe3e8d1ae546512632552/script/build-git#L6-L8) with Homebrew.  The regression in the 8.7.x versions of libcurl is described in curl/curl#13229 and affects programs such as `git-http-push(1)` and …
=> Always build Git against custom libcurl in CI workflows on macOS

t/Makefile, t/cmd/lfstest-genrandom.go, t/fixtures/migrate.sh, t/t-clean.sh, t/t-fsck.sh, t/t-malformed-pointers.sh, t/t-migrate-export.sh, t/t-migrate-fixup.sh, t/t-migrate-import.sh, t/t-migrate-info.sh, t/t-prune.sh, t/t-smudge.sh, t/testenv.sh
For the past several months our CI test suite has experienced intermittent failures when running on Windows, which are caused when no data is returned from the simulated `/dev/urandom` special file in Git Bash.
While the cause of this regression in the Git Bash/MSYS2 environment is unclear, to avoid this and any similar issues in the future, we introduce a new test helper program named `lfstest-genrandom`, and then use it to generate the contents of all the test files we need throughout our test suite.
Further, we make use of this new utility to generate random filenames and directory names, which permits us to replace calls to `mktemp(1)` and `uuidgen(1)` (which doesn't exist in Git Bash) in a number of our tests.
Each commit in this PR has a detailed description; however, it should also …
=> Use custom random data generator for all test objects and filenames

.github/workflows/ci.yml, .github/workflows/release.yml
Go version 1.23 has been released, and because we aim to build and test Git LFS against only supported versions of Go, we upgrade our GitHub Actions CI workflows to test against Go versions 1.23 and 1.22.
This resolves a problem now seen in our `Build with specific Go` CI job, where we [install](https://github.com/git-lfs/git-lfs/blob/17aaf6fbea3c2d9af5e429592a19c7dab2d7e1a8/script/cibuild#L21) the latest version of the `goimports` package and it fails because the `x/tools` module requires Go 1.22 as of commit golang/tools@70f56264139c00af8ea420899cdb440c32b5599e, and we are still using Go 1.21 for that CI job.
After this PR is merged, we will revise the required set of jobs in our CI test suite, and also upgrade the version of Go …
=> Upgrade to Go 1.23

.github/workflows/release.yml
The `azure/azure-code-signing-action` GitHub repository has been removed and replaced with the `azure/trusted-signing-action` repository, so we update our release GitHub Actions workflow to use the latest version of the new action.
This PR's changes have been tested with a successful run of our release workflow in a private repository.
=> Update release workflow to use Windows Trusted Signing Action

commands/command_fetch.go
The intention here should be to initialize a slice with a capacity of  len(refs)  rather than initializing the length of this slice.
=> fix: fix slice init length

ssh/connection.go
Commit 44b8801cbb57891b4c66fc3c43551802e5532bd1 introduced a bug where connections were being created on-demand but were not being stored in the connections slice.
When trying to end connections at the end of a transfer, there were no handles to them. As a result, all but the primary connection of the session were hung with no "quit" message. LFS clients (and servers) were simply hung until idle timeout kicked in.
Found this while implementing pure SSH protocol for Gitea (https://github.com/go-gitea/gitea/issues/17554).
This seems like important functionality, so I'd recommend adding some sort of pure SSH multiplexed tests in the suite as well.
=> ssh: fix connection creation "leaking" connections

.github/workflows/ci.yml, .github/workflows/release.yml, rpm/SPECS/git-lfs.spec, script/cibuild, t/Makefile, t/cmd/lfstest-count-tests.go, t/t-env.sh, t/t-worktree.sh, t/testenv.sh, t/testhelpers.sh, t/testlib.sh
Since we revised our test suite to use the `prove` command in PR #3125, an undiagnosed bug in our `lfstest-count-tests` test helper [program](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/t/cmd/lfstest-count-tests.go) has prevented us from running our test scripts in parallel on Windows.  Instead, several workarounds were introduced in that PR to avoid counting parallel test script executions and run all our test scripts sequentially on Windows, which slows down our CI jobs.
(The `lfstest-count-tests` program is used to track the number of active test scripts, so our `lfstest-gitserver` test server [program](https://github.com/git-lfs/git-lfs/blob/8b2882b7b791635d5deefebcc4edaa9e8eef638a/t/cmd/lfstest-gitserver.go) can be started once, shared by all our …
=> Run tests in parallel on Windows and always cleanup test directories

commands/command_migrate.go, git/git.go, lfs/gitscanner_remotes.go, t/t-push.sh
Fixes #5848.
Improves the performance of git lfs pre-push particularly for large repositories with numerous tags.
Previously, the pre-push hook would execute 'git ls-remote' with both --heads and --tags flags, which could be slow in repositories with many tags.
Tags can be omitted for pre-push however.
=> git-lfs: omit tags in ls-remote; optimize pre-push

script/build-git
As of Ubuntu 24.04, the primary list of sources for APT [moved](https://discourse.ubuntu.com/t/spec-apt-deb822-sources-by-default/29333) to the `/etc/apt/sources.list.d/ubuntu.sources` file instead of the legacy `/etc/apt/sources.list` file, and was [rewritten](https://manpages.ubuntu.com/manpages/noble/man5/sources.list.5.html) to make use of the `deb822` [format](https://manpages.debian.org/bookworm/dpkg-dev/deb822.5.en.html), which is based on RFC 822.  From the Ubuntu 24.04 [release notes](https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890#deb822-sources-management):
> The sources configuration for Ubuntu has moved from `/etc/apt/sources.list` to `/etc/apt/sources.list.d/ubuntu.sources` in the more featureful deb822 format, aligning with PPAs that already …
=> script/build-git: update Ubuntu 24.04 APT sources

commands/command_prune.go, git/git.go, git/git_test.go, t/cmd/util/testutils.go, t/t-prune-worktree.sh
This PR adds an alternative implementation of the [function](https://github.com/git-lfs/git-lfs/blob/a577e336ebdccfd312b6006c880f010b5d3fe796/git/git.go#L911-L972) used by the `git lfs prune` command to locate all linked working trees, in order to ensure that Git LFS continues to be compatible with future versions of Git.  This change addresses the recent CI job failures seen in our `Build with latest Git` jobs; for instance, in this job [run](https://github.com/git-lfs/git-lfs/actions/runs/11513482984/job/32050267427) for PR #5876.
Since the introduction of support in Git for multiple linked working trees, in version 2.5.0, paths to these working trees have been stored in the `.git/worktrees` internal file structure as full, absolute paths.  At present, Git LFS …
=> Support relative paths to linked working trees

lfs/hook.go, t/t-install.sh, t/t-update.sh
Under most shells `echo "\n"` produces \n, not a newline. This fixes it
via moving to printf, which should be more portable and is encouraged by
POSIX.
=> hook: fix newlines in command missing message

docs/spec.md
We check in a variety of places that our pointer files are less than 1 KiB in size.  Because this is a limitation, let's document it in the spec so that users can easily understand the constraint.
=> doc: mention the pointer size constraint

docs/man/git-lfs-config.adoc, lfsapi/lfsapi.go, ssh/connection.go, ssh/ssh.go, ssh/ssh_test.go, t/cmd/lfs-ssh-echo.go, t/t-batch-transfer.sh, t/testhelpers.sh
This PR fixes a bug where the Git LFS client may crash while cloning a repository with multiple Git LFS objects using the  "pure" SSH version of the Git LFS transfer [protocol](https://github.com/git-lfs/git-lfs/blob/f979a7db3b11d77975bc241f2c5ae71b02457d2c/docs/proposals/ssh_adapter.md).
Our existing [test](https://github.com/git-lfs/git-lfs/blob/f979a7db3b11d77975bc241f2c5ae71b02457d2c/t/t-batch-transfer.sh#L166-L192) of the SSH object transfer protocol did not detect the problem because it only pushes and fetches a single object, so we add more tests to confirm that the changes in this PR are effective.
In order for these additional tests to succeed, we also fix a latent issue in our `lfs-ssh-echo` test utility program whereby it silently fails while trying to emulate the behaviour of …
=> Fix crash during pure SSH object transfer with multiple objects

script/lib/distro.rb
As we anticipate releasing Git LFS version 3.6.0 in the near future, we first update our list of the Linux distributions and versions for which our scripts will publish RPM and Debian packages.
This PR will be most easily reviewed on a commit-by-commit basis.
We first reformat and correct several details of in our [list](https://github.com/git-lfs/git-lfs/blob/9d69005f1be8d860f4f5ee51dd2a81758ea1c1cd/script/lib/distro.rb#L24-L113) of Linux distribution versions and the end dates of their regular support lifecycles.
We then update our list to remove distribution versions that are no longer supported and add those which have become available since our last revisions in PR #5647, prior to our Git LFS v3.5.0 release.
There are several points of note in terms of what we change and do not …
=> Update Linux distribution package list for v3.6.0 release

t/t-batch-error-handling.sh, t/t-batch-transfer.sh, t/t-chunked-transfer-encoding.sh, t/t-clone.sh, t/t-env.sh, t/t-happy-path.sh, t/t-worktree.sh, t/testenv.sh, t/testhelpers.sh
This PR updates our test suite to remove or refine a number of stale comments and code, including [detection](https://github.com/git-lfs/git-lfs/blob/f979a7db3b11d77975bc241f2c5ae71b02457d2c/t/testhelpers.sh#L485-L488) of an old TLS/SSL client certificate problem with libcurl on macOS 10.12 ("Sierra") from 2016, which was used to [skip](https://github.com/git-lfs/git-lfs/blob/f979a7db3b11d77975bc241f2c5ae71b02457d2c/t/t-clone.sh#L182-L185) [some](https://github.com/git-lfs/git-lfs/blob/f979a7db3b11d77975bc241f2c5ae71b02457d2c/t/t-clone.sh#L270-L273) of our tests of the `git lfs clone` command, and the obscure [name](https://github.com/git-lfs/git-lfs/blob/f979a7db3b11d77975bc241f2c5ae71b02457d2c/t/testenv.sh#L155) of an environment variable intended to validate the behaviour of the `git …
=> Always capture clone logs in tests and remove or update stale workarounds

git/git.go, t/t-checkout.sh, t/t-pull.sh
When we invoke `git ls-files` to try to find all LFS files, we don't honour sparse file paths or exclusions.  While we should never actually traverse excluded files, using the `--exclude-standard` option can avoid loading some data with filtered clones, which may result in less data being downloaded.
In addition, we can honour sparse checkouts, since this code path is only used to handle the working tree and we know that the only files we need to consider are those Git actually put in the working tree.  The `--sparse` option is new in 2.35, but we already require 2.42 above, so we can use it unconditionally.
=> git: improve sparse checkout support

t/cmd/lfstest-gitserver.go, t/t-askpass.sh, t/t-clone.sh, t/t-credentials.sh, t/t-filter-process.sh, t/t-lock.sh, t/t-migrate-export.sh, t/t-migrate-import-no-rewrite.sh, t/t-migrate-import.sh, t/t-track-wildcards.sh, t/testenv.sh, t/testhelpers.sh
Following from the work in PR #5882 to fully enable all the tests in our `t/t-clone.sh` test script, this PR further refines the `clone ClientCert` and `clone ClientCert with homedir certs` [tests](https://github.com/git-lfs/git-lfs/blob/3990c7ab4fa6c99540af3f73f33da47a72df08af/t/t-clone.sh#L166-L289) so they both perform the same sets of checks, including a reworked version of the loop in the `clone ClientCert` test which clarifies when the encrypted version of the TLS/SSL certificate's private key is in use.
In particular, the `clone ClientCert with homedir certs` test does not, at the moment, actually test the `git lfs clone` command, unlike all the other tests in `t/t-clone.sh` test script, and it also does not use the encrypted private key file at all, although we …
=> Fix improper negated test expressions and refine TLS client certificate tests

CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v3.6.0, which is scheduled for Wednesday, November 20, 2024.
[git-lfs-darwin-amd64-v3.6.0-pre.zip](https://github.com/user-attachments/files/17810624/git-lfs-darwin-amd64-v3.6.0-pre.zip)
[git-lfs-darwin-arm64-v3.6.0-pre.zip](https://github.com/user-attachments/files/17810625/git-lfs-darwin-arm64-v3.6.0-pre.zip)
[git-lfs-freebsd-386-v3.6.0-pre.tar.gz](https://github.com/user-attachments/files/17810627/git-lfs-freebsd-386-v3.6.0-pre.tar.gz)
[git-lfs-freebsd-amd64-v3.6.0-pre.tar.gz](https://github.com/user-attachments/files/17810628/git-lfs-freebsd-amd64-v3.6.0-pre.tar.gz)
[git-lfs-linux-386-v3.6.0-pre.tar.gz](https://github.com/user-attachments/files/17810629/git-lfs-lin …
=> release: v3.6.0

docs/howto/release-git-lfs.md, script/hash-files, script/upload
This PR updates our "Releasing Git LFS" documentation [page](https://github.com/git-lfs/git-lfs/blob/6340befc60876f4f039f215479d9d5a945f817e1/docs/howto/release-git-lfs.md) to reflect the current state of our release process, and also adjusts two of the scripts used in that process so they function successfully on macOS systems (or provide more useful error messages if the necessary dependencies are not available).
In particular, our `script/upload` script expects that the `sha3sum(1)` utility is available and that it [accepts](https://github.com/git-lfs/git-lfs/blob/6340befc60876f4f039f215479d9d5a945f817e1/script/upload#L297) input in the format [generated](https://github.com/git-lfs/git-lfs/blob/6340befc60876f4f039f215479d9d5a945f817e1/script/hash-files#L33) by our `script/hash-files` …
=> Update release process documentation and scripts

.github/workflows/ci.yml, .github/workflows/release.yml
I was recently reading an article about a repository whose release workflow was compromised due to code injection and how it could have been detected using [zizmor](https://github.com/woodruffw/zizmor).  I did some auditing here of the Actions workflows, both manually and with zizmor, and I didn't find any obvious security problems, but I did some hardening.
The first patch was from my manual auditing and covers some improved shell quoting.  This isn't currently exploitable, but we might as well avoid the problem altogether and using proper shell quoting is a best practice anyway.  The second patch comes from the recommendation of zizmor.
We _are_ following the best practice of storing expanded Actions patterns (those with `${{}}`) in an environment variable before using them, because …
=> Tighten security of Actions workflows

go.mod, go.sum
As noted in https://github.com/git-lfs/git-lfs/issues/5939#issuecomment-2553105997, the vulnerability addressed by this update to the `x/net` Go module, reported as CVE-2024-45338, only pertains to the `x/net/html` package and the Git LFS client doesn't parse any HTML, so there is no immediate need to release a new version of Git LFS.
While we do import some packages from the `x/net` module, both directly and indirectly, none of them are the `x/net/html` package. We can confirm this is the case by running `go list -json all | grep x/net/html`, which returns no output.
Nevertheless, we might as well upgrade the module, so that when we do release v3.7.0 of the Git LFS client, security scanners will not generate false positive reports.
For reference, the details of the vulnerability are …
=> Upgrade `golang.org/x/net` from 0.23.0 to 0.33.0

docs/man/git-lfs-migrate.adoc
Removed the duplicate flag `--include-ref` flag mention.
Before:
```
--include-ref=<refname>:
See "Include and exclude references".
--include-ref=<refname>:
See "Include and exclude references".
```
After:
```
--include-ref=<refname>:
See "Include and exclude references".
```
=> docs/man/git-lfs-migrate.adoc: remove duplicate flag

docs/man/git-lfs-prune.adoc
I could not find an option `--verify-reachable` / `--no-verify-reachable` on prune sub command.
```
$ git lfs prune --verify-reachable
Error: unknown flag: --verify-reachable
$ git lfs prune --no-verify-reachable
Error: unknown flag: --no-verify-reachable
```
On the other hand, the option `--verify-unreachable` / `--no-verify-unreachable` seems to exist.
```
$ git lfs prune --verify-unreachable
prune: 0 local objects, 1 retained, done.
$ git lfs prune --no-verify-unreachable
prune: 0 local objects, 1 retained, done.
```
So I changed the content of adoc to `--verify-unreachable` / `--no-verify-unreachable`.
=> docs/man/git-lfs-prune.adoc: fix --(no-)verify-unreachable description

commands/command_fetch.go, docs/man/git-lfs-fetch.adoc, t/t-fetch.sh
This was modelled after the `git-lfs push --dry-run` option. I've removed some apparently unused code:
* computing and reporting of ready nodes
* deduplication of multiple objects with the same OID (as far as I can tell, that is already carried out by the transfer queue class, so no need to redo it in the fetch command)
* the output channel of the main fetch function which was always `nil`.
For testing, I added `--dry-run` testing to a couple of cases, but I wonder if we should add it for _all_ cases.
This is a part of what was discussed in https://github.com/git-lfs/git-lfs/issues/5888.
=> Add `--dry-run` option to `fetch`

.github/workflows/ci.yml, .github/workflows/release.yml
The default runners provided by GitHub Actions for the macOS, Windows, and Ubuntu Linux platforms are now all provisioned with an installation of Ruby 3.x, which along with the `asciidoctor` and `packagecloud-ruby` gems is all we require to run the several Ruby scripts used by our CI and release workflows.
We can therefore remove the `ruby/setup-ruby` action from our workflows.  On Windows in particular this also allows us to remove the special handling of the `TMPDIR` environment variable and the `MSYS2` environment, since these will no longer be installed by the `ruby/setup-ruby` action.
On the Ubuntu Linux runners, we do have to run the `gem` command with `sudo` as it otherwise encounters a file permission error trying to install our gems.
Note that the changes to our release workflow …
=> Use default Ruby provided by Actions runners

commands/command_clean.go, commands/command_fsck.go, commands/command_logs.go, commands/commands.go
In PR #68 the `commands` package was updated with several logging functions such as `Panic()`, `Print()`, and `Debug()`.  The last of these [only outputs](https://github.com/git-lfs/git-lfs/blob/d0d1ed06177d78e2222ed3d9a7bb07db6effb033/commands/commands.go#L251-L254) a log message if the `Debugging` [variable](https://github.com/git-lfs/git-lfs/blob/d0d1ed06177d78e2222ed3d9a7bb07db6effb033/commands/commands.go#L32) in the same package is set to `true`, which at the time was controlled by the `setupDebugging()` [function](https://github.com/git-lfs/git-lfs/blob/f83d26fa39acad6618ca537286ac710c3e6d3e8d/commands/commands.go#L163-L169).  If the user supplied the `--debug` option to a given Git LFS command, `setupDebugging()` function would set the `Debugging` variable to `true`, and any calls …
=> Replace unused debug mode with trace logging

commands/command_clone.go, commands/command_fetch.go, commands/command_lock.go, commands/command_locks.go, commands/command_ls_files.go, commands/command_status.go, commands/command_unlock.go, docs/man/git-lfs-fetch.adoc, docs/man/git-lfs-lock.adoc, docs/man/git-lfs-locks.adoc, docs/man/git-lfs-ls-files.adoc, docs/man/git-lfs-status.adoc, docs/man/git-lfs-unlock.adoc, t/t-fetch.sh, t/testhelpers.sh, tq/transfer_queue.go
This adds a `--json` option to fetch, which is done on top of https://github.com/git-lfs/git-lfs/pull/5973.
It turned out there was a minor bug in `--dry-run`, where the same object was being reported fetched multiple times from different references, which diverged from non-dry-run behaviour, where the object being fetched for one ref prevented refetching for the other. This has been fixed by keeping a set of virtually fetched OIDs. This and gathering the transfers across references required sharing a `fetchWatcher` object across `fetch*` calls.
Additionally, this PR also harmonizes the `--json` flag occurring in different commands:
* all now accept `-j` as a shorcut (previously only `status` did)
* all now have the same documentation
=> Add `--json` option to `fetch`

commands/command_locks.go, git/githistory/ref_updater.go, lfshttp/client.go, lfshttp/stats.go, tasklog/log.go, tools/math.go, tools/math_test.go, tools/ordered_set.go, tools/str_tools.go, tq/meter.go, tq/verify.go
We can use the built-in `min` and `max` functions since Go 1.21.
Reference: https://go.dev/ref/spec#Min_and_max
=> Replace min/max helpers with built-in min/max

docs/man/git-lfs-checkout.adoc
While looking into coding a solution for #5990, I stumbled upon an issue in the docs for the `checkout` command.
If you try to run the commands for the `--ours` and `--theirs` examples, it will error out complaining about missing the `--to` flag. So I added it to the doc example.
=> doc: Add missing "--to" argument in git-lfs-checkout example

commands/command_fetch.go, commands/command_migrate.go, commands/command_migrate_export.go, commands/command_migrate_import.go, commands/command_migrate_info.go, commands/command_prune.go, docs/l10n.md, docs/man/git-lfs-migrate.adoc, git/gitattr/tree.go, git/githistory/ref_updater.go, git/githistory/ref_updater_test.go, git/githistory/rewriter.go, t/t-migrate-export.sh, t/t-migrate-fixup.sh, t/t-migrate-import.sh, t/t-migrate-info.sh, t/t-prune-worktree.sh, t/t-prune.sh
Three of the Git LFS commands, namely the `git lfs fetch`, `git lfs prune`, and `git lfs migrate` commands, all output informational messages prefixed by their Git LFS subcommand names.
This behaviour differs from all of our other commands, and from the messages output by Git commands, so we revise these three Git LFS commands now to remove these message prefixes, and make some other minor adjustments to the format of the `git lfs migrate` command's output to improve its readability.
As an example, our existing output from these commands looks like the following.  Note the inconsistency in some of the lines output by the `git lfs migrate` command in particular.
```
$ git lfs prune
prune: 2 local objects, 0 retained, done.                                       
prune: Deleting objects: …
```
=> Remove command name prefixes from progress messages

.github/workflows/ci.yml, .github/workflows/release.yml
Go version 1.24 has been released, and because we aim to build and test Git LFS against only supported versions of Go, we upgrade our GitHub Actions CI workflows to test against Go versions 1.24 and 1.23.
This resolves a problem now seen in our `Build with specific Go` CI job, where we install the latest version of the `goimports` package and it fails because the `x/tools` module requires Go 1.23 as of commit golang/tools@94db7107945332a789135d458a0f0de1d7c00ddb, and we are still using Go 1.22 for that CI job.
After this PR is merged, we will revise the required set of jobs in our CI test suite, and also upgrade the version of Go used in the scripts and Dockerfiles in our `github/build-dockers` project.
=> Upgrade to Go 1.24

commands/commands.go
Since commit a343a11ddb8e3d3755590d1a3786831ccc18888b of PR #1461, a number of our commands, including `git lfs pull`, `git lfs push`, and `git lfs track`, have [checked](https://github.com/git-lfs/git-lfs/blob/97f47b9cd2102273287066e0225a6c10457c401a/commands/command_track.go#L38) the version of the currently available Git program and [reported](https://github.com/git-lfs/git-lfs/blob/97f47b9cd2102273287066e0225a6c10457c401a/commands/commands.go#L542) an error if it was not at least version 1.8.2.
However, when we added support for the `git lfs migrate` command in PR #2353, the actual minimum supported version of Git was changed from 1.8.x to 1.9.0 (in commit 1d0e834489913d05eaa2ae36f7c22d1901e5f845) and then to 2.0.0 (in commit 5aea841bb167e51592646e0c703ac37180623292).
These changes …
=> Update minimum required Git version checks

commands/command_smudge.go
the code logic I think, 
if file not exists( statErr != nil ) it will be delay write to path use the `ptr`,  so it should call with a direct nil value.
=> use direct value nil for error

Makefile
Beginning with version 4.4 of the GNU `make(1)` command, the warning message `pattern recipe did not update peer target` is output if a recipe does not build all of its assigned targets.  The next release of GNU `make(1)` will treat this condition as an error, per the v4.4 [release notes](https://lists.gnu.org/archive/html/info-gnu/2022-10/msg00008.html).
Our Makefile contains several pattern [rules](https://github.com/git-lfs/git-lfs/blob/d5db3c873ed3cf90b667d796a2c39b0dc7674578/Makefile#L724-L732) which generate roff and HTML manual pages from our AsciiDoc source files, and these specify multiple targets because the AsciiDoc source files lack a manual section number (e.g., `1` or `5`), while the target files must contain those numbers (e.g., `man/man1/git-lfs.1`).
With the latest …
=> Use single-target `Makefile` patterns for manual pages

docs/api/basic-transfers.md, docs/api/batch.md, docs/api/locking.md
These snippets are not `js` (JavaScript), they are JSON. Since many snippets also include comments, I marked them as JSON5 because raw JSON doesn't support comments.
=> Fix language in code snippets in API docs

commands/pull.go, t/t-checkout.sh, t/t-pull.sh, t/testhelpers.sh
If the user is having a problem checking out a file, it would be helpful to know why.  Let's include the reason that the error is occurring so they can learn what the cause is and report it helpfully if there's a problem.
=> pull: improve error message on failing checkout

script/build-git
This PR resolves a problem which has recently caused our `build-earliest` CI [job](https://github.com/git-lfs/git-lfs/blob/9b9bccb9a559f9e3e76807a00ff908b3e414ded9/.github/workflows/ci.yml#L142-L165) to [fail](https://github.com/git-lfs/git-lfs/actions/runs/14646748015/job/41123628361) on macOS GitHubActions runners when we try to compile Git v2.0.0.
Specifically, the compiler reports `error: use of undeclared identifier 'CURLUSESSL_TRY'` in the [call](https://github.com/git/git/blob/v2.0.0/http.c#L363) to the `curl_easy_setopt()` function in Git's `get_curl_handle()` function, where `CURLUSESSL_TRY` is passed as the final argument.
As described below, and explicated in further detail in the description of this PR's sole commit, the error occurs because older versions of Git contain a …
=> Prevent conflicting curl macros in early Git version CI jobs

commands/uploader.go, t/t-pre-push.sh, t/t-push-failures-local.sh, t/testhelpers.sh, tq/api.go, tq/ssh.go, tq/transfer_queue.go
This PR simplifies and makes consistent the messages reported by the Git LFS client during push operations when a Git LFS object is missing from local internal Git LFS storage and is also not present on the remote server, and the `lfs.allowIncompletePush` Git configuration option is set to its default value of `false`.
At present, the client outputs different messages under these conditions, depending on whether or not a file exists in the working tree at the same path as that of the Git LFS pointer which references the missing object.  We can demonstrate this variable behaviour of the client as follows:
```
$ git clone https://github.com/chrisd8088/test
$ cd test
$ git lfs track "*.bin"
$ echo foo >foo.bin
$ git add .gitattributes foo.bin
$ git commit -m test
$ rm -rf .git/lfs/objects
$ …
```
=> Report missing objects consistently when pushing

CHANGELOG.md, config/version.go, debian/changelog, rpm/SPECS/git-lfs.spec, versioninfo.json
This is an in-progress look at the next release of Git LFS, v3.7.0, which is scheduled for Thursday, June 26, 2025.
[git-lfs-darwin-amd64-v3.7.0-pre.zip](https://github.com/user-attachments/files/20895689/git-lfs-darwin-amd64-v3.7.0-pre.zip)
[git-lfs-darwin-arm64-v3.7.0-pre.zip](https://github.com/user-attachments/files/20895690/git-lfs-darwin-arm64-v3.7.0-pre.zip)
[git-lfs-freebsd-386-v3.7.0-pre.tar.gz](https://github.com/user-attachments/files/20895691/git-lfs-freebsd-386-v3.7.0-pre.tar.gz)
[git-lfs-freebsd-amd64-v3.7.0-pre.tar.gz](https://github.com/user-attachments/files/20895692/git-lfs-freebsd-amd64-v3.7.0-pre.tar.gz)
[git-lfs-linux-386-v3.7.0-pre.tar.gz](https://github.com/user-attachments/files/20895693/git-lfs-linux-38 …
=> release: v3.7.0

commands/command_fetch.go, commands/command_push.go
Replace the remaining `os.Exit()` calls with our `Exit()` wrapper for consistency. This change also alters the exit code for these exits from `1` to `2`. This is irrelevant for the `fetch` code as it was not released, yet. The push code was shipped some time ago (https://github.com/git-lfs/git-lfs/pull/5086) and therefore we need to mention this change in the release notes.
=> commands: use Exit() function to exit with a warning message
